// Auto-generated by cs2-codegen from schemas_jsonschema.json
// Revision 10638965 (May 06 2026) — https://github.com/ValveResourceFormat/DumpSource2
// Do not edit by hand.
// Module: animdoclib

#nullable enable
#pragma warning disable CS8618  // non-nullable property not initialized (expected in generated serialization types)

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CS2Schema;

/// <summary>CNmAnimDocument, 112 bytes</summary>
public class CNmAnimDocument
{
    [JsonPropertyName("m_nVersion")]
    public int M_nVersion { get; set; }  // +0x68
}

/// <summary>CNmBlendSpace1D, 24 bytes</summary>
public class CNmBlendSpace1D
{
    [JsonPropertyName("m_points")]
    public CNmBlendSpace1D_Point_t[] M_points { get; set; }  // +0x0
}

/// <summary>CNmBlendSpace1D::Point_t, 32 bytes</summary>
public class CNmBlendSpace1D_Point_t
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x0
    [JsonPropertyName("m_flValue")]
    public float M_flValue { get; set; }  // +0x8
    [JsonPropertyName("m_pinID")]
    public Guid M_pinID { get; set; }  // +0xC
}

/// <summary>CNmBlendSpace2D, 96 bytes</summary>
public class CNmBlendSpace2D
{
    [JsonPropertyName("m_pointNames")]
    public string[] M_pointNames { get; set; }  // +0x0
    [JsonPropertyName("m_points")]
    public Vector2D[] M_points { get; set; }  // +0x18
    [JsonPropertyName("m_indices")]
    public byte[] M_indices { get; set; }  // +0x30
    [JsonPropertyName("m_hullIndices")]
    public byte[] M_hullIndices { get; set; }  // +0x48
}

/// <summary>CNmClipDocEvent, 16 bytes</summary>
public class CNmClipDocEvent
{
    [JsonPropertyName("m_flStartTime")]
    public float M_flStartTime { get; set; }  // +0x8
    [JsonPropertyName("m_flDuration")]
    public float M_flDuration { get; set; }  // +0xC
}

/// <summary>CNmClipDocEvent_BodyGroup, 40 bytes</summary>
public class CNmClipDocEvent_BodyGroup : CNmClipDocEvent
{
    [JsonPropertyName("m_target")]
    public CNmEventTargetEntity_t M_target { get; set; }  // +0x10
    [JsonPropertyName("bodygroup")]
    public string Bodygroup { get; set; }  // +0x18
    [JsonPropertyName("value")]
    public int Value { get; set; }  // +0x20
}

/// <summary>CNmClipDocEvent_EntityAttribute, 104 bytes</summary>
public class CNmClipDocEvent_EntityAttribute : CNmClipDocEvent
{
    [JsonPropertyName("m_target")]
    public CNmEventTargetEntity_t M_target { get; set; }  // +0x10
    [JsonPropertyName("m_attributeName")]
    public string M_attributeName { get; set; }  // +0x18
    [JsonPropertyName("m_nValueType")]
    public CNmClipDocEvent_EntityAttribute_Type_t M_nValueType { get; set; }  // +0x20
    [JsonPropertyName("m_nIntValue")]
    public int M_nIntValue { get; set; }  // +0x24
    [JsonPropertyName("m_FloatValue")]
    public object /* opaque */ M_FloatValue { get; set; }  // +0x28
}

public enum CNmClipDocEvent_EntityAttribute_Type_t : uint
{
    EVENT_ENTITY_ATTR_TYPE_INT = 0,
    EVENT_ENTITY_ATTR_TYPE_FLOAT = 1,
}

/// <summary>CNmClipDocEvent_FloatCurve, 88 bytes</summary>
public class CNmClipDocEvent_FloatCurve : CNmClipDocEvent
{
    [JsonPropertyName("m_ID")]
    public string M_ID { get; set; }  // +0x10
    [JsonPropertyName("m_curve")]
    public object /* opaque */ M_curve { get; set; }  // +0x18
}

/// <summary>CNmClipDocEvent_Foot, 24 bytes</summary>
public class CNmClipDocEvent_Foot : CNmClipDocEvent
{
    [JsonPropertyName("m_phase")]
    public NmFootPhase_t M_phase { get; set; }  // +0x10
}

/// <summary>CNmClipDocEvent_FrameSnap, 24 bytes</summary>
public class CNmClipDocEvent_FrameSnap : CNmClipDocEvent
{
    [JsonPropertyName("m_frameSnapMode")]
    public NmFrameSnapEventMode_t M_frameSnapMode { get; set; }  // +0x10
}

/// <summary>CNmClipDocEvent_ID, 32 bytes</summary>
public class CNmClipDocEvent_ID : CNmClipDocEvent
{
    [JsonPropertyName("m_ID")]
    public string M_ID { get; set; }  // +0x10
    [JsonPropertyName("m_secondaryID")]
    public string M_secondaryID { get; set; }  // +0x18
}

/// <summary>CNmClipDocEvent_Legacy, 40 bytes</summary>
public class CNmClipDocEvent_Legacy : CNmClipDocEvent
{
    [JsonPropertyName("m_eventClass")]
    public string M_eventClass { get; set; }  // +0x10
    [JsonPropertyName("m_KV")]
    public object /* opaque */ M_KV { get; set; }  // +0x18
}

/// <summary>CNmClipDocEvent_MaterialAttribute, 288 bytes</summary>
public class CNmClipDocEvent_MaterialAttribute : CNmClipDocEvent
{
    [JsonPropertyName("m_target")]
    public CNmEventTargetEntity_t M_target { get; set; }  // +0x10
    [JsonPropertyName("m_attributeName")]
    public string M_attributeName { get; set; }  // +0x18
    [JsonPropertyName("m_x")]
    public object /* opaque */ M_x { get; set; }  // +0x20
    [JsonPropertyName("m_y")]
    public object /* opaque */ M_y { get; set; }  // +0x60
    [JsonPropertyName("m_z")]
    public object /* opaque */ M_z { get; set; }  // +0xA0
    [JsonPropertyName("m_w")]
    public object /* opaque */ M_w { get; set; }  // +0xE0
}

/// <summary>CNmClipDocEvent_OrientationWarp, 16 bytes</summary>
public class CNmClipDocEvent_OrientationWarp : CNmClipDocEvent
{
}

/// <summary>CNmClipDocEvent_Particle, 104 bytes</summary>
public class CNmClipDocEvent_Particle : CNmClipDocEvent
{
    [JsonPropertyName("m_relevance")]
    public CNmEventRelevance_t M_relevance { get; set; }  // +0x10
    [JsonPropertyName("m_type")]
    public CNmParticleEvent_Type_t M_type { get; set; }  // +0x14
    [JsonPropertyName("m_target")]
    public CNmEventTargetEntity_t M_target { get; set; }  // +0x18
    [JsonPropertyName("m_particleSystem")]
    public string M_particleSystem { get; set; }  // +0x20
    [JsonPropertyName("m_bDetachFromOwner")]
    public bool M_bDetachFromOwner { get; set; }  // +0x28
    [JsonPropertyName("m_bStopImmediately")]
    public bool M_bStopImmediately { get; set; }  // +0x29
    [JsonPropertyName("m_bPlayEndCap")]
    public bool M_bPlayEndCap { get; set; }  // +0x2A
    [JsonPropertyName("m_attachmentPoint0")]
    public string M_attachmentPoint0 { get; set; }  // +0x30
    [JsonPropertyName("m_attachmentType0")]
    public ParticleAttachment_t M_attachmentType0 { get; set; }  // +0x38
    [JsonPropertyName("m_attachmentPoint1")]
    public string M_attachmentPoint1 { get; set; }  // +0x40
    [JsonPropertyName("m_attachmentType1")]
    public ParticleAttachment_t M_attachmentType1 { get; set; }  // +0x48
    [JsonPropertyName("m_config")]
    public string M_config { get; set; }  // +0x50
    [JsonPropertyName("m_effectForConfig")]
    public string M_effectForConfig { get; set; }  // +0x58
    [JsonPropertyName("m_tags")]
    public string M_tags { get; set; }  // +0x60
}

/// <summary>CNmClipDocEvent_RootMotion, 24 bytes</summary>
public class CNmClipDocEvent_RootMotion : CNmClipDocEvent
{
    [JsonPropertyName("m_flBlendTimeSeconds")]
    public float M_flBlendTimeSeconds { get; set; }  // +0x10
}

/// <summary>CNmClipDocEvent_Sound, 64 bytes</summary>
public class CNmClipDocEvent_Sound : CNmClipDocEvent
{
    [JsonPropertyName("m_relevance")]
    public CNmEventRelevance_t M_relevance { get; set; }  // +0x10
    [JsonPropertyName("m_bContinuePlayingSoundAtDurationEnd")]
    public bool M_bContinuePlayingSoundAtDurationEnd { get; set; }  // +0x14
    [JsonPropertyName("m_flDurationInterruptionThreshold")]
    public float M_flDurationInterruptionThreshold { get; set; }  // +0x18
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x20
    [JsonPropertyName("m_position")]
    public CNmSoundEvent_Position_t M_position { get; set; }  // +0x28
    [JsonPropertyName("m_attachmentName")]
    public string M_attachmentName { get; set; }  // +0x30
    [JsonPropertyName("m_tags")]
    public string M_tags { get; set; }  // +0x38
}

/// <summary>CNmClipDocEvent_TargetWarp, 24 bytes</summary>
public class CNmClipDocEvent_TargetWarp : CNmClipDocEvent
{
    [JsonPropertyName("m_rule")]
    public NmTargetWarpRule_t M_rule { get; set; }  // +0x10
    [JsonPropertyName("m_algorithm")]
    public NmTargetWarpAlgorithm_t M_algorithm { get; set; }  // +0x11
}

/// <summary>CNmClipDocEvent_Transition, 32 bytes</summary>
public class CNmClipDocEvent_Transition : CNmClipDocEvent
{
    [JsonPropertyName("m_rule")]
    public NmTransitionRule_t M_rule { get; set; }  // +0x10
    [JsonPropertyName("m_optionalID")]
    public string M_optionalID { get; set; }  // +0x18
}

/// <summary>CNmClipDocEventTrack, 40 bytes</summary>
public class CNmClipDocEventTrack
{
    [JsonPropertyName("m_events")]
    public CNmClipDocEvent?[] M_events { get; set; }  // +0x0
    [JsonPropertyName("m_eventClassName")]
    public string M_eventClassName { get; set; }  // +0x18
    [JsonPropertyName("m_type")]
    public CNmClipDocEventTrack_Type_t M_type { get; set; }  // +0x20
    [JsonPropertyName("m_bIsSyncTrack")]
    public bool M_bIsSyncTrack { get; set; }  // +0x24
    [JsonPropertyName("m_bIsDisabled")]
    public bool M_bIsDisabled { get; set; }  // +0x25
}

public enum CNmClipDocEventTrack_Type_t : uint
{
    Immediate = 0,
    Duration = 1,
    Num = 2,
}

/// <summary>CNmClipDocument, 248 bytes</summary>
public class CNmClipDocument : CNmAnimDocument
{
    [JsonPropertyName("m_sourceFilename")]
    public string M_sourceFilename { get; set; }  // +0x70
    [JsonPropertyName("m_animationSkeletonName")]
    public string M_animationSkeletonName { get; set; }  // +0x78
    [JsonPropertyName("m_secondaryAnimationSkeletonNames")]
    public string[] M_secondaryAnimationSkeletonNames { get; set; }  // +0x80
    [JsonPropertyName("m_eventTracks")]
    public CNmClipDocEventTrack[] M_eventTracks { get; set; }  // +0x98
    [JsonPropertyName("m_nStartFrame")]
    public int M_nStartFrame { get; set; }  // +0xA8
    [JsonPropertyName("m_nEndFrame")]
    public int M_nEndFrame { get; set; }  // +0xAC
    [JsonPropertyName("m_flDurationOverrideSeconds")]
    public float M_flDurationOverrideSeconds { get; set; }  // +0xB0
    [JsonPropertyName("m_additiveType")]
    public CNmClipDocument_AdditiveType_t M_additiveType { get; set; }  // +0xB4
    [JsonPropertyName("m_additiveBaseFilename")]
    public string M_additiveBaseFilename { get; set; }  // +0xB8
    [JsonPropertyName("m_additiveBaseFrame")]
    public CNmClipDocument_AdditiveBaseFrame_t M_additiveBaseFrame { get; set; }  // +0xC0
    [JsonPropertyName("m_nAdditiveBaseFrameIdx")]
    public int M_nAdditiveBaseFrameIdx { get; set; }  // +0xC4
    [JsonPropertyName("m_bUseReferencePoseForSecondaryAnimAdditives")]
    public bool M_bUseReferencePoseForSecondaryAnimAdditives { get; set; }  // +0xC8
    [JsonPropertyName("m_bonesToSampleInModelSpace")]
    public string[] M_bonesToSampleInModelSpace { get; set; }  // +0xD0
}

public enum CNmClipDocument_AdditiveBaseFrame_t : byte
{
    FirstFrame = 0,
    LastFrame = 1,
    UserSpecifiedFrame = 2,
}

public enum CNmClipDocument_AdditiveType_t : byte
{
    None = 0,
    RelativeToSkeleton = 1,
    RelativeToFrame = 2,
    RelativeToAnimation = 3,
    RelativeToAnimationFrame = 4,
}

/// <summary>CNmGraphDocAndNode, 256 bytes</summary>
public class CNmGraphDocAndNode : CNmGraphDocFlowNode
{
}

/// <summary>CNmGraphDocAnimationPoseNode, 528 bytes</summary>
public class CNmGraphDocAnimationPoseNode : CNmGraphDocVariationDataNode
{
    [JsonPropertyName("m_inputTimeRemapRange")]
    public Range_t M_inputTimeRemapRange { get; set; }  // +0x200
    [JsonPropertyName("m_fixedTimeValue")]
    public float M_fixedTimeValue { get; set; }  // +0x208
    [JsonPropertyName("m_useFramesAsInput")]
    public bool M_useFramesAsInput { get; set; }  // +0x20C
}

/// <summary>CNmGraphDocAnimationPoseNode::CData, 24 bytes</summary>
public class CNmGraphDocAnimationPoseNode_CData : CNmGraphDocVariationDataNode_CData
{
    [JsonPropertyName("m_clip")]
    public string M_clip { get; set; }  // +0x8
    [JsonPropertyName("m_variationTimeValue")]
    public float M_variationTimeValue { get; set; }  // +0x10
}

/// <summary>CNmGraphDocBlend1DNode, 288 bytes</summary>
public class CNmGraphDocBlend1DNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_blendSpace")]
    public CNmBlendSpace1D M_blendSpace { get; set; }  // +0x100
    [JsonPropertyName("m_bAllowLooping")]
    public bool M_bAllowLooping { get; set; }  // +0x118
}

/// <summary>CNmGraphDocBlend2DNode, 360 bytes</summary>
public class CNmGraphDocBlend2DNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_blendSpace")]
    public CNmBlendSpace2D M_blendSpace { get; set; }  // +0x100
    [JsonPropertyName("m_bAllowLooping")]
    public bool M_bAllowLooping { get; set; }  // +0x160
}

/// <summary>CNmGraphDocBoneMaskBlendNode, 256 bytes</summary>
public class CNmGraphDocBoneMaskBlendNode : CNmGraphDocFlowNode
{
}

/// <summary>CNmGraphDocBoneMaskNode, 520 bytes</summary>
public class CNmGraphDocBoneMaskNode : CNmGraphDocVariationDataNode
{
    [JsonPropertyName("m_maskID")]
    public string M_maskID { get; set; }  // +0x200
}

/// <summary>CNmGraphDocBoneMaskNode::CData, 16 bytes</summary>
public class CNmGraphDocBoneMaskNode_CData : CNmGraphDocVariationDataNode_CData
{
    [JsonPropertyName("m_overrideMaskID")]
    public string M_overrideMaskID { get; set; }  // +0x8
}

/// <summary>CNmGraphDocBoneMaskParameterReferenceNode, 304 bytes</summary>
public class CNmGraphDocBoneMaskParameterReferenceNode : CNmGraphDocParameterReferenceNode
{
}

/// <summary>CNmGraphDocBoneMaskResultNode, 264 bytes</summary>
public class CNmGraphDocBoneMaskResultNode : CNmGraphDocResultNode
{
}

/// <summary>CNmGraphDocBoneMaskSelectorNode, 296 bytes</summary>
public class CNmGraphDocBoneMaskSelectorNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_switchDynamically")]
    public bool M_switchDynamically { get; set; }  // +0x100
    [JsonPropertyName("m_options")]
    public string[] M_options { get; set; }  // +0x108
    [JsonPropertyName("m_flBlendTimeSeconds")]
    public float M_flBlendTimeSeconds { get; set; }  // +0x120
}

/// <summary>CNmGraphDocBoneMaskSwitchNode, 264 bytes</summary>
public class CNmGraphDocBoneMaskSwitchNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_bSwitchDynamically")]
    public bool M_bSwitchDynamically { get; set; }  // +0x100
    [JsonPropertyName("m_flBlendTimeSeconds")]
    public float M_flBlendTimeSeconds { get; set; }  // +0x104
}

/// <summary>CNmGraphDocBoneMaskVirtualParameterNode, 264 bytes</summary>
public class CNmGraphDocBoneMaskVirtualParameterNode : CNmGraphDocVirtualParameterNode
{
}

/// <summary>CNmGraphDocBoolControlParameterNode, 288 bytes</summary>
public class CNmGraphDocBoolControlParameterNode : CNmGraphDocControlParameterNode
{
    [JsonPropertyName("m_previewStartValue")]
    public bool M_previewStartValue { get; set; }  // +0x118
}

/// <summary>CNmGraphDocBoolParameterReferenceNode, 304 bytes</summary>
public class CNmGraphDocBoolParameterReferenceNode : CNmGraphDocParameterReferenceNode
{
}

/// <summary>CNmGraphDocBoolResultNode, 264 bytes</summary>
public class CNmGraphDocBoolResultNode : CNmGraphDocResultNode
{
}

/// <summary>CNmGraphDocBoolVirtualParameterNode, 264 bytes</summary>
public class CNmGraphDocBoolVirtualParameterNode : CNmGraphDocVirtualParameterNode
{
}

/// <summary>CNmGraphDocCachedBoolNode, 264 bytes</summary>
public class CNmGraphDocCachedBoolNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_mode")]
    public NmCachedValueMode_t M_mode { get; set; }  // +0x100
}

/// <summary>CNmGraphDocCachedFloatNode, 264 bytes</summary>
public class CNmGraphDocCachedFloatNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_mode")]
    public NmCachedValueMode_t M_mode { get; set; }  // +0x100
}

/// <summary>CNmGraphDocCachedIDNode, 264 bytes</summary>
public class CNmGraphDocCachedIDNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_mode")]
    public NmCachedValueMode_t M_mode { get; set; }  // +0x100
}

/// <summary>CNmGraphDocCachedTargetNode, 264 bytes</summary>
public class CNmGraphDocCachedTargetNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_mode")]
    public NmCachedValueMode_t M_mode { get; set; }  // +0x100
}

/// <summary>CNmGraphDocCachedVectorNode, 264 bytes</summary>
public class CNmGraphDocCachedVectorNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_mode")]
    public NmCachedValueMode_t M_mode { get; set; }  // +0x100
}

/// <summary>CnmGraphDocChainLookatNode, 520 bytes</summary>
public class CnmGraphDocChainLookatNode : CNmGraphDocVariationDataNode
{
    [JsonPropertyName("m_bIsTargetInWorldSpace")]
    public bool M_bIsTargetInWorldSpace { get; set; }  // +0x200
}

/// <summary>CnmGraphDocChainLookatNode::CData, 40 bytes</summary>
public class CnmGraphDocChainLookatNode_CData : CNmGraphDocVariationDataNode_CData
{
    [JsonPropertyName("m_chainEndBoneName")]
    public string M_chainEndBoneName { get; set; }  // +0x8
    [JsonPropertyName("m_chainForwardDir")]
    public Vector M_chainForwardDir { get; set; }  // +0x10
    [JsonPropertyName("m_nChainLength")]
    public byte M_nChainLength { get; set; }  // +0x1C
    [JsonPropertyName("m_flBlendTimeSeconds")]
    public float M_flBlendTimeSeconds { get; set; }  // +0x20
}

/// <summary>CNmGraphDocClipNode, 544 bytes</summary>
public class CNmGraphDocClipNode : CNmGraphDocVariationDataNode
{
    [JsonPropertyName("m_bSampleRootMotion")]
    public bool M_bSampleRootMotion { get; set; }  // +0x200
    [JsonPropertyName("m_bAllowLooping")]
    public bool M_bAllowLooping { get; set; }  // +0x201
    [JsonPropertyName("m_graphEvents")]
    public string[] M_graphEvents { get; set; }  // +0x208
}

/// <summary>CNmGraphDocClipNode::CData, 24 bytes</summary>
public class CNmGraphDocClipNode_CData : CNmGraphDocVariationDataNode_CData
{
    [JsonPropertyName("m_clip")]
    public string M_clip { get; set; }  // +0x8
    [JsonPropertyName("m_flSpeedMultiplier")]
    public float M_flSpeedMultiplier { get; set; }  // +0x10
    [JsonPropertyName("m_nStartSyncEventOffset")]
    public int M_nStartSyncEventOffset { get; set; }  // +0x14
}

/// <summary>CNmGraphDocClipSelectorNode, 280 bytes</summary>
public class CNmGraphDocClipSelectorNode : CNmGraphDocSelectorBaseNode
{
}

/// <summary>CNmGraphDocCommentNode, 104 bytes</summary>
public class CNmGraphDocCommentNode : CNmGraphDocNode
{
    [JsonPropertyName("m_size")]
    public Vector2D M_size { get; set; }  // +0x50
    [JsonPropertyName("m_comment")]
    public string M_comment { get; set; }  // +0x58
    [JsonPropertyName("m_nodeColor")]
    public Color M_nodeColor { get; set; }  // +0x60
}

/// <summary>CnmGraphDocConstBoneTargetNode, 264 bytes</summary>
public class CnmGraphDocConstBoneTargetNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_boneName")]
    public string M_boneName { get; set; }  // +0x100
}

/// <summary>CnmGraphDocConstBoolNode, 264 bytes</summary>
public class CnmGraphDocConstBoolNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_bValue")]
    public bool M_bValue { get; set; }  // +0x100
}

/// <summary>CnmGraphDocConstFloatNode, 264 bytes</summary>
public class CnmGraphDocConstFloatNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_flValue")]
    public float M_flValue { get; set; }  // +0x100
}

/// <summary>CnmGraphDocConstIDNode, 264 bytes</summary>
public class CnmGraphDocConstIDNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_value")]
    public string M_value { get; set; }  // +0x100
}

/// <summary>CnmGraphDocConstTargetNode, 280 bytes</summary>
public class CnmGraphDocConstTargetNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_rotation")]
    public QAngle M_rotation { get; set; }  // +0x100
    [JsonPropertyName("m_translation")]
    public Vector M_translation { get; set; }  // +0x10C
}

/// <summary>CnmGraphDocConstVectorNode, 272 bytes</summary>
public class CnmGraphDocConstVectorNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_value")]
    public Vector M_value { get; set; }  // +0x100
}

/// <summary>CNmGraphDocControlParameterNode, 280 bytes</summary>
public class CNmGraphDocControlParameterNode : CNmGraphDocParameterBaseNode
{
    [JsonPropertyName("m_dictionaryParameterBinding")]
    public Guid M_dictionaryParameterBinding { get; set; }  // +0x108
}

/// <summary>CNmGraphDocCurrentSyncEventIDNode, 256 bytes</summary>
public class CNmGraphDocCurrentSyncEventIDNode : CNmGraphDocFlowNode
{
}

/// <summary>CNmGraphDocCurrentSyncEventNode, 264 bytes</summary>
public class CNmGraphDocCurrentSyncEventNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_infoType")]
    public CNmCurrentSyncEventNode_InfoType_t M_infoType { get; set; }  // +0x100
}

/// <summary>CNmGraphDocDataDictionary, 48 bytes</summary>
public class CNmGraphDocDataDictionary
{
    [JsonPropertyName("m_parameterSets")]
    public CNmGraphDocDataDictionary_ParameterSet_t[] M_parameterSets { get; set; }  // +0x0
    [JsonPropertyName("m_IDSets")]
    public CNmGraphDocDataDictionary_IDSet_t[] M_IDSets { get; set; }  // +0x18
}

/// <summary>CNmGraphDocDataDictionary::IDSet_t, 48 bytes</summary>
public class CNmGraphDocDataDictionary_IDSet_t
{
    [JsonPropertyName("m_ID")]
    public Guid M_ID { get; set; }  // +0x0
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x10
    [JsonPropertyName("m_graphIDs")]
    public string[] M_graphIDs { get; set; }  // +0x18
}

/// <summary>CNmGraphDocDataDictionary::Parameter_t, 64 bytes</summary>
public class CNmGraphDocDataDictionary_Parameter_t
{
    [JsonPropertyName("m_ID")]
    public Guid M_ID { get; set; }  // +0x0
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x10
    [JsonPropertyName("m_groupName")]
    public string M_groupName { get; set; }  // +0x18
    [JsonPropertyName("m_valueType")]
    public NmGraphValueType_t M_valueType { get; set; }  // +0x20
    [JsonPropertyName("m_expectedValues")]
    public string[] M_expectedValues { get; set; }  // +0x28
}

/// <summary>CNmGraphDocDataDictionary::ParameterSet_t, 32 bytes</summary>
public class CNmGraphDocDataDictionary_ParameterSet_t
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x0
    [JsonPropertyName("m_parameters")]
    public CNmGraphDocDataDictionary_Parameter_t[] M_parameters { get; set; }  // +0x8
}

/// <summary>CnmGraphDocDurationScaleNode, 264 bytes</summary>
public class CnmGraphDocDurationScaleNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_flDesiredDuration")]
    public float M_flDesiredDuration { get; set; }  // +0x100
}

/// <summary>CNmGraphDocEntryOverrideNode, 280 bytes</summary>
public class CNmGraphDocEntryOverrideNode : CNmGraphDocResultNode
{
    [JsonPropertyName("m_stateID")]
    public Guid M_stateID { get; set; }  // +0x108
}

/// <summary>CNmGraphDocEntryStateOverrideConditionsNode, 288 bytes</summary>
public class CNmGraphDocEntryStateOverrideConditionsNode : CNmGraphDocResultNode
{
    [JsonPropertyName("m_pinToStateMapping")]
    public Guid[] M_pinToStateMapping { get; set; }  // +0x108
}

/// <summary>CNmGraphDocEntryStateOverrideConduitNode, 80 bytes</summary>
public class CNmGraphDocEntryStateOverrideConduitNode : CNmGraphDocStateMachineGraphNode
{
}

/// <summary>CNmGraphDocExternalGraphNode, 256 bytes</summary>
public class CNmGraphDocExternalGraphNode : CNmGraphDocFlowNode
{
}

/// <summary>CNmGraphDocExternalPoseNode, 264 bytes</summary>
public class CNmGraphDocExternalPoseNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_bShouldSampleRootMotion")]
    public bool M_bShouldSampleRootMotion { get; set; }  // +0x100
}

/// <summary>CNmGraphDocFixedWeightBoneMaskNode, 264 bytes</summary>
public class CNmGraphDocFixedWeightBoneMaskNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_flBoneWeight")]
    public float M_flBoneWeight { get; set; }  // +0x100
}

/// <summary>CNmGraphDocFloatAngleMathNode, 264 bytes</summary>
public class CNmGraphDocFloatAngleMathNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_operation")]
    public CNmFloatAngleMathNode_Operation_t M_operation { get; set; }  // +0x100
}

/// <summary>CNmGraphDocFloatClampNode, 264 bytes</summary>
public class CNmGraphDocFloatClampNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_clampRange")]
    public Range_t M_clampRange { get; set; }  // +0x100
}

/// <summary>CNmGraphDocFloatComparisonNode, 272 bytes</summary>
public class CNmGraphDocFloatComparisonNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_comparison")]
    public CNmFloatComparisonNode_Comparison_t M_comparison { get; set; }  // +0x100
    [JsonPropertyName("m_flComparisonValue")]
    public float M_flComparisonValue { get; set; }  // +0x104
    [JsonPropertyName("m_flEpsilon")]
    public float M_flEpsilon { get; set; }  // +0x108
}

/// <summary>CNmGraphDocFloatControlParameterNode, 296 bytes</summary>
public class CNmGraphDocFloatControlParameterNode : CNmGraphDocControlParameterNode
{
    [JsonPropertyName("m_previewStartValue")]
    public float M_previewStartValue { get; set; }  // +0x118
    [JsonPropertyName("m_previewMin")]
    public float M_previewMin { get; set; }  // +0x11C
    [JsonPropertyName("m_previewMax")]
    public float M_previewMax { get; set; }  // +0x120
}

/// <summary>CNmGraphDocFloatCurveEventNode, 272 bytes</summary>
public class CNmGraphDocFloatCurveEventNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_matchID")]
    public string M_matchID { get; set; }  // +0x100
    [JsonPropertyName("m_flDefaultValue")]
    public float M_flDefaultValue { get; set; }  // +0x108
    [JsonPropertyName("m_priorityRule")]
    public NmEventPriorityRule_t M_priorityRule { get; set; }  // +0x10C
    [JsonPropertyName("m_bLimitSearchToSourceState")]
    public bool M_bLimitSearchToSourceState { get; set; }  // +0x10D
    [JsonPropertyName("m_bIgnoreInactiveBranchEvents")]
    public bool M_bIgnoreInactiveBranchEvents { get; set; }  // +0x10E
}

/// <summary>CNmGraphDocFloatCurveNode, 320 bytes</summary>
public class CNmGraphDocFloatCurveNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_curve")]
    public object /* opaque */ M_curve { get; set; }  // +0x100
}

/// <summary>CNmGraphDocFloatEaseNode, 272 bytes</summary>
public class CNmGraphDocFloatEaseNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_easing")]
    public NmEasingOperation_t M_easing { get; set; }  // +0x100
    [JsonPropertyName("m_flEaseTime")]
    public float M_flEaseTime { get; set; }  // +0x104
    [JsonPropertyName("m_bUseStartValue")]
    public bool M_bUseStartValue { get; set; }  // +0x108
    [JsonPropertyName("m_flStartValue")]
    public float M_flStartValue { get; set; }  // +0x10C
}

/// <summary>CNmGraphDocFloatMathNode, 264 bytes</summary>
public class CNmGraphDocFloatMathNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_bReturnAbsoluteResult")]
    public bool M_bReturnAbsoluteResult { get; set; }  // +0x100
    [JsonPropertyName("m_bReturnNegatedResult")]
    public bool M_bReturnNegatedResult { get; set; }  // +0x101
    [JsonPropertyName("m_operator")]
    public CNmFloatMathNode_Operator_t M_operator { get; set; }  // +0x102
    [JsonPropertyName("m_flValueB")]
    public float M_flValueB { get; set; }  // +0x104
}

/// <summary>CNmGraphDocFloatParameterReferenceNode, 304 bytes</summary>
public class CNmGraphDocFloatParameterReferenceNode : CNmGraphDocParameterReferenceNode
{
}

/// <summary>CNmGraphDocFloatRangeComparisonNode, 272 bytes</summary>
public class CNmGraphDocFloatRangeComparisonNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_range")]
    public Range_t M_range { get; set; }  // +0x100
    [JsonPropertyName("m_isInclusiveCheck")]
    public bool M_isInclusiveCheck { get; set; }  // +0x108
}

/// <summary>CNmGraphDocFloatRemapNode, 272 bytes</summary>
public class CNmGraphDocFloatRemapNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_inputRange")]
    public CNmGraphDocFloatRemapNode_RemapRange_t M_inputRange { get; set; }  // +0x100
    [JsonPropertyName("m_outputRange")]
    public CNmGraphDocFloatRemapNode_RemapRange_t M_outputRange { get; set; }  // +0x108
}

/// <summary>CNmGraphDocFloatRemapNode::RemapRange_t, 8 bytes</summary>
public class CNmGraphDocFloatRemapNode_RemapRange_t
{
    [JsonPropertyName("m_flBegin")]
    public float M_flBegin { get; set; }  // +0x0
    [JsonPropertyName("m_flEnd")]
    public float M_flEnd { get; set; }  // +0x4
}

/// <summary>CNmGraphDocFloatResultNode, 264 bytes</summary>
public class CNmGraphDocFloatResultNode : CNmGraphDocResultNode
{
}

/// <summary>CNmGraphDocFloatSelectorNode, 296 bytes</summary>
public class CNmGraphDocFloatSelectorNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_options")]
    public CNmGraphDocFloatSelectorNode_Option_t[] M_options { get; set; }  // +0x100
    [JsonPropertyName("m_flDefaultValue")]
    public float M_flDefaultValue { get; set; }  // +0x118
    [JsonPropertyName("m_easing")]
    public NmEasingOperation_t M_easing { get; set; }  // +0x11C
    [JsonPropertyName("m_easeTime")]
    public float M_easeTime { get; set; }  // +0x120
}

/// <summary>CNmGraphDocFloatSelectorNode::Option_t, 16 bytes</summary>
public class CNmGraphDocFloatSelectorNode_Option_t
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x0
    [JsonPropertyName("m_flValue")]
    public float M_flValue { get; set; }  // +0x8
}

/// <summary>CNmGraphDocFloatSpringNode, 272 bytes</summary>
public class CNmGraphDocFloatSpringNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_flHertz")]
    public float M_flHertz { get; set; }  // +0x100
    [JsonPropertyName("m_flDampingRatio")]
    public float M_flDampingRatio { get; set; }  // +0x104
    [JsonPropertyName("m_bUseStartValue")]
    public bool M_bUseStartValue { get; set; }  // +0x108
    [JsonPropertyName("m_flStartValue")]
    public float M_flStartValue { get; set; }  // +0x10C
}

/// <summary>CNmGraphDocFloatSwitchNode, 264 bytes</summary>
public class CNmGraphDocFloatSwitchNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_flFalseValue")]
    public float M_flFalseValue { get; set; }  // +0x100
    [JsonPropertyName("m_flTrueValue")]
    public float M_flTrueValue { get; set; }  // +0x104
}

/// <summary>CNmGraphDocFloatVirtualParameterNode, 264 bytes</summary>
public class CNmGraphDocFloatVirtualParameterNode : CNmGraphDocVirtualParameterNode
{
}

/// <summary>CNmGraphDocFlowGraph, 104 bytes</summary>
public class CNmGraphDocFlowGraph : CNmGraphDocGraph
{
    [JsonPropertyName("m_connections")]
    public CNmGraphDocFlowGraph_Connection_t[] M_connections { get; set; }  // +0x50
}

/// <summary>CNmGraphDocFlowGraph::Connection_t, 80 bytes</summary>
public class CNmGraphDocFlowGraph_Connection_t
{
    [JsonPropertyName("m_ID")]
    public Guid M_ID { get; set; }  // +0x0
    [JsonPropertyName("m_fromNodeID")]
    public Guid M_fromNodeID { get; set; }  // +0x10
    [JsonPropertyName("m_outputPinID")]
    public Guid M_outputPinID { get; set; }  // +0x20
    [JsonPropertyName("m_toNodeID")]
    public Guid M_toNodeID { get; set; }  // +0x30
    [JsonPropertyName("m_inputPinID")]
    public Guid M_inputPinID { get; set; }  // +0x40
}

/// <summary>CNmGraphDocFlowNode, 256 bytes</summary>
public class CNmGraphDocFlowNode : CNmGraphDocNode
{
    [JsonPropertyName("m_inputPins")]
    public NmGraphDocPin_t[] M_inputPins { get; set; }  // +0x50
    [JsonPropertyName("m_outputPins")]
    public NmGraphDocPin_t[] M_outputPins { get; set; }  // +0xD8
}

/// <summary>CnmGraphDocFollowBoneNode, 520 bytes</summary>
public class CnmGraphDocFollowBoneNode : CNmGraphDocVariationDataNode
{
    [JsonPropertyName("m_mode")]
    public NmFollowBoneMode_t M_mode { get; set; }  // +0x200
}

/// <summary>CnmGraphDocFollowBoneNode::CData, 24 bytes</summary>
public class CnmGraphDocFollowBoneNode_CData : CNmGraphDocVariationDataNode_CData
{
    [JsonPropertyName("m_boneName")]
    public string M_boneName { get; set; }  // +0x8
    [JsonPropertyName("m_followTargetBoneName")]
    public string M_followTargetBoneName { get; set; }  // +0x10
}

/// <summary>CNmGraphDocFootEventConditionNode, 264 bytes</summary>
public class CNmGraphDocFootEventConditionNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_phaseCondition")]
    public NmFootPhaseCondition_t M_phaseCondition { get; set; }  // +0x100
    [JsonPropertyName("m_bLimitSearchToSourceState")]
    public bool M_bLimitSearchToSourceState { get; set; }  // +0x101
    [JsonPropertyName("m_bIgnoreInactiveBranchEvents")]
    public bool M_bIgnoreInactiveBranchEvents { get; set; }  // +0x102
}

/// <summary>CnmGraphDocFootIKNode, 520 bytes</summary>
public class CnmGraphDocFootIKNode : CNmGraphDocVariationDataNode
{
    [JsonPropertyName("m_bIsTargetInWorldSpace")]
    public bool M_bIsTargetInWorldSpace { get; set; }  // +0x200
    [JsonPropertyName("m_blendMode")]
    public NmIKBlendMode_t M_blendMode { get; set; }  // +0x201
}

/// <summary>CnmGraphDocFootIKNode::CData, 32 bytes</summary>
public class CnmGraphDocFootIKNode_CData : CNmGraphDocVariationDataNode_CData
{
    [JsonPropertyName("m_leftEffectorBoneName")]
    public string M_leftEffectorBoneName { get; set; }  // +0x8
    [JsonPropertyName("m_rightEffectorBoneName")]
    public string M_rightEffectorBoneName { get; set; }  // +0x10
    [JsonPropertyName("m_flBlendTimeSeconds")]
    public float M_flBlendTimeSeconds { get; set; }  // +0x18
}

/// <summary>CNmGraphDocFootstepEventIDNode, 264 bytes</summary>
public class CNmGraphDocFootstepEventIDNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_priorityRule")]
    public NmEventPriorityRule_t M_priorityRule { get; set; }  // +0x100
    [JsonPropertyName("m_bLimitSearchToSourceState")]
    public bool M_bLimitSearchToSourceState { get; set; }  // +0x101
    [JsonPropertyName("m_bIgnoreInactiveBranchEvents")]
    public bool M_bIgnoreInactiveBranchEvents { get; set; }  // +0x102
}

/// <summary>CNmGraphDocFootstepEventPercentageThroughNode, 264 bytes</summary>
public class CNmGraphDocFootstepEventPercentageThroughNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_phaseCondition")]
    public NmFootPhaseCondition_t M_phaseCondition { get; set; }  // +0x100
    [JsonPropertyName("m_priorityRule")]
    public NmEventPriorityRule_t M_priorityRule { get; set; }  // +0x101
    [JsonPropertyName("m_bLimitSearchToSourceState")]
    public bool M_bLimitSearchToSourceState { get; set; }  // +0x102
    [JsonPropertyName("m_bIgnoreInactiveBranchEvents")]
    public bool M_bIgnoreInactiveBranchEvents { get; set; }  // +0x103
}

/// <summary>CNmGraphDocGlobalTransitionConduitNode, 80 bytes</summary>
public class CNmGraphDocGlobalTransitionConduitNode : CNmGraphDocStateMachineGraphNode
{
}

/// <summary>CNmGraphDocGlobalTransitionNode, 304 bytes</summary>
public class CNmGraphDocGlobalTransitionNode : CNmGraphDocTransitionNode
{
    [JsonPropertyName("m_stateID")]
    public Guid M_stateID { get; set; }  // +0x120
}

/// <summary>CNmGraphDocGraph, 80 bytes</summary>
public class CNmGraphDocGraph
{
    [JsonPropertyName("m_ID")]
    public Guid M_ID { get; set; }  // +0x8
    [JsonPropertyName("m_nodes")]
    public CNmGraphDocNode?[] M_nodes { get; set; }  // +0x20
    [JsonPropertyName("m_graphType")]
    public NmGraphDocGraphType_t M_graphType { get; set; }  // +0x38
    [JsonPropertyName("m_viewOffset")]
    public Vector2D M_viewOffset { get; set; }  // +0x3C
    [JsonPropertyName("m_flViewZoom")]
    public float M_flViewZoom { get; set; }  // +0x44
}

/// <summary>CNmGraphDocGraphEventConditionNode, 288 bytes</summary>
public class CNmGraphDocGraphEventConditionNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_operator")]
    public NmEventConditionOperator_t M_operator { get; set; }  // +0x100
    [JsonPropertyName("m_bLimitSearchToSourceState")]
    public bool M_bLimitSearchToSourceState { get; set; }  // +0x101
    [JsonPropertyName("m_bIgnoreInactiveBranchEvents")]
    public bool M_bIgnoreInactiveBranchEvents { get; set; }  // +0x102
    [JsonPropertyName("m_conditions")]
    public CNmGraphDocGraphEventConditionNode_Condition_t[] M_conditions { get; set; }  // +0x108
}

/// <summary>CNmGraphDocGraphEventConditionNode::Condition_t, 16 bytes</summary>
public class CNmGraphDocGraphEventConditionNode_Condition_t
{
    [JsonPropertyName("m_eventID")]
    public string M_eventID { get; set; }  // +0x0
    [JsonPropertyName("m_type")]
    public NmGraphEventTypeCondition_t M_type { get; set; }  // +0x8
}

/// <summary>CNmGraphDocIDBasedClipSelectorNode, 288 bytes</summary>
public class CNmGraphDocIDBasedClipSelectorNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_optionLabels")]
    public string[] M_optionLabels { get; set; }  // +0x100
    [JsonPropertyName("m_bIgnoreInvalidOptions")]
    public bool M_bIgnoreInvalidOptions { get; set; }  // +0x118
}

/// <summary>CNmGraphDocIDBasedSelectorNode, 288 bytes</summary>
public class CNmGraphDocIDBasedSelectorNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_optionLabels")]
    public string[] M_optionLabels { get; set; }  // +0x100
    [JsonPropertyName("m_bIgnoreInvalidOptions")]
    public bool M_bIgnoreInvalidOptions { get; set; }  // +0x118
}

/// <summary>CNmGraphDocIDComparisonNode, 288 bytes</summary>
public class CNmGraphDocIDComparisonNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_comparison")]
    public CNmIDComparisonNode_Comparison_t M_comparison { get; set; }  // +0x100
    [JsonPropertyName("m_values")]
    public string[] M_values { get; set; }  // +0x108
}

/// <summary>CNmGraphDocIDControlParameterNode, 336 bytes</summary>
public class CNmGraphDocIDControlParameterNode : CNmGraphDocControlParameterNode
{
    [JsonPropertyName("m_previewStartValue")]
    public string M_previewStartValue { get; set; }  // +0x118
    [JsonPropertyName("m_expectedValues")]
    public string[] M_expectedValues { get; set; }  // +0x120
}

/// <summary>CNmGraphDocIDEventConditionNode, 288 bytes</summary>
public class CNmGraphDocIDEventConditionNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_operator")]
    public NmEventConditionOperator_t M_operator { get; set; }  // +0x100
    [JsonPropertyName("m_searchRule")]
    public CNmGraphDocIDEventConditionNode_SearchRule_t M_searchRule { get; set; }  // +0x101
    [JsonPropertyName("m_bLimitSearchToSourceState")]
    public bool M_bLimitSearchToSourceState { get; set; }  // +0x102
    [JsonPropertyName("m_bIgnoreInactiveBranchEvents")]
    public bool M_bIgnoreInactiveBranchEvents { get; set; }  // +0x103
    [JsonPropertyName("m_eventIDs")]
    public string[] M_eventIDs { get; set; }  // +0x108
}

public enum CNmGraphDocIDEventConditionNode_SearchRule_t : byte
{
    SearchAll = 0,
    OnlySearchGraphEvents = 1,
    OnlySearchAnimEvents = 2,
}

/// <summary>CNmGraphDocIDEventNode, 272 bytes</summary>
public class CNmGraphDocIDEventNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_defaultValue")]
    public string M_defaultValue { get; set; }  // +0x100
    [JsonPropertyName("m_bLimitSearchToSourceState")]
    public bool M_bLimitSearchToSourceState { get; set; }  // +0x108
    [JsonPropertyName("m_priorityRule")]
    public NmEventPriorityRule_t M_priorityRule { get; set; }  // +0x109
    [JsonPropertyName("m_bIgnoreInactiveBranchEvents")]
    public bool M_bIgnoreInactiveBranchEvents { get; set; }  // +0x10A
}

/// <summary>CNmGraphDocIDEventPercentageThroughNode, 272 bytes</summary>
public class CNmGraphDocIDEventPercentageThroughNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_priorityRule")]
    public NmEventPriorityRule_t M_priorityRule { get; set; }  // +0x100
    [JsonPropertyName("m_bLimitSearchToSourceState")]
    public bool M_bLimitSearchToSourceState { get; set; }  // +0x101
    [JsonPropertyName("m_bIgnoreInactiveBranchEvents")]
    public bool M_bIgnoreInactiveBranchEvents { get; set; }  // +0x102
    [JsonPropertyName("m_eventID")]
    public string M_eventID { get; set; }  // +0x108
}

/// <summary>CNmGraphDocIDParameterReferenceNode, 304 bytes</summary>
public class CNmGraphDocIDParameterReferenceNode : CNmGraphDocParameterReferenceNode
{
}

/// <summary>CNmGraphDocIDResultNode, 264 bytes</summary>
public class CNmGraphDocIDResultNode : CNmGraphDocResultNode
{
}

/// <summary>CNmGraphDocIDSelectorNode, 288 bytes</summary>
public class CNmGraphDocIDSelectorNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_options")]
    public string[] M_options { get; set; }  // +0x100
    [JsonPropertyName("m_defaultID")]
    public string M_defaultID { get; set; }  // +0x118
}

/// <summary>CNmGraphDocIDSwitchNode, 272 bytes</summary>
public class CNmGraphDocIDSwitchNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_falseValue")]
    public string M_falseValue { get; set; }  // +0x100
    [JsonPropertyName("m_trueValue")]
    public string M_trueValue { get; set; }  // +0x108
}

/// <summary>CNmGraphDocIDToFloatNode, 288 bytes</summary>
public class CNmGraphDocIDToFloatNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_defaultValue")]
    public float M_defaultValue { get; set; }  // +0x100
    [JsonPropertyName("m_mappings")]
    public CNmGraphDocIDToFloatNode_Mapping_t[] M_mappings { get; set; }  // +0x108
}

/// <summary>CNmGraphDocIDToFloatNode::Mapping_t, 16 bytes</summary>
public class CNmGraphDocIDToFloatNode_Mapping_t
{
    [JsonPropertyName("m_ID")]
    public string M_ID { get; set; }  // +0x0
    [JsonPropertyName("m_value")]
    public float M_value { get; set; }  // +0x8
}

/// <summary>CNmGraphDocIDVirtualParameterNode, 264 bytes</summary>
public class CNmGraphDocIDVirtualParameterNode : CNmGraphDocVirtualParameterNode
{
}

/// <summary>CNmGraphDocIsExternalGraphSlotFilledNode, 264 bytes</summary>
public class CNmGraphDocIsExternalGraphSlotFilledNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_slotID")]
    public string M_slotID { get; set; }  // +0x100
}

/// <summary>CNmGraphDocIsExternalPoseSetNode, 264 bytes</summary>
public class CNmGraphDocIsExternalPoseSetNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_slotID")]
    public string M_slotID { get; set; }  // +0x100
}

/// <summary>CNmGraphDocIsInactiveBranchConditionNode, 256 bytes</summary>
public class CNmGraphDocIsInactiveBranchConditionNode : CNmGraphDocFlowNode
{
}

/// <summary>CNmGraphDocIsTargetSetNode, 256 bytes</summary>
public class CNmGraphDocIsTargetSetNode : CNmGraphDocFlowNode
{
}

/// <summary>CNmGraphDocLayerBaseNode, 264 bytes</summary>
public class CNmGraphDocLayerBaseNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_isSynchronized")]
    public bool M_isSynchronized { get; set; }  // +0x100
    [JsonPropertyName("m_ignoreEvents")]
    public bool M_ignoreEvents { get; set; }  // +0x101
    [JsonPropertyName("m_blendMode")]
    public NmPoseBlendMode_t M_blendMode { get; set; }  // +0x102
}

/// <summary>CNmGraphDocLayerBlendNode, 264 bytes</summary>
public class CNmGraphDocLayerBlendNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_onlySampleBaseRootMotion")]
    public bool M_onlySampleBaseRootMotion { get; set; }  // +0x100
}

/// <summary>CNmGraphDocLocalLayerNode, 264 bytes</summary>
public class CNmGraphDocLocalLayerNode : CNmGraphDocLayerBaseNode
{
}

/// <summary>CNmGraphDocNode, 80 bytes</summary>
public class CNmGraphDocNode
{
    [JsonPropertyName("m_ID")]
    public Guid M_ID { get; set; }  // +0x8
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x18
    [JsonPropertyName("m_floatingComment")]
    public string M_floatingComment { get; set; }  // +0x20
    [JsonPropertyName("m_position")]
    public Vector2D M_position { get; set; }  // +0x28
    [JsonPropertyName("m_pChildGraph")]
    public CNmGraphDocGraph? M_pChildGraph { get; set; }  // +0x40
    [JsonPropertyName("m_pSecondaryGraph")]
    public CNmGraphDocGraph? M_pSecondaryGraph { get; set; }  // +0x48
}

/// <summary>CNmGraphDocNotNode, 256 bytes</summary>
public class CNmGraphDocNotNode : CNmGraphDocFlowNode
{
}

/// <summary>CNmGraphDocOrientationWarpNode, 264 bytes</summary>
public class CNmGraphDocOrientationWarpNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_offsetType")]
    public CNmGraphDocOrientationWarpNode_OffsetType_t M_offsetType { get; set; }  // +0x100
    [JsonPropertyName("m_samplingMode")]
    public CNmRootMotionData_SamplingMode_t M_samplingMode { get; set; }  // +0x104
    [JsonPropertyName("m_bWarpTranslation")]
    public bool M_bWarpTranslation { get; set; }  // +0x105
}

public enum CNmGraphDocOrientationWarpNode_OffsetType_t : uint
{
    RelativeToCharacter = 0,
    RelativeToOriginalRootMotion = 1,
}

/// <summary>CNmGraphDocOrNode, 256 bytes</summary>
public class CNmGraphDocOrNode : CNmGraphDocFlowNode
{
}

/// <summary>CNmGraphDocParameterBaseNode, 264 bytes</summary>
public class CNmGraphDocParameterBaseNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_groupName")]
    public string M_groupName { get; set; }  // +0x100
}

/// <summary>CNmGraphDocParameterizedClipSelectorNode, 544 bytes</summary>
public class CNmGraphDocParameterizedClipSelectorNode : CNmGraphDocVariationDataNode
{
    [JsonPropertyName("m_optionLabels")]
    public string[] M_optionLabels { get; set; }  // +0x200
    [JsonPropertyName("m_bIgnoreInvalidOptions")]
    public bool M_bIgnoreInvalidOptions { get; set; }  // +0x218
}

/// <summary>CNmGraphDocParameterizedClipSelectorNode::CData, 32 bytes</summary>
public class CNmGraphDocParameterizedClipSelectorNode_CData : CNmGraphDocVariationDataNode_CData
{
    [JsonPropertyName("m_optionWeights")]
    public byte[] M_optionWeights { get; set; }  // +0x8
}

/// <summary>CNmGraphDocParameterizedSelectorNode, 544 bytes</summary>
public class CNmGraphDocParameterizedSelectorNode : CNmGraphDocVariationDataNode
{
    [JsonPropertyName("m_optionLabels")]
    public string[] M_optionLabels { get; set; }  // +0x200
    [JsonPropertyName("m_bIgnoreInvalidOptions")]
    public bool M_bIgnoreInvalidOptions { get; set; }  // +0x218
}

/// <summary>CNmGraphDocParameterizedSelectorNode::CData, 32 bytes</summary>
public class CNmGraphDocParameterizedSelectorNode_CData : CNmGraphDocVariationDataNode_CData
{
    [JsonPropertyName("m_optionWeights")]
    public byte[] M_optionWeights { get; set; }  // +0x8
}

/// <summary>CNmGraphDocParameterReferenceNode, 304 bytes</summary>
public class CNmGraphDocParameterReferenceNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_parameterUUID")]
    public Guid M_parameterUUID { get; set; }  // +0x108
    [JsonPropertyName("m_parameterValueType")]
    public NmGraphValueType_t M_parameterValueType { get; set; }  // +0x118
    [JsonPropertyName("m_parameterName")]
    public string M_parameterName { get; set; }  // +0x120
    [JsonPropertyName("m_parameterGroupName")]
    public string M_parameterGroupName { get; set; }  // +0x128
}

/// <summary>CNmGraphDocPoseResultNode, 264 bytes</summary>
public class CNmGraphDocPoseResultNode : CNmGraphDocResultNode
{
}

/// <summary>CNmGraphDocReferencedGraphNode, 512 bytes</summary>
public class CNmGraphDocReferencedGraphNode : CNmGraphDocVariationDataNode
{
}

/// <summary>CNmGraphDocReferencedGraphNode::CData, 16 bytes</summary>
public class CNmGraphDocReferencedGraphNode_CData : CNmGraphDocVariationDataNode_CData
{
    [JsonPropertyName("m_variation")]
    public string M_variation { get; set; }  // +0x8
}

/// <summary>CNmGraphDocReferencePoseNode, 256 bytes</summary>
public class CNmGraphDocReferencePoseNode : CNmGraphDocFlowNode
{
}

/// <summary>CNmGraphDocResultNode, 264 bytes</summary>
public class CNmGraphDocResultNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_resultType")]
    public NmGraphValueType_t M_resultType { get; set; }  // +0x100
}

/// <summary>CNmGraphDocRootMotionOverrideNode, 272 bytes</summary>
public class CNmGraphDocRootMotionOverrideNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_flMaxLinearVelocity")]
    public float M_flMaxLinearVelocity { get; set; }  // +0x100
    [JsonPropertyName("m_flMaxAngularVelocityDegrees")]
    public float M_flMaxAngularVelocityDegrees { get; set; }  // +0x104
    [JsonPropertyName("m_bOverrideMoveDirX")]
    public bool M_bOverrideMoveDirX { get; set; }  // +0x108
    [JsonPropertyName("m_bOverrideMoveDirY")]
    public bool M_bOverrideMoveDirY { get; set; }  // +0x109
    [JsonPropertyName("m_bOverrideMoveDirZ")]
    public bool M_bOverrideMoveDirZ { get; set; }  // +0x10A
    [JsonPropertyName("m_bAllowPitchForFacing")]
    public bool M_bAllowPitchForFacing { get; set; }  // +0x10B
    [JsonPropertyName("m_bListenForRootMotionEvents")]
    public bool M_bListenForRootMotionEvents { get; set; }  // +0x10C
}

/// <summary>CNmGraphDocScaleNode, 256 bytes</summary>
public class CNmGraphDocScaleNode : CNmGraphDocFlowNode
{
}

/// <summary>CNmGraphDocSelectorBaseNode, 280 bytes</summary>
public class CNmGraphDocSelectorBaseNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_optionLabels")]
    public string[] M_optionLabels { get; set; }  // +0x100
}

/// <summary>CNmGraphDocSelectorConditionNode, 264 bytes</summary>
public class CNmGraphDocSelectorConditionNode : CNmGraphDocResultNode
{
}

/// <summary>CNmGraphDocSelectorNode, 280 bytes</summary>
public class CNmGraphDocSelectorNode : CNmGraphDocSelectorBaseNode
{
}

/// <summary>CnmGraphDocSpeedScaleNode, 264 bytes</summary>
public class CnmGraphDocSpeedScaleNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_flMultiplier")]
    public float M_flMultiplier { get; set; }  // +0x100
}

/// <summary>CNmGraphDocStateCompletedConditionNode, 256 bytes</summary>
public class CNmGraphDocStateCompletedConditionNode : CNmGraphDocFlowNode
{
}

/// <summary>CNmGraphDocStateLayerDataNode, 264 bytes</summary>
public class CNmGraphDocStateLayerDataNode : CNmGraphDocResultNode
{
}

/// <summary>CNmGraphDocStateMachineGraph, 96 bytes</summary>
public class CNmGraphDocStateMachineGraph : CNmGraphDocGraph
{
    [JsonPropertyName("m_entryStateID")]
    public Guid M_entryStateID { get; set; }  // +0x50
}

/// <summary>CNmGraphDocStateMachineGraphNode, 80 bytes</summary>
public class CNmGraphDocStateMachineGraphNode : CNmGraphDocNode
{
}

/// <summary>CNmGraphDocStateMachineLayerNode, 264 bytes</summary>
public class CNmGraphDocStateMachineLayerNode : CNmGraphDocLayerBaseNode
{
}

/// <summary>CNmGraphDocStateMachineNode, 256 bytes</summary>
public class CNmGraphDocStateMachineNode : CNmGraphDocFlowNode
{
}

/// <summary>CNmGraphDocStateNode, 304 bytes</summary>
public class CNmGraphDocStateNode : CNmGraphDocStateMachineGraphNode
{
    [JsonPropertyName("m_type")]
    public CNmGraphDocStateNode_StateType_t M_type { get; set; }  // +0x50
    [JsonPropertyName("m_cloneSourceStateID")]
    public Guid M_cloneSourceStateID { get; set; }  // +0x54
    [JsonPropertyName("m_stateEvents")]
    public CNmGraphDocStateNode_StateEvent_t[] M_stateEvents { get; set; }  // +0x68
    [JsonPropertyName("m_timedStateEvents")]
    public CNmGraphDocStateNode_TimedStateEvent_t[] M_timedStateEvents { get; set; }  // +0x80
    [JsonPropertyName("m_events")]
    public string[] M_events { get; set; }  // +0x98
    [JsonPropertyName("m_entryEvents")]
    public string[] M_entryEvents { get; set; }  // +0xB0
    [JsonPropertyName("m_executeEvents")]
    public string[] M_executeEvents { get; set; }  // +0xC8
    [JsonPropertyName("m_exitEvents")]
    public string[] M_exitEvents { get; set; }  // +0xE0
    [JsonPropertyName("m_timeRemainingEvents")]
    public CNmGraphDocStateNode_TimedStateEvent_t[] M_timeRemainingEvents { get; set; }  // +0xF8
    [JsonPropertyName("m_timeElapsedEvents")]
    public CNmGraphDocStateNode_TimedStateEvent_t[] M_timeElapsedEvents { get; set; }  // +0x110
    [JsonPropertyName("m_bUseActualElapsedTimeInStateForTimedEvents")]
    public bool M_bUseActualElapsedTimeInStateForTimedEvents { get; set; }  // +0x128
}

/// <summary>CNmGraphDocStateNode::StateEvent_t, 16 bytes</summary>
public class CNmGraphDocStateNode_StateEvent_t
{
    [JsonPropertyName("m_ID")]
    public string M_ID { get; set; }  // +0x0
    [JsonPropertyName("m_bIsEntry")]
    public bool M_bIsEntry { get; set; }  // +0x8
    [JsonPropertyName("m_bIsFullyInState")]
    public bool M_bIsFullyInState { get; set; }  // +0x9
    [JsonPropertyName("m_bIsExit")]
    public bool M_bIsExit { get; set; }  // +0xA
}

public enum CNmGraphDocStateNode_StateType_t : uint
{
    OffState = 0,
    BlendTreeState = 1,
    StateMachineState = 2,
    Clone = 3,
}

/// <summary>CNmGraphDocStateNode::TimedStateEvent_t, 24 bytes</summary>
public class CNmGraphDocStateNode_TimedStateEvent_t
{
    [JsonPropertyName("m_ID")]
    public string M_ID { get; set; }  // +0x0
    [JsonPropertyName("m_type")]
    public CNmGraphDocStateNode_TimedStateEventType_t M_type { get; set; }  // +0x8
    [JsonPropertyName("m_comparisonOperator")]
    public CNmStateNode_TimedEvent_t_Comparison_t M_comparisonOperator { get; set; }  // +0xC
    [JsonPropertyName("m_flTimeValueSeconds")]
    public float M_flTimeValueSeconds { get; set; }  // +0x10
}

public enum CNmGraphDocStateNode_TimedStateEventType_t : uint
{
    TimeElapsed = 0,
    TimeRemaining = 1,
}

/// <summary>CNmGraphDocSyncEventIndexConditionNode, 264 bytes</summary>
public class CNmGraphDocSyncEventIndexConditionNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_triggerMode")]
    public CNmSyncEventIndexConditionNode_TriggerMode_t M_triggerMode { get; set; }  // +0x100
    [JsonPropertyName("m_nSyncEventIdx")]
    public int M_nSyncEventIdx { get; set; }  // +0x104
}

/// <summary>CNmGraphDocTargetControlParameterNode, 320 bytes</summary>
public class CNmGraphDocTargetControlParameterNode : CNmGraphDocControlParameterNode
{
    [JsonPropertyName("m_bIsSet")]
    public bool M_bIsSet { get; set; }  // +0x118
    [JsonPropertyName("m_bIsBoneID")]
    public bool M_bIsBoneID { get; set; }  // +0x119
    [JsonPropertyName("m_targetOrientation")]
    public QAngle M_targetOrientation { get; set; }  // +0x11C
    [JsonPropertyName("m_targetPosition")]
    public Vector M_targetPosition { get; set; }  // +0x128
    [JsonPropertyName("m_previewStartBoneID")]
    public string M_previewStartBoneID { get; set; }  // +0x138
}

/// <summary>CNmGraphDocTargetInfoNode, 264 bytes</summary>
public class CNmGraphDocTargetInfoNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_infoType")]
    public CNmTargetInfoNode_Info_t M_infoType { get; set; }  // +0x100
    [JsonPropertyName("m_bIsWorldSpaceTarget")]
    public bool M_bIsWorldSpaceTarget { get; set; }  // +0x104
}

/// <summary>CNmGraphDocTargetOffsetNode, 288 bytes</summary>
public class CNmGraphDocTargetOffsetNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_bIsBoneSpaceOffset")]
    public bool M_bIsBoneSpaceOffset { get; set; }  // +0x100
    [JsonPropertyName("m_rotationOffset")]
    public QAngle M_rotationOffset { get; set; }  // +0x104
    [JsonPropertyName("m_translationOffset")]
    public Vector M_translationOffset { get; set; }  // +0x110
}

/// <summary>CNmGraphDocTargetParameterReferenceNode, 304 bytes</summary>
public class CNmGraphDocTargetParameterReferenceNode : CNmGraphDocParameterReferenceNode
{
}

/// <summary>CNmGraphDocTargetPointNode, 264 bytes</summary>
public class CNmGraphDocTargetPointNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_bIsWorldSpaceTarget")]
    public bool M_bIsWorldSpaceTarget { get; set; }  // +0x100
}

/// <summary>CNmGraphDocTargetResultNode, 264 bytes</summary>
public class CNmGraphDocTargetResultNode : CNmGraphDocResultNode
{
}

/// <summary>CNmGraphDocTargetSelectorNode, 296 bytes</summary>
public class CNmGraphDocTargetSelectorNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_optionLabels")]
    public string[] M_optionLabels { get; set; }  // +0x100
    [JsonPropertyName("m_flOrientationScoreWeight")]
    public float M_flOrientationScoreWeight { get; set; }  // +0x118
    [JsonPropertyName("m_flPositionScoreWeight")]
    public float M_flPositionScoreWeight { get; set; }  // +0x11C
    [JsonPropertyName("m_bIsWorldSpaceTarget")]
    public bool M_bIsWorldSpaceTarget { get; set; }  // +0x120
    [JsonPropertyName("m_bIgnoreInvalidOptions")]
    public bool M_bIgnoreInvalidOptions { get; set; }  // +0x121
}

/// <summary>CNmGraphDocTargetVirtualParameterNode, 264 bytes</summary>
public class CNmGraphDocTargetVirtualParameterNode : CNmGraphDocVirtualParameterNode
{
}

/// <summary>CNmGraphDocTargetWarpNode, 536 bytes</summary>
public class CNmGraphDocTargetWarpNode : CNmGraphDocVariationDataNode
{
    [JsonPropertyName("m_targetUpdateRule")]
    public CNmTargetWarpNode_TargetUpdateRule_t M_targetUpdateRule { get; set; }  // +0x200
    [JsonPropertyName("m_bAllowTargetUpdate")]
    public bool M_bAllowTargetUpdate { get; set; }  // +0x201
    [JsonPropertyName("m_bAlignWithTargetAtLastWarpEvent")]
    public bool M_bAlignWithTargetAtLastWarpEvent { get; set; }  // +0x202
    [JsonPropertyName("m_samplingMode")]
    public CNmRootMotionData_SamplingMode_t M_samplingMode { get; set; }  // +0x203
    [JsonPropertyName("m_flSamplingPositionErrorThreshold")]
    public float M_flSamplingPositionErrorThreshold { get; set; }  // +0x204
    [JsonPropertyName("m_flMaxTangentLength")]
    public float M_flMaxTangentLength { get; set; }  // +0x208
    [JsonPropertyName("m_flLerpFallbackDistanceThreshold")]
    public float M_flLerpFallbackDistanceThreshold { get; set; }  // +0x20C
    [JsonPropertyName("m_flTargetUpdateDistanceThresholdDegrees")]
    public float M_flTargetUpdateDistanceThresholdDegrees { get; set; }  // +0x210
    [JsonPropertyName("m_flTargetUpdateAngleThresholdDegrees")]
    public float M_flTargetUpdateAngleThresholdDegrees { get; set; }  // +0x214
}

/// <summary>CNmGraphDocTargetWarpNode::CData, 16 bytes</summary>
public class CNmGraphDocTargetWarpNode_CData : CNmGraphDocVariationDataNode_CData
{
    [JsonPropertyName("m_strAlignmentBoneName")]
    public string M_strAlignmentBoneName { get; set; }  // +0x8
}

/// <summary>CNmGraphDocTimeConditionNode, 264 bytes</summary>
public class CNmGraphDocTimeConditionNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_flComparand")]
    public float M_flComparand { get; set; }  // +0x100
    [JsonPropertyName("m_type")]
    public CNmTimeConditionNode_ComparisonType_t M_type { get; set; }  // +0x104
    [JsonPropertyName("m_operator")]
    public CNmTimeConditionNode_Operator_t M_operator { get; set; }  // +0x105
}

/// <summary>CNmGraphDocTransitionConduitNode, 112 bytes</summary>
public class CNmGraphDocTransitionConduitNode : CNmGraphDocStateMachineGraphNode
{
    [JsonPropertyName("m_startStateID")]
    public Guid M_startStateID { get; set; }  // +0x50
    [JsonPropertyName("m_endStateID")]
    public Guid M_endStateID { get; set; }  // +0x60
}

/// <summary>CNmGraphDocTransitionEventConditionNode, 280 bytes</summary>
public class CNmGraphDocTransitionEventConditionNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_ruleCondition")]
    public NmTransitionRuleCondition_t M_ruleCondition { get; set; }  // +0x100
    [JsonPropertyName("m_bMatchOnlySpecificMarkerID")]
    public bool M_bMatchOnlySpecificMarkerID { get; set; }  // +0x101
    [JsonPropertyName("m_markerIDToMatch")]
    public string M_markerIDToMatch { get; set; }  // +0x108
    [JsonPropertyName("m_bLimitSearchToSourceState")]
    public bool M_bLimitSearchToSourceState { get; set; }  // +0x110
    [JsonPropertyName("m_bIgnoreInactiveBranchEvents")]
    public bool M_bIgnoreInactiveBranchEvents { get; set; }  // +0x111
}

/// <summary>CNmGraphDocTransitionNode, 288 bytes</summary>
public class CNmGraphDocTransitionNode : CNmGraphDocResultNode
{
    [JsonPropertyName("m_flDurationSeconds")]
    public float M_flDurationSeconds { get; set; }  // +0x108
    [JsonPropertyName("m_bClampDurationToSource")]
    public bool M_bClampDurationToSource { get; set; }  // +0x10C
    [JsonPropertyName("m_rootMotionBlend")]
    public NmRootMotionBlendMode_t M_rootMotionBlend { get; set; }  // +0x10D
    [JsonPropertyName("m_blendWeightEasing")]
    public NmEasingOperation_t M_blendWeightEasing { get; set; }  // +0x10E
    [JsonPropertyName("m_flBoneMaskBlendInTimePercentage")]
    public float M_flBoneMaskBlendInTimePercentage { get; set; }  // +0x110
    [JsonPropertyName("m_timeMatchMode")]
    public CNmGraphDocTransitionNode_TimeMatchMode_t M_timeMatchMode { get; set; }  // +0x114
    [JsonPropertyName("m_flTimeOffset")]
    public float M_flTimeOffset { get; set; }  // +0x118
    [JsonPropertyName("m_bCanBeForced")]
    public bool M_bCanBeForced { get; set; }  // +0x11C
}

public enum CNmGraphDocTransitionNode_TimeMatchMode_t : uint
{
    None = 0,
    Synchronized = 1,
    MatchSourceSyncEventIndex = 2,
    MatchSourceSyncEventPercentage = 3,
    MatchSourceSyncEventIndexAndPercentage = 4,
    MatchSyncEventID = 5,
    MatchClosestSyncEventID = 6,
    MatchSyncEventIDAndPercentage = 7,
    MatchClosestSyncEventIDAndPercentage = 8,
    MatchTimeInSeconds = 9,
    OffsetTimeInSeconds = 10,
}

/// <summary>CnmGraphDocTwoBoneIKNode, 520 bytes</summary>
public class CnmGraphDocTwoBoneIKNode : CNmGraphDocVariationDataNode
{
    [JsonPropertyName("m_bIsTargetInWorldSpace")]
    public bool M_bIsTargetInWorldSpace { get; set; }  // +0x200
    [JsonPropertyName("m_blendMode")]
    public NmIKBlendMode_t M_blendMode { get; set; }  // +0x201
    [JsonPropertyName("m_flChainRotationWeight")]
    public float M_flChainRotationWeight { get; set; }  // +0x204
}

/// <summary>CnmGraphDocTwoBoneIKNode::CData, 24 bytes</summary>
public class CnmGraphDocTwoBoneIKNode_CData : CNmGraphDocVariationDataNode_CData
{
    [JsonPropertyName("m_effectorBoneName")]
    public string M_effectorBoneName { get; set; }  // +0x8
    [JsonPropertyName("m_flBlendTimeSeconds")]
    public float M_flBlendTimeSeconds { get; set; }  // +0x10
}

/// <summary>CNmGraphDocument, 184 bytes</summary>
public class CNmGraphDocument : CNmAnimDocument
{
    [JsonPropertyName("m_pRootGraph")]
    public CNmGraphDocFlowGraph? M_pRootGraph { get; set; }  // +0x70
    [JsonPropertyName("m_variationHierarchy")]
    public CNmVariationHierarchy M_variationHierarchy { get; set; }  // +0x78
    [JsonPropertyName("m_debugParameterSets")]
    public CNmGraphDocument_DebugParameterSet_t[] M_debugParameterSets { get; set; }  // +0x90
    [JsonPropertyName("m_dictionaryIDSetIDs")]
    public Guid[] M_dictionaryIDSetIDs { get; set; }  // +0xA0
}

/// <summary>CNmGraphDocument::DebugParameterSet_t, 88 bytes</summary>
public class CNmGraphDocument_DebugParameterSet_t
{
    [JsonPropertyName("m_ID")]
    public string M_ID { get; set; }  // +0x0
    [JsonPropertyName("m_boolValues")]
    public Dictionary<string, object> /* map */[] M_boolValues { get; set; }  // +0x8
    [JsonPropertyName("m_floatValues")]
    public Dictionary<string, object> /* map */[] M_floatValues { get; set; }  // +0x18
    [JsonPropertyName("m_IDValues")]
    public Dictionary<string, object> /* map */[] M_IDValues { get; set; }  // +0x28
    [JsonPropertyName("m_vectorValues")]
    public Dictionary<string, object> /* map */[] M_vectorValues { get; set; }  // +0x38
    [JsonPropertyName("m_targetValues")]
    public Dictionary<string, object> /* map */[] M_targetValues { get; set; }  // +0x48
}

/// <summary>CnmGraphDocVariationConstFloatNode, 512 bytes</summary>
public class CnmGraphDocVariationConstFloatNode : CNmGraphDocVariationDataNode
{
}

/// <summary>CnmGraphDocVariationConstFloatNode::CData, 16 bytes</summary>
public class CnmGraphDocVariationConstFloatNode_CData : CNmGraphDocVariationDataNode_CData
{
    [JsonPropertyName("m_flValue")]
    public float M_flValue { get; set; }  // +0x8
}

/// <summary>CNmGraphDocVariationDataNode, 512 bytes</summary>
public class CNmGraphDocVariationDataNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_pDefaultVariationData")]
    public CNmGraphDocVariationDataNode_CData? M_pDefaultVariationData { get; set; }  // +0x100
    [JsonPropertyName("m_overrides")]
    public CNmGraphDocVariationDataNode_OverrideValue_t[] M_overrides { get; set; }  // +0x108
    [JsonPropertyName("m_defaultResourceName")]
    public string M_defaultResourceName { get; set; }  // +0x120
}

/// <summary>CNmGraphDocVariationDataNode::CData, 8 bytes</summary>
public class CNmGraphDocVariationDataNode_CData
{
}

/// <summary>CNmGraphDocVariationDataNode::OverrideValue_t, 16 bytes</summary>
public class CNmGraphDocVariationDataNode_OverrideValue_t
{
    [JsonPropertyName("m_variationID")]
    public string M_variationID { get; set; }  // +0x0
    [JsonPropertyName("m_pData")]
    public CNmGraphDocVariationDataNode_CData? M_pData { get; set; }  // +0x8
}

/// <summary>CNmGraphDocVariationIDComparisonNode, 520 bytes</summary>
public class CNmGraphDocVariationIDComparisonNode : CNmGraphDocVariationDataNode
{
    [JsonPropertyName("m_comparison")]
    public CNmIDComparisonNode_Comparison_t M_comparison { get; set; }  // +0x200
}

/// <summary>CNmGraphDocVariationIDComparisonNode::CData, 32 bytes</summary>
public class CNmGraphDocVariationIDComparisonNode_CData : CNmGraphDocVariationDataNode_CData
{
    [JsonPropertyName("m_values")]
    public string[] M_values { get; set; }  // +0x8
}

/// <summary>CNmGraphDocVectorControlParameterNode, 296 bytes</summary>
public class CNmGraphDocVectorControlParameterNode : CNmGraphDocControlParameterNode
{
    [JsonPropertyName("m_previewStartValue")]
    public Vector M_previewStartValue { get; set; }  // +0x118
}

/// <summary>CNmGraphDocVectorCreateNode, 256 bytes</summary>
public class CNmGraphDocVectorCreateNode : CNmGraphDocFlowNode
{
}

/// <summary>CNmGraphDocVectorInfoNode, 264 bytes</summary>
public class CNmGraphDocVectorInfoNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_desiredInfo")]
    public CNmVectorInfoNode_Info_t M_desiredInfo { get; set; }  // +0x100
}

/// <summary>CNmGraphDocVectorNegateNode, 256 bytes</summary>
public class CNmGraphDocVectorNegateNode : CNmGraphDocFlowNode
{
}

/// <summary>CNmGraphDocVectorParameterReferenceNode, 304 bytes</summary>
public class CNmGraphDocVectorParameterReferenceNode : CNmGraphDocParameterReferenceNode
{
}

/// <summary>CNmGraphDocVectorResultNode, 264 bytes</summary>
public class CNmGraphDocVectorResultNode : CNmGraphDocResultNode
{
}

/// <summary>CNmGraphDocVectorVirtualParameterNode, 264 bytes</summary>
public class CNmGraphDocVectorVirtualParameterNode : CNmGraphDocVirtualParameterNode
{
}

/// <summary>CnmGraphDocVelocityBasedSpeedScaleNode, 264 bytes</summary>
public class CnmGraphDocVelocityBasedSpeedScaleNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_flDesiredVelocity")]
    public float M_flDesiredVelocity { get; set; }  // +0x100
}

/// <summary>CNmGraphDocVelocityBlendNode, 264 bytes</summary>
public class CNmGraphDocVelocityBlendNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_bAllowLooping")]
    public bool M_bAllowLooping { get; set; }  // +0x100
}

/// <summary>CNmGraphDocVirtualParameterNode, 264 bytes</summary>
public class CNmGraphDocVirtualParameterNode : CNmGraphDocParameterBaseNode
{
}

/// <summary>CNmGraphDocZeroPoseNode, 256 bytes</summary>
public class CNmGraphDocZeroPoseNode : CNmGraphDocFlowNode
{
}

/// <summary>CNmPreviewArchetype, 48 bytes</summary>
public class CNmPreviewArchetype
{
    [JsonPropertyName("m_primarySkeleton")]
    public string M_primarySkeleton { get; set; }  // +0x0
    [JsonPropertyName("m_previewModel")]
    public string M_previewModel { get; set; }  // +0x8
    [JsonPropertyName("m_bodyPartChoiceName")]
    public string M_bodyPartChoiceName { get; set; }  // +0x10
    [JsonPropertyName("m_secondarySkeletonSettings")]
    public CNmPreviewArchetype_SecondarySkeleton_t[] M_secondarySkeletonSettings { get; set; }  // +0x18
}

/// <summary>CNmPreviewArchetype::SecondarySkeleton_t, 32 bytes</summary>
public class CNmPreviewArchetype_SecondarySkeleton_t
{
    [JsonPropertyName("m_skeleton")]
    public string M_skeleton { get; set; }  // +0x0
    [JsonPropertyName("m_previewModel")]
    public string M_previewModel { get; set; }  // +0x8
    [JsonPropertyName("m_bodyPartChoiceName")]
    public string M_bodyPartChoiceName { get; set; }  // +0x10
    [JsonPropertyName("m_attachToBoneName")]
    public string M_attachToBoneName { get; set; }  // +0x18
}

/// <summary>CNmSkeletonDocument, 264 bytes</summary>
public class CNmSkeletonDocument : CNmAnimDocument
{
    [JsonPropertyName("m_sourceFilename")]
    public string M_sourceFilename { get; set; }  // +0x70
    [JsonPropertyName("m_rootBoneName")]
    public string M_rootBoneName { get; set; }  // +0x78
    [JsonPropertyName("m_flGlobalScale")]
    public float M_flGlobalScale { get; set; }  // +0x80
    [JsonPropertyName("m_bIsAttachableProp")]
    public bool M_bIsAttachableProp { get; set; }  // +0x84
    [JsonPropertyName("m_bIsCS_HACK")]
    public bool M_bIsCS_HACK { get; set; }  // +0x85
    [JsonPropertyName("m_secondarySkeletons")]
    public CNmSkeletonDocument_SecondarySkeleton_t[] M_secondarySkeletons { get; set; }  // +0x88
    [JsonPropertyName("m_gameplayRelevantBones")]
    public string[] M_gameplayRelevantBones { get; set; }  // +0xA0
    [JsonPropertyName("m_highLODBones")]
    public string[] M_highLODBones { get; set; }  // +0xB8
    [JsonPropertyName("m_boneMaskSetDefinitions")]
    public NmBoneMaskSetDefinition_t[] M_boneMaskSetDefinitions { get; set; }  // +0xD0
    [JsonPropertyName("m_previewModelName")]
    public string M_previewModelName { get; set; }  // +0xE8
}

/// <summary>CNmSkeletonDocument::SecondarySkeleton_t, 16 bytes</summary>
public class CNmSkeletonDocument_SecondarySkeleton_t
{
    [JsonPropertyName("m_skeleton")]
    public string M_skeleton { get; set; }  // +0x0
    [JsonPropertyName("m_attachToBoneID")]
    public string M_attachToBoneID { get; set; }  // +0x8
}

/// <summary>CNmVariationHierarchy, 24 bytes</summary>
public class CNmVariationHierarchy
{
    [JsonPropertyName("m_variations")]
    public NmVariation_t[] M_variations { get; set; }  // +0x0
}

public enum NmEventConditionOperator_t : byte
{
    Or = 0,
    And = 1,
}

public enum NmEventPriorityRule_t : byte
{
    HighestWeight = 0,
    HighestPercentageThrough = 1,
}

public enum NmGraphDocGraphType_t : uint
{
    Invalid = 0,
    BlendTree = 1,
    ValueTree = 2,
    StateMachine = 3,
    EntryOverrideTree = 4,
    TransitionConduit = 5,
    GlobalTransitionConduit = 6,
    VirtualParameterValueTree = 7,
}

/// <summary>NmGraphDocPin_t, 32 bytes</summary>
public class NmGraphDocPin_t
{
    [JsonPropertyName("m_ID")]
    public Guid M_ID { get; set; }  // +0x0
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x10
    [JsonPropertyName("m_type")]
    public NmGraphValueType_t M_type { get; set; }  // +0x18
    [JsonPropertyName("m_bIsDynamicPin")]
    public bool M_bIsDynamicPin { get; set; }  // +0x19
    [JsonPropertyName("m_bAllowMultipleOutConnections")]
    public bool M_bAllowMultipleOutConnections { get; set; }  // +0x1A
}

/// <summary>NmVariation_t, 248 bytes</summary>
public class NmVariation_t
{
    [JsonPropertyName("m_ID")]
    public string M_ID { get; set; }  // +0x0
    [JsonPropertyName("m_parentID")]
    public string M_parentID { get; set; }  // +0x8
    [JsonPropertyName("m_skeleton")]
    public string M_skeleton { get; set; }  // +0x10
    [JsonPropertyName("m_pUserData")]
    public CNmGraphVariationUserData? M_pUserData { get; set; }  // +0xF0
}

