// Auto-generated by cs2-codegen from schemas_jsonschema.json
// Revision 10638965 (May 06 2026) — https://github.com/ValveResourceFormat/DumpSource2
// Do not edit by hand.
// Module: animationsystem

#nullable enable
#pragma warning disable CS8618  // non-nullable property not initialized (expected in generated serialization types)

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CS2Schema;

/// <summary>AnimationDecodeDebugDump_t, 32 bytes</summary>
public class AnimationDecodeDebugDump_t
{
    [JsonPropertyName("m_processingType")]
    public AnimationProcessingType_t M_processingType { get; set; }  // +0x0
    [JsonPropertyName("m_elems")]
    public AnimationDecodeDebugDumpElement_t[] M_elems { get; set; }  // +0x8
}

/// <summary>AnimationDecodeDebugDumpElement_t, 112 bytes</summary>
public class AnimationDecodeDebugDumpElement_t
{
    [JsonPropertyName("m_nEntityIndex")]
    public int M_nEntityIndex { get; set; }  // +0x0
    [JsonPropertyName("m_modelName")]
    public string M_modelName { get; set; }  // +0x8
    [JsonPropertyName("m_poseParams")]
    public string[] M_poseParams { get; set; }  // +0x10
    [JsonPropertyName("m_decodeOps")]
    public string[] M_decodeOps { get; set; }  // +0x28
    [JsonPropertyName("m_internalOps")]
    public string[] M_internalOps { get; set; }  // +0x40
    [JsonPropertyName("m_decodedAnims")]
    public string[] M_decodedAnims { get; set; }  // +0x58
}

public enum AnimationProcessingType_t : uint
{
    ANIMATION_PROCESSING_SERVER_SIMULATION = 0,
    ANIMATION_PROCESSING_CLIENT_SIMULATION = 1,
    ANIMATION_PROCESSING_CLIENT_PREDICTION = 2,
    ANIMATION_PROCESSING_CLIENT_INTERPOLATION = 3,
    ANIMATION_PROCESSING_CLIENT_RENDER = 4,
    ANIMATION_PROCESSING_MAX = 5,
}

/// <summary>AnimationSnapshot_t, 288 bytes</summary>
public class AnimationSnapshot_t : AnimationSnapshotBase_t
{
    [JsonPropertyName("m_nEntIndex")]
    public int M_nEntIndex { get; set; }  // +0x110
    [JsonPropertyName("m_modelName")]
    public string M_modelName { get; set; }  // +0x118
}

/// <summary>AnimationSnapshotBase_t, 272 bytes</summary>
public class AnimationSnapshotBase_t
{
    [JsonPropertyName("m_flRealTime")]
    public float M_flRealTime { get; set; }  // +0x0
    [JsonPropertyName("m_rootToWorld")]
    public matrix3x4a_t M_rootToWorld { get; set; }  // +0x10
    [JsonPropertyName("m_bBonesInWorldSpace")]
    public bool M_bBonesInWorldSpace { get; set; }  // +0x40
    [JsonPropertyName("m_boneSetupMask")]
    public uint[] M_boneSetupMask { get; set; }  // +0x48
    [JsonPropertyName("m_boneTransforms")]
    public matrix3x4a_t[] M_boneTransforms { get; set; }  // +0x60
    [JsonPropertyName("m_flexControllers")]
    public float[] M_flexControllers { get; set; }  // +0x78
    [JsonPropertyName("m_SnapshotType")]
    public AnimationSnapshotType_t M_SnapshotType { get; set; }  // +0x90
    [JsonPropertyName("m_bHasDecodeDump")]
    public bool M_bHasDecodeDump { get; set; }  // +0x94
    [JsonPropertyName("m_DecodeDump")]
    public AnimationDecodeDebugDumpElement_t M_DecodeDump { get; set; }  // +0x98
}

public enum AnimationSnapshotType_t : uint
{
    ANIMATION_SNAPSHOT_SERVER_SIMULATION = 0,
    ANIMATION_SNAPSHOT_CLIENT_SIMULATION = 1,
    ANIMATION_SNAPSHOT_CLIENT_PREDICTION = 2,
    ANIMATION_SNAPSHOT_CLIENT_INTERPOLATION = 3,
    ANIMATION_SNAPSHOT_CLIENT_RENDER = 4,
    ANIMATION_SNAPSHOT_FINAL_COMPOSITE = 5,
    ANIMATION_SNAPSHOT_MAX = 6,
}

public enum BoneTransformSpace_t : uint
{
    BoneTransformSpace_Invalid = 4294967295,
    BoneTransformSpace_Parent = 0,
    BoneTransformSpace_Model = 1,
    BoneTransformSpace_World = 2,
}

/// <summary>CAnimActivity, 32 bytes</summary>
public class CAnimActivity
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x0
    [JsonPropertyName("m_nActivity")]
    public int M_nActivity { get; set; }  // +0x10
    [JsonPropertyName("m_nFlags")]
    public int M_nFlags { get; set; }  // +0x14
    [JsonPropertyName("m_nWeight")]
    public int M_nWeight { get; set; }  // +0x18
}

/// <summary>CAnimationGroup, 328 bytes</summary>
public class CAnimationGroup
{
    [JsonPropertyName("m_nFlags")]
    public uint M_nFlags { get; set; }  // +0x10
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x18
    [JsonPropertyName("m_localHAnimArray_Handle")]
    public InfoForResourceTypeCAnimData?[] M_localHAnimArray_Handle { get; set; }  // +0x60
    [JsonPropertyName("m_includedGroupArray_Handle")]
    public InfoForResourceTypeCAnimationGroup?[] M_includedGroupArray_Handle { get; set; }  // +0x78
    [JsonPropertyName("m_directHSeqGroup_Handle")]
    public InfoForResourceTypeCSequenceGroupData? M_directHSeqGroup_Handle { get; set; }  // +0x90
    [JsonPropertyName("m_decodeKey")]
    public CAnimKeyData M_decodeKey { get; set; }  // +0x98
    [JsonPropertyName("m_szScripts")]
    public string[] M_szScripts { get; set; }  // +0x110
    [JsonPropertyName("m_AdditionalExtRefs")]
    public object /* opaque */[] M_AdditionalExtRefs { get; set; }  // +0x128
}

/// <summary>CAnimBone, 72 bytes</summary>
public class CAnimBone
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x0
    [JsonPropertyName("m_parent")]
    public int M_parent { get; set; }  // +0x10
    [JsonPropertyName("m_pos")]
    public Vector M_pos { get; set; }  // +0x14
    [JsonPropertyName("m_quat")]
    public QuaternionStorage M_quat { get; set; }  // +0x20
    [JsonPropertyName("m_scale")]
    public float M_scale { get; set; }  // +0x30
    [JsonPropertyName("m_qAlignment")]
    public QuaternionStorage M_qAlignment { get; set; }  // +0x34
    [JsonPropertyName("m_flags")]
    public int M_flags { get; set; }  // +0x44
}

/// <summary>CAnimBoneDifference, 48 bytes</summary>
public class CAnimBoneDifference
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x0
    [JsonPropertyName("m_parent")]
    public string M_parent { get; set; }  // +0x10
    [JsonPropertyName("m_posError")]
    public Vector M_posError { get; set; }  // +0x20
    [JsonPropertyName("m_bHasRotation")]
    public bool M_bHasRotation { get; set; }  // +0x2C
    [JsonPropertyName("m_bHasMovement")]
    public bool M_bHasMovement { get; set; }  // +0x2D
}

/// <summary>CAnimData, 112 bytes</summary>
public class CAnimData
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x10
    [JsonPropertyName("m_animArray")]
    public CAnimDesc[] M_animArray { get; set; }  // +0x20
    [JsonPropertyName("m_decoderArray")]
    public CAnimDecoder[] M_decoderArray { get; set; }  // +0x38
    [JsonPropertyName("m_nMaxUniqueFrameIndex")]
    public int M_nMaxUniqueFrameIndex { get; set; }  // +0x50
    [JsonPropertyName("m_segmentArray")]
    public CAnimFrameSegment[] M_segmentArray { get; set; }  // +0x58
}

/// <summary>CAnimDataChannelDesc, 144 bytes</summary>
public class CAnimDataChannelDesc
{
    [JsonPropertyName("m_szChannelClass")]
    public string M_szChannelClass { get; set; }  // +0x0
    [JsonPropertyName("m_szVariableName")]
    public string M_szVariableName { get; set; }  // +0x10
    [JsonPropertyName("m_nFlags")]
    public int M_nFlags { get; set; }  // +0x20
    [JsonPropertyName("m_nType")]
    public int M_nType { get; set; }  // +0x24
    [JsonPropertyName("m_szGrouping")]
    public string M_szGrouping { get; set; }  // +0x28
    [JsonPropertyName("m_szDescription")]
    public string M_szDescription { get; set; }  // +0x38
    [JsonPropertyName("m_szElementNameArray")]
    public string[] M_szElementNameArray { get; set; }  // +0x48
    [JsonPropertyName("m_nElementIndexArray")]
    public int[] M_nElementIndexArray { get; set; }  // +0x60
    [JsonPropertyName("m_nElementMaskArray")]
    public uint[] M_nElementMaskArray { get; set; }  // +0x78
}

/// <summary>CAnimDecoder, 24 bytes</summary>
public class CAnimDecoder
{
    [JsonPropertyName("m_szName")]
    public string M_szName { get; set; }  // +0x0
    [JsonPropertyName("m_nVersion")]
    public int M_nVersion { get; set; }  // +0x10
    [JsonPropertyName("m_nType")]
    public int M_nType { get; set; }  // +0x14
}

/// <summary>CAnimDesc, 464 bytes</summary>
public class CAnimDesc
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x0
    [JsonPropertyName("m_flags")]
    public CAnimDesc_Flag M_flags { get; set; }  // +0x10
    [JsonPropertyName("fps")]
    public float Fps { get; set; }  // +0x18
    [JsonPropertyName("m_Data")]
    public CAnimEncodedFrames M_Data { get; set; }  // +0x20
    [JsonPropertyName("m_movementArray")]
    public CAnimMovement[] M_movementArray { get; set; }  // +0xF8
    [JsonPropertyName("m_xInitialOffset")]
    public CTransform M_xInitialOffset { get; set; }  // +0x110
    [JsonPropertyName("m_eventArray")]
    public CAnimEventDefinition[] M_eventArray { get; set; }  // +0x130
    [JsonPropertyName("m_activityArray")]
    public CAnimActivity[] M_activityArray { get; set; }  // +0x148
    [JsonPropertyName("m_hierarchyArray")]
    public CAnimLocalHierarchy[] M_hierarchyArray { get; set; }  // +0x160
    [JsonPropertyName("framestalltime")]
    public float Framestalltime { get; set; }  // +0x178
    [JsonPropertyName("m_vecRootMin")]
    public Vector M_vecRootMin { get; set; }  // +0x17C
    [JsonPropertyName("m_vecRootMax")]
    public Vector M_vecRootMax { get; set; }  // +0x188
    [JsonPropertyName("m_vecBoneWorldMin")]
    public Vector[] M_vecBoneWorldMin { get; set; }  // +0x198
    [JsonPropertyName("m_vecBoneWorldMax")]
    public Vector[] M_vecBoneWorldMax { get; set; }  // +0x1B0
    [JsonPropertyName("m_sequenceParams")]
    public CAnimSequenceParams M_sequenceParams { get; set; }  // +0x1C8
}

/// <summary>CAnimDesc_Flag, 8 bytes</summary>
public class CAnimDesc_Flag
{
    [JsonPropertyName("m_bLooping")]
    public bool M_bLooping { get; set; }  // +0x0
    [JsonPropertyName("m_bAllZeros")]
    public bool M_bAllZeros { get; set; }  // +0x1
    [JsonPropertyName("m_bHidden")]
    public bool M_bHidden { get; set; }  // +0x2
    [JsonPropertyName("m_bDelta")]
    public bool M_bDelta { get; set; }  // +0x3
    [JsonPropertyName("m_bLegacyWorldspace")]
    public bool M_bLegacyWorldspace { get; set; }  // +0x4
    [JsonPropertyName("m_bModelDoc")]
    public bool M_bModelDoc { get; set; }  // +0x5
    [JsonPropertyName("m_bImplicitSeqIgnoreDelta")]
    public bool M_bImplicitSeqIgnoreDelta { get; set; }  // +0x6
    [JsonPropertyName("m_bAnimGraphAdditive")]
    public bool M_bAnimGraphAdditive { get; set; }  // +0x7
}

/// <summary>CAnimEncodedFrames, 216 bytes</summary>
public class CAnimEncodedFrames
{
    [JsonPropertyName("m_fileName")]
    public string M_fileName { get; set; }  // +0x0
    [JsonPropertyName("m_nFrames")]
    public int M_nFrames { get; set; }  // +0x10
    [JsonPropertyName("m_nFramesPerBlock")]
    public int M_nFramesPerBlock { get; set; }  // +0x14
    [JsonPropertyName("m_frameblockArray")]
    public CAnimFrameBlockAnim[] M_frameblockArray { get; set; }  // +0x18
    [JsonPropertyName("m_usageDifferences")]
    public CAnimEncodeDifference M_usageDifferences { get; set; }  // +0x30
}

/// <summary>CAnimEncodeDifference, 168 bytes</summary>
public class CAnimEncodeDifference
{
    [JsonPropertyName("m_boneArray")]
    public CAnimBoneDifference[] M_boneArray { get; set; }  // +0x0
    [JsonPropertyName("m_morphArray")]
    public CAnimMorphDifference[] M_morphArray { get; set; }  // +0x18
    [JsonPropertyName("m_userArray")]
    public CAnimUserDifference[] M_userArray { get; set; }  // +0x30
    [JsonPropertyName("m_bHasRotationBitArray")]
    public byte[] M_bHasRotationBitArray { get; set; }  // +0x48
    [JsonPropertyName("m_bHasMovementBitArray")]
    public byte[] M_bHasMovementBitArray { get; set; }  // +0x60
    [JsonPropertyName("m_bHasMorphBitArray")]
    public byte[] M_bHasMorphBitArray { get; set; }  // +0x78
    [JsonPropertyName("m_bHasUserBitArray")]
    public byte[] M_bHasUserBitArray { get; set; }  // +0x90
}

/// <summary>CAnimEnum, 1 bytes</summary>
public class CAnimEnum
{
    [JsonPropertyName("m_value")]
    public byte M_value { get; set; }  // +0x0
}

/// <summary>CAnimEventDefinition, 64 bytes</summary>
public class CAnimEventDefinition
{
    [JsonPropertyName("m_nFrame")]
    public int M_nFrame { get; set; }  // +0x8
    [JsonPropertyName("m_nEndFrame")]
    public int M_nEndFrame { get; set; }  // +0xC
    [JsonPropertyName("m_flCycle")]
    public float M_flCycle { get; set; }  // +0x10
    [JsonPropertyName("m_flDuration")]
    public float M_flDuration { get; set; }  // +0x14
    [JsonPropertyName("m_EventData")]
    public object /* opaque */ M_EventData { get; set; }  // +0x18
    [JsonPropertyName("m_sLegacyOptions")]
    public string M_sLegacyOptions { get; set; }  // +0x28
    [JsonPropertyName("m_sEventName")]
    public string M_sEventName { get; set; }  // +0x38
}

/// <summary>CAnimFrameBlockAnim, 32 bytes</summary>
public class CAnimFrameBlockAnim
{
    [JsonPropertyName("m_nStartFrame")]
    public int M_nStartFrame { get; set; }  // +0x0
    [JsonPropertyName("m_nEndFrame")]
    public int M_nEndFrame { get; set; }  // +0x4
    [JsonPropertyName("m_segmentIndexArray")]
    public int[] M_segmentIndexArray { get; set; }  // +0x8
}

/// <summary>CAnimFrameSegment, 32 bytes</summary>
public class CAnimFrameSegment
{
    [JsonPropertyName("m_nUniqueFrameIndex")]
    public int M_nUniqueFrameIndex { get; set; }  // +0x0
    [JsonPropertyName("m_nLocalElementMasks")]
    public uint M_nLocalElementMasks { get; set; }  // +0x4
    [JsonPropertyName("m_nLocalChannel")]
    public int M_nLocalChannel { get; set; }  // +0x8
    [JsonPropertyName("m_container")]
    public object /* opaque */ M_container { get; set; }  // +0x10
}

/// <summary>CAnimKeyData, 120 bytes</summary>
public class CAnimKeyData
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x0
    [JsonPropertyName("m_boneArray")]
    public CAnimBone[] M_boneArray { get; set; }  // +0x10
    [JsonPropertyName("m_userArray")]
    public CAnimUser[] M_userArray { get; set; }  // +0x28
    [JsonPropertyName("m_morphArray")]
    public string[] M_morphArray { get; set; }  // +0x40
    [JsonPropertyName("m_nChannelElements")]
    public int M_nChannelElements { get; set; }  // +0x58
    [JsonPropertyName("m_dataChannelArray")]
    public CAnimDataChannelDesc[] M_dataChannelArray { get; set; }  // +0x60
}

/// <summary>CAnimLocalHierarchy, 48 bytes</summary>
public class CAnimLocalHierarchy
{
    [JsonPropertyName("m_sBone")]
    public string M_sBone { get; set; }  // +0x0
    [JsonPropertyName("m_sNewParent")]
    public string M_sNewParent { get; set; }  // +0x10
    [JsonPropertyName("m_nStartFrame")]
    public int M_nStartFrame { get; set; }  // +0x20
    [JsonPropertyName("m_nPeakFrame")]
    public int M_nPeakFrame { get; set; }  // +0x24
    [JsonPropertyName("m_nTailFrame")]
    public int M_nTailFrame { get; set; }  // +0x28
    [JsonPropertyName("m_nEndFrame")]
    public int M_nEndFrame { get; set; }  // +0x2C
}

/// <summary>CAnimMorphDifference, 16 bytes</summary>
public class CAnimMorphDifference
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x0
}

/// <summary>CAnimMovement, 44 bytes</summary>
public class CAnimMovement
{
    [JsonPropertyName("endframe")]
    public int Endframe { get; set; }  // +0x0
    [JsonPropertyName("motionflags")]
    public int Motionflags { get; set; }  // +0x4
    [JsonPropertyName("v0")]
    public float V0 { get; set; }  // +0x8
    [JsonPropertyName("v1")]
    public float V1 { get; set; }  // +0xC
    [JsonPropertyName("angle")]
    public float Angle { get; set; }  // +0x10
    [JsonPropertyName("vector")]
    public Vector Vector { get; set; }  // +0x14
    [JsonPropertyName("position")]
    public Vector Position { get; set; }  // +0x20
}

/// <summary>CAnimSequenceParams, 8 bytes</summary>
public class CAnimSequenceParams
{
    [JsonPropertyName("m_flFadeInTime")]
    public float M_flFadeInTime { get; set; }  // +0x0
    [JsonPropertyName("m_flFadeOutTime")]
    public float M_flFadeOutTime { get; set; }  // +0x4
}

/// <summary>CAnimUser, 24 bytes</summary>
public class CAnimUser
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x0
    [JsonPropertyName("m_nType")]
    public int M_nType { get; set; }  // +0x10
}

/// <summary>CAnimUserDifference, 24 bytes</summary>
public class CAnimUserDifference
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x0
    [JsonPropertyName("m_nType")]
    public int M_nType { get; set; }  // +0x10
}

/// <summary>CCompressorGroup, 416 bytes</summary>
public class CCompressorGroup
{
    [JsonPropertyName("m_nTotalElementCount")]
    public int M_nTotalElementCount { get; set; }  // +0x0
    [JsonPropertyName("m_szChannelClass")]
    public sbyte?[] M_szChannelClass { get; set; }  // +0x8
    [JsonPropertyName("m_szVariableName")]
    public sbyte?[] M_szVariableName { get; set; }  // +0x20
    [JsonPropertyName("m_nType")]
    public fieldtype_t[] M_nType { get; set; }  // +0x38
    [JsonPropertyName("m_nFlags")]
    public int[] M_nFlags { get; set; }  // +0x50
    [JsonPropertyName("m_szGrouping")]
    public string[] M_szGrouping { get; set; }  // +0x68
    [JsonPropertyName("m_nCompressorIndex")]
    public int[] M_nCompressorIndex { get; set; }  // +0x80
    [JsonPropertyName("m_szElementNames")]
    public sbyte?[][] M_szElementNames { get; set; }  // +0x98
    [JsonPropertyName("m_nElementUniqueID")]
    public int[][] M_nElementUniqueID { get; set; }  // +0xB0
    [JsonPropertyName("m_nElementMask")]
    public uint[] M_nElementMask { get; set; }  // +0xC8
    [JsonPropertyName("m_vectorCompressor")]
    public object /* opaque */?[] M_vectorCompressor { get; set; }  // +0xF8
    [JsonPropertyName("m_quaternionCompressor")]
    public object /* opaque */?[] M_quaternionCompressor { get; set; }  // +0x110
    [JsonPropertyName("m_intCompressor")]
    public object /* opaque */?[] M_intCompressor { get; set; }  // +0x128
    [JsonPropertyName("m_boolCompressor")]
    public object /* opaque */?[] M_boolCompressor { get; set; }  // +0x140
    [JsonPropertyName("m_colorCompressor")]
    public object /* opaque */?[] M_colorCompressor { get; set; }  // +0x158
    [JsonPropertyName("m_vector2DCompressor")]
    public object /* opaque */?[] M_vector2DCompressor { get; set; }  // +0x170
    [JsonPropertyName("m_vector4DCompressor")]
    public object /* opaque */?[] M_vector4DCompressor { get; set; }  // +0x188
}

/// <summary>CMoodVData, 256 bytes</summary>
public class CMoodVData
{
    [JsonPropertyName("m_sModelName")]
    public string M_sModelName { get; set; }  // +0x0
    [JsonPropertyName("m_nMoodType")]
    public MoodType_t M_nMoodType { get; set; }  // +0xE0
    [JsonPropertyName("m_animationLayers")]
    public MoodAnimationLayer_t[] M_animationLayers { get; set; }  // +0xE8
}

/// <summary>CSeqAutoLayer, 28 bytes</summary>
public class CSeqAutoLayer
{
    [JsonPropertyName("m_nLocalReference")]
    public short M_nLocalReference { get; set; }  // +0x0
    [JsonPropertyName("m_nLocalPose")]
    public short M_nLocalPose { get; set; }  // +0x2
    [JsonPropertyName("m_flags")]
    public CSeqAutoLayerFlag M_flags { get; set; }  // +0x4
    [JsonPropertyName("m_start")]
    public float M_start { get; set; }  // +0xC
    [JsonPropertyName("m_peak")]
    public float M_peak { get; set; }  // +0x10
    [JsonPropertyName("m_tail")]
    public float M_tail { get; set; }  // +0x14
    [JsonPropertyName("m_end")]
    public float M_end { get; set; }  // +0x18
}

/// <summary>CSeqAutoLayerFlag, 8 bytes</summary>
public class CSeqAutoLayerFlag
{
    [JsonPropertyName("m_bPost")]
    public bool M_bPost { get; set; }  // +0x0
    [JsonPropertyName("m_bSpline")]
    public bool M_bSpline { get; set; }  // +0x1
    [JsonPropertyName("m_bXFade")]
    public bool M_bXFade { get; set; }  // +0x2
    [JsonPropertyName("m_bNoBlend")]
    public bool M_bNoBlend { get; set; }  // +0x3
    [JsonPropertyName("m_bLocal")]
    public bool M_bLocal { get; set; }  // +0x4
    [JsonPropertyName("m_bPose")]
    public bool M_bPose { get; set; }  // +0x5
    [JsonPropertyName("m_bFetchFrame")]
    public bool M_bFetchFrame { get; set; }  // +0x6
    [JsonPropertyName("m_bSubtract")]
    public bool M_bSubtract { get; set; }  // +0x7
}

/// <summary>CSeqBoneMaskList, 96 bytes</summary>
public class CSeqBoneMaskList
{
    [JsonPropertyName("m_sName")]
    public string M_sName { get; set; }  // +0x0
    [JsonPropertyName("m_nLocalBoneArray")]
    public short[] M_nLocalBoneArray { get; set; }  // +0x10
    [JsonPropertyName("m_flBoneWeightArray")]
    public float[] M_flBoneWeightArray { get; set; }  // +0x28
    [JsonPropertyName("m_flDefaultMorphCtrlWeight")]
    public float M_flDefaultMorphCtrlWeight { get; set; }  // +0x40
    [JsonPropertyName("m_morphCtrlWeightArray")]
    public Dictionary<string, object> /* map */[] M_morphCtrlWeightArray { get; set; }  // +0x48
}

/// <summary>CSeqCmdLayer, 24 bytes</summary>
public class CSeqCmdLayer
{
    [JsonPropertyName("m_cmd")]
    public short M_cmd { get; set; }  // +0x0
    [JsonPropertyName("m_nLocalReference")]
    public short M_nLocalReference { get; set; }  // +0x2
    [JsonPropertyName("m_nLocalBonemask")]
    public short M_nLocalBonemask { get; set; }  // +0x4
    [JsonPropertyName("m_nDstResult")]
    public short M_nDstResult { get; set; }  // +0x6
    [JsonPropertyName("m_nSrcResult")]
    public short M_nSrcResult { get; set; }  // +0x8
    [JsonPropertyName("m_bSpline")]
    public bool M_bSpline { get; set; }  // +0xA
    [JsonPropertyName("m_flVar1")]
    public float M_flVar1 { get; set; }  // +0xC
    [JsonPropertyName("m_flVar2")]
    public float M_flVar2 { get; set; }  // +0x10
    [JsonPropertyName("m_nLineNumber")]
    public short M_nLineNumber { get; set; }  // +0x14
}

/// <summary>CSeqCmdSeqDesc, 144 bytes</summary>
public class CSeqCmdSeqDesc
{
    [JsonPropertyName("m_sName")]
    public string M_sName { get; set; }  // +0x0
    [JsonPropertyName("m_flags")]
    public CSeqSeqDescFlag M_flags { get; set; }  // +0x10
    [JsonPropertyName("m_transition")]
    public CSeqTransition M_transition { get; set; }  // +0x1C
    [JsonPropertyName("m_nFrameRangeSequence")]
    public short M_nFrameRangeSequence { get; set; }  // +0x24
    [JsonPropertyName("m_nFrameCount")]
    public short M_nFrameCount { get; set; }  // +0x26
    [JsonPropertyName("m_flFPS")]
    public float M_flFPS { get; set; }  // +0x28
    [JsonPropertyName("m_nSubCycles")]
    public short M_nSubCycles { get; set; }  // +0x2C
    [JsonPropertyName("m_numLocalResults")]
    public short M_numLocalResults { get; set; }  // +0x2E
    [JsonPropertyName("m_cmdLayerArray")]
    public CSeqCmdLayer[] M_cmdLayerArray { get; set; }  // +0x30
    [JsonPropertyName("m_eventArray")]
    public CAnimEventDefinition[] M_eventArray { get; set; }  // +0x48
    [JsonPropertyName("m_activityArray")]
    public CAnimActivity[] M_activityArray { get; set; }  // +0x60
    [JsonPropertyName("m_poseSettingArray")]
    public CSeqPoseSetting[] M_poseSettingArray { get; set; }  // +0x78
}

/// <summary>CSeqIKLock, 12 bytes</summary>
public class CSeqIKLock
{
    [JsonPropertyName("m_flPosWeight")]
    public float M_flPosWeight { get; set; }  // +0x0
    [JsonPropertyName("m_flAngleWeight")]
    public float M_flAngleWeight { get; set; }  // +0x4
    [JsonPropertyName("m_nLocalBone")]
    public short M_nLocalBone { get; set; }  // +0x8
    [JsonPropertyName("m_bBonesOrientedAlongPositiveX")]
    public bool M_bBonesOrientedAlongPositiveX { get; set; }  // +0xA
}

/// <summary>CSeqMultiFetch, 112 bytes</summary>
public class CSeqMultiFetch
{
    [JsonPropertyName("m_flags")]
    public CSeqMultiFetchFlag M_flags { get; set; }  // +0x0
    [JsonPropertyName("m_localReferenceArray")]
    public short[] M_localReferenceArray { get; set; }  // +0x8
    [JsonPropertyName("m_nGroupSize")]
    public int[] M_nGroupSize { get; set; }  // +0x20
    [JsonPropertyName("m_nLocalPose")]
    public int[] M_nLocalPose { get; set; }  // +0x28
    [JsonPropertyName("m_poseKeyArray0")]
    public float[] M_poseKeyArray0 { get; set; }  // +0x30
    [JsonPropertyName("m_poseKeyArray1")]
    public float[] M_poseKeyArray1 { get; set; }  // +0x48
    [JsonPropertyName("m_nLocalCyclePoseParameter")]
    public int M_nLocalCyclePoseParameter { get; set; }  // +0x60
    [JsonPropertyName("m_bCalculatePoseParameters")]
    public bool M_bCalculatePoseParameters { get; set; }  // +0x64
    [JsonPropertyName("m_bFixedBlendWeight")]
    public bool M_bFixedBlendWeight { get; set; }  // +0x65
    [JsonPropertyName("m_flFixedBlendWeightVals")]
    public float[] M_flFixedBlendWeightVals { get; set; }  // +0x68
}

/// <summary>CSeqMultiFetchFlag, 6 bytes</summary>
public class CSeqMultiFetchFlag
{
    [JsonPropertyName("m_bRealtime")]
    public bool M_bRealtime { get; set; }  // +0x0
    [JsonPropertyName("m_bCylepose")]
    public bool M_bCylepose { get; set; }  // +0x1
    [JsonPropertyName("m_b0D")]
    public bool M_b0D { get; set; }  // +0x2
    [JsonPropertyName("m_b1D")]
    public bool M_b1D { get; set; }  // +0x3
    [JsonPropertyName("m_b2D")]
    public bool M_b2D { get; set; }  // +0x4
    [JsonPropertyName("m_b2D_TRI")]
    public bool M_b2D_TRI { get; set; }  // +0x5
}

/// <summary>CSeqPoseParamDesc, 32 bytes</summary>
public class CSeqPoseParamDesc
{
    [JsonPropertyName("m_sName")]
    public string M_sName { get; set; }  // +0x0
    [JsonPropertyName("m_flStart")]
    public float M_flStart { get; set; }  // +0x10
    [JsonPropertyName("m_flEnd")]
    public float M_flEnd { get; set; }  // +0x14
    [JsonPropertyName("m_flLoop")]
    public float M_flLoop { get; set; }  // +0x18
    [JsonPropertyName("m_bLooping")]
    public bool M_bLooping { get; set; }  // +0x1C
}

/// <summary>CSeqPoseSetting, 64 bytes</summary>
public class CSeqPoseSetting
{
    [JsonPropertyName("m_sPoseParameter")]
    public string M_sPoseParameter { get; set; }  // +0x0
    [JsonPropertyName("m_sAttachment")]
    public string M_sAttachment { get; set; }  // +0x10
    [JsonPropertyName("m_sReferenceSequence")]
    public string M_sReferenceSequence { get; set; }  // +0x20
    [JsonPropertyName("m_flValue")]
    public float M_flValue { get; set; }  // +0x30
    [JsonPropertyName("m_bX")]
    public bool M_bX { get; set; }  // +0x34
    [JsonPropertyName("m_bY")]
    public bool M_bY { get; set; }  // +0x35
    [JsonPropertyName("m_bZ")]
    public bool M_bZ { get; set; }  // +0x36
    [JsonPropertyName("m_eType")]
    public int M_eType { get; set; }  // +0x38
}

/// <summary>CSeqS1SeqDesc, 288 bytes</summary>
public class CSeqS1SeqDesc
{
    [JsonPropertyName("m_sName")]
    public string M_sName { get; set; }  // +0x0
    [JsonPropertyName("m_flags")]
    public CSeqSeqDescFlag M_flags { get; set; }  // +0x10
    [JsonPropertyName("m_fetch")]
    public CSeqMultiFetch M_fetch { get; set; }  // +0x20
    [JsonPropertyName("m_nLocalWeightlist")]
    public int M_nLocalWeightlist { get; set; }  // +0x90
    [JsonPropertyName("m_autoLayerArray")]
    public CSeqAutoLayer[] M_autoLayerArray { get; set; }  // +0x98
    [JsonPropertyName("m_IKLockArray")]
    public CSeqIKLock[] M_IKLockArray { get; set; }  // +0xB0
    [JsonPropertyName("m_transition")]
    public CSeqTransition M_transition { get; set; }  // +0xC8
    [JsonPropertyName("m_SequenceKeys")]
    public object /* opaque */ M_SequenceKeys { get; set; }  // +0xD0
    [JsonPropertyName("m_LegacyKeyValueText")]
    public string M_LegacyKeyValueText { get; set; }  // +0xE0
    [JsonPropertyName("m_activityArray")]
    public CAnimActivity[] M_activityArray { get; set; }  // +0xF0
    [JsonPropertyName("m_footMotion")]
    public CFootMotion[] M_footMotion { get; set; }  // +0x108
}

/// <summary>CSeqScaleSet, 80 bytes</summary>
public class CSeqScaleSet
{
    [JsonPropertyName("m_sName")]
    public string M_sName { get; set; }  // +0x0
    [JsonPropertyName("m_bRootOffset")]
    public bool M_bRootOffset { get; set; }  // +0x10
    [JsonPropertyName("m_vRootOffset")]
    public Vector M_vRootOffset { get; set; }  // +0x14
    [JsonPropertyName("m_nLocalBoneArray")]
    public short[] M_nLocalBoneArray { get; set; }  // +0x20
    [JsonPropertyName("m_flBoneScaleArray")]
    public float[] M_flBoneScaleArray { get; set; }  // +0x38
}

/// <summary>CSeqSeqDescFlag, 11 bytes</summary>
public class CSeqSeqDescFlag
{
    [JsonPropertyName("m_bLooping")]
    public bool M_bLooping { get; set; }  // +0x0
    [JsonPropertyName("m_bSnap")]
    public bool M_bSnap { get; set; }  // +0x1
    [JsonPropertyName("m_bAutoplay")]
    public bool M_bAutoplay { get; set; }  // +0x2
    [JsonPropertyName("m_bPost")]
    public bool M_bPost { get; set; }  // +0x3
    [JsonPropertyName("m_bHidden")]
    public bool M_bHidden { get; set; }  // +0x4
    [JsonPropertyName("m_bMulti")]
    public bool M_bMulti { get; set; }  // +0x5
    [JsonPropertyName("m_bLegacyDelta")]
    public bool M_bLegacyDelta { get; set; }  // +0x6
    [JsonPropertyName("m_bLegacyWorldspace")]
    public bool M_bLegacyWorldspace { get; set; }  // +0x7
    [JsonPropertyName("m_bLegacyCyclepose")]
    public bool M_bLegacyCyclepose { get; set; }  // +0x8
    [JsonPropertyName("m_bLegacyRealtime")]
    public bool M_bLegacyRealtime { get; set; }  // +0x9
    [JsonPropertyName("m_bModelDoc")]
    public bool M_bModelDoc { get; set; }  // +0xA
}

/// <summary>CSeqSynthAnimDesc, 64 bytes</summary>
public class CSeqSynthAnimDesc
{
    [JsonPropertyName("m_sName")]
    public string M_sName { get; set; }  // +0x0
    [JsonPropertyName("m_flags")]
    public CSeqSeqDescFlag M_flags { get; set; }  // +0x10
    [JsonPropertyName("m_transition")]
    public CSeqTransition M_transition { get; set; }  // +0x1C
    [JsonPropertyName("m_nLocalBaseReference")]
    public short M_nLocalBaseReference { get; set; }  // +0x24
    [JsonPropertyName("m_nLocalBoneMask")]
    public short M_nLocalBoneMask { get; set; }  // +0x26
    [JsonPropertyName("m_activityArray")]
    public CAnimActivity[] M_activityArray { get; set; }  // +0x28
}

/// <summary>CSeqTransition, 8 bytes</summary>
public class CSeqTransition
{
    [JsonPropertyName("m_flFadeInTime")]
    public float M_flFadeInTime { get; set; }  // +0x0
    [JsonPropertyName("m_flFadeOutTime")]
    public float M_flFadeOutTime { get; set; }  // +0x4
}

/// <summary>CSequenceGroupData, 312 bytes</summary>
public class CSequenceGroupData
{
    [JsonPropertyName("m_sName")]
    public string M_sName { get; set; }  // +0x10
    [JsonPropertyName("m_nFlags")]
    public uint M_nFlags { get; set; }  // +0x20
    [JsonPropertyName("m_localSequenceNameArray")]
    public string[] M_localSequenceNameArray { get; set; }  // +0x28
    [JsonPropertyName("m_localS1SeqDescArray")]
    public CSeqS1SeqDesc[] M_localS1SeqDescArray { get; set; }  // +0x40
    [JsonPropertyName("m_localMultiSeqDescArray")]
    public CSeqS1SeqDesc[] M_localMultiSeqDescArray { get; set; }  // +0x58
    [JsonPropertyName("m_localSynthAnimDescArray")]
    public CSeqSynthAnimDesc[] M_localSynthAnimDescArray { get; set; }  // +0x70
    [JsonPropertyName("m_localCmdSeqDescArray")]
    public CSeqCmdSeqDesc[] M_localCmdSeqDescArray { get; set; }  // +0x88
    [JsonPropertyName("m_localBoneMaskArray")]
    public CSeqBoneMaskList[] M_localBoneMaskArray { get; set; }  // +0xA0
    [JsonPropertyName("m_localScaleSetArray")]
    public CSeqScaleSet[] M_localScaleSetArray { get; set; }  // +0xB8
    [JsonPropertyName("m_localBoneNameArray")]
    public string[] M_localBoneNameArray { get; set; }  // +0xD0
    [JsonPropertyName("m_localNodeName")]
    public string M_localNodeName { get; set; }  // +0xE8
    [JsonPropertyName("m_localPoseParamArray")]
    public CSeqPoseParamDesc[] M_localPoseParamArray { get; set; }  // +0xF8
    [JsonPropertyName("m_keyValues")]
    public object /* opaque */ M_keyValues { get; set; }  // +0x110
    [JsonPropertyName("m_localIKAutoplayLockArray")]
    public CSeqIKLock[] M_localIKAutoplayLockArray { get; set; }  // +0x120
}

/// <summary>FollowAttachmentData, 8 bytes</summary>
public class FollowAttachmentData
{
    [JsonPropertyName("m_boneIndex")]
    public int M_boneIndex { get; set; }  // +0x0
    [JsonPropertyName("m_attachmentHandle")]
    public AttachmentHandle_t M_attachmentHandle { get; set; }  // +0x4
}

/// <summary>HSequence, 4 bytes</summary>
public class HSequence
{
    [JsonPropertyName("m_Value")]
    public int M_Value { get; set; }  // +0x0
}

/// <summary>MoodAnimation_t, 16 bytes</summary>
public class MoodAnimation_t
{
    [JsonPropertyName("m_sName")]
    public string M_sName { get; set; }  // +0x0
    [JsonPropertyName("m_flWeight")]
    public float M_flWeight { get; set; }  // +0x8
}

/// <summary>MoodAnimationLayer_t, 96 bytes</summary>
public class MoodAnimationLayer_t
{
    [JsonPropertyName("m_sName")]
    public string M_sName { get; set; }  // +0x0
    [JsonPropertyName("m_bActiveListening")]
    public bool M_bActiveListening { get; set; }  // +0x8
    [JsonPropertyName("m_bActiveTalking")]
    public bool M_bActiveTalking { get; set; }  // +0x9
    [JsonPropertyName("m_layerAnimations")]
    public MoodAnimation_t[] M_layerAnimations { get; set; }  // +0x10
    [JsonPropertyName("m_flIntensity")]
    public CRangeFloat M_flIntensity { get; set; }  // +0x28
    [JsonPropertyName("m_flDurationScale")]
    public CRangeFloat M_flDurationScale { get; set; }  // +0x30
    [JsonPropertyName("m_bScaleWithInts")]
    public bool M_bScaleWithInts { get; set; }  // +0x38
    [JsonPropertyName("m_flNextStart")]
    public CRangeFloat M_flNextStart { get; set; }  // +0x3C
    [JsonPropertyName("m_flStartOffset")]
    public CRangeFloat M_flStartOffset { get; set; }  // +0x44
    [JsonPropertyName("m_flEndOffset")]
    public CRangeFloat M_flEndOffset { get; set; }  // +0x4C
    [JsonPropertyName("m_flFadeIn")]
    public float M_flFadeIn { get; set; }  // +0x54
    [JsonPropertyName("m_flFadeOut")]
    public float M_flFadeOut { get; set; }  // +0x58
}

public enum MoodType_t : uint
{
    eMoodType_Head = 0,
    eMoodType_Body = 1,
}

public enum ParticleAttachment_t : uint
{
    PATTACH_INVALID = 4294967295,
    PATTACH_ABSORIGIN = 0,
    PATTACH_ABSORIGIN_FOLLOW = 1,
    PATTACH_CUSTOMORIGIN = 2,
    PATTACH_CUSTOMORIGIN_FOLLOW = 3,
    PATTACH_POINT = 4,
    PATTACH_POINT_FOLLOW = 5,
    PATTACH_EYES_FOLLOW = 6,
    PATTACH_OVERHEAD_FOLLOW = 7,
    PATTACH_WORLDORIGIN = 8,
    PATTACH_ROOTBONE_FOLLOW = 9,
    PATTACH_RENDERORIGIN_FOLLOW = 10,
    PATTACH_MAIN_VIEW = 11,
    PATTACH_WATERWAKE = 12,
    PATTACH_CENTER_FOLLOW = 13,
    PATTACH_CUSTOM_GAME_STATE_1 = 14,
    PATTACH_HEALTHBAR = 15,
    MAX_PATTACH_TYPES = 16,
}

public enum SeqCmd_t : uint
{
    SeqCmd_Nop = 0,
    SeqCmd_LinearDelta = 1,
    SeqCmd_FetchFrameRange = 2,
    SeqCmd_Slerp = 3,
    SeqCmd_Add = 4,
    SeqCmd_Subtract = 5,
    SeqCmd_Scale = 6,
    SeqCmd_Copy = 7,
    SeqCmd_Blend = 8,
    SeqCmd_Worldspace = 9,
    SeqCmd_Sequence = 10,
    SeqCmd_FetchCycle = 11,
    SeqCmd_FetchFrame = 12,
    SeqCmd_IKLockInPlace = 13,
    SeqCmd_IKRestoreAll = 14,
    SeqCmd_ReverseSequence = 15,
    SeqCmd_Transform = 16,
}

public enum SeqPoseSetting_t : uint
{
    SEQ_POSE_SETTING_CONSTANT = 0,
    SEQ_POSE_SETTING_ROTATION = 1,
    SEQ_POSE_SETTING_POSITION = 2,
    SEQ_POSE_SETTING_VELOCITY = 3,
}

