// Auto-generated by cs2-codegen from schemas_jsonschema.json
// Revision 10638965 (May 06 2026) — https://github.com/ValveResourceFormat/DumpSource2
// Do not edit by hand.
// Module: compositematerialslib

#nullable enable
#pragma warning disable CS8618  // non-nullable property not initialized (expected in generated serialization types)

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CS2Schema;

/// <summary>CCompositeMaterialEditorDoc, 56 bytes</summary>
public class CCompositeMaterialEditorDoc
{
    [JsonPropertyName("m_nVersion")]
    public int M_nVersion { get; set; }  // +0x8
    [JsonPropertyName("m_Points")]
    public CompositeMaterialEditorPoint_t[] M_Points { get; set; }  // +0x10
    [JsonPropertyName("m_KVthumbnail")]
    public object /* opaque */ M_KVthumbnail { get; set; }  // +0x28
}

/// <summary>CompMatMutatorCondition_t, 40 bytes</summary>
public class CompMatMutatorCondition_t
{
    [JsonPropertyName("m_nMutatorCondition")]
    public CompMatPropertyMutatorConditionType_t M_nMutatorCondition { get; set; }  // +0x0
    [JsonPropertyName("m_strMutatorConditionContainerName")]
    public string M_strMutatorConditionContainerName { get; set; }  // +0x8
    [JsonPropertyName("m_strMutatorConditionContainerVarName")]
    public string M_strMutatorConditionContainerVarName { get; set; }  // +0x10
    [JsonPropertyName("m_strMutatorConditionContainerVarValue")]
    public string M_strMutatorConditionContainerVarValue { get; set; }  // +0x18
    [JsonPropertyName("m_bPassWhenTrue")]
    public bool M_bPassWhenTrue { get; set; }  // +0x20
}

/// <summary>CompMatPropertyMutator_t, 912 bytes</summary>
public class CompMatPropertyMutator_t
{
    [JsonPropertyName("m_bEnabled")]
    public bool M_bEnabled { get; set; }  // +0x0
    [JsonPropertyName("m_nMutatorCommandType")]
    public CompMatPropertyMutatorType_t M_nMutatorCommandType { get; set; }  // +0x4
    [JsonPropertyName("m_strInitWith_Container")]
    public string M_strInitWith_Container { get; set; }  // +0x8
    [JsonPropertyName("m_strCopyProperty_InputContainerSrc")]
    public string M_strCopyProperty_InputContainerSrc { get; set; }  // +0x10
    [JsonPropertyName("m_strCopyProperty_InputContainerProperty")]
    public string M_strCopyProperty_InputContainerProperty { get; set; }  // +0x18
    [JsonPropertyName("m_strCopyProperty_TargetProperty")]
    public string M_strCopyProperty_TargetProperty { get; set; }  // +0x20
    [JsonPropertyName("m_strRandomRollInputVars_SeedInputVar")]
    public string M_strRandomRollInputVars_SeedInputVar { get; set; }  // +0x28
    [JsonPropertyName("m_vecRandomRollInputVars_InputVarsToRoll")]
    public string[] M_vecRandomRollInputVars_InputVarsToRoll { get; set; }  // +0x30
    [JsonPropertyName("m_strCopyMatchingKeys_InputContainerSrc")]
    public string M_strCopyMatchingKeys_InputContainerSrc { get; set; }  // +0x48
    [JsonPropertyName("m_strCopyKeysWithSuffix_InputContainerSrc")]
    public string M_strCopyKeysWithSuffix_InputContainerSrc { get; set; }  // +0x50
    [JsonPropertyName("m_strCopyKeysWithSuffix_FindSuffix")]
    public string M_strCopyKeysWithSuffix_FindSuffix { get; set; }  // +0x58
    [JsonPropertyName("m_strCopyKeysWithSuffix_ReplaceSuffix")]
    public string M_strCopyKeysWithSuffix_ReplaceSuffix { get; set; }  // +0x60
    [JsonPropertyName("m_nSetValue_Value")]
    public CompositeMaterialInputLooseVariable_t M_nSetValue_Value { get; set; }  // +0x68
    [JsonPropertyName("m_strGenerateTexture_TargetParam")]
    public string M_strGenerateTexture_TargetParam { get; set; }  // +0x2F0
    [JsonPropertyName("m_strGenerateTexture_InitialContainer")]
    public string M_strGenerateTexture_InitialContainer { get; set; }  // +0x2F8
    [JsonPropertyName("m_nResolution")]
    public int M_nResolution { get; set; }  // +0x300
    [JsonPropertyName("m_bIsScratchTarget")]
    public bool M_bIsScratchTarget { get; set; }  // +0x304
    [JsonPropertyName("m_strCompressionFormat")]
    public string M_strCompressionFormat { get; set; }  // +0x308
    [JsonPropertyName("m_bSplatDebugInfo")]
    public bool M_bSplatDebugInfo { get; set; }  // +0x310
    [JsonPropertyName("m_bCaptureInRenderDoc")]
    public bool M_bCaptureInRenderDoc { get; set; }  // +0x311
    [JsonPropertyName("m_vecTexGenInstructions")]
    public CompMatPropertyMutator_t[] M_vecTexGenInstructions { get; set; }  // +0x318
    [JsonPropertyName("m_vecConditionalMutators")]
    public CompMatPropertyMutator_t[] M_vecConditionalMutators { get; set; }  // +0x330
    [JsonPropertyName("m_strPopInputQueue_Container")]
    public string M_strPopInputQueue_Container { get; set; }  // +0x348
    [JsonPropertyName("m_strDrawText_InputContainerSrc")]
    public string M_strDrawText_InputContainerSrc { get; set; }  // +0x350
    [JsonPropertyName("m_strDrawText_InputContainerProperty")]
    public string M_strDrawText_InputContainerProperty { get; set; }  // +0x358
    [JsonPropertyName("m_vecDrawText_Position")]
    public Vector2D M_vecDrawText_Position { get; set; }  // +0x360
    [JsonPropertyName("m_colDrawText_Color")]
    public Color M_colDrawText_Color { get; set; }  // +0x368
    [JsonPropertyName("m_strDrawText_Font")]
    public string M_strDrawText_Font { get; set; }  // +0x370
    [JsonPropertyName("m_vecConditions")]
    public CompMatMutatorCondition_t[] M_vecConditions { get; set; }  // +0x378
}

public enum CompMatPropertyMutatorConditionType_t : uint
{
    COMP_MAT_MUTATOR_CONDITION_INPUT_CONTAINER_EXISTS = 0,
    COMP_MAT_MUTATOR_CONDITION_INPUT_CONTAINER_VALUE_EXISTS = 1,
    COMP_MAT_MUTATOR_CONDITION_INPUT_CONTAINER_VALUE_EQUALS = 2,
}

public enum CompMatPropertyMutatorType_t : uint
{
    COMP_MAT_PROPERTY_MUTATOR_INIT = 0,
    COMP_MAT_PROPERTY_MUTATOR_COPY_MATCHING_KEYS = 1,
    COMP_MAT_PROPERTY_MUTATOR_COPY_KEYS_WITH_SUFFIX = 2,
    COMP_MAT_PROPERTY_MUTATOR_COPY_PROPERTY = 3,
    COMP_MAT_PROPERTY_MUTATOR_SET_VALUE = 4,
    COMP_MAT_PROPERTY_MUTATOR_GENERATE_TEXTURE = 5,
    COMP_MAT_PROPERTY_MUTATOR_CONDITIONAL_MUTATORS = 6,
    COMP_MAT_PROPERTY_MUTATOR_POP_INPUT_QUEUE = 7,
    COMP_MAT_PROPERTY_MUTATOR_DRAW_TEXT = 8,
    COMP_MAT_PROPERTY_MUTATOR_RANDOM_ROLL_INPUT_VARIABLES = 9,
}

/// <summary>CompositeMaterial_t, 160 bytes</summary>
public class CompositeMaterial_t
{
    [JsonPropertyName("m_TargetKVs")]
    public object /* opaque */ M_TargetKVs { get; set; }  // +0x8
    [JsonPropertyName("m_PreGenerationKVs")]
    public object /* opaque */ M_PreGenerationKVs { get; set; }  // +0x18
    [JsonPropertyName("m_FinalKVs")]
    public object /* opaque */ M_FinalKVs { get; set; }  // +0x58
    [JsonPropertyName("m_vecGeneratedTextures")]
    public GeneratedTextureHandle_t[] M_vecGeneratedTextures { get; set; }  // +0x80
}

/// <summary>CompositeMaterialAssemblyProcedure_t, 96 bytes</summary>
public class CompositeMaterialAssemblyProcedure_t
{
    [JsonPropertyName("m_vecCompMatIncludes")]
    public string[] M_vecCompMatIncludes { get; set; }  // +0x0
    [JsonPropertyName("m_vecMatchFilters")]
    public CompositeMaterialMatchFilter_t[] M_vecMatchFilters { get; set; }  // +0x18
    [JsonPropertyName("m_vecCompositeInputContainers")]
    public CompositeMaterialInputContainer_t[] M_vecCompositeInputContainers { get; set; }  // +0x30
    [JsonPropertyName("m_vecPropertyMutators")]
    public CompMatPropertyMutator_t[] M_vecPropertyMutators { get; set; }  // +0x48
}

/// <summary>CompositeMaterialEditorPoint_t, 536 bytes</summary>
public class CompositeMaterialEditorPoint_t
{
    [JsonPropertyName("m_ModelName")]
    public string M_ModelName { get; set; }  // +0x0
    [JsonPropertyName("m_nSequenceIndex")]
    public int M_nSequenceIndex { get; set; }  // +0xE0
    [JsonPropertyName("m_flCycle")]
    public float M_flCycle { get; set; }  // +0xE4
    [JsonPropertyName("m_KVModelStateChoices")]
    public object /* opaque */ M_KVModelStateChoices { get; set; }  // +0xE8
    [JsonPropertyName("m_bEnableChildModel")]
    public bool M_bEnableChildModel { get; set; }  // +0xF8
    [JsonPropertyName("m_ChildModelName")]
    public string M_ChildModelName { get; set; }  // +0x100
    [JsonPropertyName("m_vecCompositeMaterialAssemblyProcedures")]
    public CompositeMaterialAssemblyProcedure_t[] M_vecCompositeMaterialAssemblyProcedures { get; set; }  // +0x1E0
    [JsonPropertyName("m_vecCompositeMaterials")]
    public CompositeMaterial_t[] M_vecCompositeMaterials { get; set; }  // +0x1F8
}

/// <summary>CompositeMaterialInputContainer_t, 312 bytes</summary>
public class CompositeMaterialInputContainer_t
{
    [JsonPropertyName("m_bEnabled")]
    public bool M_bEnabled { get; set; }  // +0x0
    [JsonPropertyName("m_nCompositeMaterialInputContainerSourceType")]
    public CompositeMaterialInputContainerSourceType_t M_nCompositeMaterialInputContainerSourceType { get; set; }  // +0x4
    [JsonPropertyName("m_strSpecificContainerMaterial")]
    public string M_strSpecificContainerMaterial { get; set; }  // +0x8
    [JsonPropertyName("m_strAttrName")]
    public string M_strAttrName { get; set; }  // +0xE8
    [JsonPropertyName("m_strAlias")]
    public string M_strAlias { get; set; }  // +0xF0
    [JsonPropertyName("m_vecLooseVariables")]
    public CompositeMaterialInputLooseVariable_t[] M_vecLooseVariables { get; set; }  // +0xF8
    [JsonPropertyName("m_strAttrNameForVar")]
    public string M_strAttrNameForVar { get; set; }  // +0x110
    [JsonPropertyName("m_bExposeExternally")]
    public bool M_bExposeExternally { get; set; }  // +0x118
}

public enum CompositeMaterialInputContainerSourceType_t : uint
{
    CONTAINER_SOURCE_TYPE_TARGET_MATERIAL = 0,
    CONTAINER_SOURCE_TYPE_MATERIAL_FROM_TARGET_ATTR = 1,
    CONTAINER_SOURCE_TYPE_SPECIFIC_MATERIAL = 2,
    CONTAINER_SOURCE_TYPE_LOOSE_VARIABLES = 3,
    CONTAINER_SOURCE_TYPE_VARIABLE_FROM_TARGET_ATTR = 4,
    CONTAINER_SOURCE_TYPE_TARGET_INSTANCE_MATERIAL = 5,
}

/// <summary>CompositeMaterialInputLooseVariable_t, 648 bytes</summary>
public class CompositeMaterialInputLooseVariable_t
{
    [JsonPropertyName("m_strName")]
    public string M_strName { get; set; }  // +0x0
    [JsonPropertyName("m_bExposeExternally")]
    public bool M_bExposeExternally { get; set; }  // +0x8
    [JsonPropertyName("m_strExposedFriendlyName")]
    public string M_strExposedFriendlyName { get; set; }  // +0x10
    [JsonPropertyName("m_strExposedFriendlyGroupName")]
    public string M_strExposedFriendlyGroupName { get; set; }  // +0x18
    [JsonPropertyName("m_bExposedVariableIsFixedRange")]
    public bool M_bExposedVariableIsFixedRange { get; set; }  // +0x20
    [JsonPropertyName("m_strExposedVisibleWhenTrue")]
    public string M_strExposedVisibleWhenTrue { get; set; }  // +0x28
    [JsonPropertyName("m_strExposedHiddenWhenTrue")]
    public string M_strExposedHiddenWhenTrue { get; set; }  // +0x30
    [JsonPropertyName("m_strExposedValueList")]
    public string M_strExposedValueList { get; set; }  // +0x38
    [JsonPropertyName("m_nVariableType")]
    public CompositeMaterialInputLooseVariableType_t M_nVariableType { get; set; }  // +0x40
    [JsonPropertyName("m_bValueBoolean")]
    public bool M_bValueBoolean { get; set; }  // +0x44
    [JsonPropertyName("m_nValueIntX")]
    public int M_nValueIntX { get; set; }  // +0x48
    [JsonPropertyName("m_nValueIntY")]
    public int M_nValueIntY { get; set; }  // +0x4C
    [JsonPropertyName("m_nValueIntZ")]
    public int M_nValueIntZ { get; set; }  // +0x50
    [JsonPropertyName("m_nValueIntW")]
    public int M_nValueIntW { get; set; }  // +0x54
    [JsonPropertyName("m_bHasFloatBounds")]
    public bool M_bHasFloatBounds { get; set; }  // +0x58
    [JsonPropertyName("m_flValueFloatX")]
    public float M_flValueFloatX { get; set; }  // +0x5C
    [JsonPropertyName("m_flValueFloatX_Min")]
    public float M_flValueFloatX_Min { get; set; }  // +0x60
    [JsonPropertyName("m_flValueFloatX_Max")]
    public float M_flValueFloatX_Max { get; set; }  // +0x64
    [JsonPropertyName("m_flValueFloatY")]
    public float M_flValueFloatY { get; set; }  // +0x68
    [JsonPropertyName("m_flValueFloatY_Min")]
    public float M_flValueFloatY_Min { get; set; }  // +0x6C
    [JsonPropertyName("m_flValueFloatY_Max")]
    public float M_flValueFloatY_Max { get; set; }  // +0x70
    [JsonPropertyName("m_flValueFloatZ")]
    public float M_flValueFloatZ { get; set; }  // +0x74
    [JsonPropertyName("m_flValueFloatZ_Min")]
    public float M_flValueFloatZ_Min { get; set; }  // +0x78
    [JsonPropertyName("m_flValueFloatZ_Max")]
    public float M_flValueFloatZ_Max { get; set; }  // +0x7C
    [JsonPropertyName("m_flValueFloatW")]
    public float M_flValueFloatW { get; set; }  // +0x80
    [JsonPropertyName("m_flValueFloatW_Min")]
    public float M_flValueFloatW_Min { get; set; }  // +0x84
    [JsonPropertyName("m_flValueFloatW_Max")]
    public float M_flValueFloatW_Max { get; set; }  // +0x88
    [JsonPropertyName("m_cValueColor4")]
    public Color M_cValueColor4 { get; set; }  // +0x8C
    [JsonPropertyName("m_nValueSystemVar")]
    public CompositeMaterialVarSystemVar_t M_nValueSystemVar { get; set; }  // +0x90
    [JsonPropertyName("m_strResourceMaterial")]
    public string M_strResourceMaterial { get; set; }  // +0x98
    [JsonPropertyName("m_strTextureContentAssetPath")]
    public string M_strTextureContentAssetPath { get; set; }  // +0x178
    [JsonPropertyName("m_strTextureRuntimeResourcePath")]
    public string M_strTextureRuntimeResourcePath { get; set; }  // +0x180
    [JsonPropertyName("m_strTextureCompilationVtexTemplate")]
    public string M_strTextureCompilationVtexTemplate { get; set; }  // +0x260
    [JsonPropertyName("m_nTextureType")]
    public CompositeMaterialInputTextureType_t M_nTextureType { get; set; }  // +0x268
    [JsonPropertyName("m_strString")]
    public string M_strString { get; set; }  // +0x270
    [JsonPropertyName("m_strPanoramaPanelPath")]
    public string M_strPanoramaPanelPath { get; set; }  // +0x278
    [JsonPropertyName("m_nPanoramaRenderRes")]
    public int M_nPanoramaRenderRes { get; set; }  // +0x280
}

public enum CompositeMaterialInputLooseVariableType_t : uint
{
    LOOSE_VARIABLE_TYPE_BOOLEAN = 0,
    LOOSE_VARIABLE_TYPE_INTEGER1 = 1,
    LOOSE_VARIABLE_TYPE_INTEGER2 = 2,
    LOOSE_VARIABLE_TYPE_INTEGER3 = 3,
    LOOSE_VARIABLE_TYPE_INTEGER4 = 4,
    LOOSE_VARIABLE_TYPE_FLOAT1 = 5,
    LOOSE_VARIABLE_TYPE_FLOAT2 = 6,
    LOOSE_VARIABLE_TYPE_FLOAT3 = 7,
    LOOSE_VARIABLE_TYPE_FLOAT4 = 8,
    LOOSE_VARIABLE_TYPE_COLOR4 = 9,
    LOOSE_VARIABLE_TYPE_STRING = 10,
    LOOSE_VARIABLE_TYPE_SYSTEMVAR = 11,
    LOOSE_VARIABLE_TYPE_RESOURCE_MATERIAL = 12,
    LOOSE_VARIABLE_TYPE_RESOURCE_TEXTURE = 13,
    LOOSE_VARIABLE_TYPE_PANORAMA_RENDER = 14,
}

public enum CompositeMaterialInputTextureType_t : uint
{
    INPUT_TEXTURE_TYPE_DEFAULT = 0,
    INPUT_TEXTURE_TYPE_NORMALMAP = 1,
    INPUT_TEXTURE_TYPE_COLOR = 2,
    INPUT_TEXTURE_TYPE_MASKS = 3,
    INPUT_TEXTURE_TYPE_ROUGHNESS = 4,
    INPUT_TEXTURE_TYPE_PEARLESCENCE_MASK = 5,
    INPUT_TEXTURE_TYPE_AO = 6,
    INPUT_TEXTURE_TYPE_POSITION = 7,
}

/// <summary>CompositeMaterialMatchFilter_t, 32 bytes</summary>
public class CompositeMaterialMatchFilter_t
{
    [JsonPropertyName("m_nCompositeMaterialMatchFilterType")]
    public CompositeMaterialMatchFilterType_t M_nCompositeMaterialMatchFilterType { get; set; }  // +0x0
    [JsonPropertyName("m_strMatchFilter")]
    public string M_strMatchFilter { get; set; }  // +0x8
    [JsonPropertyName("m_strMatchValue")]
    public string M_strMatchValue { get; set; }  // +0x10
    [JsonPropertyName("m_bPassWhenTrue")]
    public bool M_bPassWhenTrue { get; set; }  // +0x18
}

public enum CompositeMaterialMatchFilterType_t : uint
{
    MATCH_FILTER_MATERIAL_ATTRIBUTE_EXISTS = 0,
    MATCH_FILTER_MATERIAL_SHADER = 1,
    MATCH_FILTER_MATERIAL_NAME_SUBSTR = 2,
    MATCH_FILTER_MATERIAL_ATTRIBUTE_EQUALS = 3,
    MATCH_FILTER_MATERIAL_PROPERTY_EXISTS = 4,
    MATCH_FILTER_MATERIAL_PROPERTY_EQUALS = 5,
}

public enum CompositeMaterialVarSystemVar_t : uint
{
    COMPMATSYSVAR_COMPOSITETIME = 0,
    COMPMATSYSVAR_EMPTY_RESOURCE_SPACER = 1,
}

/// <summary>GeneratedTextureHandle_t, 96 bytes</summary>
public class GeneratedTextureHandle_t
{
    [JsonPropertyName("m_strBitmapName")]
    public string M_strBitmapName { get; set; }  // +0x0
}

