// Auto-generated by cs2-codegen from schemas_jsonschema.json
// Revision 10638965 (May 06 2026) — https://github.com/ValveResourceFormat/DumpSource2
// Do not edit by hand.
// Module: hammer

#nullable enable
#pragma warning disable CS8618  // non-nullable property not initialized (expected in generated serialization types)

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CS2Schema;

/// <summary>ColorOptionsEditableData_t, 30 bytes</summary>
public class ColorOptionsEditableData_t
{
    [JsonPropertyName("bUseCustom")]
    public bool BUseCustom { get; set; }  // +0x0
    [JsonPropertyName("bWhiteOnBlack")]
    public bool BWhiteOnBlack { get; set; }  // +0x1
    [JsonPropertyName("clrGrid")]
    public Color ClrGrid { get; set; }  // +0x2
    [JsonPropertyName("clrGridFractional")]
    public Color ClrGridFractional { get; set; }  // +0x6
    [JsonPropertyName("clrGrid10")]
    public Color ClrGrid10 { get; set; }  // +0xA
    [JsonPropertyName("clrGrid1024")]
    public Color ClrGrid1024 { get; set; }  // +0xE
    [JsonPropertyName("clrBrush")]
    public Color ClrBrush { get; set; }  // +0x12
    [JsonPropertyName("clrSelection")]
    public Color ClrSelection { get; set; }  // +0x16
    [JsonPropertyName("clrToolSelection")]
    public Color ClrToolSelection { get; set; }  // +0x1A
}

/// <summary>GeneralOptionsEditableData_t, 56 bytes</summary>
public class GeneralOptionsEditableData_t
{
    [JsonPropertyName("iUndoLevels")]
    public int IUndoLevels { get; set; }  // +0x0
    [JsonPropertyName("bSaveChangesOnBuildMap")]
    public bool BSaveChangesOnBuildMap { get; set; }  // +0x4
    [JsonPropertyName("bRenderFullyUnlitAsFullbright")]
    public bool BRenderFullyUnlitAsFullbright { get; set; }  // +0x5
    [JsonPropertyName("bShowSelectionModeChangeNotificationIcons")]
    public bool BShowSelectionModeChangeNotificationIcons { get; set; }  // +0x6
    [JsonPropertyName("bShowToolChangeNotificationIcons")]
    public bool BShowToolChangeNotificationIcons { get; set; }  // +0x7
    [JsonPropertyName("bPauseGameOnActivate")]
    public bool BPauseGameOnActivate { get; set; }  // +0x8
    [JsonPropertyName("SolidEntity")]
    public string SolidEntity { get; set; }  // +0x10
    [JsonPropertyName("PointEntity")]
    public string PointEntity { get; set; }  // +0x18
    [JsonPropertyName("PathEntity")]
    public string PathEntity { get; set; }  // +0x20
    [JsonPropertyName("bReportMapCompileCrashes")]
    public bool BReportMapCompileCrashes { get; set; }  // +0x28
    [JsonPropertyName("bViewFocusStealing")]
    public bool BViewFocusStealing { get; set; }  // +0x29
    [JsonPropertyName("bMoveSelectedEnabled")]
    public bool BMoveSelectedEnabled { get; set; }  // +0x2A
    [JsonPropertyName("bPreviewMotionExtraction")]
    public bool BPreviewMotionExtraction { get; set; }  // +0x2B
    [JsonPropertyName("nViewportFontSize")]
    public int NViewportFontSize { get; set; }  // +0x2C
    [JsonPropertyName("flVertexSnapRadius")]
    public float FlVertexSnapRadius { get; set; }  // +0x30
    [JsonPropertyName("m_bForceStaticPropsForModelDrags")]
    public bool M_bForceStaticPropsForModelDrags { get; set; }  // +0x34
}

/// <summary>ImportExportOptionsEditableData_t, 16 bytes</summary>
public class ImportExportOptionsEditableData_t
{
    [JsonPropertyName("bExportProps")]
    public bool BExportProps { get; set; }  // +0x0
    [JsonPropertyName("bExportHidden")]
    public bool BExportHidden { get; set; }  // +0x1
    [JsonPropertyName("bExportFbxEmbedTextures")]
    public bool BExportFbxEmbedTextures { get; set; }  // +0x2
    [JsonPropertyName("nExportFbxUnit")]
    public ImportExportOptionsEditableData_t_ExportFbxUnit_t NExportFbxUnit { get; set; }  // +0x4
    [JsonPropertyName("nExportDefaultFormat")]
    public ImportExportOptionsEditableData_t_ExportDefaultFormat_t NExportDefaultFormat { get; set; }  // +0x8
    [JsonPropertyName("nExportEncoding")]
    public ImportExportOptionsEditableData_t_ExportEncoding_t NExportEncoding { get; set; }  // +0xC
}

public enum ImportExportOptionsEditableData_t_ExportDefaultFormat_t : uint
{
    DEFAULT_FORMAT_DMX = 0,
    DEFAULT_FORMAT_OBJ = 1,
    DEFAULT_FORMAT_FBX = 2,
}

public enum ImportExportOptionsEditableData_t_ExportEncoding_t : uint
{
    EXPORT_ENCODING_TEXT = 0,
    EXPORT_ENCODING_BINARY = 1,
}

public enum ImportExportOptionsEditableData_t_ExportFbxUnit_t : uint
{
    FBX_UNIT_CENTIMETERS = 0,
    FBX_UNIT_INCHES = 1,
}

/// <summary>TexturesOptionsEditableData_t, 8 bytes</summary>
public class TexturesOptionsEditableData_t
{
    [JsonPropertyName("m_DefaultMaterialName")]
    public string M_DefaultMaterialName { get; set; }  // +0x0
}

/// <summary>ToolsOptionsEditableData_t, 9 bytes</summary>
public class ToolsOptionsEditableData_t
{
    [JsonPropertyName("bTranslateToolAlignToSurface")]
    public bool BTranslateToolAlignToSurface { get; set; }  // +0x0
    [JsonPropertyName("bRotateToolUseRelativeMode")]
    public bool BRotateToolUseRelativeMode { get; set; }  // +0x1
    [JsonPropertyName("bPivotToolSnapToBBox")]
    public bool BPivotToolSnapToBBox { get; set; }  // +0x2
    [JsonPropertyName("bEdgeSelectionPreviewEdgeLength")]
    public bool BEdgeSelectionPreviewEdgeLength { get; set; }  // +0x3
    [JsonPropertyName("bShowSelectionBounds")]
    public bool BShowSelectionBounds { get; set; }  // +0x4
    [JsonPropertyName("bShowSelectionDimensions")]
    public bool BShowSelectionDimensions { get; set; }  // +0x5
    [JsonPropertyName("bShowSelectedEdgeAngles")]
    public bool BShowSelectedEdgeAngles { get; set; }  // +0x6
    [JsonPropertyName("bShowTranslationDistance")]
    public bool BShowTranslationDistance { get; set; }  // +0x7
    [JsonPropertyName("bConvertMeshHardEdgesFromUVBoundaries")]
    public bool BConvertMeshHardEdgesFromUVBoundaries { get; set; }  // +0x8
}

/// <summary>View2DOptionsEditableData_t, 12 bytes</summary>
public class View2DOptionsEditableData_t
{
    [JsonPropertyName("bNudge")]
    public bool BNudge { get; set; }  // +0x0
    [JsonPropertyName("bUsegroupcolors")]
    public bool BUsegroupcolors { get; set; }  // +0x1
    [JsonPropertyName("iGridIntensity")]
    public int IGridIntensity { get; set; }  // +0x4
    [JsonPropertyName("bShowEntityNames")]
    public bool BShowEntityNames { get; set; }  // +0x8
}

/// <summary>View3DOptionsEditableData_t, 88 bytes</summary>
public class View3DOptionsEditableData_t
{
    [JsonPropertyName("bReverseY")]
    public bool BReverseY { get; set; }  // +0x0
    [JsonPropertyName("flPanSpeed")]
    public float FlPanSpeed { get; set; }  // +0x4
    [JsonPropertyName("flRotationScale")]
    public float FlRotationScale { get; set; }  // +0x8
    [JsonPropertyName("nForwardSpeedMax")]
    public int NForwardSpeedMax { get; set; }  // +0xC
    [JsonPropertyName("nTimeToMaxSpeed")]
    public int NTimeToMaxSpeed { get; set; }  // +0x10
    [JsonPropertyName("flFOV")]
    public int FlFOV { get; set; }  // +0x14
    [JsonPropertyName("szResolutionGate")]
    public string SzResolutionGate { get; set; }  // +0x18
    [JsonPropertyName("iBackPlane")]
    public int IBackPlane { get; set; }  // +0x20
    [JsonPropertyName("flNearPlane")]
    public float FlNearPlane { get; set; }  // +0x24
    [JsonPropertyName("flShadowFarPlane")]
    public float FlShadowFarPlane { get; set; }  // +0x28
    [JsonPropertyName("bMouseWheelControlsFarPlane")]
    public bool BMouseWheelControlsFarPlane { get; set; }  // +0x2C
    [JsonPropertyName("nMouseMoveZoomSensitivity")]
    public int NMouseMoveZoomSensitivity { get; set; }  // +0x30
    [JsonPropertyName("nMouseWheelZoomSensitivity")]
    public int NMouseWheelZoomSensitivity { get; set; }  // +0x34
    [JsonPropertyName("nCameraTargetDist")]
    public int NCameraTargetDist { get; set; }  // +0x38
    [JsonPropertyName("iGridIntensity")]
    public int IGridIntensity { get; set; }  // +0x3C
    [JsonPropertyName("fSelectionOverlayAlpha")]
    public float FSelectionOverlayAlpha { get; set; }  // +0x40
    [JsonPropertyName("bShowSelectionOutline")]
    public bool BShowSelectionOutline { get; set; }  // +0x44
    [JsonPropertyName("bSelectionOutlineDepth")]
    public bool BSelectionOutlineDepth { get; set; }  // +0x45
    [JsonPropertyName("fToolsVisSSAORadiusScale")]
    public float FToolsVisSSAORadiusScale { get; set; }  // +0x48
    [JsonPropertyName("fToolsVisSSAOPowerScale")]
    public float FToolsVisSSAOPowerScale { get; set; }  // +0x4C
    [JsonPropertyName("bPostProcessingEnabled")]
    public bool BPostProcessingEnabled { get; set; }  // +0x50
}

