// Auto-generated by cs2-codegen from schemas_jsonschema.json
// Revision 10638965 (May 06 2026) — https://github.com/ValveResourceFormat/DumpSource2
// Do not edit by hand.
// Module: mapdoclib

#nullable enable
#pragma warning disable CS8618  // non-nullable property not initialized (expected in generated serialization types)

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CS2Schema;

/// <summary>CSprayedDataPreset, 48 bytes</summary>
public class CSprayedDataPreset
{
    [JsonPropertyName("m_nCounterMin")]
    public int M_nCounterMin { get; set; }  // +0x0
    [JsonPropertyName("m_nCounterMax")]
    public int M_nCounterMax { get; set; }  // +0x4
    [JsonPropertyName("m_flSpacing")]
    public float M_flSpacing { get; set; }  // +0x8
    [JsonPropertyName("m_flRadius")]
    public float M_flRadius { get; set; }  // +0xC
    [JsonPropertyName("m_flEraseAmount")]
    public float M_flEraseAmount { get; set; }  // +0x10
    [JsonPropertyName("m_bConstantDensity")]
    public bool M_bConstantDensity { get; set; }  // +0x14
    [JsonPropertyName("m_bOnlyHitMeshes")]
    public bool M_bOnlyHitMeshes { get; set; }  // +0x15
    [JsonPropertyName("m_bRadialFalloff")]
    public bool M_bRadialFalloff { get; set; }  // +0x16
    [JsonPropertyName("m_elements")]
    public CSprayedDataPresetElement[] M_elements { get; set; }  // +0x18
}

/// <summary>CSprayedDataPresetElement, 144 bytes</summary>
public class CSprayedDataPresetElement
{
    [JsonPropertyName("m_assetName")]
    public string M_assetName { get; set; }  // +0x0
    [JsonPropertyName("m_vBoundsMin")]
    public Vector M_vBoundsMin { get; set; }  // +0x18
    [JsonPropertyName("m_vBoundsMax")]
    public Vector M_vBoundsMax { get; set; }  // +0x24
    [JsonPropertyName("m_settings")]
    public CSprayedDataSettingsBlock M_settings { get; set; }  // +0x30
}

/// <summary>CSprayedDataSettingsBlock, 92 bytes</summary>
public class CSprayedDataSettingsBlock
{
    [JsonPropertyName("m_flMinDensity")]
    public float M_flMinDensity { get; set; }  // +0x0
    [JsonPropertyName("m_flMaxDensity")]
    public float M_flMaxDensity { get; set; }  // +0x4
    [JsonPropertyName("m_flMinScale")]
    public float M_flMinScale { get; set; }  // +0x8
    [JsonPropertyName("m_flMaxScale")]
    public float M_flMaxScale { get; set; }  // +0xC
    [JsonPropertyName("m_vMinAngle")]
    public QAngle M_vMinAngle { get; set; }  // +0x10
    [JsonPropertyName("m_vMaxAngle")]
    public QAngle M_vMaxAngle { get; set; }  // +0x1C
    [JsonPropertyName("m_vMinColor")]
    public Vector M_vMinColor { get; set; }  // +0x28
    [JsonPropertyName("m_vMaxColor")]
    public Vector M_vMaxColor { get; set; }  // +0x34
    [JsonPropertyName("m_flSpacingMul")]
    public float M_flSpacingMul { get; set; }  // +0x40
    [JsonPropertyName("m_flSlopeThreshold")]
    public float M_flSlopeThreshold { get; set; }  // +0x44
    [JsonPropertyName("m_vMasterDirection")]
    public Vector M_vMasterDirection { get; set; }  // +0x48
    [JsonPropertyName("m_flMasterDirectionInfluence")]
    public float M_flMasterDirectionInfluence { get; set; }  // +0x54
    [JsonPropertyName("m_bEnabled")]
    public bool M_bEnabled { get; set; }  // +0x58
}

