// Auto-generated by cs2-codegen from schemas_jsonschema.json
// Revision 10638965 (May 06 2026) — https://github.com/ValveResourceFormat/DumpSource2
// Do not edit by hand.
// Module: materialsystem2

#nullable enable
#pragma warning disable CS8618  // non-nullable property not initialized (expected in generated serialization types)

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CS2Schema;

public enum BloomBlendMode_t : uint
{
    BLOOM_BLEND_ADD = 0,
    BLOOM_BLEND_SCREEN = 1,
    BLOOM_BLEND_BLUR = 2,
}

public enum HorizJustification_e : uint
{
    HORIZ_JUSTIFICATION_LEFT = 0,
    HORIZ_JUSTIFICATION_CENTER = 1,
    HORIZ_JUSTIFICATION_RIGHT = 2,
    HORIZ_JUSTIFICATION_NONE = 3,
}

public enum LayoutPositionType_e : uint
{
    LAYOUTPOSITIONTYPE_VIEWPORT_RELATIVE = 0,
    LAYOUTPOSITIONTYPE_FRACTIONAL = 1,
    LAYOUTPOSITIONTYPE_NONE = 2,
}

/// <summary>MaterialParam_t, 8 bytes</summary>
public class MaterialParam_t
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x0
}

/// <summary>MaterialParamBuffer_t, 24 bytes</summary>
public class MaterialParamBuffer_t : MaterialParam_t
{
    [JsonPropertyName("m_value")]
    public object /* opaque */ M_value { get; set; }  // +0x8
}

/// <summary>MaterialParamFloat_t, 16 bytes</summary>
public class MaterialParamFloat_t : MaterialParam_t
{
    [JsonPropertyName("m_flValue")]
    public float M_flValue { get; set; }  // +0x8
}

/// <summary>MaterialParamInt_t, 16 bytes</summary>
public class MaterialParamInt_t : MaterialParam_t
{
    [JsonPropertyName("m_nValue")]
    public int M_nValue { get; set; }  // +0x8
}

/// <summary>MaterialParamString_t, 16 bytes</summary>
public class MaterialParamString_t : MaterialParam_t
{
    [JsonPropertyName("m_value")]
    public string M_value { get; set; }  // +0x8
}

/// <summary>MaterialParamTexture_t, 16 bytes</summary>
public class MaterialParamTexture_t : MaterialParam_t
{
    [JsonPropertyName("m_pValue")]
    public InfoForResourceTypeCTextureBase? M_pValue { get; set; }  // +0x8
}

/// <summary>MaterialParamVector_t, 24 bytes</summary>
public class MaterialParamVector_t : MaterialParam_t
{
    [JsonPropertyName("m_value")]
    public Vector4D M_value { get; set; }  // +0x8
}

/// <summary>MaterialResourceData_t, 304 bytes</summary>
public class MaterialResourceData_t
{
    [JsonPropertyName("m_materialName")]
    public string M_materialName { get; set; }  // +0x0
    [JsonPropertyName("m_shaderName")]
    public string M_shaderName { get; set; }  // +0x8
    [JsonPropertyName("m_intParams")]
    public MaterialParamInt_t[] M_intParams { get; set; }  // +0x10
    [JsonPropertyName("m_floatParams")]
    public MaterialParamFloat_t[] M_floatParams { get; set; }  // +0x28
    [JsonPropertyName("m_vectorParams")]
    public MaterialParamVector_t[] M_vectorParams { get; set; }  // +0x40
    [JsonPropertyName("m_textureParams")]
    public MaterialParamTexture_t[] M_textureParams { get; set; }  // +0x58
    [JsonPropertyName("m_dynamicParams")]
    public MaterialParamBuffer_t[] M_dynamicParams { get; set; }  // +0x70
    [JsonPropertyName("m_dynamicTextureParams")]
    public MaterialParamBuffer_t[] M_dynamicTextureParams { get; set; }  // +0x88
    [JsonPropertyName("m_intAttributes")]
    public MaterialParamInt_t[] M_intAttributes { get; set; }  // +0xA0
    [JsonPropertyName("m_floatAttributes")]
    public MaterialParamFloat_t[] M_floatAttributes { get; set; }  // +0xB8
    [JsonPropertyName("m_vectorAttributes")]
    public MaterialParamVector_t[] M_vectorAttributes { get; set; }  // +0xD0
    [JsonPropertyName("m_textureAttributes")]
    public MaterialParamTexture_t[] M_textureAttributes { get; set; }  // +0xE8
    [JsonPropertyName("m_stringAttributes")]
    public MaterialParamString_t[] M_stringAttributes { get; set; }  // +0x100
    [JsonPropertyName("m_renderAttributesUsed")]
    public string[] M_renderAttributesUsed { get; set; }  // +0x118
}

/// <summary>PostProcessingBloomParameters_t, 136 bytes</summary>
public class PostProcessingBloomParameters_t
{
    [JsonPropertyName("m_blendMode")]
    public BloomBlendMode_t M_blendMode { get; set; }  // +0x0
    [JsonPropertyName("m_flBloomStrength")]
    public float M_flBloomStrength { get; set; }  // +0x4
    [JsonPropertyName("m_flScreenBloomStrength")]
    public float M_flScreenBloomStrength { get; set; }  // +0x8
    [JsonPropertyName("m_flBlurBloomStrength")]
    public float M_flBlurBloomStrength { get; set; }  // +0xC
    [JsonPropertyName("m_flBloomThreshold")]
    public float M_flBloomThreshold { get; set; }  // +0x10
    [JsonPropertyName("m_flBloomThresholdWidth")]
    public float M_flBloomThresholdWidth { get; set; }  // +0x14
    [JsonPropertyName("m_flSkyboxBloomStrength")]
    public float M_flSkyboxBloomStrength { get; set; }  // +0x18
    [JsonPropertyName("m_flBloomStartValue")]
    public float M_flBloomStartValue { get; set; }  // +0x1C
    [JsonPropertyName("m_flComputeBloomStrength")]
    public float M_flComputeBloomStrength { get; set; }  // +0x20
    [JsonPropertyName("m_flComputeBloomThreshold")]
    public float M_flComputeBloomThreshold { get; set; }  // +0x24
    [JsonPropertyName("m_flComputeBloomRadius")]
    public float M_flComputeBloomRadius { get; set; }  // +0x28
    [JsonPropertyName("m_flComputeBloomEffectsScale")]
    public float M_flComputeBloomEffectsScale { get; set; }  // +0x2C
    [JsonPropertyName("m_flComputeBloomLensDirtStrength")]
    public float M_flComputeBloomLensDirtStrength { get; set; }  // +0x30
    [JsonPropertyName("m_flComputeBloomLensDirtBlackLevel")]
    public float M_flComputeBloomLensDirtBlackLevel { get; set; }  // +0x34
    [JsonPropertyName("m_flBlurWeight")]
    public float[] M_flBlurWeight { get; set; }  // +0x38
    [JsonPropertyName("m_vBlurTint")]
    public Vector[] M_vBlurTint { get; set; }  // +0x4C
}

/// <summary>PostProcessingFogScatteringParameters_t, 20 bytes</summary>
public class PostProcessingFogScatteringParameters_t
{
    [JsonPropertyName("m_fRadius")]
    public float M_fRadius { get; set; }  // +0x0
    [JsonPropertyName("m_fScale")]
    public float M_fScale { get; set; }  // +0x4
    [JsonPropertyName("m_fCubemapScale")]
    public float M_fCubemapScale { get; set; }  // +0x8
    [JsonPropertyName("m_fVolumetricScale")]
    public float M_fVolumetricScale { get; set; }  // +0xC
    [JsonPropertyName("m_fGradientScale")]
    public float M_fGradientScale { get; set; }  // +0x10
}

/// <summary>PostProcessingLocalContrastParameters_t, 20 bytes</summary>
public class PostProcessingLocalContrastParameters_t
{
    [JsonPropertyName("m_flLocalContrastStrength")]
    public float M_flLocalContrastStrength { get; set; }  // +0x0
    [JsonPropertyName("m_flLocalContrastEdgeStrength")]
    public float M_flLocalContrastEdgeStrength { get; set; }  // +0x4
    [JsonPropertyName("m_flLocalContrastVignetteStart")]
    public float M_flLocalContrastVignetteStart { get; set; }  // +0x8
    [JsonPropertyName("m_flLocalContrastVignetteEnd")]
    public float M_flLocalContrastVignetteEnd { get; set; }  // +0xC
    [JsonPropertyName("m_flLocalContrastVignetteBlur")]
    public float M_flLocalContrastVignetteBlur { get; set; }  // +0x10
}

/// <summary>PostProcessingResource_t, 312 bytes</summary>
public class PostProcessingResource_t
{
    [JsonPropertyName("m_bHasTonemapParams")]
    public bool M_bHasTonemapParams { get; set; }  // +0x0
    [JsonPropertyName("m_toneMapParams")]
    public PostProcessingTonemapParameters_t M_toneMapParams { get; set; }  // +0x4
    [JsonPropertyName("m_bHasBloomParams")]
    public bool M_bHasBloomParams { get; set; }  // +0x40
    [JsonPropertyName("m_bloomParams")]
    public PostProcessingBloomParameters_t M_bloomParams { get; set; }  // +0x44
    [JsonPropertyName("m_bHasVignetteParams")]
    public bool M_bHasVignetteParams { get; set; }  // +0xCC
    [JsonPropertyName("m_vignetteParams")]
    public PostProcessingVignetteParameters_t M_vignetteParams { get; set; }  // +0xD0
    [JsonPropertyName("m_bHasLocalContrastParams")]
    public bool M_bHasLocalContrastParams { get; set; }  // +0xF4
    [JsonPropertyName("m_localConstrastParams")]
    public PostProcessingLocalContrastParameters_t M_localConstrastParams { get; set; }  // +0xF8
    [JsonPropertyName("m_nColorCorrectionVolumeDim")]
    public int M_nColorCorrectionVolumeDim { get; set; }  // +0x10C
    [JsonPropertyName("m_colorCorrectionVolumeData")]
    public object /* opaque */ M_colorCorrectionVolumeData { get; set; }  // +0x110
    [JsonPropertyName("m_bHasColorCorrection")]
    public bool M_bHasColorCorrection { get; set; }  // +0x120
    [JsonPropertyName("m_bHasFogScatteringParams")]
    public bool M_bHasFogScatteringParams { get; set; }  // +0x121
    [JsonPropertyName("m_fogScatteringParams")]
    public PostProcessingFogScatteringParameters_t M_fogScatteringParams { get; set; }  // +0x124
}

/// <summary>PostProcessingTonemapParameters_t, 60 bytes</summary>
public class PostProcessingTonemapParameters_t
{
    [JsonPropertyName("m_flExposureBias")]
    public float M_flExposureBias { get; set; }  // +0x0
    [JsonPropertyName("m_flShoulderStrength")]
    public float M_flShoulderStrength { get; set; }  // +0x4
    [JsonPropertyName("m_flLinearStrength")]
    public float M_flLinearStrength { get; set; }  // +0x8
    [JsonPropertyName("m_flLinearAngle")]
    public float M_flLinearAngle { get; set; }  // +0xC
    [JsonPropertyName("m_flToeStrength")]
    public float M_flToeStrength { get; set; }  // +0x10
    [JsonPropertyName("m_flToeNum")]
    public float M_flToeNum { get; set; }  // +0x14
    [JsonPropertyName("m_flToeDenom")]
    public float M_flToeDenom { get; set; }  // +0x18
    [JsonPropertyName("m_flWhitePoint")]
    public float M_flWhitePoint { get; set; }  // +0x1C
    [JsonPropertyName("m_flLuminanceSource")]
    public float M_flLuminanceSource { get; set; }  // +0x20
    [JsonPropertyName("m_flExposureBiasShadows")]
    public float M_flExposureBiasShadows { get; set; }  // +0x24
    [JsonPropertyName("m_flExposureBiasHighlights")]
    public float M_flExposureBiasHighlights { get; set; }  // +0x28
    [JsonPropertyName("m_flMinShadowLum")]
    public float M_flMinShadowLum { get; set; }  // +0x2C
    [JsonPropertyName("m_flMaxShadowLum")]
    public float M_flMaxShadowLum { get; set; }  // +0x30
    [JsonPropertyName("m_flMinHighlightLum")]
    public float M_flMinHighlightLum { get; set; }  // +0x34
    [JsonPropertyName("m_flMaxHighlightLum")]
    public float M_flMaxHighlightLum { get; set; }  // +0x38
}

/// <summary>PostProcessingVignetteParameters_t, 36 bytes</summary>
public class PostProcessingVignetteParameters_t
{
    [JsonPropertyName("m_flVignetteStrength")]
    public float M_flVignetteStrength { get; set; }  // +0x0
    [JsonPropertyName("m_vCenter")]
    public Vector2D M_vCenter { get; set; }  // +0x4
    [JsonPropertyName("m_flRadius")]
    public float M_flRadius { get; set; }  // +0xC
    [JsonPropertyName("m_flRoundness")]
    public float M_flRoundness { get; set; }  // +0x10
    [JsonPropertyName("m_flFeather")]
    public float M_flFeather { get; set; }  // +0x14
    [JsonPropertyName("m_vColorTint")]
    public Vector M_vColorTint { get; set; }  // +0x18
}

public enum VertJustification_e : uint
{
    VERT_JUSTIFICATION_TOP = 0,
    VERT_JUSTIFICATION_CENTER = 1,
    VERT_JUSTIFICATION_BOTTOM = 2,
    VERT_JUSTIFICATION_NONE = 3,
}

public enum ViewFadeMode_t : uint
{
    VIEW_FADE_CONSTANT_COLOR = 0,
    VIEW_FADE_MODULATE = 1,
    VIEW_FADE_MOD2X = 2,
}

