// Auto-generated by cs2-codegen from schemas_jsonschema.json
// Revision 10638965 (May 06 2026) — https://github.com/ValveResourceFormat/DumpSource2
// Do not edit by hand.
// Module: mathlib_extended

#nullable enable
#pragma warning disable CS8618  // non-nullable property not initialized (expected in generated serialization types)

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CS2Schema;

/// <summary>AABB_t, 24 bytes</summary>
public class AABB_t
{
    [JsonPropertyName("m_vMinBounds")]
    public Vector M_vMinBounds { get; set; }  // +0x0
    [JsonPropertyName("m_vMaxBounds")]
    public Vector M_vMaxBounds { get; set; }  // +0xC
}

/// <summary>CFuseProgram, 80 bytes</summary>
public class CFuseProgram
{
    [JsonPropertyName("m_programBuffer")]
    public byte[] M_programBuffer { get; set; }  // +0x0
    [JsonPropertyName("m_variablesRead")]
    public FuseVariableIndex_t[] M_variablesRead { get; set; }  // +0x18
    [JsonPropertyName("m_variablesWritten")]
    public FuseVariableIndex_t[] M_variablesWritten { get; set; }  // +0x30
    [JsonPropertyName("m_nMaxTempVarsUsed")]
    public int M_nMaxTempVarsUsed { get; set; }  // +0x48
}

/// <summary>CFuseSymbolTable, 176 bytes</summary>
public class CFuseSymbolTable
{
    [JsonPropertyName("m_constants")]
    public ConstantInfo_t[] M_constants { get; set; }  // +0x0
    [JsonPropertyName("m_variables")]
    public VariableInfo_t[] M_variables { get; set; }  // +0x18
    [JsonPropertyName("m_functions")]
    public FunctionInfo_t[] M_functions { get; set; }  // +0x30
    [JsonPropertyName("m_constantMap")]
    public Dictionary<string, object> /* map */ M_constantMap { get; set; }  // +0x48
    [JsonPropertyName("m_variableMap")]
    public Dictionary<string, object> /* map */ M_variableMap { get; set; }  // +0x68
    [JsonPropertyName("m_functionMap")]
    public Dictionary<string, object> /* map */ M_functionMap { get; set; }  // +0x88
}

/// <summary>ConstantInfo_t, 16 bytes</summary>
public class ConstantInfo_t
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x0
    [JsonPropertyName("m_nameToken")]
    public string M_nameToken { get; set; }  // +0x8
    [JsonPropertyName("m_flValue")]
    public float M_flValue { get; set; }  // +0xC
}

/// <summary>FourQuaternions, 64 bytes</summary>
public class FourQuaternions
{
    [JsonPropertyName("x")]
    public fltx4 X { get; set; }  // +0x0
    [JsonPropertyName("y")]
    public fltx4 Y { get; set; }  // +0x10
    [JsonPropertyName("z")]
    public fltx4 Z { get; set; }  // +0x20
    [JsonPropertyName("w")]
    public fltx4 W { get; set; }  // +0x30
}

/// <summary>FunctionInfo_t, 32 bytes</summary>
public class FunctionInfo_t
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x8
    [JsonPropertyName("m_nameToken")]
    public string M_nameToken { get; set; }  // +0x10
    [JsonPropertyName("m_nParamCount")]
    public int M_nParamCount { get; set; }  // +0x14
    [JsonPropertyName("m_nIndex")]
    public FuseFunctionIndex_t M_nIndex { get; set; }  // +0x18
    [JsonPropertyName("m_bIsPure")]
    public bool M_bIsPure { get; set; }  // +0x1A
}

/// <summary>FuseFunctionIndex_t, 2 bytes</summary>
public class FuseFunctionIndex_t
{
    [JsonPropertyName("m_Value")]
    public ushort M_Value { get; set; }  // +0x0
}

public enum FuseVariableAccess_t : byte
{
    WRITABLE = 0,
    READ_ONLY = 1,
}

/// <summary>FuseVariableIndex_t, 2 bytes</summary>
public class FuseVariableIndex_t
{
    [JsonPropertyName("m_Value")]
    public ushort M_Value { get; set; }  // +0x0
}

public enum FuseVariableType_t : byte
{
    INVALID = 0,
    BOOL = 1,
    INT8 = 2,
    INT16 = 3,
    INT32 = 4,
    UINT8 = 5,
    UINT16 = 6,
    UINT32 = 7,
    FLOAT32 = 8,
}

/// <summary>PackedAABB_t, 8 bytes</summary>
public class PackedAABB_t
{
    [JsonPropertyName("m_nPackedMin")]
    public uint M_nPackedMin { get; set; }  // +0x0
    [JsonPropertyName("m_nPackedMax")]
    public uint M_nPackedMax { get; set; }  // +0x4
}

/// <summary>VariableInfo_t, 24 bytes</summary>
public class VariableInfo_t
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x0
    [JsonPropertyName("m_nameToken")]
    public string M_nameToken { get; set; }  // +0x8
    [JsonPropertyName("m_nIndex")]
    public FuseVariableIndex_t M_nIndex { get; set; }  // +0xC
    [JsonPropertyName("m_nNumComponents")]
    public byte M_nNumComponents { get; set; }  // +0xE
    [JsonPropertyName("m_eVarType")]
    public FuseVariableType_t M_eVarType { get; set; }  // +0xF
    [JsonPropertyName("m_eAccess")]
    public FuseVariableAccess_t M_eAccess { get; set; }  // +0x10
}

