// Auto-generated by cs2-codegen from schemas_jsonschema.json
// Revision 10638965 (May 06 2026) — https://github.com/ValveResourceFormat/DumpSource2
// Do not edit by hand.
// Module: met

#nullable enable
#pragma warning disable CS8618  // non-nullable property not initialized (expected in generated serialization types)

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CS2Schema;

/// <summary>EMaterialLayer_t, 112 bytes</summary>
public class EMaterialLayer_t
{
    [JsonPropertyName("m_VariableNames")]
    public string[] M_VariableNames { get; set; }  // +0x0
    [JsonPropertyName("m_HiddenVariableUiNames")]
    public Dictionary<string, object> /* map */[] M_HiddenVariableUiNames { get; set; }  // +0x18
    [JsonPropertyName("m_ReferenceVariableIndex")]
    public int M_ReferenceVariableIndex { get; set; }  // +0x30
    [JsonPropertyName("m_RefType")]
    public string M_RefType { get; set; }  // +0x38
    [JsonPropertyName("m_RefFileEnding")]
    public string M_RefFileEnding { get; set; }  // +0x40
    [JsonPropertyName("m_bActive")]
    public bool M_bActive { get; set; }  // +0x48
    [JsonPropertyName("inheritedVariableValues")]
    public object /* opaque */ InheritedVariableValues { get; set; }  // +0x50
    [JsonPropertyName("inheritedVariableSources")]
    public object /* opaque */ InheritedVariableSources { get; set; }  // +0x60
}

/// <summary>EMaterialVariable_t, 248 bytes</summary>
public class EMaterialVariable_t
{
    [JsonPropertyName("m_Name")]
    public string M_Name { get; set; }  // +0x0
    [JsonPropertyName("m_ExportName")]
    public string M_ExportName { get; set; }  // +0x8
    [JsonPropertyName("m_UiName")]
    public string M_UiName { get; set; }  // +0x10
    [JsonPropertyName("m_UiOptions")]
    public string M_UiOptions { get; set; }  // +0x18
    [JsonPropertyName("m_bEnabled")]
    public bool M_bEnabled { get; set; }  // +0x20
    [JsonPropertyName("m_bHidden")]
    public bool M_bHidden { get; set; }  // +0x21
    [JsonPropertyName("m_EnumLabel")]
    public string M_EnumLabel { get; set; }  // +0x28
    [JsonPropertyName("m_nLayerId")]
    public int M_nLayerId { get; set; }  // +0x30
    [JsonPropertyName("m_bLayerAllowOverride")]
    public bool M_bLayerAllowOverride { get; set; }  // +0x34
    [JsonPropertyName("m_bLayerReference")]
    public bool M_bLayerReference { get; set; }  // +0x35
    [JsonPropertyName("m_inheritedValue")]
    public string M_inheritedValue { get; set; }  // +0x38
    [JsonPropertyName("m_inheritedValueSource")]
    public string M_inheritedValueSource { get; set; }  // +0x40
    [JsonPropertyName("m_Group")]
    public string M_Group { get; set; }  // +0x48
    [JsonPropertyName("m_SubGroup")]
    public string M_SubGroup { get; set; }  // +0x50
    [JsonPropertyName("m_nSortKeyGroup")]
    public int M_nSortKeyGroup { get; set; }  // +0x58
    [JsonPropertyName("m_nSortKeySubGroup")]
    public int M_nSortKeySubGroup { get; set; }  // +0x5C
    [JsonPropertyName("m_nSortKeyVariable")]
    public int M_nSortKeyVariable { get; set; }  // +0x60
    [JsonPropertyName("m_error")]
    public string M_error { get; set; }  // +0x68
    [JsonPropertyName("m_expression")]
    public string M_expression { get; set; }  // +0x70
    [JsonPropertyName("m_referencedExpressionPath")]
    public string M_referencedExpressionPath { get; set; }  // +0x78
    [JsonPropertyName("m_referencedValuePath")]
    public string M_referencedValuePath { get; set; }  // +0x80
    [JsonPropertyName("m_nElements")]
    public int M_nElements { get; set; }  // +0x88
    [JsonPropertyName("m_value")]
    public string M_value { get; set; }  // +0x90
    [JsonPropertyName("m_default")]
    public string M_default { get; set; }  // +0x98
    [JsonPropertyName("m_min")]
    public string M_min { get; set; }  // +0xA0
    [JsonPropertyName("m_max")]
    public string M_max { get; set; }  // +0xA8
    [JsonPropertyName("m_step")]
    public string M_step { get; set; }  // +0xB0
    [JsonPropertyName("m_precision")]
    public string M_precision { get; set; }  // +0xB8
    [JsonPropertyName("m_bInitialTextureInput")]
    public bool M_bInitialTextureInput { get; set; }  // +0xC0
    [JsonPropertyName("m_nTextureAutoFillCount")]
    public int M_nTextureAutoFillCount { get; set; }  // +0xC4
    [JsonPropertyName("m_alternateInput")]
    public string M_alternateInput { get; set; }  // +0xC8
    [JsonPropertyName("m_defaultColor")]
    public string M_defaultColor { get; set; }  // +0xD0
    [JsonPropertyName("m_defaultInput")]
    public string M_defaultInput { get; set; }  // +0xD8
    [JsonPropertyName("m_textureSuffix")]
    public string M_textureSuffix { get; set; }  // +0xE0
    [JsonPropertyName("m_defaultSlider")]
    public string M_defaultSlider { get; set; }  // +0xE8
    [JsonPropertyName("m_fDefaultSlider")]
    public float[] M_fDefaultSlider { get; set; }  // +0xF0
}

/// <summary>EMaterialVariables_t, 64 bytes</summary>
public class EMaterialVariables_t
{
    [JsonPropertyName("m_bIsLayeredShader")]
    public bool M_bIsLayeredShader { get; set; }  // +0x0
    [JsonPropertyName("m_Variables")]
    public EMaterialVariable_t[] M_Variables { get; set; }  // +0x8
    [JsonPropertyName("m_Layers")]
    public EMaterialLayer_t[] M_Layers { get; set; }  // +0x20
}

