// Auto-generated by cs2-codegen from schemas_jsonschema.json
// Revision 10638965 (May 06 2026) — https://github.com/ValveResourceFormat/DumpSource2
// Do not edit by hand.
// Module: modeldoc_editor

#nullable enable
#pragma warning disable CS8618  // non-nullable property not initialized (expected in generated serialization types)

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CS2Schema;

/// <summary>CMotionAnalysisSettings, 144 bytes</summary>
public class CMotionAnalysisSettings
{
    [JsonPropertyName("m_Description")]
    public string M_Description { get; set; }  // +0x0
    [JsonPropertyName("m_flLinearThresholdSlow")]
    public float M_flLinearThresholdSlow { get; set; }  // +0x8
    [JsonPropertyName("m_flLinearThresholdStopped")]
    public float M_flLinearThresholdStopped { get; set; }  // +0xC
    [JsonPropertyName("m_flAngularThresholdSlow")]
    public float M_flAngularThresholdSlow { get; set; }  // +0x10
    [JsonPropertyName("m_flAngularThresholdStopped")]
    public float M_flAngularThresholdStopped { get; set; }  // +0x14
    [JsonPropertyName("m_Feet")]
    public object /* opaque */ M_Feet { get; set; }  // +0x18
}

/// <summary>CMotionAnalysisSettings_Foot, 72 bytes</summary>
public class CMotionAnalysisSettings_Foot
{
    [JsonPropertyName("m_AnkleBoneNames")]
    public string[] M_AnkleBoneNames { get; set; }  // +0x0
    [JsonPropertyName("m_AttachmentNames")]
    public string[] M_AttachmentNames { get; set; }  // +0x18
    [JsonPropertyName("m_DebugColor")]
    public Color M_DebugColor { get; set; }  // +0x30
    [JsonPropertyName("m_CreatedEventType")]
    public string M_CreatedEventType { get; set; }  // +0x38
    [JsonPropertyName("m_CreatedEventFootValue")]
    public string M_CreatedEventFootValue { get; set; }  // +0x40
}

/// <summary>DuplicateAndMirrorAttachmentOpts_t, 16 bytes</summary>
public class DuplicateAndMirrorAttachmentOpts_t
{
    [JsonPropertyName("m_Name")]
    public string M_Name { get; set; }  // +0x0
    [JsonPropertyName("m_eMirrorSpace")]
    public MirrorSpace_t M_eMirrorSpace { get; set; }  // +0x8
    [JsonPropertyName("m_bSwapLeftRightParentBones")]
    public bool M_bSwapLeftRightParentBones { get; set; }  // +0xC
    [JsonPropertyName("m_bMirrorX")]
    public bool M_bMirrorX { get; set; }  // +0xD
    [JsonPropertyName("m_bMirrorY")]
    public bool M_bMirrorY { get; set; }  // +0xE
    [JsonPropertyName("m_bMirrorZ")]
    public bool M_bMirrorZ { get; set; }  // +0xF
}

public enum MirrorSpace_t : uint
{
    MIRROR_SPACE_BONE_RELATIVE = 0,
    MIRROR_SPACE_MODEL_RELATIVE = 1,
}

