// Auto-generated by cs2-codegen from schemas_jsonschema.json
// Revision 10638965 (May 06 2026) — https://github.com/ValveResourceFormat/DumpSource2
// Do not edit by hand.
// Module: modellib

#nullable enable
#pragma warning disable CS8618  // non-nullable property not initialized (expected in generated serialization types)

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CS2Schema;

/// <summary>AnimComponentID, 4 bytes</summary>
public class AnimComponentID
{
    [JsonPropertyName("m_id")]
    public uint M_id { get; set; }  // +0x0
}

/// <summary>AnimNodeID, 4 bytes</summary>
public class AnimNodeID
{
    [JsonPropertyName("m_id")]
    public uint M_id { get; set; }  // +0x0
}

/// <summary>AnimNodeOutputID, 4 bytes</summary>
public class AnimNodeOutputID
{
    [JsonPropertyName("m_id")]
    public uint M_id { get; set; }  // +0x0
}

/// <summary>AnimParamID, 4 bytes</summary>
public class AnimParamID
{
    [JsonPropertyName("m_id")]
    public uint M_id { get; set; }  // +0x0
}

/// <summary>AnimScriptHandle, 4 bytes</summary>
public class AnimScriptHandle
{
    [JsonPropertyName("m_id")]
    public uint M_id { get; set; }  // +0x0
}

/// <summary>AnimStateID, 4 bytes</summary>
public class AnimStateID
{
    [JsonPropertyName("m_id")]
    public uint M_id { get; set; }  // +0x0
}

/// <summary>AnimTagID, 4 bytes</summary>
public class AnimTagID
{
    [JsonPropertyName("m_id")]
    public uint M_id { get; set; }  // +0x0
}

/// <summary>AttachmentHandle_t, 1 bytes</summary>
public class AttachmentHandle_t
{
    [JsonPropertyName("m_Value")]
    public byte M_Value { get; set; }  // +0x0
}

/// <summary>CAimConstraint, 128 bytes</summary>
public class CAimConstraint : CBaseConstraint
{
    [JsonPropertyName("m_qAimOffset")]
    public Quaternion M_qAimOffset { get; set; }  // +0x60
    [JsonPropertyName("m_nUpType")]
    public uint M_nUpType { get; set; }  // +0x70
}

/// <summary>CAnimAttachment, 128 bytes</summary>
public class CAnimAttachment
{
    [JsonPropertyName("m_influenceRotations")]
    public Quaternion[] M_influenceRotations { get; set; }  // +0x0
    [JsonPropertyName("m_influenceOffsets")]
    public VectorAligned[] M_influenceOffsets { get; set; }  // +0x30
    [JsonPropertyName("m_influenceIndices")]
    public int[] M_influenceIndices { get; set; }  // +0x60
    [JsonPropertyName("m_influenceWeights")]
    public float[] M_influenceWeights { get; set; }  // +0x6C
    [JsonPropertyName("m_numInfluences")]
    public byte M_numInfluences { get; set; }  // +0x78
}

/// <summary>CAnimCycle, 4 bytes</summary>
public class CAnimCycle : CCycleBase
{
}

/// <summary>CAnimFoot, 40 bytes</summary>
public class CAnimFoot
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x0
    [JsonPropertyName("m_vBallOffset")]
    public Vector M_vBallOffset { get; set; }  // +0x8
    [JsonPropertyName("m_vHeelOffset")]
    public Vector M_vHeelOffset { get; set; }  // +0x14
    [JsonPropertyName("m_ankleBoneIndex")]
    public int M_ankleBoneIndex { get; set; }  // +0x20
    [JsonPropertyName("m_toeBoneIndex")]
    public int M_toeBoneIndex { get; set; }  // +0x24
}

/// <summary>CAnimSkeleton, 208 bytes</summary>
public class CAnimSkeleton
{
    [JsonPropertyName("m_localSpaceTransforms")]
    public CTransform[] M_localSpaceTransforms { get; set; }  // +0x10
    [JsonPropertyName("m_modelSpaceTransforms")]
    public CTransform[] M_modelSpaceTransforms { get; set; }  // +0x28
    [JsonPropertyName("m_boneNames")]
    public string[] M_boneNames { get; set; }  // +0x40
    [JsonPropertyName("m_children")]
    public int[][] M_children { get; set; }  // +0x58
    [JsonPropertyName("m_parents")]
    public int[] M_parents { get; set; }  // +0x70
    [JsonPropertyName("m_feet")]
    public CAnimFoot[] M_feet { get; set; }  // +0x88
    [JsonPropertyName("m_morphNames")]
    public string[] M_morphNames { get; set; }  // +0xA0
    [JsonPropertyName("m_lodBoneCounts")]
    public int[] M_lodBoneCounts { get; set; }  // +0xB8
}

/// <summary>CAttachment, 144 bytes</summary>
public class CAttachment
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x0
    [JsonPropertyName("m_influenceNames")]
    public string[] M_influenceNames { get; set; }  // +0x8
    [JsonPropertyName("m_vInfluenceRotations")]
    public Quaternion[] M_vInfluenceRotations { get; set; }  // +0x20
    [JsonPropertyName("m_vInfluenceOffsets")]
    public Vector[] M_vInfluenceOffsets { get; set; }  // +0x50
    [JsonPropertyName("m_influenceWeights")]
    public float[] M_influenceWeights { get; set; }  // +0x74
    [JsonPropertyName("m_bInfluenceRootTransform")]
    public bool[] M_bInfluenceRootTransform { get; set; }  // +0x80
    [JsonPropertyName("m_nInfluences")]
    public byte M_nInfluences { get; set; }  // +0x83
    [JsonPropertyName("m_bIgnoreRotation")]
    public bool M_bIgnoreRotation { get; set; }  // +0x84
}

/// <summary>CBaseConstraint, 96 bytes</summary>
public class CBaseConstraint : CBoneConstraintBase
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x20
    [JsonPropertyName("m_vUpVector")]
    public Vector M_vUpVector { get; set; }  // +0x28
    [JsonPropertyName("m_slaves")]
    public CConstraintSlave[] M_slaves { get; set; }  // +0x38
    [JsonPropertyName("m_targets")]
    public CConstraintTarget[] M_targets { get; set; }  // +0x48
}

/// <summary>CBoneConstraintBase, 32 bytes</summary>
public class CBoneConstraintBase
{
}

/// <summary>CBoneConstraintDotToMorph, 88 bytes</summary>
public class CBoneConstraintDotToMorph : CBoneConstraintBase
{
    [JsonPropertyName("m_sBoneName")]
    public string M_sBoneName { get; set; }  // +0x20
    [JsonPropertyName("m_sTargetBoneName")]
    public string M_sTargetBoneName { get; set; }  // +0x28
    [JsonPropertyName("m_sMorphChannelName")]
    public string M_sMorphChannelName { get; set; }  // +0x30
    [JsonPropertyName("m_flRemap")]
    public float[] M_flRemap { get; set; }  // +0x38
}

/// <summary>CBoneConstraintPoseSpaceBone, 136 bytes</summary>
public class CBoneConstraintPoseSpaceBone : CBaseConstraint
{
    [JsonPropertyName("m_inputList")]
    public CBoneConstraintPoseSpaceBone_Input_t[] M_inputList { get; set; }  // +0x60
}

/// <summary>CBoneConstraintPoseSpaceBone::Input_t, 40 bytes</summary>
public class CBoneConstraintPoseSpaceBone_Input_t
{
    [JsonPropertyName("m_inputValue")]
    public Vector M_inputValue { get; set; }  // +0x0
    [JsonPropertyName("m_outputTransformList")]
    public CTransform[] M_outputTransformList { get; set; }  // +0x10
}

/// <summary>CBoneConstraintPoseSpaceMorph, 160 bytes</summary>
public class CBoneConstraintPoseSpaceMorph : CBoneConstraintBase
{
    [JsonPropertyName("m_sBoneName")]
    public string M_sBoneName { get; set; }  // +0x20
    [JsonPropertyName("m_sAttachmentName")]
    public string M_sAttachmentName { get; set; }  // +0x28
    [JsonPropertyName("m_outputMorph")]
    public string[] M_outputMorph { get; set; }  // +0x30
    [JsonPropertyName("m_inputList")]
    public CBoneConstraintPoseSpaceMorph_Input_t[] M_inputList { get; set; }  // +0x48
    [JsonPropertyName("m_bClamp")]
    public bool M_bClamp { get; set; }  // +0x60
}

/// <summary>CBoneConstraintPoseSpaceMorph::Input_t, 40 bytes</summary>
public class CBoneConstraintPoseSpaceMorph_Input_t
{
    [JsonPropertyName("m_inputValue")]
    public Vector M_inputValue { get; set; }  // +0x0
    [JsonPropertyName("m_outputWeightList")]
    public float[] M_outputWeightList { get; set; }  // +0x10
}

/// <summary>CBoneConstraintRbf, 200 bytes</summary>
public class CBoneConstraintRbf : CBoneConstraintBase
{
    [JsonPropertyName("m_inputBones")]
    public Dictionary<string, object> /* map */[] M_inputBones { get; set; }  // +0x20
    [JsonPropertyName("m_outputBones")]
    public Dictionary<string, object> /* map */[] M_outputBones { get; set; }  // +0x38
}

/// <summary>CConstraintSlave, 80 bytes</summary>
public class CConstraintSlave
{
    [JsonPropertyName("m_qBaseOrientation")]
    public Quaternion M_qBaseOrientation { get; set; }  // +0x0
    [JsonPropertyName("m_vBasePosition")]
    public Vector M_vBasePosition { get; set; }  // +0x10
    [JsonPropertyName("m_nBoneHash")]
    public uint M_nBoneHash { get; set; }  // +0x1C
    [JsonPropertyName("m_flWeight")]
    public float M_flWeight { get; set; }  // +0x20
    [JsonPropertyName("m_sName")]
    public string M_sName { get; set; }  // +0x28
}

/// <summary>CConstraintTarget, 96 bytes</summary>
public class CConstraintTarget
{
    [JsonPropertyName("m_qOffset")]
    public Quaternion M_qOffset { get; set; }  // +0x20
    [JsonPropertyName("m_vOffset")]
    public Vector M_vOffset { get; set; }  // +0x30
    [JsonPropertyName("m_nBoneHash")]
    public uint M_nBoneHash { get; set; }  // +0x3C
    [JsonPropertyName("m_sName")]
    public string M_sName { get; set; }  // +0x40
    [JsonPropertyName("m_flWeight")]
    public float M_flWeight { get; set; }  // +0x48
    [JsonPropertyName("m_bIsAttachment")]
    public bool M_bIsAttachment { get; set; }  // +0x59
}

/// <summary>CCycleBase, 4 bytes</summary>
public class CCycleBase
{
    [JsonPropertyName("m_flCycle")]
    public float M_flCycle { get; set; }  // +0x0
}

/// <summary>CDrawCullingData, 4 bytes</summary>
public class CDrawCullingData
{
    [JsonPropertyName("m_ConeAxis")]
    public sbyte[] M_ConeAxis { get; set; }  // +0x0
    [JsonPropertyName("m_ConeCutoff")]
    public sbyte M_ConeCutoff { get; set; }  // +0x3
}

/// <summary>CFlexController, 24 bytes</summary>
public class CFlexController
{
    [JsonPropertyName("m_szName")]
    public string M_szName { get; set; }  // +0x0
    [JsonPropertyName("m_szType")]
    public string M_szType { get; set; }  // +0x8
    [JsonPropertyName("min")]
    public float Min { get; set; }  // +0x10
    [JsonPropertyName("max")]
    public float Max { get; set; }  // +0x14
}

/// <summary>CFlexDesc, 8 bytes</summary>
public class CFlexDesc
{
    [JsonPropertyName("m_szFacs")]
    public string M_szFacs { get; set; }  // +0x0
}

/// <summary>CFlexOp, 8 bytes</summary>
public class CFlexOp
{
    [JsonPropertyName("m_OpCode")]
    public FlexOpCode_t M_OpCode { get; set; }  // +0x0
    [JsonPropertyName("m_Data")]
    public int M_Data { get; set; }  // +0x4
}

/// <summary>CFlexRule, 32 bytes</summary>
public class CFlexRule
{
    [JsonPropertyName("m_nFlex")]
    public int M_nFlex { get; set; }  // +0x0
    [JsonPropertyName("m_FlexOps")]
    public CFlexOp[] M_FlexOps { get; set; }  // +0x8
}

/// <summary>CFootCycle, 4 bytes</summary>
public class CFootCycle : CCycleBase
{
}

/// <summary>CFootCycleDefinition, 60 bytes</summary>
public class CFootCycleDefinition
{
    [JsonPropertyName("m_vStancePositionMS")]
    public Vector M_vStancePositionMS { get; set; }  // +0x0
    [JsonPropertyName("m_vMidpointPositionMS")]
    public Vector M_vMidpointPositionMS { get; set; }  // +0xC
    [JsonPropertyName("m_flStanceDirectionMS")]
    public float M_flStanceDirectionMS { get; set; }  // +0x18
    [JsonPropertyName("m_vToStrideStartPos")]
    public Vector M_vToStrideStartPos { get; set; }  // +0x1C
    [JsonPropertyName("m_stanceCycle")]
    public CAnimCycle M_stanceCycle { get; set; }  // +0x28
    [JsonPropertyName("m_footLiftCycle")]
    public CFootCycle M_footLiftCycle { get; set; }  // +0x2C
    [JsonPropertyName("m_footOffCycle")]
    public CFootCycle M_footOffCycle { get; set; }  // +0x30
    [JsonPropertyName("m_footStrikeCycle")]
    public CFootCycle M_footStrikeCycle { get; set; }  // +0x34
    [JsonPropertyName("m_footLandCycle")]
    public CFootCycle M_footLandCycle { get; set; }  // +0x38
}

/// <summary>CFootDefinition, 64 bytes</summary>
public class CFootDefinition
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x0
    [JsonPropertyName("m_ankleBoneName")]
    public string M_ankleBoneName { get; set; }  // +0x8
    [JsonPropertyName("m_toeBoneName")]
    public string M_toeBoneName { get; set; }  // +0x10
    [JsonPropertyName("m_vBallOffset")]
    public Vector M_vBallOffset { get; set; }  // +0x18
    [JsonPropertyName("m_vHeelOffset")]
    public Vector M_vHeelOffset { get; set; }  // +0x24
    [JsonPropertyName("m_flFootLength")]
    public float M_flFootLength { get; set; }  // +0x30
    [JsonPropertyName("m_flBindPoseDirectionMS")]
    public float M_flBindPoseDirectionMS { get; set; }  // +0x34
    [JsonPropertyName("m_flTraceHeight")]
    public float M_flTraceHeight { get; set; }  // +0x38
    [JsonPropertyName("m_flTraceRadius")]
    public float M_flTraceRadius { get; set; }  // +0x3C
}

/// <summary>CFootMotion, 40 bytes</summary>
public class CFootMotion
{
    [JsonPropertyName("m_strides")]
    public CFootStride[] M_strides { get; set; }  // +0x0
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x18
    [JsonPropertyName("m_bAdditive")]
    public bool M_bAdditive { get; set; }  // +0x20
}

/// <summary>CFootStride, 88 bytes</summary>
public class CFootStride
{
    [JsonPropertyName("m_definition")]
    public CFootCycleDefinition M_definition { get; set; }  // +0x0
    [JsonPropertyName("m_trajectories")]
    public CFootTrajectories M_trajectories { get; set; }  // +0x40
}

/// <summary>CFootTrajectories, 24 bytes</summary>
public class CFootTrajectories
{
    [JsonPropertyName("m_trajectories")]
    public CFootTrajectory[] M_trajectories { get; set; }  // +0x0
}

/// <summary>CFootTrajectory, 32 bytes</summary>
public class CFootTrajectory
{
    [JsonPropertyName("m_vOffset")]
    public Vector M_vOffset { get; set; }  // +0x8
    [JsonPropertyName("m_flRotationOffset")]
    public float M_flRotationOffset { get; set; }  // +0x14
    [JsonPropertyName("m_flProgression")]
    public float M_flProgression { get; set; }  // +0x18
}

/// <summary>CHitBox, 112 bytes</summary>
public class CHitBox
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x0
    [JsonPropertyName("m_sSurfaceProperty")]
    public string M_sSurfaceProperty { get; set; }  // +0x8
    [JsonPropertyName("m_sBoneName")]
    public string M_sBoneName { get; set; }  // +0x10
    [JsonPropertyName("m_vMinBounds")]
    public Vector M_vMinBounds { get; set; }  // +0x18
    [JsonPropertyName("m_vMaxBounds")]
    public Vector M_vMaxBounds { get; set; }  // +0x24
    [JsonPropertyName("m_flShapeRadius")]
    public float M_flShapeRadius { get; set; }  // +0x30
    [JsonPropertyName("m_nBoneNameHash")]
    public uint M_nBoneNameHash { get; set; }  // +0x34
    [JsonPropertyName("m_nGroupId")]
    public int M_nGroupId { get; set; }  // +0x38
    [JsonPropertyName("m_nShapeType")]
    public byte M_nShapeType { get; set; }  // +0x3C
    [JsonPropertyName("m_bTranslationOnly")]
    public bool M_bTranslationOnly { get; set; }  // +0x3D
    [JsonPropertyName("m_CRC")]
    public uint M_CRC { get; set; }  // +0x40
    [JsonPropertyName("m_cRenderColor")]
    public Color M_cRenderColor { get; set; }  // +0x44
    [JsonPropertyName("m_nHitBoxIndex")]
    public ushort M_nHitBoxIndex { get; set; }  // +0x48
}

/// <summary>CHitBoxSet, 48 bytes</summary>
public class CHitBoxSet
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x0
    [JsonPropertyName("m_nNameHash")]
    public uint M_nNameHash { get; set; }  // +0x8
    [JsonPropertyName("m_HitBoxes")]
    public CHitBox[] M_HitBoxes { get; set; }  // +0x10
    [JsonPropertyName("m_SourceFilename")]
    public string M_SourceFilename { get; set; }  // +0x28
}

/// <summary>CHitBoxSetList, 24 bytes</summary>
public class CHitBoxSetList
{
    [JsonPropertyName("m_HitBoxSets")]
    public CHitBoxSet[] M_HitBoxSets { get; set; }  // +0x0
}

/// <summary>CMaterialDrawDescriptor, 264 bytes</summary>
public class CMaterialDrawDescriptor
{
    [JsonPropertyName("m_flUvDensity")]
    public float M_flUvDensity { get; set; }  // +0x0
    [JsonPropertyName("m_vTintColor")]
    public Vector M_vTintColor { get; set; }  // +0x4
    [JsonPropertyName("m_flAlpha")]
    public float M_flAlpha { get; set; }  // +0x10
    [JsonPropertyName("m_nNumMeshlets")]
    public ushort M_nNumMeshlets { get; set; }  // +0x16
    [JsonPropertyName("m_nFirstMeshlet")]
    public uint M_nFirstMeshlet { get; set; }  // +0x1C
    [JsonPropertyName("m_nAppliedIndexOffset")]
    public uint M_nAppliedIndexOffset { get; set; }  // +0x20
    [JsonPropertyName("m_nDepthVertexBufferIndex")]
    public byte M_nDepthVertexBufferIndex { get; set; }  // +0x24
    [JsonPropertyName("m_nMeshletPackedIVBIndex")]
    public byte M_nMeshletPackedIVBIndex { get; set; }  // +0x25
    [JsonPropertyName("m_rigidMeshParts")]
    public CMaterialDrawDescriptor_RigidMeshPart_t[] M_rigidMeshParts { get; set; }  // +0x28
    [JsonPropertyName("m_nPrimitiveType")]
    public RenderPrimitiveType_t M_nPrimitiveType { get; set; }  // +0x38
    [JsonPropertyName("m_nBaseVertex")]
    public int M_nBaseVertex { get; set; }  // +0x3C
    [JsonPropertyName("m_nVertexCount")]
    public int M_nVertexCount { get; set; }  // +0x40
    [JsonPropertyName("m_nStartIndex")]
    public int M_nStartIndex { get; set; }  // +0x44
    [JsonPropertyName("m_nIndexCount")]
    public int M_nIndexCount { get; set; }  // +0x48
    [JsonPropertyName("m_indexBuffer")]
    public CRenderBufferBinding M_indexBuffer { get; set; }  // +0xB0
    [JsonPropertyName("m_meshletPackedIVB")]
    public CRenderBufferBinding M_meshletPackedIVB { get; set; }  // +0xD0
    [JsonPropertyName("m_material")]
    public InfoForResourceTypeIMaterial2? M_material { get; set; }  // +0x100
}

/// <summary>CMaterialDrawDescriptor::RigidMeshPart_t, 12 bytes</summary>
public class CMaterialDrawDescriptor_RigidMeshPart_t
{
    [JsonPropertyName("m_nRigidBLASIndex")]
    public ushort M_nRigidBLASIndex { get; set; }  // +0x0
    [JsonPropertyName("m_nBoneIndex")]
    public short M_nBoneIndex { get; set; }  // +0x2
    [JsonPropertyName("m_nStartIndexOffset")]
    public uint M_nStartIndexOffset { get; set; }  // +0x4
    [JsonPropertyName("m_nPrimitiveCount")]
    public uint M_nPrimitiveCount { get; set; }  // +0x8
}

/// <summary>CMeshletDescriptor, 24 bytes</summary>
public class CMeshletDescriptor
{
    [JsonPropertyName("m_PackedAABB")]
    public PackedAABB_t M_PackedAABB { get; set; }  // +0x0
    [JsonPropertyName("m_CullingData")]
    public CDrawCullingData M_CullingData { get; set; }  // +0x8
    [JsonPropertyName("m_nVertexOffset")]
    public uint M_nVertexOffset { get; set; }  // +0xC
    [JsonPropertyName("m_nTriangleOffset")]
    public uint M_nTriangleOffset { get; set; }  // +0x10
    [JsonPropertyName("m_nVertexCount")]
    public byte M_nVertexCount { get; set; }  // +0x14
    [JsonPropertyName("m_nTriangleCount")]
    public byte M_nTriangleCount { get; set; }  // +0x15
}

/// <summary>CModelConfig, 40 bytes</summary>
public class CModelConfig
{
    [JsonPropertyName("m_ConfigName")]
    public string M_ConfigName { get; set; }  // +0x0
    [JsonPropertyName("m_Elements")]
    public CModelConfigElement?[] M_Elements { get; set; }  // +0x8
    [JsonPropertyName("m_bTopLevel")]
    public bool M_bTopLevel { get; set; }  // +0x20
    [JsonPropertyName("m_bActiveInEditorByDefault")]
    public bool M_bActiveInEditorByDefault { get; set; }  // +0x21
}

/// <summary>CModelConfigElement, 72 bytes</summary>
public class CModelConfigElement
{
    [JsonPropertyName("m_ElementName")]
    public string M_ElementName { get; set; }  // +0x8
    [JsonPropertyName("m_NestedElements")]
    public CModelConfigElement?[] M_NestedElements { get; set; }  // +0x10
}

/// <summary>CModelConfigElement_AttachedModel, 232 bytes</summary>
public class CModelConfigElement_AttachedModel : CModelConfigElement
{
    [JsonPropertyName("m_InstanceName")]
    public string M_InstanceName { get; set; }  // +0x48
    [JsonPropertyName("m_EntityClass")]
    public string M_EntityClass { get; set; }  // +0x50
    [JsonPropertyName("m_hModel")]
    public InfoForResourceTypeCModel? M_hModel { get; set; }  // +0x58
    [JsonPropertyName("m_vOffset")]
    public Vector M_vOffset { get; set; }  // +0x60
    [JsonPropertyName("m_aAngOffset")]
    public QAngle M_aAngOffset { get; set; }  // +0x6C
    [JsonPropertyName("m_AttachmentName")]
    public string M_AttachmentName { get; set; }  // +0x78
    [JsonPropertyName("m_LocalAttachmentOffsetName")]
    public string M_LocalAttachmentOffsetName { get; set; }  // +0x80
    [JsonPropertyName("m_AttachmentType")]
    public ModelConfigAttachmentType_t M_AttachmentType { get; set; }  // +0x88
    [JsonPropertyName("m_bBoneMergeFlex")]
    public bool M_bBoneMergeFlex { get; set; }  // +0x8C
    [JsonPropertyName("m_bUserSpecifiedColor")]
    public bool M_bUserSpecifiedColor { get; set; }  // +0x8D
    [JsonPropertyName("m_bUserSpecifiedMaterialGroup")]
    public bool M_bUserSpecifiedMaterialGroup { get; set; }  // +0x8E
    [JsonPropertyName("m_BodygroupOnOtherModels")]
    public string M_BodygroupOnOtherModels { get; set; }  // +0x90
    [JsonPropertyName("m_MaterialGroupOnOtherModels")]
    public string M_MaterialGroupOnOtherModels { get; set; }  // +0x98
}

/// <summary>CModelConfigElement_Command, 96 bytes</summary>
public class CModelConfigElement_Command : CModelConfigElement
{
    [JsonPropertyName("m_Command")]
    public string M_Command { get; set; }  // +0x48
    [JsonPropertyName("m_Args")]
    public object /* opaque */ M_Args { get; set; }  // +0x50
}

/// <summary>CModelConfigElement_RandomColor, 96 bytes</summary>
public class CModelConfigElement_RandomColor : CModelConfigElement
{
    [JsonPropertyName("m_Gradient")]
    public object /* opaque */ M_Gradient { get; set; }  // +0x48
}

/// <summary>CModelConfigElement_RandomPick, 128 bytes</summary>
public class CModelConfigElement_RandomPick : CModelConfigElement
{
    [JsonPropertyName("m_Choices")]
    public string[] M_Choices { get; set; }  // +0x48
    [JsonPropertyName("m_ChoiceWeights")]
    public float[] M_ChoiceWeights { get; set; }  // +0x60
}

/// <summary>CModelConfigElement_SetBodygroup, 88 bytes</summary>
public class CModelConfigElement_SetBodygroup : CModelConfigElement
{
    [JsonPropertyName("m_GroupName")]
    public string M_GroupName { get; set; }  // +0x48
    [JsonPropertyName("m_nChoice")]
    public int M_nChoice { get; set; }  // +0x50
}

/// <summary>CModelConfigElement_SetBodygroupOnAttachedModels, 88 bytes</summary>
public class CModelConfigElement_SetBodygroupOnAttachedModels : CModelConfigElement
{
    [JsonPropertyName("m_GroupName")]
    public string M_GroupName { get; set; }  // +0x48
    [JsonPropertyName("m_nChoice")]
    public int M_nChoice { get; set; }  // +0x50
}

/// <summary>CModelConfigElement_SetMaterialGroup, 80 bytes</summary>
public class CModelConfigElement_SetMaterialGroup : CModelConfigElement
{
    [JsonPropertyName("m_MaterialGroupName")]
    public string M_MaterialGroupName { get; set; }  // +0x48
}

/// <summary>CModelConfigElement_SetMaterialGroupOnAttachedModels, 80 bytes</summary>
public class CModelConfigElement_SetMaterialGroupOnAttachedModels : CModelConfigElement
{
    [JsonPropertyName("m_MaterialGroupName")]
    public string M_MaterialGroupName { get; set; }  // +0x48
}

/// <summary>CModelConfigElement_SetRenderColor, 80 bytes</summary>
public class CModelConfigElement_SetRenderColor : CModelConfigElement
{
    [JsonPropertyName("m_Color")]
    public Color M_Color { get; set; }  // +0x48
}

/// <summary>CModelConfigElement_UserPick, 96 bytes</summary>
public class CModelConfigElement_UserPick : CModelConfigElement
{
    [JsonPropertyName("m_Choices")]
    public string[] M_Choices { get; set; }  // +0x48
}

/// <summary>CModelConfigList, 32 bytes</summary>
public class CModelConfigList
{
    [JsonPropertyName("m_bHideMaterialGroupInTools")]
    public bool M_bHideMaterialGroupInTools { get; set; }  // +0x0
    [JsonPropertyName("m_bHideRenderColorInTools")]
    public bool M_bHideRenderColorInTools { get; set; }  // +0x1
    [JsonPropertyName("m_Configs")]
    public CModelConfig?[] M_Configs { get; set; }  // +0x8
}

/// <summary>CMorphBundleData, 56 bytes</summary>
public class CMorphBundleData
{
    [JsonPropertyName("m_flULeftSrc")]
    public float M_flULeftSrc { get; set; }  // +0x0
    [JsonPropertyName("m_flVTopSrc")]
    public float M_flVTopSrc { get; set; }  // +0x4
    [JsonPropertyName("m_offsets")]
    public float[] M_offsets { get; set; }  // +0x8
    [JsonPropertyName("m_ranges")]
    public float[] M_ranges { get; set; }  // +0x20
}

/// <summary>CMorphConstraint, 128 bytes</summary>
public class CMorphConstraint : CBaseConstraint
{
    [JsonPropertyName("m_sTargetMorph")]
    public string M_sTargetMorph { get; set; }  // +0x60
    [JsonPropertyName("m_nSlaveChannel")]
    public int M_nSlaveChannel { get; set; }  // +0x68
    [JsonPropertyName("m_flMin")]
    public float M_flMin { get; set; }  // +0x6C
    [JsonPropertyName("m_flMax")]
    public float M_flMax { get; set; }  // +0x70
}

/// <summary>CMorphData, 32 bytes</summary>
public class CMorphData
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x0
    [JsonPropertyName("m_morphRectDatas")]
    public CMorphRectData[] M_morphRectDatas { get; set; }  // +0x8
}

/// <summary>CMorphRectData, 40 bytes</summary>
public class CMorphRectData
{
    [JsonPropertyName("m_nXLeftDst")]
    public short M_nXLeftDst { get; set; }  // +0x0
    [JsonPropertyName("m_nYTopDst")]
    public short M_nYTopDst { get; set; }  // +0x2
    [JsonPropertyName("m_flUWidthSrc")]
    public float M_flUWidthSrc { get; set; }  // +0x4
    [JsonPropertyName("m_flVHeightSrc")]
    public float M_flVHeightSrc { get; set; }  // +0x8
    [JsonPropertyName("m_bundleDatas")]
    public CMorphBundleData[] M_bundleDatas { get; set; }  // +0x10
}

/// <summary>CMorphSetData, 152 bytes</summary>
public class CMorphSetData
{
    [JsonPropertyName("m_nWidth")]
    public int M_nWidth { get; set; }  // +0x10
    [JsonPropertyName("m_nHeight")]
    public int M_nHeight { get; set; }  // +0x14
    [JsonPropertyName("m_bundleTypes")]
    public MorphBundleType_t[] M_bundleTypes { get; set; }  // +0x18
    [JsonPropertyName("m_morphDatas")]
    public CMorphData[] M_morphDatas { get; set; }  // +0x30
    [JsonPropertyName("m_pTextureAtlas")]
    public InfoForResourceTypeCTextureBase? M_pTextureAtlas { get; set; }  // +0x48
    [JsonPropertyName("m_FlexDesc")]
    public CFlexDesc[] M_FlexDesc { get; set; }  // +0x50
    [JsonPropertyName("m_FlexControllers")]
    public CFlexController[] M_FlexControllers { get; set; }  // +0x68
    [JsonPropertyName("m_FlexRules")]
    public CFlexRule[] M_FlexRules { get; set; }  // +0x80
}

/// <summary>CNPCPhysicsHull, 56 bytes</summary>
public class CNPCPhysicsHull
{
    [JsonPropertyName("m_sName")]
    public string M_sName { get; set; }  // +0x0
    [JsonPropertyName("m_eType")]
    public NPCPhysicsHullType_t M_eType { get; set; }  // +0x8
    [JsonPropertyName("m_flCapsuleHeight")]
    public float M_flCapsuleHeight { get; set; }  // +0xC
    [JsonPropertyName("m_flCapsuleRadius")]
    public float M_flCapsuleRadius { get; set; }  // +0x10
    [JsonPropertyName("m_vCapsuleCenter1")]
    public Vector M_vCapsuleCenter1 { get; set; }  // +0x14
    [JsonPropertyName("m_vCapsuleCenter2")]
    public Vector M_vCapsuleCenter2 { get; set; }  // +0x20
    [JsonPropertyName("m_flGroundBoxHeight")]
    public float M_flGroundBoxHeight { get; set; }  // +0x2C
    [JsonPropertyName("m_flGroundBoxWidth")]
    public float M_flGroundBoxWidth { get; set; }  // +0x30
}

/// <summary>COrientConstraint, 96 bytes</summary>
public class COrientConstraint : CBaseConstraint
{
}

/// <summary>CParentConstraint, 96 bytes</summary>
public class CParentConstraint : CBaseConstraint
{
}

/// <summary>CPhysSurfaceProperties, 200 bytes</summary>
public class CPhysSurfaceProperties
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x0
    [JsonPropertyName("m_nameHash")]
    public uint M_nameHash { get; set; }  // +0x8
    [JsonPropertyName("m_baseNameHash")]
    public uint M_baseNameHash { get; set; }  // +0xC
    [JsonPropertyName("m_bHidden")]
    public bool M_bHidden { get; set; }  // +0x18
    [JsonPropertyName("m_description")]
    public string M_description { get; set; }  // +0x20
    [JsonPropertyName("m_physics")]
    public CPhysSurfacePropertiesPhysics M_physics { get; set; }  // +0x28
    [JsonPropertyName("m_vehicleParams")]
    public CPhysSurfacePropertiesVehicle M_vehicleParams { get; set; }  // +0x40
    [JsonPropertyName("m_audioSounds")]
    public CPhysSurfacePropertiesSoundNames M_audioSounds { get; set; }  // +0x48
    [JsonPropertyName("m_audioParams")]
    public CPhysSurfacePropertiesAudio M_audioParams { get; set; }  // +0xA8
}

/// <summary>CPhysSurfacePropertiesAudio, 32 bytes</summary>
public class CPhysSurfacePropertiesAudio
{
    [JsonPropertyName("m_reflectivity")]
    public float M_reflectivity { get; set; }  // +0x0
    [JsonPropertyName("m_hardnessFactor")]
    public float M_hardnessFactor { get; set; }  // +0x4
    [JsonPropertyName("m_roughnessFactor")]
    public float M_roughnessFactor { get; set; }  // +0x8
    [JsonPropertyName("m_roughThreshold")]
    public float M_roughThreshold { get; set; }  // +0xC
    [JsonPropertyName("m_hardThreshold")]
    public float M_hardThreshold { get; set; }  // +0x10
    [JsonPropertyName("m_hardVelocityThreshold")]
    public float M_hardVelocityThreshold { get; set; }  // +0x14
    [JsonPropertyName("m_flStaticImpactVolume")]
    public float M_flStaticImpactVolume { get; set; }  // +0x18
    [JsonPropertyName("m_flOcclusionFactor")]
    public float M_flOcclusionFactor { get; set; }  // +0x1C
}

/// <summary>CPhysSurfacePropertiesPhysics, 24 bytes</summary>
public class CPhysSurfacePropertiesPhysics
{
    [JsonPropertyName("m_friction")]
    public float M_friction { get; set; }  // +0x0
    [JsonPropertyName("m_elasticity")]
    public float M_elasticity { get; set; }  // +0x4
    [JsonPropertyName("m_density")]
    public float M_density { get; set; }  // +0x8
    [JsonPropertyName("m_thickness")]
    public float M_thickness { get; set; }  // +0xC
    [JsonPropertyName("m_softContactFrequency")]
    public float M_softContactFrequency { get; set; }  // +0x10
    [JsonPropertyName("m_softContactDampingRatio")]
    public float M_softContactDampingRatio { get; set; }  // +0x14
}

/// <summary>CPhysSurfacePropertiesSoundNames, 96 bytes</summary>
public class CPhysSurfacePropertiesSoundNames
{
    [JsonPropertyName("m_impactSoft")]
    public string M_impactSoft { get; set; }  // +0x0
    [JsonPropertyName("m_impactHard")]
    public string M_impactHard { get; set; }  // +0x8
    [JsonPropertyName("m_scrapeSmooth")]
    public string M_scrapeSmooth { get; set; }  // +0x10
    [JsonPropertyName("m_scrapeRough")]
    public string M_scrapeRough { get; set; }  // +0x18
    [JsonPropertyName("m_bulletImpact")]
    public string M_bulletImpact { get; set; }  // +0x20
    [JsonPropertyName("m_rolling")]
    public string M_rolling { get; set; }  // +0x28
    [JsonPropertyName("m_break")]
    public string M_break { get; set; }  // +0x30
    [JsonPropertyName("m_strain")]
    public string M_strain { get; set; }  // +0x38
    [JsonPropertyName("m_meleeImpact")]
    public string M_meleeImpact { get; set; }  // +0x40
    [JsonPropertyName("m_pushOff")]
    public string M_pushOff { get; set; }  // +0x48
    [JsonPropertyName("m_skidStop")]
    public string M_skidStop { get; set; }  // +0x50
    [JsonPropertyName("m_resonant")]
    public string M_resonant { get; set; }  // +0x58
}

/// <summary>CPhysSurfacePropertiesVehicle, 8 bytes</summary>
public class CPhysSurfacePropertiesVehicle
{
    [JsonPropertyName("m_wheelDrag")]
    public float M_wheelDrag { get; set; }  // +0x0
    [JsonPropertyName("m_wheelFrictionScale")]
    public float M_wheelFrictionScale { get; set; }  // +0x4
}

/// <summary>CPointConstraint, 96 bytes</summary>
public class CPointConstraint : CBaseConstraint
{
}

/// <summary>CRenderBufferBinding, 32 bytes</summary>
public class CRenderBufferBinding
{
    [JsonPropertyName("m_hBuffer")]
    public ulong M_hBuffer { get; set; }  // +0x0
    [JsonPropertyName("m_nBindOffsetBytes")]
    public uint M_nBindOffsetBytes { get; set; }  // +0x10
}

/// <summary>CRenderGroom, 176 bytes</summary>
public class CRenderGroom
{
    [JsonPropertyName("m_hairs")]
    public RenderHairStrandInfo_t[] M_hairs { get; set; }  // +0x0
    [JsonPropertyName("m_hairPositionOffsets")]
    public uint[] M_hairPositionOffsets { get; set; }  // +0x18
    [JsonPropertyName("m_hSimParamsMat")]
    public object /* opaque */ M_hSimParamsMat { get; set; }  // +0x40
    [JsonPropertyName("m_strandSegmentCountHist")]
    public int[] M_strandSegmentCountHist { get; set; }  // +0x48
    [JsonPropertyName("m_nMaxSegmentsPerHairStrand")]
    public int M_nMaxSegmentsPerHairStrand { get; set; }  // +0x78
    [JsonPropertyName("m_nGuideHairCount")]
    public int M_nGuideHairCount { get; set; }  // +0x7C
    [JsonPropertyName("m_nHairCount")]
    public int M_nHairCount { get; set; }  // +0x80
    [JsonPropertyName("m_nTotalVertexCount")]
    public int M_nTotalVertexCount { get; set; }  // +0x84
    [JsonPropertyName("m_nTotalSegmentCount")]
    public int M_nTotalSegmentCount { get; set; }  // +0x88
    [JsonPropertyName("m_nGroomGroupID")]
    public int M_nGroomGroupID { get; set; }  // +0x8C
    [JsonPropertyName("m_nAttachBoneIdx")]
    public int M_nAttachBoneIdx { get; set; }  // +0x90
    [JsonPropertyName("m_nAttachMeshIdx")]
    public int M_nAttachMeshIdx { get; set; }  // +0x94
    [JsonPropertyName("m_nAttachMeshDrawCallIdx")]
    public int M_nAttachMeshDrawCallIdx { get; set; }  // +0x98
    [JsonPropertyName("m_bEnableSimulation")]
    public bool M_bEnableSimulation { get; set; }  // +0xAC
}

/// <summary>CRenderMesh, 528 bytes</summary>
public class CRenderMesh
{
    [JsonPropertyName("m_sceneObjects")]
    public CSceneObjectData[] M_sceneObjects { get; set; }  // +0x10
    [JsonPropertyName("m_constraints")]
    public CBaseConstraint?[] M_constraints { get; set; }  // +0xB8
    [JsonPropertyName("m_skeleton")]
    public CRenderSkeleton M_skeleton { get; set; }  // +0xC8
    [JsonPropertyName("m_bUseUV2ForCharting")]
    public bool M_bUseUV2ForCharting { get; set; }  // +0x1D4
    [JsonPropertyName("m_bEmbeddedMapMesh")]
    public bool M_bEmbeddedMapMesh { get; set; }  // +0x1D5
    [JsonPropertyName("m_meshDeformParams")]
    public DynamicMeshDeformParams_t M_meshDeformParams { get; set; }  // +0x1F8
    [JsonPropertyName("m_pGroomData")]
    public CRenderGroom? M_pGroomData { get; set; }  // +0x208
}

/// <summary>CRenderSkeleton, 80 bytes</summary>
public class CRenderSkeleton
{
    [JsonPropertyName("m_bones")]
    public RenderSkeletonBone_t[] M_bones { get; set; }  // +0x0
    [JsonPropertyName("m_boneParents")]
    public int[] M_boneParents { get; set; }  // +0x30
    [JsonPropertyName("m_nBoneWeightCount")]
    public int M_nBoneWeightCount { get; set; }  // +0x48
}

/// <summary>CSceneObjectData, 160 bytes</summary>
public class CSceneObjectData
{
    [JsonPropertyName("m_vMinBounds")]
    public Vector M_vMinBounds { get; set; }  // +0x0
    [JsonPropertyName("m_vMaxBounds")]
    public Vector M_vMaxBounds { get; set; }  // +0xC
    [JsonPropertyName("m_drawCalls")]
    public CMaterialDrawDescriptor[] M_drawCalls { get; set; }  // +0x18
    [JsonPropertyName("m_drawBounds")]
    public AABB_t[] M_drawBounds { get; set; }  // +0x28
    [JsonPropertyName("m_meshlets")]
    public CMeshletDescriptor[] M_meshlets { get; set; }  // +0x38
    [JsonPropertyName("m_rtProxyDrawCalls")]
    public CSceneObjectData_RTProxyDrawDescriptor_t[] M_rtProxyDrawCalls { get; set; }  // +0x48
    [JsonPropertyName("m_vTintColor")]
    public Vector4D M_vTintColor { get; set; }  // +0x58
}

/// <summary>CSceneObjectData::RTProxyDrawDescriptor_t, 320 bytes</summary>
public class CSceneObjectData_RTProxyDrawDescriptor_t
{
    [JsonPropertyName("m_drawDesc")]
    public CMaterialDrawDescriptor M_drawDesc { get; set; }  // +0x0
    [JsonPropertyName("m_mWorldFromLocal")]
    public matrix3x4_t M_mWorldFromLocal { get; set; }  // +0x108
    [JsonPropertyName("m_nVertexAlbedoFormat")]
    public VertexAlbedoFormat_t M_nVertexAlbedoFormat { get; set; }  // +0x138
    [JsonPropertyName("m_nVertexAlbedoVB")]
    public sbyte M_nVertexAlbedoVB { get; set; }  // +0x139
    [JsonPropertyName("m_nVertexAlbedoOffset")]
    public ushort M_nVertexAlbedoOffset { get; set; }  // +0x13A
    [JsonPropertyName("m_nVertexAlbedoStride")]
    public ushort M_nVertexAlbedoStride { get; set; }  // +0x13C
}

/// <summary>CTiltTwistConstraint, 144 bytes</summary>
public class CTiltTwistConstraint : CBaseConstraint
{
    [JsonPropertyName("m_nTargetAxis")]
    public int M_nTargetAxis { get; set; }  // +0x60
    [JsonPropertyName("m_nSlaveAxis")]
    public int M_nSlaveAxis { get; set; }  // +0x64
}

/// <summary>CTwistConstraint, 144 bytes</summary>
public class CTwistConstraint : CBaseConstraint
{
    [JsonPropertyName("m_bInverse")]
    public bool M_bInverse { get; set; }  // +0x60
    [JsonPropertyName("m_qParentBindRotation")]
    public Quaternion M_qParentBindRotation { get; set; }  // +0x70
    [JsonPropertyName("m_qChildBindRotation")]
    public Quaternion M_qChildBindRotation { get; set; }  // +0x80
}

/// <summary>CVPhysXSurfacePropertiesList, 24 bytes</summary>
public class CVPhysXSurfacePropertiesList
{
    [JsonPropertyName("m_surfacePropertiesList")]
    public CPhysSurfaceProperties?[] M_surfacePropertiesList { get; set; }  // +0x0
}

/// <summary>DynamicMeshDeformParams_t, 12 bytes</summary>
public class DynamicMeshDeformParams_t
{
    [JsonPropertyName("m_flTensionCompressScale")]
    public float M_flTensionCompressScale { get; set; }  // +0x0
    [JsonPropertyName("m_flTensionStretchScale")]
    public float M_flTensionStretchScale { get; set; }  // +0x4
    [JsonPropertyName("m_bRecomputeSmoothNormalsAfterAnimation")]
    public bool M_bRecomputeSmoothNormalsAfterAnimation { get; set; }  // +0x8
    [JsonPropertyName("m_bComputeDynamicMeshTensionAfterAnimation")]
    public bool M_bComputeDynamicMeshTensionAfterAnimation { get; set; }  // +0x9
    [JsonPropertyName("m_bSmoothNormalsAcrossUvSeams")]
    public bool M_bSmoothNormalsAcrossUvSeams { get; set; }  // +0xA
    [JsonPropertyName("m_bEnableEyeBulgeDeformation")]
    public bool M_bEnableEyeBulgeDeformation { get; set; }  // +0xB
}

public enum FlexOpCode_t : uint
{
    FLEX_OP_CONST = 1,
    FLEX_OP_FETCH1 = 2,
    FLEX_OP_FETCH2 = 3,
    FLEX_OP_ADD = 4,
    FLEX_OP_SUB = 5,
    FLEX_OP_MUL = 6,
    FLEX_OP_DIV = 7,
    FLEX_OP_NEG = 8,
    FLEX_OP_EXP = 9,
    FLEX_OP_OPEN = 10,
    FLEX_OP_CLOSE = 11,
    FLEX_OP_COMMA = 12,
    FLEX_OP_MAX = 13,
    FLEX_OP_MIN = 14,
    FLEX_OP_2WAY_0 = 15,
    FLEX_OP_2WAY_1 = 16,
    FLEX_OP_NWAY = 17,
    FLEX_OP_COMBO = 18,
    FLEX_OP_DOMINATE = 19,
    FLEX_OP_DME_LOWER_EYELID = 20,
    FLEX_OP_DME_UPPER_EYELID = 21,
    FLEX_OP_SQRT = 22,
    FLEX_OP_REMAPVALCLAMPED = 23,
    FLEX_OP_SIN = 24,
    FLEX_OP_COS = 25,
    FLEX_OP_ABS = 26,
}

public enum InputLayoutVariation_t : byte
{
    INPUT_LAYOUT_VARIATION_DEFAULT = 0,
    INPUT_LAYOUT_VARIATION_STREAM1_INSTANCEID = 1,
    INPUT_LAYOUT_VARIATION_STREAM1_INSTANCEID_MORPH_VERT_ID = 2,
    INPUT_LAYOUT_VARIATION_MAX = 3,
}

/// <summary>MaterialGroup_t, 32 bytes</summary>
public class MaterialGroup_t
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x0
    [JsonPropertyName("m_materials")]
    public InfoForResourceTypeIMaterial2?[] M_materials { get; set; }  // +0x8
}

public enum MeshDrawPrimitiveFlags_t : uint
{
    MESH_DRAW_FLAGS_NONE = 0,
    MESH_DRAW_FLAGS_USE_SHADOW_FAST_PATH = 1,
    MESH_DRAW_FLAGS_USE_COMPRESSED_NORMAL_TANGENT = 2,
    MESH_DRAW_INPUT_LAYOUT_IS_NOT_MATCHED_TO_MATERIAL = 8,
    MESH_DRAW_FLAGS_USE_COMPRESSED_PER_VERTEX_LIGHTING = 16,
    MESH_DRAW_FLAGS_USE_UNCOMPRESSED_PER_VERTEX_LIGHTING = 32,
    MESH_DRAW_FLAGS_CAN_BATCH_WITH_DYNAMIC_SHADER_CONSTANTS = 64,
    MESH_DRAW_FLAGS_DRAW_LAST = 128,
}

/// <summary>ModelAnimGraph2Ref_t, 16 bytes</summary>
public class ModelAnimGraph2Ref_t
{
    [JsonPropertyName("m_sIdentifier")]
    public string M_sIdentifier { get; set; }  // +0x0
    [JsonPropertyName("m_hGraph")]
    public InfoForResourceTypeCNmGraphDefinition? M_hGraph { get; set; }  // +0x8
}

public enum ModelBoneFlexComponent_t : uint
{
    MODEL_BONE_FLEX_INVALID = 4294967295,
    MODEL_BONE_FLEX_TX = 0,
    MODEL_BONE_FLEX_TY = 1,
    MODEL_BONE_FLEX_TZ = 2,
}

/// <summary>ModelBoneFlexDriver_t, 40 bytes</summary>
public class ModelBoneFlexDriver_t
{
    [JsonPropertyName("m_boneName")]
    public string M_boneName { get; set; }  // +0x0
    [JsonPropertyName("m_boneNameToken")]
    public uint M_boneNameToken { get; set; }  // +0x8
    [JsonPropertyName("m_controls")]
    public ModelBoneFlexDriverControl_t[] M_controls { get; set; }  // +0x10
}

/// <summary>ModelBoneFlexDriverControl_t, 32 bytes</summary>
public class ModelBoneFlexDriverControl_t
{
    [JsonPropertyName("m_nBoneComponent")]
    public ModelBoneFlexComponent_t M_nBoneComponent { get; set; }  // +0x0
    [JsonPropertyName("m_flexController")]
    public string M_flexController { get; set; }  // +0x8
    [JsonPropertyName("m_flexControllerToken")]
    public uint M_flexControllerToken { get; set; }  // +0x10
    [JsonPropertyName("m_flMin")]
    public float M_flMin { get; set; }  // +0x14
    [JsonPropertyName("m_flMax")]
    public float M_flMax { get; set; }  // +0x18
}

public enum ModelConfigAttachmentType_t : uint
{
    MODEL_CONFIG_ATTACHMENT_INVALID = 4294967295,
    MODEL_CONFIG_ATTACHMENT_BONE_OR_ATTACHMENT = 0,
    MODEL_CONFIG_ATTACHMENT_ROOT_RELATIVE = 1,
    MODEL_CONFIG_ATTACHMENT_BONEMERGE = 2,
    MODEL_CONFIG_ATTACHMENT_COUNT = 3,
}

/// <summary>ModelEmbeddedMesh_t, 112 bytes</summary>
public class ModelEmbeddedMesh_t
{
    [JsonPropertyName("m_Name")]
    public string M_Name { get; set; }  // +0x0
    [JsonPropertyName("m_nMeshIndex")]
    public int M_nMeshIndex { get; set; }  // +0x10
    [JsonPropertyName("m_nDataBlock")]
    public int M_nDataBlock { get; set; }  // +0x14
    [JsonPropertyName("m_nMorphBlock")]
    public int M_nMorphBlock { get; set; }  // +0x18
    [JsonPropertyName("m_vertexBuffers")]
    public ModelMeshBufferData_t[] M_vertexBuffers { get; set; }  // +0x20
    [JsonPropertyName("m_indexBuffers")]
    public ModelMeshBufferData_t[] M_indexBuffers { get; set; }  // +0x38
    [JsonPropertyName("m_toolsBuffers")]
    public ModelMeshBufferData_t[] M_toolsBuffers { get; set; }  // +0x50
    [JsonPropertyName("m_nVBIBBlock")]
    public int M_nVBIBBlock { get; set; }  // +0x68
    [JsonPropertyName("m_nToolsVBBlock")]
    public int M_nToolsVBBlock { get; set; }  // +0x6C
}

/// <summary>ModelMeshBufferData_t, 48 bytes</summary>
public class ModelMeshBufferData_t
{
    [JsonPropertyName("m_nBlockIndex")]
    public int M_nBlockIndex { get; set; }  // +0x0
    [JsonPropertyName("m_nElementCount")]
    public uint M_nElementCount { get; set; }  // +0x4
    [JsonPropertyName("m_nElementSizeInBytes")]
    public uint M_nElementSizeInBytes { get; set; }  // +0x8
    [JsonPropertyName("m_bMeshoptCompressed")]
    public bool M_bMeshoptCompressed { get; set; }  // +0xC
    [JsonPropertyName("m_bMeshoptIndexSequence")]
    public bool M_bMeshoptIndexSequence { get; set; }  // +0xD
    [JsonPropertyName("m_nMeshoptMeshletEncodeVersion")]
    public sbyte M_nMeshoptMeshletEncodeVersion { get; set; }  // +0xE
    [JsonPropertyName("m_bCompressedZSTD")]
    public bool M_bCompressedZSTD { get; set; }  // +0xF
    [JsonPropertyName("m_bCreateBufferSRV")]
    public bool M_bCreateBufferSRV { get; set; }  // +0x10
    [JsonPropertyName("m_bCreateBufferUAV")]
    public bool M_bCreateBufferUAV { get; set; }  // +0x11
    [JsonPropertyName("m_bCreateRawBuffer")]
    public bool M_bCreateRawBuffer { get; set; }  // +0x12
    [JsonPropertyName("m_bCreatePooledBuffer")]
    public bool M_bCreatePooledBuffer { get; set; }  // +0x13
    [JsonPropertyName("m_nBufferUsage")]
    public byte M_nBufferUsage { get; set; }  // +0x14
    [JsonPropertyName("m_inputLayoutFields")]
    public RenderInputLayoutField_t[] M_inputLayoutFields { get; set; }  // +0x18
}

public enum ModelMeshBufferUsage_t : byte
{
    MESH_BUFFER_USAGE_NONE = 0,
    MESH_BUFFER_USAGE_VB = 1,
    MESH_BUFFER_USAGE_IB = 2,
    MESH_BUFFER_USAGE_ADJACENCY = 4,
    MESH_BUFFER_USAGE_MESHLET_TRIS = 8,
    MESH_BUFFER_USAGE_RT_PROXY = 16,
    MESH_BUFFER_USAGE_VERTEX_ALBEDO = 32,
}

/// <summary>ModelSkeletonData_t, 168 bytes</summary>
public class ModelSkeletonData_t
{
    [JsonPropertyName("m_boneName")]
    public string[] M_boneName { get; set; }  // +0x0
    [JsonPropertyName("m_nParent")]
    public short[] M_nParent { get; set; }  // +0x18
    [JsonPropertyName("m_boneSphere")]
    public float[] M_boneSphere { get; set; }  // +0x30
    [JsonPropertyName("m_nFlag")]
    public uint[] M_nFlag { get; set; }  // +0x48
    [JsonPropertyName("m_bonePosParent")]
    public Vector[] M_bonePosParent { get; set; }  // +0x60
    [JsonPropertyName("m_boneRotParent")]
    public QuaternionStorage[] M_boneRotParent { get; set; }  // +0x78
    [JsonPropertyName("m_boneScaleParent")]
    public float[] M_boneScaleParent { get; set; }  // +0x90
}

public enum ModelSkeletonData_t_BoneFlags_t : uint
{
    FLAG_NO_BONE_FLAGS = 0,
    FLAG_BONEFLEXDRIVER = 4,
    FLAG_CLOTH = 8,
    FLAG_PHYSICS = 16,
    FLAG_ATTACHMENT = 32,
    FLAG_ANIMATION = 64,
    FLAG_MESH = 128,
    FLAG_HITBOX = 256,
    FLAG_BONE_USED_BY_VERTEX_LOD0 = 1024,
    FLAG_BONE_USED_BY_VERTEX_LOD1 = 2048,
    FLAG_BONE_USED_BY_VERTEX_LOD2 = 4096,
    FLAG_BONE_USED_BY_VERTEX_LOD3 = 8192,
    FLAG_BONE_USED_BY_VERTEX_LOD4 = 16384,
    FLAG_BONE_USED_BY_VERTEX_LOD5 = 32768,
    FLAG_BONE_USED_BY_VERTEX_LOD6 = 65536,
    FLAG_BONE_USED_BY_VERTEX_LOD7 = 131072,
    FLAG_BONE_MERGE_READ = 262144,
    FLAG_BONE_MERGE_WRITE = 524288,
    FLAG_ALL_BONE_FLAGS = 1048575,
    BLEND_PREALIGNED = 1048576,
    FLAG_RIGIDLENGTH = 2097152,
    FLAG_PROCEDURAL = 4194304,
}

public enum MorphBundleType_t : uint
{
    MORPH_BUNDLE_TYPE_NONE = 0,
    MORPH_BUNDLE_TYPE_POSITION_SPEED = 1,
    MORPH_BUNDLE_TYPE_NORMAL_WRINKLE = 2,
    MORPH_BUNDLE_TYPE_COUNT = 3,
}

public enum MorphFlexControllerRemapType_t : uint
{
    MORPH_FLEXCONTROLLER_REMAP_PASSTHRU = 0,
    MORPH_FLEXCONTROLLER_REMAP_2WAY = 1,
    MORPH_FLEXCONTROLLER_REMAP_NWAY = 2,
    MORPH_FLEXCONTROLLER_REMAP_EYELID = 3,
}

public enum MovementCapability_t : uint
{
    eStrafe = 0,
    eIdleTurn = 1,
    eStart = 2,
    eStop = 3,
    eInstantStop = 4,
    eShuffle = 5,
    ePlantedTurn = 6,
    eUseStartAsPlantedTurn = 7,
    eLean = 8,
    eCount = 9,
}

public enum NPCPhysicsHullType_t : uint
{
    eInvalid = 0,
    eGroundCapsule = 1,
    eCenteredCapsule = 2,
    eGenericCapsule = 3,
    eGroundBox = 4,
}

/// <summary>PermModelData_t, 760 bytes</summary>
public class PermModelData_t
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x0
    [JsonPropertyName("m_modelInfo")]
    public PermModelInfo_t M_modelInfo { get; set; }  // +0x8
    [JsonPropertyName("m_ExtParts")]
    public PermModelExtPart_t[] M_ExtParts { get; set; }  // +0x60
    [JsonPropertyName("m_refMeshes")]
    public InfoForResourceTypeCRenderMesh?[] M_refMeshes { get; set; }  // +0x78
    [JsonPropertyName("m_refMeshGroupMasks")]
    public ulong[] M_refMeshGroupMasks { get; set; }  // +0x90
    [JsonPropertyName("m_refPhysGroupMasks")]
    public ulong[] M_refPhysGroupMasks { get; set; }  // +0xA8
    [JsonPropertyName("m_refLODGroupMasks")]
    public byte[] M_refLODGroupMasks { get; set; }  // +0xC0
    [JsonPropertyName("m_lodGroupSwitchDistances")]
    public float[] M_lodGroupSwitchDistances { get; set; }  // +0xD8
    [JsonPropertyName("m_refPhysicsData")]
    public InfoForResourceTypeCPhysAggregateData?[] M_refPhysicsData { get; set; }  // +0xF0
    [JsonPropertyName("m_refPhysicsHitboxData")]
    public InfoForResourceTypeCPhysAggregateData?[] M_refPhysicsHitboxData { get; set; }  // +0x108
    [JsonPropertyName("m_refAnimGroups")]
    public InfoForResourceTypeCAnimationGroup?[] M_refAnimGroups { get; set; }  // +0x120
    [JsonPropertyName("m_refSequenceGroups")]
    public InfoForResourceTypeCSequenceGroupData?[] M_refSequenceGroups { get; set; }  // +0x138
    [JsonPropertyName("m_meshGroups")]
    public string[] M_meshGroups { get; set; }  // +0x150
    [JsonPropertyName("m_materialGroups")]
    public MaterialGroup_t[] M_materialGroups { get; set; }  // +0x168
    [JsonPropertyName("m_nDefaultMeshGroupMask")]
    public ulong M_nDefaultMeshGroupMask { get; set; }  // +0x180
    [JsonPropertyName("m_modelSkeleton")]
    public ModelSkeletonData_t M_modelSkeleton { get; set; }  // +0x188
    [JsonPropertyName("m_remappingTable")]
    public short[] M_remappingTable { get; set; }  // +0x230
    [JsonPropertyName("m_remappingTableStarts")]
    public ushort[] M_remappingTableStarts { get; set; }  // +0x248
    [JsonPropertyName("m_boneFlexDrivers")]
    public ModelBoneFlexDriver_t[] M_boneFlexDrivers { get; set; }  // +0x260
    [JsonPropertyName("m_pModelConfigList")]
    public CModelConfigList? M_pModelConfigList { get; set; }  // +0x278
    [JsonPropertyName("m_BodyGroupsHiddenInTools")]
    public string[] M_BodyGroupsHiddenInTools { get; set; }  // +0x280
    [JsonPropertyName("m_refAnimIncludeModels")]
    public InfoForResourceTypeCModel?[] M_refAnimIncludeModels { get; set; }  // +0x298
    [JsonPropertyName("m_AnimatedMaterialAttributes")]
    public PermModelDataAnimatedMaterialAttribute_t[] M_AnimatedMaterialAttributes { get; set; }  // +0x2B0
    [JsonPropertyName("m_animGraph2Refs")]
    public ModelAnimGraph2Ref_t[] M_animGraph2Refs { get; set; }  // +0x2C8
    [JsonPropertyName("m_vecNmSkeletonRefs")]
    public InfoForResourceTypeCNmSkeleton?[] M_vecNmSkeletonRefs { get; set; }  // +0x2E0
}

/// <summary>PermModelDataAnimatedMaterialAttribute_t, 16 bytes</summary>
public class PermModelDataAnimatedMaterialAttribute_t
{
    [JsonPropertyName("m_AttributeName")]
    public string M_AttributeName { get; set; }  // +0x0
    [JsonPropertyName("m_nNumChannels")]
    public int M_nNumChannels { get; set; }  // +0x8
}

/// <summary>PermModelExtPart_t, 64 bytes</summary>
public class PermModelExtPart_t
{
    [JsonPropertyName("m_Transform")]
    public CTransform M_Transform { get; set; }  // +0x0
    [JsonPropertyName("m_Name")]
    public string M_Name { get; set; }  // +0x20
    [JsonPropertyName("m_nParent")]
    public int M_nParent { get; set; }  // +0x28
    [JsonPropertyName("m_refModel")]
    public InfoForResourceTypeCModel? M_refModel { get; set; }  // +0x30
}

/// <summary>PermModelInfo_t, 88 bytes</summary>
public class PermModelInfo_t
{
    [JsonPropertyName("m_nFlags")]
    public uint M_nFlags { get; set; }  // +0x0
    [JsonPropertyName("m_vHullMin")]
    public Vector M_vHullMin { get; set; }  // +0x4
    [JsonPropertyName("m_vHullMax")]
    public Vector M_vHullMax { get; set; }  // +0x10
    [JsonPropertyName("m_vViewMin")]
    public Vector M_vViewMin { get; set; }  // +0x1C
    [JsonPropertyName("m_vViewMax")]
    public Vector M_vViewMax { get; set; }  // +0x28
    [JsonPropertyName("m_flMass")]
    public float M_flMass { get; set; }  // +0x34
    [JsonPropertyName("m_vEyePosition")]
    public Vector M_vEyePosition { get; set; }  // +0x38
    [JsonPropertyName("m_flMaxEyeDeflection")]
    public float M_flMaxEyeDeflection { get; set; }  // +0x44
    [JsonPropertyName("m_sSurfaceProperty")]
    public string M_sSurfaceProperty { get; set; }  // +0x48
    [JsonPropertyName("m_keyValueText")]
    public string M_keyValueText { get; set; }  // +0x50
}

public enum PermModelInfo_t_FlagEnum : uint
{
    FLAG_TRANSLUCENT = 1,
    FLAG_TRANSLUCENT_TWO_PASS = 2,
    FLAG_MODEL_IS_RUNTIME_COMBINED = 4,
    FLAG_SOURCE1_IMPORT = 8,
    FLAG_MODEL_PART_CHILD = 16,
    FLAG_NAV_GEN_NONE = 32,
    FLAG_NAV_GEN_HULL = 64,
    FLAG_NO_FORCED_FADE = 2048,
    FLAG_HAS_SKINNED_MESHES = 1024,
    FLAG_DO_NOT_CAST_SHADOWS = 131072,
    FLAG_FORCE_PHONEME_CROSSFADE = 4096,
    FLAG_NO_ANIM_EVENTS = 1048576,
    FLAG_ANIMATION_DRIVEN_FLEXES = 2097152,
    FLAG_IMPLICIT_BIND_POSE_SEQUENCE = 4194304,
    FLAG_MODEL_DOC = 8388608,
}

/// <summary>PhysShapeMarkup_t, 16 bytes</summary>
public class PhysShapeMarkup_t
{
    [JsonPropertyName("m_nBodyInAggregate")]
    public int M_nBodyInAggregate { get; set; }  // +0x0
    [JsonPropertyName("m_nShapeInBody")]
    public int M_nShapeInBody { get; set; }  // +0x4
    [JsonPropertyName("m_sHitGroup")]
    public string M_sHitGroup { get; set; }  // +0x8
}

/// <summary>PhysSoftbodyDesc_t, 144 bytes</summary>
public class PhysSoftbodyDesc_t
{
    [JsonPropertyName("m_ParticleBoneHash")]
    public uint[] M_ParticleBoneHash { get; set; }  // +0x0
    [JsonPropertyName("m_Particles")]
    public RnSoftbodyParticle_t[] M_Particles { get; set; }  // +0x18
    [JsonPropertyName("m_Springs")]
    public RnSoftbodySpring_t[] M_Springs { get; set; }  // +0x30
    [JsonPropertyName("m_Capsules")]
    public RnSoftbodyCapsule_t[] M_Capsules { get; set; }  // +0x48
    [JsonPropertyName("m_InitPose")]
    public CTransform[] M_InitPose { get; set; }  // +0x60
    [JsonPropertyName("m_ParticleBoneName")]
    public string[] M_ParticleBoneName { get; set; }  // +0x78
}

public enum RenderBufferFlags_t : uint
{
    RENDER_BUFFER_USAGE_NONE = 0,
    RENDER_BUFFER_USAGE_VERTEX_BUFFER = 1,
    RENDER_BUFFER_USAGE_INDEX_BUFFER = 2,
    RENDER_BUFFER_USAGE_SHADER_RESOURCE = 4,
    RENDER_BUFFER_USAGE_UNORDERED_ACCESS = 8,
    RENDER_BUFFER_BYTEADDRESS_BUFFER = 16,
    RENDER_BUFFER_STRUCTURED_BUFFER = 32,
    RENDER_BUFFER_UAV_DRAW_INDIRECT_ARGS = 256,
    RENDER_BUFFER_ACCELERATION_STRUCTURE = 512,
    RENDER_BUFFER_SHADER_BINDING_TABLE = 1024,
    RENDER_BUFFER_POOL_ALLOCATED = 2048,
    RENDER_BUFFER_USAGE_CONDITIONAL_RENDERING = 4096,
    RENDER_BUFFER_IMMOVABLE_ALLOCATION = 8192,
}

/// <summary>RenderHairStrandInfo_t, 40 bytes</summary>
public class RenderHairStrandInfo_t
{
    [JsonPropertyName("m_nGuideHairIndices_nSurfaceTriIndex")]
    public uint[] M_nGuideHairIndices_nSurfaceTriIndex { get; set; }  // +0x0
    [JsonPropertyName("m_vGuideBary_vBaseBary")]
    public ushort[] M_vGuideBary_vBaseBary { get; set; }  // +0x8
    [JsonPropertyName("m_vRootOffset_flLengthScale")]
    public ushort[] M_vRootOffset_flLengthScale { get; set; }  // +0x10
    [JsonPropertyName("m_nPackedBaseUv")]
    public ushort[] M_nPackedBaseUv { get; set; }  // +0x18
    [JsonPropertyName("m_nPackedSurfaceNormalOs")]
    public uint M_nPackedSurfaceNormalOs { get; set; }  // +0x1C
    [JsonPropertyName("m_nPackedSurfaceTangentOs")]
    public uint M_nPackedSurfaceTangentOs { get; set; }  // +0x20
    [JsonPropertyName("m_nDataOffset_Segments")]
    public uint M_nDataOffset_Segments { get; set; }  // +0x24
}

/// <summary>RenderInputLayoutField_t, 76 bytes</summary>
public class RenderInputLayoutField_t
{
    [JsonPropertyName("m_pSemanticName")]
    public sbyte[] M_pSemanticName { get; set; }  // +0x0
    [JsonPropertyName("m_nSemanticIndex")]
    public sbyte M_nSemanticIndex { get; set; }  // +0x20
    [JsonPropertyName("m_nOffset")]
    public short M_nOffset { get; set; }  // +0x28
    [JsonPropertyName("m_nSlot")]
    public sbyte M_nSlot { get; set; }  // +0x2A
    [JsonPropertyName("m_nSlotType")]
    public RenderSlotType_t M_nSlotType { get; set; }  // +0x2B
    [JsonPropertyName("m_szShaderSemantic")]
    public sbyte[] M_szShaderSemantic { get; set; }  // +0x2C
}

public enum RenderMeshSlotType_t : byte
{
    RENDERMESH_SLOT_INVALID = 255,
    RENDERMESH_SLOT_PER_VERTEX = 0,
    RENDERMESH_SLOT_PER_INSTANCE = 1,
}

public enum RenderMultisampleType_t : byte
{
    RENDER_MULTISAMPLE_INVALID = 255,
    RENDER_MULTISAMPLE_NONE = 0,
    RENDER_MULTISAMPLE_2X = 1,
    RENDER_MULTISAMPLE_4X = 2,
    RENDER_MULTISAMPLE_6X = 3,
    RENDER_MULTISAMPLE_8X = 4,
    RENDER_MULTISAMPLE_16X = 5,
    RENDER_MULTISAMPLE_TYPE_COUNT = 6,
}

public enum RenderPrimitiveType_t : uint
{
    RENDER_PRIM_POINTS = 0,
    RENDER_PRIM_LINES = 1,
    RENDER_PRIM_LINES_WITH_ADJACENCY = 2,
    RENDER_PRIM_LINE_STRIP = 3,
    RENDER_PRIM_LINE_STRIP_WITH_ADJACENCY = 4,
    RENDER_PRIM_TRIANGLES = 5,
    RENDER_PRIM_TRIANGLES_WITH_ADJACENCY = 6,
    RENDER_PRIM_TRIANGLE_STRIP = 7,
    RENDER_PRIM_TRIANGLE_STRIP_WITH_ADJACENCY = 8,
    RENDER_PRIM_INSTANCED_QUADS = 9,
    RENDER_PRIM_HETEROGENOUS = 10,
    RENDER_PRIM_COMPUTE_SHADER = 11,
    RENDER_PRIM_MESH_SHADER = 12,
    RENDER_PRIM_TYPE_COUNT = 13,
}

/// <summary>RenderSkeletonBone_t, 96 bytes</summary>
public class RenderSkeletonBone_t
{
    [JsonPropertyName("m_boneName")]
    public string M_boneName { get; set; }  // +0x0
    [JsonPropertyName("m_parentName")]
    public string M_parentName { get; set; }  // +0x8
    [JsonPropertyName("m_invBindPose")]
    public matrix3x4_t M_invBindPose { get; set; }  // +0x10
    [JsonPropertyName("m_bbox")]
    public SkeletonBoneBounds_t M_bbox { get; set; }  // +0x40
    [JsonPropertyName("m_flSphereRadius")]
    public float M_flSphereRadius { get; set; }  // +0x58
}

public enum RenderSlotType_t : byte
{
    RENDER_SLOT_INVALID = 255,
    RENDER_SLOT_PER_VERTEX = 0,
    RENDER_SLOT_PER_INSTANCE = 1,
}

public enum ScriptedHeldWeaponBehavior_t : uint
{
    eInvalid = 4294967295,
    eHolster = 0,
    eDeploy = 1,
    eDrop = 2,
}

public enum ScriptedMoveTo_t : uint
{
    eWait = 0,
    eMoveWithGait = 3,
    eTeleport = 4,
    eWaitFacing = 5,
    eObsoleteBackCompat1 = 1,
    eObsoleteBackCompat2 = 2,
}

public enum SharedMovementGait_t : byte
{
    eInvalid = 255,
    eSlow = 0,
    eMedium = 1,
    eFast = 2,
    eVeryFast = 3,
    eCount = 4,
}

/// <summary>SheetSequenceIntegerId_t, 4 bytes</summary>
public class SheetSequenceIntegerId_t
{
    [JsonPropertyName("m_Value")]
    public uint M_Value { get; set; }  // +0x0
}

/// <summary>SkeletonAnimCapture_t, 192 bytes</summary>
public class SkeletonAnimCapture_t
{
    [JsonPropertyName("m_nEntIndex")]
    public int M_nEntIndex { get; set; }  // +0x0
    [JsonPropertyName("m_nEntParent")]
    public int M_nEntParent { get; set; }  // +0x4
    [JsonPropertyName("m_ImportedCollision")]
    public int[] M_ImportedCollision { get; set; }  // +0x8
    [JsonPropertyName("m_ModelName")]
    public string M_ModelName { get; set; }  // +0x20
    [JsonPropertyName("m_CaptureName")]
    public string M_CaptureName { get; set; }  // +0x28
    [JsonPropertyName("m_ModelBindPose")]
    public SkeletonAnimCapture_t_Bone_t[] M_ModelBindPose { get; set; }  // +0x30
    [JsonPropertyName("m_FeModelInitPose")]
    public SkeletonAnimCapture_t_Bone_t[] M_FeModelInitPose { get; set; }  // +0x48
    [JsonPropertyName("m_nFlexControllers")]
    public int M_nFlexControllers { get; set; }  // +0x60
    [JsonPropertyName("m_bPredicted")]
    public bool M_bPredicted { get; set; }  // +0x64
    [JsonPropertyName("m_Frames")]
    public SkeletonAnimCapture_t_Frame_t[] M_Frames { get; set; }  // +0xA8
}

/// <summary>SkeletonAnimCapture_t::Bone_t, 64 bytes</summary>
public class SkeletonAnimCapture_t_Bone_t
{
    [JsonPropertyName("m_Name")]
    public string M_Name { get; set; }  // +0x0
    [JsonPropertyName("m_BindPose")]
    public CTransform M_BindPose { get; set; }  // +0x10
    [JsonPropertyName("m_nParent")]
    public int M_nParent { get; set; }  // +0x30
}

/// <summary>SkeletonAnimCapture_t::Camera_t, 48 bytes</summary>
public class SkeletonAnimCapture_t_Camera_t
{
    [JsonPropertyName("m_tmCamera")]
    public CTransform M_tmCamera { get; set; }  // +0x0
    [JsonPropertyName("m_flTime")]
    public float M_flTime { get; set; }  // +0x20
}

/// <summary>SkeletonAnimCapture_t::Frame_t, 192 bytes</summary>
public class SkeletonAnimCapture_t_Frame_t
{
    [JsonPropertyName("m_flTime")]
    public float M_flTime { get; set; }  // +0x0
    [JsonPropertyName("m_Stamp")]
    public SkeletonAnimCapture_t_FrameStamp_t M_Stamp { get; set; }  // +0x4
    [JsonPropertyName("m_Transform")]
    public CTransform M_Transform { get; set; }  // +0x20
    [JsonPropertyName("m_bTeleport")]
    public bool M_bTeleport { get; set; }  // +0x40
    [JsonPropertyName("m_CompositeBones")]
    public CTransform[] M_CompositeBones { get; set; }  // +0x48
    [JsonPropertyName("m_SimStateBones")]
    public CTransform[] M_SimStateBones { get; set; }  // +0x60
    [JsonPropertyName("m_FeModelAnims")]
    public CTransform[] M_FeModelAnims { get; set; }  // +0x78
    [JsonPropertyName("m_FeModelPos")]
    public VectorAligned[] M_FeModelPos { get; set; }  // +0x90
    [JsonPropertyName("m_FlexControllerWeights")]
    public float[] M_FlexControllerWeights { get; set; }  // +0xA8
}

/// <summary>SkeletonAnimCapture_t::FrameStamp_t, 28 bytes</summary>
public class SkeletonAnimCapture_t_FrameStamp_t
{
    [JsonPropertyName("m_flTime")]
    public float M_flTime { get; set; }  // +0x0
    [JsonPropertyName("m_flEntitySimTime")]
    public float M_flEntitySimTime { get; set; }  // +0x4
    [JsonPropertyName("m_bTeleportTick")]
    public bool M_bTeleportTick { get; set; }  // +0x8
    [JsonPropertyName("m_bPredicted")]
    public bool M_bPredicted { get; set; }  // +0x9
    [JsonPropertyName("m_flCurTime")]
    public float M_flCurTime { get; set; }  // +0xC
    [JsonPropertyName("m_flRealTime")]
    public float M_flRealTime { get; set; }  // +0x10
    [JsonPropertyName("m_nFrameCount")]
    public int M_nFrameCount { get; set; }  // +0x14
    [JsonPropertyName("m_nTickCount")]
    public int M_nTickCount { get; set; }  // +0x18
}

/// <summary>SkeletonBoneBounds_t, 24 bytes</summary>
public class SkeletonBoneBounds_t
{
    [JsonPropertyName("m_vecCenter")]
    public Vector M_vecCenter { get; set; }  // +0x0
    [JsonPropertyName("m_vecSize")]
    public Vector M_vecSize { get; set; }  // +0xC
}

/// <summary>SkeletonDemoDb_t, 56 bytes</summary>
public class SkeletonDemoDb_t
{
    [JsonPropertyName("m_AnimCaptures")]
    public SkeletonAnimCapture_t?[] M_AnimCaptures { get; set; }  // +0x0
    [JsonPropertyName("m_CameraTrack")]
    public SkeletonAnimCapture_t_Camera_t[] M_CameraTrack { get; set; }  // +0x18
    [JsonPropertyName("m_flRecordingTime")]
    public float M_flRecordingTime { get; set; }  // +0x30
}

public enum VertexAlbedoFormat_t : byte
{
    VERTEX_ALBEDO_NONE = 0,
    VERTEX_ALBEDO_8888 = 1,
    VERTEX_ALBEDO_565 = 2,
}

/// <summary>VPhysics2ShapeDef_t, 120 bytes</summary>
public class VPhysics2ShapeDef_t
{
    [JsonPropertyName("m_spheres")]
    public RnSphereDesc_t[] M_spheres { get; set; }  // +0x0
    [JsonPropertyName("m_capsules")]
    public RnCapsuleDesc_t[] M_capsules { get; set; }  // +0x18
    [JsonPropertyName("m_hulls")]
    public RnHullDesc_t[] M_hulls { get; set; }  // +0x30
    [JsonPropertyName("m_meshes")]
    public RnMeshDesc_t[] M_meshes { get; set; }  // +0x48
    [JsonPropertyName("m_CollisionAttributeIndices")]
    public ushort[] M_CollisionAttributeIndices { get; set; }  // +0x60
}

/// <summary>VPhysXAggregateData_t, 336 bytes</summary>
public class VPhysXAggregateData_t
{
    [JsonPropertyName("m_nFlags")]
    public ushort M_nFlags { get; set; }  // +0x0
    [JsonPropertyName("m_nRefCounter")]
    public ushort M_nRefCounter { get; set; }  // +0x2
    [JsonPropertyName("m_bonesHash")]
    public uint[] M_bonesHash { get; set; }  // +0x8
    [JsonPropertyName("m_boneNames")]
    public string[] M_boneNames { get; set; }  // +0x20
    [JsonPropertyName("m_indexNames")]
    public ushort[] M_indexNames { get; set; }  // +0x38
    [JsonPropertyName("m_indexHash")]
    public ushort[] M_indexHash { get; set; }  // +0x50
    [JsonPropertyName("m_bindPose")]
    public matrix3x4a_t[] M_bindPose { get; set; }  // +0x68
    [JsonPropertyName("m_parts")]
    public VPhysXBodyPart_t[] M_parts { get; set; }  // +0x80
    [JsonPropertyName("m_shapeMarkups")]
    public PhysShapeMarkup_t[] M_shapeMarkups { get; set; }  // +0x98
    [JsonPropertyName("m_constraints2")]
    public VPhysXConstraint2_t[] M_constraints2 { get; set; }  // +0xB0
    [JsonPropertyName("m_joints")]
    public VPhysXJoint_t[] M_joints { get; set; }  // +0xC8
    [JsonPropertyName("m_pFeModel")]
    public PhysFeModelDesc_t? M_pFeModel { get; set; }  // +0xE0
    [JsonPropertyName("m_boneParents")]
    public ushort[] M_boneParents { get; set; }  // +0xE8
    [JsonPropertyName("m_surfacePropertyHashes")]
    public uint[] M_surfacePropertyHashes { get; set; }  // +0x100
    [JsonPropertyName("m_collisionAttributes")]
    public VPhysXCollisionAttributes_t[] M_collisionAttributes { get; set; }  // +0x118
    [JsonPropertyName("m_debugPartNames")]
    public string[] M_debugPartNames { get; set; }  // +0x130
    [JsonPropertyName("m_embeddedKeyvalues")]
    public string M_embeddedKeyvalues { get; set; }  // +0x148
}

public enum VPhysXAggregateData_t_VPhysXFlagEnum_t : uint
{
    FLAG_IS_POLYSOUP_GEOMETRY = 1,
    FLAG_LEVEL_COLLISION = 16,
    FLAG_IGNORE_SCALE_OBSOLETE_DO_NOT_USE = 32,
}

/// <summary>VPhysXBodyPart_t, 168 bytes</summary>
public class VPhysXBodyPart_t
{
    [JsonPropertyName("m_nFlags")]
    public uint M_nFlags { get; set; }  // +0x0
    [JsonPropertyName("m_flMass")]
    public float M_flMass { get; set; }  // +0x4
    [JsonPropertyName("m_rnShape")]
    public VPhysics2ShapeDef_t M_rnShape { get; set; }  // +0x8
    [JsonPropertyName("m_nCollisionAttributeIndex")]
    public ushort M_nCollisionAttributeIndex { get; set; }  // +0x80
    [JsonPropertyName("m_nReserved")]
    public ushort M_nReserved { get; set; }  // +0x82
    [JsonPropertyName("m_flInertiaScale")]
    public float M_flInertiaScale { get; set; }  // +0x84
    [JsonPropertyName("m_flLinearDamping")]
    public float M_flLinearDamping { get; set; }  // +0x88
    [JsonPropertyName("m_flAngularDamping")]
    public float M_flAngularDamping { get; set; }  // +0x8C
    [JsonPropertyName("m_flLinearDrag")]
    public float M_flLinearDrag { get; set; }  // +0x90
    [JsonPropertyName("m_flAngularDrag")]
    public float M_flAngularDrag { get; set; }  // +0x94
    [JsonPropertyName("m_bOverrideMassCenter")]
    public bool M_bOverrideMassCenter { get; set; }  // +0x98
    [JsonPropertyName("m_vMassCenterOverride")]
    public Vector M_vMassCenterOverride { get; set; }  // +0x9C
}

public enum VPhysXBodyPart_t_VPhysXFlagEnum_t : uint
{
    FLAG_STATIC = 1,
    FLAG_KINEMATIC = 2,
    FLAG_JOINT = 4,
    FLAG_MASS = 8,
    FLAG_ALWAYS_DYNAMIC_ON_CLIENT = 16,
    FLAG_DISABLE_CCD = 32,
}

/// <summary>VPhysXCollisionAttributes_t, 208 bytes</summary>
public class VPhysXCollisionAttributes_t
{
    [JsonPropertyName("m_nIncludeDetailLayerCount")]
    public int M_nIncludeDetailLayerCount { get; set; }  // +0x0
    [JsonPropertyName("m_CollisionGroup")]
    public uint M_CollisionGroup { get; set; }  // +0x4
    [JsonPropertyName("m_InteractAs")]
    public uint[] M_InteractAs { get; set; }  // +0x8
    [JsonPropertyName("m_InteractWith")]
    public uint[] M_InteractWith { get; set; }  // +0x20
    [JsonPropertyName("m_InteractExclude")]
    public uint[] M_InteractExclude { get; set; }  // +0x38
    [JsonPropertyName("m_DetailLayers")]
    public uint[] M_DetailLayers { get; set; }  // +0x50
    [JsonPropertyName("m_CollisionGroupString")]
    public string M_CollisionGroupString { get; set; }  // +0x68
    [JsonPropertyName("m_InteractAsStrings")]
    public string[] M_InteractAsStrings { get; set; }  // +0x70
    [JsonPropertyName("m_InteractWithStrings")]
    public string[] M_InteractWithStrings { get; set; }  // +0x88
    [JsonPropertyName("m_InteractExcludeStrings")]
    public string[] M_InteractExcludeStrings { get; set; }  // +0xA0
    [JsonPropertyName("m_DetailLayerStrings")]
    public string[] M_DetailLayerStrings { get; set; }  // +0xB8
}

/// <summary>VPhysXConstraint2_t, 256 bytes</summary>
public class VPhysXConstraint2_t
{
    [JsonPropertyName("m_nFlags")]
    public uint M_nFlags { get; set; }  // +0x0
    [JsonPropertyName("m_nParent")]
    public ushort M_nParent { get; set; }  // +0x4
    [JsonPropertyName("m_nChild")]
    public ushort M_nChild { get; set; }  // +0x6
    [JsonPropertyName("m_params")]
    public VPhysXConstraintParams_t M_params { get; set; }  // +0x8
}

/// <summary>VPhysXConstraintParams_t, 248 bytes</summary>
public class VPhysXConstraintParams_t
{
    [JsonPropertyName("m_nType")]
    public sbyte M_nType { get; set; }  // +0x0
    [JsonPropertyName("m_nTranslateMotion")]
    public sbyte M_nTranslateMotion { get; set; }  // +0x1
    [JsonPropertyName("m_nRotateMotion")]
    public sbyte M_nRotateMotion { get; set; }  // +0x2
    [JsonPropertyName("m_nFlags")]
    public sbyte M_nFlags { get; set; }  // +0x3
    [JsonPropertyName("m_anchor")]
    public Vector[] M_anchor { get; set; }  // +0x4
    [JsonPropertyName("m_axes")]
    public QuaternionStorage[] M_axes { get; set; }  // +0x1C
    [JsonPropertyName("m_maxForce")]
    public float M_maxForce { get; set; }  // +0x3C
    [JsonPropertyName("m_maxTorque")]
    public float M_maxTorque { get; set; }  // +0x40
    [JsonPropertyName("m_linearLimitValue")]
    public float M_linearLimitValue { get; set; }  // +0x44
    [JsonPropertyName("m_linearLimitRestitution")]
    public float M_linearLimitRestitution { get; set; }  // +0x48
    [JsonPropertyName("m_linearLimitSpring")]
    public float M_linearLimitSpring { get; set; }  // +0x4C
    [JsonPropertyName("m_linearLimitDamping")]
    public float M_linearLimitDamping { get; set; }  // +0x50
    [JsonPropertyName("m_twistLowLimitValue")]
    public float M_twistLowLimitValue { get; set; }  // +0x54
    [JsonPropertyName("m_twistLowLimitRestitution")]
    public float M_twistLowLimitRestitution { get; set; }  // +0x58
    [JsonPropertyName("m_twistLowLimitSpring")]
    public float M_twistLowLimitSpring { get; set; }  // +0x5C
    [JsonPropertyName("m_twistLowLimitDamping")]
    public float M_twistLowLimitDamping { get; set; }  // +0x60
    [JsonPropertyName("m_twistHighLimitValue")]
    public float M_twistHighLimitValue { get; set; }  // +0x64
    [JsonPropertyName("m_twistHighLimitRestitution")]
    public float M_twistHighLimitRestitution { get; set; }  // +0x68
    [JsonPropertyName("m_twistHighLimitSpring")]
    public float M_twistHighLimitSpring { get; set; }  // +0x6C
    [JsonPropertyName("m_twistHighLimitDamping")]
    public float M_twistHighLimitDamping { get; set; }  // +0x70
    [JsonPropertyName("m_swing1LimitValue")]
    public float M_swing1LimitValue { get; set; }  // +0x74
    [JsonPropertyName("m_swing1LimitRestitution")]
    public float M_swing1LimitRestitution { get; set; }  // +0x78
    [JsonPropertyName("m_swing1LimitSpring")]
    public float M_swing1LimitSpring { get; set; }  // +0x7C
    [JsonPropertyName("m_swing1LimitDamping")]
    public float M_swing1LimitDamping { get; set; }  // +0x80
    [JsonPropertyName("m_swing2LimitValue")]
    public float M_swing2LimitValue { get; set; }  // +0x84
    [JsonPropertyName("m_swing2LimitRestitution")]
    public float M_swing2LimitRestitution { get; set; }  // +0x88
    [JsonPropertyName("m_swing2LimitSpring")]
    public float M_swing2LimitSpring { get; set; }  // +0x8C
    [JsonPropertyName("m_swing2LimitDamping")]
    public float M_swing2LimitDamping { get; set; }  // +0x90
    [JsonPropertyName("m_goalPosition")]
    public Vector M_goalPosition { get; set; }  // +0x94
    [JsonPropertyName("m_goalOrientation")]
    public QuaternionStorage M_goalOrientation { get; set; }  // +0xA0
    [JsonPropertyName("m_goalAngularVelocity")]
    public Vector M_goalAngularVelocity { get; set; }  // +0xB0
    [JsonPropertyName("m_driveSpringX")]
    public float M_driveSpringX { get; set; }  // +0xBC
    [JsonPropertyName("m_driveSpringY")]
    public float M_driveSpringY { get; set; }  // +0xC0
    [JsonPropertyName("m_driveSpringZ")]
    public float M_driveSpringZ { get; set; }  // +0xC4
    [JsonPropertyName("m_driveDampingX")]
    public float M_driveDampingX { get; set; }  // +0xC8
    [JsonPropertyName("m_driveDampingY")]
    public float M_driveDampingY { get; set; }  // +0xCC
    [JsonPropertyName("m_driveDampingZ")]
    public float M_driveDampingZ { get; set; }  // +0xD0
    [JsonPropertyName("m_driveSpringTwist")]
    public float M_driveSpringTwist { get; set; }  // +0xD4
    [JsonPropertyName("m_driveSpringSwing")]
    public float M_driveSpringSwing { get; set; }  // +0xD8
    [JsonPropertyName("m_driveSpringSlerp")]
    public float M_driveSpringSlerp { get; set; }  // +0xDC
    [JsonPropertyName("m_driveDampingTwist")]
    public float M_driveDampingTwist { get; set; }  // +0xE0
    [JsonPropertyName("m_driveDampingSwing")]
    public float M_driveDampingSwing { get; set; }  // +0xE4
    [JsonPropertyName("m_driveDampingSlerp")]
    public float M_driveDampingSlerp { get; set; }  // +0xE8
    [JsonPropertyName("m_solverIterationCount")]
    public int M_solverIterationCount { get; set; }  // +0xEC
    [JsonPropertyName("m_projectionLinearTolerance")]
    public float M_projectionLinearTolerance { get; set; }  // +0xF0
    [JsonPropertyName("m_projectionAngularTolerance")]
    public float M_projectionAngularTolerance { get; set; }  // +0xF4
}

public enum VPhysXConstraintParams_t_EnumFlags0_t : uint
{
    FLAG0_SHIFT_INTERPENETRATE = 0,
    FLAG0_SHIFT_CONSTRAIN = 1,
    FLAG0_SHIFT_BREAKABLE_FORCE = 2,
    FLAG0_SHIFT_BREAKABLE_TORQUE = 3,
}

/// <summary>VPhysXJoint_t, 208 bytes</summary>
public class VPhysXJoint_t
{
    [JsonPropertyName("m_nType")]
    public ushort M_nType { get; set; }  // +0x0
    [JsonPropertyName("m_nBody1")]
    public ushort M_nBody1 { get; set; }  // +0x2
    [JsonPropertyName("m_nBody2")]
    public ushort M_nBody2 { get; set; }  // +0x4
    [JsonPropertyName("m_nFlags")]
    public ushort M_nFlags { get; set; }  // +0x6
    [JsonPropertyName("m_Frame1")]
    public CTransform M_Frame1 { get; set; }  // +0x10
    [JsonPropertyName("m_Frame2")]
    public CTransform M_Frame2 { get; set; }  // +0x30
    [JsonPropertyName("m_bEnableCollision")]
    public bool M_bEnableCollision { get; set; }  // +0x50
    [JsonPropertyName("m_bIsLinearConstraintDisabled")]
    public bool M_bIsLinearConstraintDisabled { get; set; }  // +0x51
    [JsonPropertyName("m_bIsAngularConstraintDisabled")]
    public bool M_bIsAngularConstraintDisabled { get; set; }  // +0x52
    [JsonPropertyName("m_bEnableLinearLimit")]
    public bool M_bEnableLinearLimit { get; set; }  // +0x53
    [JsonPropertyName("m_LinearLimit")]
    public VPhysXRange_t M_LinearLimit { get; set; }  // +0x54
    [JsonPropertyName("m_bEnableLinearMotor")]
    public bool M_bEnableLinearMotor { get; set; }  // +0x5C
    [JsonPropertyName("m_vLinearTargetVelocity")]
    public Vector M_vLinearTargetVelocity { get; set; }  // +0x60
    [JsonPropertyName("m_flMaxForce")]
    public float M_flMaxForce { get; set; }  // +0x6C
    [JsonPropertyName("m_bEnableSwingLimit")]
    public bool M_bEnableSwingLimit { get; set; }  // +0x70
    [JsonPropertyName("m_SwingLimit")]
    public VPhysXRange_t M_SwingLimit { get; set; }  // +0x74
    [JsonPropertyName("m_bEnableTwistLimit")]
    public bool M_bEnableTwistLimit { get; set; }  // +0x7C
    [JsonPropertyName("m_TwistLimit")]
    public VPhysXRange_t M_TwistLimit { get; set; }  // +0x80
    [JsonPropertyName("m_bEnableAngularMotor")]
    public bool M_bEnableAngularMotor { get; set; }  // +0x88
    [JsonPropertyName("m_vAngularTargetVelocity")]
    public Vector M_vAngularTargetVelocity { get; set; }  // +0x8C
    [JsonPropertyName("m_flMaxTorque")]
    public float M_flMaxTorque { get; set; }  // +0x98
    [JsonPropertyName("m_flLinearFrequency")]
    public float M_flLinearFrequency { get; set; }  // +0x9C
    [JsonPropertyName("m_flLinearDampingRatio")]
    public float M_flLinearDampingRatio { get; set; }  // +0xA0
    [JsonPropertyName("m_flAngularFrequency")]
    public float M_flAngularFrequency { get; set; }  // +0xA4
    [JsonPropertyName("m_flAngularDampingRatio")]
    public float M_flAngularDampingRatio { get; set; }  // +0xA8
    [JsonPropertyName("m_flFriction")]
    public float M_flFriction { get; set; }  // +0xAC
    [JsonPropertyName("m_flElasticity")]
    public float M_flElasticity { get; set; }  // +0xB0
    [JsonPropertyName("m_flElasticDamping")]
    public float M_flElasticDamping { get; set; }  // +0xB4
    [JsonPropertyName("m_flPlasticity")]
    public float M_flPlasticity { get; set; }  // +0xB8
    [JsonPropertyName("m_Tag")]
    public string M_Tag { get; set; }  // +0xC0
}

public enum VPhysXJoint_t_Flags_t : uint
{
    JOINT_FLAGS_NONE = 0,
    JOINT_FLAGS_BODY1_FIXED = 1,
    JOINT_FLAGS_USE_BLOCK_SOLVER = 2,
}

/// <summary>VPhysXRange_t, 8 bytes</summary>
public class VPhysXRange_t
{
    [JsonPropertyName("m_flMin")]
    public float M_flMin { get; set; }  // +0x0
    [JsonPropertyName("m_flMax")]
    public float M_flMax { get; set; }  // +0x4
}

/// <summary>VsInputSignature_t, 48 bytes</summary>
public class VsInputSignature_t
{
    [JsonPropertyName("m_elems")]
    public VsInputSignatureElement_t[] M_elems { get; set; }  // +0x0
    [JsonPropertyName("m_depth_elems")]
    public VsInputSignatureElement_t[] M_depth_elems { get; set; }  // +0x18
}

/// <summary>VsInputSignatureElement_t, 196 bytes</summary>
public class VsInputSignatureElement_t
{
    [JsonPropertyName("m_pName")]
    public sbyte[] M_pName { get; set; }  // +0x0
    [JsonPropertyName("m_pSemantic")]
    public sbyte[] M_pSemantic { get; set; }  // +0x40
    [JsonPropertyName("m_pD3DSemanticName")]
    public sbyte[] M_pD3DSemanticName { get; set; }  // +0x80
    [JsonPropertyName("m_nD3DSemanticIndex")]
    public int M_nD3DSemanticIndex { get; set; }  // +0xC0
}

