// Auto-generated by cs2-codegen from schemas_jsonschema.json
// Revision 10638965 (May 06 2026) — https://github.com/ValveResourceFormat/DumpSource2
// Do not edit by hand.
// Module: modtools

#nullable enable
#pragma warning disable CS8618  // non-nullable property not initialized (expected in generated serialization types)

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CS2Schema;

/// <summary>CNmGraphDocAimCSNode, 272 bytes</summary>
public class CNmGraphDocAimCSNode : CNmGraphDocFlowNode
{
    [JsonPropertyName("m_flActionBlendTimeSeconds")]
    public float M_flActionBlendTimeSeconds { get; set; }  // +0x100
    [JsonPropertyName("m_flHandIKBlendInTimeSeconds")]
    public float M_flHandIKBlendInTimeSeconds { get; set; }  // +0x104
    [JsonPropertyName("m_flPlantingBlendTimeSeconds")]
    public float M_flPlantingBlendTimeSeconds { get; set; }  // +0x108
}

/// <summary>CnmGraphDocSnapWeaponNode, 256 bytes</summary>
public class CnmGraphDocSnapWeaponNode : CNmGraphDocFlowNode
{
}

