// Auto-generated by cs2-codegen from schemas_jsonschema.json
// Revision 10638965 (May 06 2026) — https://github.com/ValveResourceFormat/DumpSource2
// Do not edit by hand.
// Module: navlib

#nullable enable
#pragma warning disable CS8618  // non-nullable property not initialized (expected in generated serialization types)

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CS2Schema;

/// <summary>CNavHullPresetVData, 24 bytes</summary>
public class CNavHullPresetVData
{
    [JsonPropertyName("m_vecNavHulls")]
    public string[] M_vecNavHulls { get; set; }  // +0x0
}

/// <summary>CNavHullVData, 60 bytes</summary>
public class CNavHullVData
{
    [JsonPropertyName("m_bAgentEnabled")]
    public bool M_bAgentEnabled { get; set; }  // +0x0
    [JsonPropertyName("m_agentRadius")]
    public float M_agentRadius { get; set; }  // +0x4
    [JsonPropertyName("m_agentHeight")]
    public float M_agentHeight { get; set; }  // +0x8
    [JsonPropertyName("m_agentShortHeightEnabled")]
    public bool M_agentShortHeightEnabled { get; set; }  // +0xC
    [JsonPropertyName("m_agentShortHeight")]
    public float M_agentShortHeight { get; set; }  // +0x10
    [JsonPropertyName("m_agentCrawlEnabled")]
    public bool M_agentCrawlEnabled { get; set; }  // +0x14
    [JsonPropertyName("m_agentCrawlHeight")]
    public float M_agentCrawlHeight { get; set; }  // +0x18
    [JsonPropertyName("m_agentMaxClimb")]
    public float M_agentMaxClimb { get; set; }  // +0x1C
    [JsonPropertyName("m_agentMaxSlope")]
    public int M_agentMaxSlope { get; set; }  // +0x20
    [JsonPropertyName("m_agentMaxJumpDownDist")]
    public float M_agentMaxJumpDownDist { get; set; }  // +0x24
    [JsonPropertyName("m_agentMaxJumpHorizDistBase")]
    public float M_agentMaxJumpHorizDistBase { get; set; }  // +0x28
    [JsonPropertyName("m_agentMaxJumpUpDist")]
    public float M_agentMaxJumpUpDist { get; set; }  // +0x2C
    [JsonPropertyName("m_agentBorderErosion")]
    public int M_agentBorderErosion { get; set; }  // +0x30
    [JsonPropertyName("m_flowMapGenerationEnabled")]
    public bool M_flowMapGenerationEnabled { get; set; }  // +0x34
    [JsonPropertyName("m_flowMapNodeMaxRadius")]
    public float M_flowMapNodeMaxRadius { get; set; }  // +0x38
}

/// <summary>CNavVolume, 120 bytes</summary>
public class CNavVolume
{
}

/// <summary>CNavVolumeAll, 160 bytes</summary>
public class CNavVolumeAll : CNavVolumeVector
{
}

/// <summary>CNavVolumeSphere, 136 bytes</summary>
public class CNavVolumeSphere : CNavVolume
{
    [JsonPropertyName("m_vCenter")]
    public VectorWS M_vCenter { get; set; }  // +0x78
    [JsonPropertyName("m_flRadius")]
    public float M_flRadius { get; set; }  // +0x84
}

/// <summary>CNavVolumeSphericalShell, 144 bytes</summary>
public class CNavVolumeSphericalShell : CNavVolumeSphere
{
    [JsonPropertyName("m_flRadiusInner")]
    public float M_flRadiusInner { get; set; }  // +0x88
}

/// <summary>CNavVolumeVector, 160 bytes</summary>
public class CNavVolumeVector : CNavVolume
{
    [JsonPropertyName("m_bHasBeenPreFiltered")]
    public bool M_bHasBeenPreFiltered { get; set; }  // +0x80
}

/// <summary>Extent, 24 bytes</summary>
public class Extent
{
    [JsonPropertyName("lo")]
    public VectorWS Lo { get; set; }  // +0x0
    [JsonPropertyName("hi")]
    public VectorWS Hi { get; set; }  // +0xC
}

public enum NavAttributeEnum : ulong
{
    NAV_MESH_AVOID = 128,
    NAV_MESH_STAIRS = 4096,
    NAV_MESH_NON_ZUP = 32768,
    NAV_MESH_CROUCH_HEIGHT = 65536,
    NAV_MESH_NON_ZUP_TRANSITION = 131072,
    NAV_MESH_CRAWL_HEIGHT = 262144,
    NAV_MESH_CROUCH = 65536,
    NAV_MESH_JUMP = 2,
    NAV_MESH_NO_JUMP = 8,
    NAV_MESH_STOP = 16,
    NAV_MESH_RUN = 32,
    NAV_MESH_WALK = 64,
    NAV_MESH_TRANSIENT = 256,
    NAV_MESH_DONT_HIDE = 512,
    NAV_MESH_STAND = 1024,
    NAV_MESH_NO_HOSTAGES = 2048,
    NAV_MESH_NO_MERGE = 8192,
    NAV_MESH_OBSTACLE_TOP = 16384,
    NAV_ATTR_FIRST_GAME_INDEX = 19,
    NAV_ATTR_LAST_INDEX = 63,
}

public enum NavDirType : uint
{
    NORTH = 0,
    EAST = 1,
    SOUTH = 2,
    WEST = 3,
    NUM_NAV_DIR_TYPE_DIRECTIONS = 4,
}

/// <summary>NavGravity_t, 16 bytes</summary>
public class NavGravity_t
{
    [JsonPropertyName("m_vGravity")]
    public Vector M_vGravity { get; set; }  // +0x0
    [JsonPropertyName("m_bDefault")]
    public bool M_bDefault { get; set; }  // +0xC
}

/// <summary>NavHull_t, 4 bytes</summary>
public class NavHull_t
{
    [JsonPropertyName("m_nHullIdx")]
    public int M_nHullIdx { get; set; }  // +0x0
}

