// Auto-generated by cs2-codegen from schemas_jsonschema.json
// Revision 10638965 (May 06 2026) — https://github.com/ValveResourceFormat/DumpSource2
// Do not edit by hand.
// Module: networksystem

#nullable enable
#pragma warning disable CS8618  // non-nullable property not initialized (expected in generated serialization types)

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CS2Schema;

/// <summary>ChangeAccessorFieldPathIndex_t, 4 bytes</summary>
public class ChangeAccessorFieldPathIndex_t
{
    [JsonPropertyName("m_Value")]
    public int M_Value { get; set; }  // +0x0
}

