// Auto-generated by cs2-codegen from schemas_jsonschema.json
// Revision 10638965 (May 06 2026) — https://github.com/ValveResourceFormat/DumpSource2
// Do not edit by hand.
// Module: physicslib

#nullable enable
#pragma warning disable CS8618  // non-nullable property not initialized (expected in generated serialization types)

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CS2Schema;

/// <summary>CastSphereSATParams_t, 48 bytes</summary>
public class CastSphereSATParams_t
{
    [JsonPropertyName("m_vRayStart")]
    public Vector M_vRayStart { get; set; }  // +0x0
    [JsonPropertyName("m_vRayDelta")]
    public Vector M_vRayDelta { get; set; }  // +0xC
    [JsonPropertyName("m_flRadius")]
    public float M_flRadius { get; set; }  // +0x18
    [JsonPropertyName("m_flMaxFraction")]
    public float M_flMaxFraction { get; set; }  // +0x1C
    [JsonPropertyName("m_flScale")]
    public float M_flScale { get; set; }  // +0x20
    [JsonPropertyName("m_pHull")]
    public RnHull_t? M_pHull { get; set; }  // +0x28
}

/// <summary>CFeIndexedJiggleBone, 164 bytes</summary>
public class CFeIndexedJiggleBone
{
    [JsonPropertyName("m_nNode")]
    public uint M_nNode { get; set; }  // +0x0
    [JsonPropertyName("m_nJiggleParent")]
    public uint M_nJiggleParent { get; set; }  // +0x4
    [JsonPropertyName("m_jiggleBone")]
    public CFeJiggleBone M_jiggleBone { get; set; }  // +0x8
}

/// <summary>CFeJiggleBone, 156 bytes</summary>
public class CFeJiggleBone
{
    [JsonPropertyName("m_nFlags")]
    public uint M_nFlags { get; set; }  // +0x0
    [JsonPropertyName("m_flLength")]
    public float M_flLength { get; set; }  // +0x4
    [JsonPropertyName("m_flTipMass")]
    public float M_flTipMass { get; set; }  // +0x8
    [JsonPropertyName("m_flYawStiffness")]
    public float M_flYawStiffness { get; set; }  // +0xC
    [JsonPropertyName("m_flYawDamping")]
    public float M_flYawDamping { get; set; }  // +0x10
    [JsonPropertyName("m_flPitchStiffness")]
    public float M_flPitchStiffness { get; set; }  // +0x14
    [JsonPropertyName("m_flPitchDamping")]
    public float M_flPitchDamping { get; set; }  // +0x18
    [JsonPropertyName("m_flAlongStiffness")]
    public float M_flAlongStiffness { get; set; }  // +0x1C
    [JsonPropertyName("m_flAlongDamping")]
    public float M_flAlongDamping { get; set; }  // +0x20
    [JsonPropertyName("m_flAngleLimit")]
    public float M_flAngleLimit { get; set; }  // +0x24
    [JsonPropertyName("m_flMinYaw")]
    public float M_flMinYaw { get; set; }  // +0x28
    [JsonPropertyName("m_flMaxYaw")]
    public float M_flMaxYaw { get; set; }  // +0x2C
    [JsonPropertyName("m_flYawFriction")]
    public float M_flYawFriction { get; set; }  // +0x30
    [JsonPropertyName("m_flYawBounce")]
    public float M_flYawBounce { get; set; }  // +0x34
    [JsonPropertyName("m_flMinPitch")]
    public float M_flMinPitch { get; set; }  // +0x38
    [JsonPropertyName("m_flMaxPitch")]
    public float M_flMaxPitch { get; set; }  // +0x3C
    [JsonPropertyName("m_flPitchFriction")]
    public float M_flPitchFriction { get; set; }  // +0x40
    [JsonPropertyName("m_flPitchBounce")]
    public float M_flPitchBounce { get; set; }  // +0x44
    [JsonPropertyName("m_flBaseMass")]
    public float M_flBaseMass { get; set; }  // +0x48
    [JsonPropertyName("m_flBaseStiffness")]
    public float M_flBaseStiffness { get; set; }  // +0x4C
    [JsonPropertyName("m_flBaseDamping")]
    public float M_flBaseDamping { get; set; }  // +0x50
    [JsonPropertyName("m_flBaseMinLeft")]
    public float M_flBaseMinLeft { get; set; }  // +0x54
    [JsonPropertyName("m_flBaseMaxLeft")]
    public float M_flBaseMaxLeft { get; set; }  // +0x58
    [JsonPropertyName("m_flBaseLeftFriction")]
    public float M_flBaseLeftFriction { get; set; }  // +0x5C
    [JsonPropertyName("m_flBaseMinUp")]
    public float M_flBaseMinUp { get; set; }  // +0x60
    [JsonPropertyName("m_flBaseMaxUp")]
    public float M_flBaseMaxUp { get; set; }  // +0x64
    [JsonPropertyName("m_flBaseUpFriction")]
    public float M_flBaseUpFriction { get; set; }  // +0x68
    [JsonPropertyName("m_flBaseMinForward")]
    public float M_flBaseMinForward { get; set; }  // +0x6C
    [JsonPropertyName("m_flBaseMaxForward")]
    public float M_flBaseMaxForward { get; set; }  // +0x70
    [JsonPropertyName("m_flBaseForwardFriction")]
    public float M_flBaseForwardFriction { get; set; }  // +0x74
    [JsonPropertyName("m_flRadius0")]
    public float M_flRadius0 { get; set; }  // +0x78
    [JsonPropertyName("m_flRadius1")]
    public float M_flRadius1 { get; set; }  // +0x7C
    [JsonPropertyName("m_vPoint0")]
    public Vector M_vPoint0 { get; set; }  // +0x80
    [JsonPropertyName("m_vPoint1")]
    public Vector M_vPoint1 { get; set; }  // +0x8C
    [JsonPropertyName("m_nCollisionMask")]
    public ushort M_nCollisionMask { get; set; }  // +0x98
}

/// <summary>CFeMorphLayer, 136 bytes</summary>
public class CFeMorphLayer
{
    [JsonPropertyName("m_Name")]
    public string M_Name { get; set; }  // +0x0
    [JsonPropertyName("m_nNameHash")]
    public uint M_nNameHash { get; set; }  // +0x8
    [JsonPropertyName("m_Nodes")]
    public ushort[] M_Nodes { get; set; }  // +0x10
    [JsonPropertyName("m_InitPos")]
    public Vector[] M_InitPos { get; set; }  // +0x28
    [JsonPropertyName("m_Gravity")]
    public float[] M_Gravity { get; set; }  // +0x40
    [JsonPropertyName("m_GoalStrength")]
    public float[] M_GoalStrength { get; set; }  // +0x58
    [JsonPropertyName("m_GoalDamping")]
    public float[] M_GoalDamping { get; set; }  // +0x70
}

/// <summary>CFeNamedJiggleBone, 208 bytes</summary>
public class CFeNamedJiggleBone
{
    [JsonPropertyName("m_strParentBone")]
    public string M_strParentBone { get; set; }  // +0x0
    [JsonPropertyName("m_transform")]
    public CTransform M_transform { get; set; }  // +0x10
    [JsonPropertyName("m_nJiggleParent")]
    public uint M_nJiggleParent { get; set; }  // +0x30
    [JsonPropertyName("m_jiggleBone")]
    public CFeJiggleBone M_jiggleBone { get; set; }  // +0x34
}

/// <summary>CFeVertexMapBuildArray, 24 bytes</summary>
public class CFeVertexMapBuildArray
{
    [JsonPropertyName("m_Array")]
    public FeVertexMapBuild_t?[] M_Array { get; set; }  // +0x0
}

/// <summary>CollisionDetailLayerInfo_t, 64 bytes</summary>
public class CollisionDetailLayerInfo_t
{
    [JsonPropertyName("m_sDescription")]
    public string M_sDescription { get; set; }  // +0x0
    [JsonPropertyName("m_sFriendlyName")]
    public string M_sFriendlyName { get; set; }  // +0x8
    [JsonPropertyName("m_bIsQueryOnly")]
    public bool M_bIsQueryOnly { get; set; }  // +0x10
    [JsonPropertyName("m_sParentDetailLayer")]
    public string M_sParentDetailLayer { get; set; }  // +0x18
    [JsonPropertyName("m_vecSubtreeDetailLayers")]
    public CollisionDetailLayerInfo_t_Name_t[] M_vecSubtreeDetailLayers { get; set; }  // +0x20
    [JsonPropertyName("m_bNotPickable")]
    public bool M_bNotPickable { get; set; }  // +0x38
}

/// <summary>CollisionDetailLayerInfo_t::Name_t, 16 bytes</summary>
public class CollisionDetailLayerInfo_t_Name_t
{
    [JsonPropertyName("m_nNameToken")]
    public string M_nNameToken { get; set; }  // +0x0
    [JsonPropertyName("m_sNameString")]
    public string M_sNameString { get; set; }  // +0x8
}

/// <summary>CovMatrix3, 24 bytes</summary>
public class CovMatrix3
{
    [JsonPropertyName("m_vDiag")]
    public Vector M_vDiag { get; set; }  // +0x0
    [JsonPropertyName("m_flXY")]
    public float M_flXY { get; set; }  // +0xC
    [JsonPropertyName("m_flXZ")]
    public float M_flXZ { get; set; }  // +0x10
    [JsonPropertyName("m_flYZ")]
    public float M_flYZ { get; set; }  // +0x14
}

/// <summary>CRegionSVM, 48 bytes</summary>
public class CRegionSVM
{
    [JsonPropertyName("m_Planes")]
    public RnPlane_t[] M_Planes { get; set; }  // +0x0
    [JsonPropertyName("m_Nodes")]
    public uint[] M_Nodes { get; set; }  // +0x18
}

/// <summary>Dop26_t, 104 bytes</summary>
public class Dop26_t
{
    [JsonPropertyName("m_flSupport")]
    public float[] M_flSupport { get; set; }  // +0x0
}

public enum DynamicContinuousContactBehavior_t : byte
{
    DYNAMIC_CONTINUOUS_ALLOW_IF_REQUESTED_BY_OTHER_BODY = 0,
    DYNAMIC_CONTINUOUS_ALWAYS = 1,
    DYNAMIC_CONTINUOUS_NEVER = 2,
}

/// <summary>FeAnimStrayRadius_t, 12 bytes</summary>
public class FeAnimStrayRadius_t
{
    [JsonPropertyName("nNode")]
    public ushort[] NNode { get; set; }  // +0x0
    [JsonPropertyName("flMaxDist")]
    public float FlMaxDist { get; set; }  // +0x4
    [JsonPropertyName("flRelaxationFactor")]
    public float FlRelaxationFactor { get; set; }  // +0x8
}

/// <summary>FeAntiTunnelGroupBuild_t, 8 bytes</summary>
public class FeAntiTunnelGroupBuild_t
{
    [JsonPropertyName("m_nVertexMapHash")]
    public uint M_nVertexMapHash { get; set; }  // +0x0
    [JsonPropertyName("m_nCollisionMask")]
    public uint M_nCollisionMask { get; set; }  // +0x4
}

/// <summary>FeAntiTunnelProbe_t, 28 bytes</summary>
public class FeAntiTunnelProbe_t
{
    [JsonPropertyName("flWeight")]
    public float FlWeight { get; set; }  // +0x0
    [JsonPropertyName("nFlags")]
    public uint NFlags { get; set; }  // +0x4
    [JsonPropertyName("nProbeNode")]
    public ushort NProbeNode { get; set; }  // +0x8
    [JsonPropertyName("nCount")]
    public ushort NCount { get; set; }  // +0xA
    [JsonPropertyName("nBegin")]
    public uint NBegin { get; set; }  // +0xC
    [JsonPropertyName("flActivationDistance")]
    public float FlActivationDistance { get; set; }  // +0x10
    [JsonPropertyName("flCurvatureRadius")]
    public float FlCurvatureRadius { get; set; }  // +0x14
    [JsonPropertyName("flBias")]
    public float FlBias { get; set; }  // +0x18
}

/// <summary>FeAntiTunnelProbeBuild_t, 48 bytes</summary>
public class FeAntiTunnelProbeBuild_t
{
    [JsonPropertyName("flWeight")]
    public float FlWeight { get; set; }  // +0x0
    [JsonPropertyName("flActivationDistance")]
    public float FlActivationDistance { get; set; }  // +0x4
    [JsonPropertyName("flBias")]
    public float FlBias { get; set; }  // +0x8
    [JsonPropertyName("flCurvature")]
    public float FlCurvature { get; set; }  // +0xC
    [JsonPropertyName("nFlags")]
    public uint NFlags { get; set; }  // +0x10
    [JsonPropertyName("nProbeNode")]
    public ushort NProbeNode { get; set; }  // +0x14
    [JsonPropertyName("targetNodes")]
    public ushort[] TargetNodes { get; set; }  // +0x18
}

/// <summary>FeAxialEdgeBend_t, 40 bytes</summary>
public class FeAxialEdgeBend_t
{
    [JsonPropertyName("te")]
    public float Te { get; set; }  // +0x0
    [JsonPropertyName("tv")]
    public float Tv { get; set; }  // +0x4
    [JsonPropertyName("flDist")]
    public float FlDist { get; set; }  // +0x8
    [JsonPropertyName("flWeight")]
    public float[] FlWeight { get; set; }  // +0xC
    [JsonPropertyName("nNode")]
    public ushort[] NNode { get; set; }  // +0x1C
}

/// <summary>FeBandBendLimit_t, 20 bytes</summary>
public class FeBandBendLimit_t
{
    [JsonPropertyName("flDistMin")]
    public float FlDistMin { get; set; }  // +0x0
    [JsonPropertyName("flDistMax")]
    public float FlDistMax { get; set; }  // +0x4
    [JsonPropertyName("nNode")]
    public ushort[] NNode { get; set; }  // +0x8
}

/// <summary>FeBoxRigid_t, 64 bytes</summary>
public class FeBoxRigid_t
{
    [JsonPropertyName("tmFrame2")]
    public CTransform TmFrame2 { get; set; }  // +0x0
    [JsonPropertyName("nNode")]
    public ushort NNode { get; set; }  // +0x20
    [JsonPropertyName("nCollisionMask")]
    public ushort NCollisionMask { get; set; }  // +0x22
    [JsonPropertyName("vSize")]
    public Vector VSize { get; set; }  // +0x24
    [JsonPropertyName("nVertexMapIndex")]
    public ushort NVertexMapIndex { get; set; }  // +0x30
    [JsonPropertyName("nFlags")]
    public ushort NFlags { get; set; }  // +0x32
}

/// <summary>FeBuildBoxRigid_t, 80 bytes</summary>
public class FeBuildBoxRigid_t : FeBoxRigid_t
{
    [JsonPropertyName("m_nPriority")]
    public int M_nPriority { get; set; }  // +0x40
    [JsonPropertyName("m_nVertexMapHash")]
    public uint M_nVertexMapHash { get; set; }  // +0x44
    [JsonPropertyName("m_nAntitunnelGroupBits")]
    public uint M_nAntitunnelGroupBits { get; set; }  // +0x48
}

/// <summary>FeBuildSDFRigid_t, 96 bytes</summary>
public class FeBuildSDFRigid_t : FeSDFRigid_t
{
    [JsonPropertyName("m_nPriority")]
    public int M_nPriority { get; set; }  // +0x50
    [JsonPropertyName("m_nVertexMapHash")]
    public uint M_nVertexMapHash { get; set; }  // +0x54
    [JsonPropertyName("m_nAntitunnelGroupBits")]
    public uint M_nAntitunnelGroupBits { get; set; }  // +0x58
}

/// <summary>FeBuildSphereRigid_t, 48 bytes</summary>
public class FeBuildSphereRigid_t : FeSphereRigid_t
{
    [JsonPropertyName("m_nPriority")]
    public int M_nPriority { get; set; }  // +0x20
    [JsonPropertyName("m_nVertexMapHash")]
    public uint M_nVertexMapHash { get; set; }  // +0x24
    [JsonPropertyName("m_nAntitunnelGroupBits")]
    public uint M_nAntitunnelGroupBits { get; set; }  // +0x28
}

/// <summary>FeBuildTaperedCapsuleRigid_t, 64 bytes</summary>
public class FeBuildTaperedCapsuleRigid_t : FeTaperedCapsuleRigid_t
{
    [JsonPropertyName("m_nPriority")]
    public int M_nPriority { get; set; }  // +0x30
    [JsonPropertyName("m_nVertexMapHash")]
    public uint M_nVertexMapHash { get; set; }  // +0x34
    [JsonPropertyName("m_nAntitunnelGroupBits")]
    public uint M_nAntitunnelGroupBits { get; set; }  // +0x38
}

/// <summary>FeCollisionPlane_t, 24 bytes</summary>
public class FeCollisionPlane_t
{
    [JsonPropertyName("nCtrlParent")]
    public ushort NCtrlParent { get; set; }  // +0x0
    [JsonPropertyName("nChildNode")]
    public ushort NChildNode { get; set; }  // +0x2
    [JsonPropertyName("m_Plane")]
    public RnPlane_t M_Plane { get; set; }  // +0x4
    [JsonPropertyName("flStrength")]
    public float FlStrength { get; set; }  // +0x14
}

/// <summary>FeCtrlOffset_t, 16 bytes</summary>
public class FeCtrlOffset_t
{
    [JsonPropertyName("vOffset")]
    public Vector VOffset { get; set; }  // +0x0
    [JsonPropertyName("nCtrlParent")]
    public ushort NCtrlParent { get; set; }  // +0xC
    [JsonPropertyName("nCtrlChild")]
    public ushort NCtrlChild { get; set; }  // +0xE
}

/// <summary>FeCtrlOsOffset_t, 4 bytes</summary>
public class FeCtrlOsOffset_t
{
    [JsonPropertyName("nCtrlParent")]
    public ushort NCtrlParent { get; set; }  // +0x0
    [JsonPropertyName("nCtrlChild")]
    public ushort NCtrlChild { get; set; }  // +0x2
}

/// <summary>FeCtrlSoftOffset_t, 20 bytes</summary>
public class FeCtrlSoftOffset_t
{
    [JsonPropertyName("nCtrlParent")]
    public ushort NCtrlParent { get; set; }  // +0x0
    [JsonPropertyName("nCtrlChild")]
    public ushort NCtrlChild { get; set; }  // +0x2
    [JsonPropertyName("vOffset")]
    public Vector VOffset { get; set; }  // +0x4
    [JsonPropertyName("flAlpha")]
    public float FlAlpha { get; set; }  // +0x10
}

/// <summary>FeDynKinLink_t, 4 bytes</summary>
public class FeDynKinLink_t
{
    [JsonPropertyName("m_nParent")]
    public ushort M_nParent { get; set; }  // +0x0
    [JsonPropertyName("m_nChild")]
    public ushort M_nChild { get; set; }  // +0x2
}

/// <summary>FeEdgeDesc_t, 16 bytes</summary>
public class FeEdgeDesc_t
{
    [JsonPropertyName("nEdge")]
    public ushort[] NEdge { get; set; }  // +0x0
    [JsonPropertyName("nSide")]
    public ushort[][] NSide { get; set; }  // +0x4
    [JsonPropertyName("nVirtElem")]
    public ushort[] NVirtElem { get; set; }  // +0xC
}

/// <summary>FeEffectDesc_t, 32 bytes</summary>
public class FeEffectDesc_t
{
    [JsonPropertyName("sName")]
    public string SName { get; set; }  // +0x0
    [JsonPropertyName("nNameHash")]
    public uint NNameHash { get; set; }  // +0x8
    [JsonPropertyName("nType")]
    public int NType { get; set; }  // +0xC
    [JsonPropertyName("m_Params")]
    public object /* opaque */ M_Params { get; set; }  // +0x10
}

/// <summary>FeFitInfluence_t, 12 bytes</summary>
public class FeFitInfluence_t
{
    [JsonPropertyName("nVertexNode")]
    public uint NVertexNode { get; set; }  // +0x0
    [JsonPropertyName("flWeight")]
    public float FlWeight { get; set; }  // +0x4
    [JsonPropertyName("nMatrixNode")]
    public uint NMatrixNode { get; set; }  // +0x8
}

/// <summary>FeFitMatrix_t, 64 bytes</summary>
public class FeFitMatrix_t
{
    [JsonPropertyName("bone")]
    public CTransform Bone { get; set; }  // +0x0
    [JsonPropertyName("vCenter")]
    public Vector VCenter { get; set; }  // +0x20
    [JsonPropertyName("nEnd")]
    public ushort NEnd { get; set; }  // +0x2C
    [JsonPropertyName("nNode")]
    public ushort NNode { get; set; }  // +0x2E
    [JsonPropertyName("nBeginDynamic")]
    public ushort NBeginDynamic { get; set; }  // +0x30
}

/// <summary>FeFitWeight_t, 8 bytes</summary>
public class FeFitWeight_t
{
    [JsonPropertyName("flWeight")]
    public float FlWeight { get; set; }  // +0x0
    [JsonPropertyName("nNode")]
    public ushort NNode { get; set; }  // +0x4
    [JsonPropertyName("nDummy")]
    public ushort NDummy { get; set; }  // +0x6
}

/// <summary>FeFollowNode_t, 8 bytes</summary>
public class FeFollowNode_t
{
    [JsonPropertyName("nParentNode")]
    public ushort NParentNode { get; set; }  // +0x0
    [JsonPropertyName("nChildNode")]
    public ushort NChildNode { get; set; }  // +0x2
    [JsonPropertyName("flWeight")]
    public float FlWeight { get; set; }  // +0x4
}

/// <summary>FeHingeLimit_t, 32 bytes</summary>
public class FeHingeLimit_t
{
    [JsonPropertyName("nNode")]
    public ushort[] NNode { get; set; }  // +0x0
    [JsonPropertyName("nFlags")]
    public uint NFlags { get; set; }  // +0xC
    [JsonPropertyName("flWeight4")]
    public float FlWeight4 { get; set; }  // +0x10
    [JsonPropertyName("flWeight5")]
    public float FlWeight5 { get; set; }  // +0x14
    [JsonPropertyName("flAngleCenter")]
    public float FlAngleCenter { get; set; }  // +0x18
    [JsonPropertyName("flAngleExtents")]
    public float FlAngleExtents { get; set; }  // +0x1C
}

/// <summary>FeHingeLimitBuild_t, 24 bytes</summary>
public class FeHingeLimitBuild_t
{
    [JsonPropertyName("nNode")]
    public ushort[] NNode { get; set; }  // +0x0
    [JsonPropertyName("nFlags")]
    public uint NFlags { get; set; }  // +0xC
    [JsonPropertyName("flLimitCW")]
    public float FlLimitCW { get; set; }  // +0x10
    [JsonPropertyName("flLimitCCW")]
    public float FlLimitCCW { get; set; }  // +0x14
}

/// <summary>FeKelagerBend2_t, 24 bytes</summary>
public class FeKelagerBend2_t
{
    [JsonPropertyName("flWeight")]
    public float[] FlWeight { get; set; }  // +0x0
    [JsonPropertyName("flHeight0")]
    public float FlHeight0 { get; set; }  // +0xC
    [JsonPropertyName("nNode")]
    public ushort[] NNode { get; set; }  // +0x10
    [JsonPropertyName("nReserved")]
    public ushort NReserved { get; set; }  // +0x16
}

/// <summary>FeModelSelfCollisionLayer_t, 56 bytes</summary>
public class FeModelSelfCollisionLayer_t
{
    [JsonPropertyName("m_Name")]
    public string M_Name { get; set; }  // +0x0
    [JsonPropertyName("m_Nodes")]
    public ushort[] M_Nodes { get; set; }  // +0x8
    [JsonPropertyName("m_flParentReaction")]
    public float M_flParentReaction { get; set; }  // +0x20
    [JsonPropertyName("m_nFlags")]
    public uint M_nFlags { get; set; }  // +0x24
    [JsonPropertyName("m_nEndIdx")]
    public uint[] M_nEndIdx { get; set; }  // +0x28
}

/// <summary>FeMorphLayerDepr_t, 144 bytes</summary>
public class FeMorphLayerDepr_t
{
    [JsonPropertyName("m_Name")]
    public string M_Name { get; set; }  // +0x0
    [JsonPropertyName("m_nNameHash")]
    public uint M_nNameHash { get; set; }  // +0x8
    [JsonPropertyName("m_Nodes")]
    public ushort[] M_Nodes { get; set; }  // +0x10
    [JsonPropertyName("m_InitPos")]
    public Vector[] M_InitPos { get; set; }  // +0x28
    [JsonPropertyName("m_Gravity")]
    public float[] M_Gravity { get; set; }  // +0x40
    [JsonPropertyName("m_GoalStrength")]
    public float[] M_GoalStrength { get; set; }  // +0x58
    [JsonPropertyName("m_GoalDamping")]
    public float[] M_GoalDamping { get; set; }  // +0x70
    [JsonPropertyName("m_nFlags")]
    public uint M_nFlags { get; set; }  // +0x88
}

/// <summary>FeNodeBase_t, 32 bytes</summary>
public class FeNodeBase_t
{
    [JsonPropertyName("nNode")]
    public ushort NNode { get; set; }  // +0x0
    [JsonPropertyName("nDummy")]
    public ushort[] NDummy { get; set; }  // +0x2
    [JsonPropertyName("nNodeX0")]
    public ushort NNodeX0 { get; set; }  // +0x8
    [JsonPropertyName("nNodeX1")]
    public ushort NNodeX1 { get; set; }  // +0xA
    [JsonPropertyName("nNodeY0")]
    public ushort NNodeY0 { get; set; }  // +0xC
    [JsonPropertyName("nNodeY1")]
    public ushort NNodeY1 { get; set; }  // +0xE
    [JsonPropertyName("qAdjust")]
    public QuaternionStorage QAdjust { get; set; }  // +0x10
}

/// <summary>FeNodeIntegrator_t, 16 bytes</summary>
public class FeNodeIntegrator_t
{
    [JsonPropertyName("flPointDamping")]
    public float FlPointDamping { get; set; }  // +0x0
    [JsonPropertyName("flAnimationForceAttraction")]
    public float FlAnimationForceAttraction { get; set; }  // +0x4
    [JsonPropertyName("flAnimationVertexAttraction")]
    public float FlAnimationVertexAttraction { get; set; }  // +0x8
    [JsonPropertyName("flGravity")]
    public float FlGravity { get; set; }  // +0xC
}

/// <summary>FeNodeReverseOffset_t, 16 bytes</summary>
public class FeNodeReverseOffset_t
{
    [JsonPropertyName("vOffset")]
    public Vector VOffset { get; set; }  // +0x0
    [JsonPropertyName("nBoneCtrl")]
    public ushort NBoneCtrl { get; set; }  // +0xC
    [JsonPropertyName("nTargetNode")]
    public ushort NTargetNode { get; set; }  // +0xE
}

/// <summary>FeNodeStrayBox_t, 32 bytes</summary>
public class FeNodeStrayBox_t
{
    [JsonPropertyName("vMin")]
    public Vector VMin { get; set; }  // +0x0
    [JsonPropertyName("nFlags")]
    public uint NFlags { get; set; }  // +0xC
    [JsonPropertyName("vMax")]
    public Vector VMax { get; set; }  // +0x10
    [JsonPropertyName("nNode")]
    public ushort[] NNode { get; set; }  // +0x1C
}

/// <summary>FeNodeWindBase_t, 8 bytes</summary>
public class FeNodeWindBase_t
{
    [JsonPropertyName("nNodeX0")]
    public ushort NNodeX0 { get; set; }  // +0x0
    [JsonPropertyName("nNodeX1")]
    public ushort NNodeX1 { get; set; }  // +0x2
    [JsonPropertyName("nNodeY0")]
    public ushort NNodeY0 { get; set; }  // +0x4
    [JsonPropertyName("nNodeY1")]
    public ushort NNodeY1 { get; set; }  // +0x6
}

/// <summary>FeProxyVertexMap_t, 16 bytes</summary>
public class FeProxyVertexMap_t
{
    [JsonPropertyName("m_Name")]
    public string M_Name { get; set; }  // +0x0
    [JsonPropertyName("m_flWeight")]
    public float M_flWeight { get; set; }  // +0x8
}

/// <summary>FeQuad_t, 76 bytes</summary>
public class FeQuad_t
{
    [JsonPropertyName("nNode")]
    public ushort[] NNode { get; set; }  // +0x0
    [JsonPropertyName("flSlack")]
    public float FlSlack { get; set; }  // +0x8
    [JsonPropertyName("vShape")]
    public Vector4D[] VShape { get; set; }  // +0xC
}

/// <summary>FeRigidColliderIndices_t, 10 bytes</summary>
public class FeRigidColliderIndices_t
{
    [JsonPropertyName("m_nTaperedCapsuleRigidIndex")]
    public ushort M_nTaperedCapsuleRigidIndex { get; set; }  // +0x0
    [JsonPropertyName("m_nSphereRigidIndex")]
    public ushort M_nSphereRigidIndex { get; set; }  // +0x2
    [JsonPropertyName("m_nBoxRigidIndex")]
    public ushort M_nBoxRigidIndex { get; set; }  // +0x4
    [JsonPropertyName("m_nSDFRigidIndex")]
    public ushort M_nSDFRigidIndex { get; set; }  // +0x6
    [JsonPropertyName("m_nCollisionPlaneIndex")]
    public ushort M_nCollisionPlaneIndex { get; set; }  // +0x8
}

/// <summary>FeRodConstraint_t, 20 bytes</summary>
public class FeRodConstraint_t
{
    [JsonPropertyName("nNode")]
    public ushort[] NNode { get; set; }  // +0x0
    [JsonPropertyName("flMaxDist")]
    public float FlMaxDist { get; set; }  // +0x4
    [JsonPropertyName("flMinDist")]
    public float FlMinDist { get; set; }  // +0x8
    [JsonPropertyName("flWeight0")]
    public float FlWeight0 { get; set; }  // +0xC
    [JsonPropertyName("flRelaxationFactor")]
    public float FlRelaxationFactor { get; set; }  // +0x10
}

/// <summary>FeSDFRigid_t, 80 bytes</summary>
public class FeSDFRigid_t
{
    [JsonPropertyName("vLocalMin")]
    public Vector VLocalMin { get; set; }  // +0x0
    [JsonPropertyName("vLocalMax")]
    public Vector VLocalMax { get; set; }  // +0xC
    [JsonPropertyName("flBounciness")]
    public float FlBounciness { get; set; }  // +0x18
    [JsonPropertyName("nNode")]
    public ushort NNode { get; set; }  // +0x1C
    [JsonPropertyName("nCollisionMask")]
    public ushort NCollisionMask { get; set; }  // +0x1E
    [JsonPropertyName("nVertexMapIndex")]
    public ushort NVertexMapIndex { get; set; }  // +0x20
    [JsonPropertyName("nFlags")]
    public ushort NFlags { get; set; }  // +0x22
    [JsonPropertyName("m_Distances")]
    public float[] M_Distances { get; set; }  // +0x28
    [JsonPropertyName("m_nWidth")]
    public int M_nWidth { get; set; }  // +0x40
    [JsonPropertyName("m_nHeight")]
    public int M_nHeight { get; set; }  // +0x44
    [JsonPropertyName("m_nDepth")]
    public int M_nDepth { get; set; }  // +0x48
}

/// <summary>FeSimdAnimStrayRadius_t, 48 bytes</summary>
public class FeSimdAnimStrayRadius_t
{
    [JsonPropertyName("nNode")]
    public ushort[][] NNode { get; set; }  // +0x0
    [JsonPropertyName("flMaxDist")]
    public fltx4 FlMaxDist { get; set; }  // +0x10
    [JsonPropertyName("flRelaxationFactor")]
    public fltx4 FlRelaxationFactor { get; set; }  // +0x20
}

/// <summary>FeSimdNodeBase_t, 112 bytes</summary>
public class FeSimdNodeBase_t
{
    [JsonPropertyName("nNode")]
    public ushort[] NNode { get; set; }  // +0x0
    [JsonPropertyName("nNodeX0")]
    public ushort[] NNodeX0 { get; set; }  // +0x8
    [JsonPropertyName("nNodeX1")]
    public ushort[] NNodeX1 { get; set; }  // +0x10
    [JsonPropertyName("nNodeY0")]
    public ushort[] NNodeY0 { get; set; }  // +0x18
    [JsonPropertyName("nNodeY1")]
    public ushort[] NNodeY1 { get; set; }  // +0x20
    [JsonPropertyName("nDummy")]
    public ushort[] NDummy { get; set; }  // +0x28
    [JsonPropertyName("qAdjust")]
    public FourQuaternions QAdjust { get; set; }  // +0x30
}

/// <summary>FeSimdQuad_t, 304 bytes</summary>
public class FeSimdQuad_t
{
    [JsonPropertyName("nNode")]
    public ushort[][] NNode { get; set; }  // +0x0
    [JsonPropertyName("f4Slack")]
    public fltx4 F4Slack { get; set; }  // +0x20
    [JsonPropertyName("vShape")]
    public object /* opaque */[] VShape { get; set; }  // +0x30
    [JsonPropertyName("f4Weights")]
    public fltx4[] F4Weights { get; set; }  // +0xF0
}

/// <summary>FeSimdRodConstraint_t, 80 bytes</summary>
public class FeSimdRodConstraint_t
{
    [JsonPropertyName("nNode")]
    public ushort[][] NNode { get; set; }  // +0x0
    [JsonPropertyName("f4MaxDist")]
    public fltx4 F4MaxDist { get; set; }  // +0x10
    [JsonPropertyName("f4MinDist")]
    public fltx4 F4MinDist { get; set; }  // +0x20
    [JsonPropertyName("f4Weight0")]
    public fltx4 F4Weight0 { get; set; }  // +0x30
    [JsonPropertyName("f4RelaxationFactor")]
    public fltx4 F4RelaxationFactor { get; set; }  // +0x40
}

/// <summary>FeSimdRodConstraintAnim_t, 48 bytes</summary>
public class FeSimdRodConstraintAnim_t
{
    [JsonPropertyName("nNode")]
    public ushort[][] NNode { get; set; }  // +0x0
    [JsonPropertyName("f4Weight0")]
    public fltx4 F4Weight0 { get; set; }  // +0x10
    [JsonPropertyName("f4RelaxationFactor")]
    public fltx4 F4RelaxationFactor { get; set; }  // +0x20
}

/// <summary>FeSimdSpringIntegrator_t, 80 bytes</summary>
public class FeSimdSpringIntegrator_t
{
    [JsonPropertyName("nNode")]
    public ushort[][] NNode { get; set; }  // +0x0
    [JsonPropertyName("flSpringRestLength")]
    public fltx4 FlSpringRestLength { get; set; }  // +0x10
    [JsonPropertyName("flSpringConstant")]
    public fltx4 FlSpringConstant { get; set; }  // +0x20
    [JsonPropertyName("flSpringDamping")]
    public fltx4 FlSpringDamping { get; set; }  // +0x30
    [JsonPropertyName("flNodeWeight0")]
    public fltx4 FlNodeWeight0 { get; set; }  // +0x40
}

/// <summary>FeSimdTri_t, 128 bytes</summary>
public class FeSimdTri_t
{
    [JsonPropertyName("nNode")]
    public uint[][] NNode { get; set; }  // +0x0
    [JsonPropertyName("w1")]
    public fltx4 W1 { get; set; }  // +0x30
    [JsonPropertyName("w2")]
    public fltx4 W2 { get; set; }  // +0x40
    [JsonPropertyName("v1x")]
    public fltx4 V1x { get; set; }  // +0x50
    [JsonPropertyName("v2")]
    public FourVectors2D V2 { get; set; }  // +0x60
}

/// <summary>FeSoftParent_t, 8 bytes</summary>
public class FeSoftParent_t
{
    [JsonPropertyName("nParent")]
    public int NParent { get; set; }  // +0x0
    [JsonPropertyName("flAlpha")]
    public float FlAlpha { get; set; }  // +0x4
}

/// <summary>FeSourceEdge_t, 4 bytes</summary>
public class FeSourceEdge_t
{
    [JsonPropertyName("nNode")]
    public ushort[] NNode { get; set; }  // +0x0
}

/// <summary>FeSphereRigid_t, 32 bytes</summary>
public class FeSphereRigid_t
{
    [JsonPropertyName("vSphere")]
    public fltx4 VSphere { get; set; }  // +0x0
    [JsonPropertyName("nNode")]
    public ushort NNode { get; set; }  // +0x10
    [JsonPropertyName("nCollisionMask")]
    public ushort NCollisionMask { get; set; }  // +0x12
    [JsonPropertyName("nVertexMapIndex")]
    public ushort NVertexMapIndex { get; set; }  // +0x14
    [JsonPropertyName("nFlags")]
    public ushort NFlags { get; set; }  // +0x16
}

/// <summary>FeSpringIntegrator_t, 20 bytes</summary>
public class FeSpringIntegrator_t
{
    [JsonPropertyName("nNode")]
    public ushort[] NNode { get; set; }  // +0x0
    [JsonPropertyName("flSpringRestLength")]
    public float FlSpringRestLength { get; set; }  // +0x4
    [JsonPropertyName("flSpringConstant")]
    public float FlSpringConstant { get; set; }  // +0x8
    [JsonPropertyName("flSpringDamping")]
    public float FlSpringDamping { get; set; }  // +0xC
    [JsonPropertyName("flNodeWeight0")]
    public float FlNodeWeight0 { get; set; }  // +0x10
}

/// <summary>FeStiffHingeBuild_t, 28 bytes</summary>
public class FeStiffHingeBuild_t
{
    [JsonPropertyName("flMaxAngle")]
    public float FlMaxAngle { get; set; }  // +0x0
    [JsonPropertyName("flStrength")]
    public float FlStrength { get; set; }  // +0x4
    [JsonPropertyName("flMotionBias")]
    public float[] FlMotionBias { get; set; }  // +0x8
    [JsonPropertyName("nNode")]
    public ushort[] NNode { get; set; }  // +0x14
}

/// <summary>FeTaperedCapsuleRigid_t, 48 bytes</summary>
public class FeTaperedCapsuleRigid_t
{
    [JsonPropertyName("vSphere")]
    public fltx4[] VSphere { get; set; }  // +0x0
    [JsonPropertyName("nNode")]
    public ushort NNode { get; set; }  // +0x20
    [JsonPropertyName("nCollisionMask")]
    public ushort NCollisionMask { get; set; }  // +0x22
    [JsonPropertyName("nVertexMapIndex")]
    public ushort NVertexMapIndex { get; set; }  // +0x24
    [JsonPropertyName("nFlags")]
    public ushort NFlags { get; set; }  // +0x26
}

/// <summary>FeTaperedCapsuleStretch_t, 16 bytes</summary>
public class FeTaperedCapsuleStretch_t
{
    [JsonPropertyName("nNode")]
    public ushort[] NNode { get; set; }  // +0x0
    [JsonPropertyName("nCollisionMask")]
    public ushort NCollisionMask { get; set; }  // +0x4
    [JsonPropertyName("nDummy")]
    public ushort NDummy { get; set; }  // +0x6
    [JsonPropertyName("flRadius")]
    public float[] FlRadius { get; set; }  // +0x8
}

/// <summary>FeTreeChildren_t, 4 bytes</summary>
public class FeTreeChildren_t
{
    [JsonPropertyName("nChild")]
    public ushort[] NChild { get; set; }  // +0x0
}

/// <summary>FeTri_t, 28 bytes</summary>
public class FeTri_t
{
    [JsonPropertyName("nNode")]
    public ushort[] NNode { get; set; }  // +0x0
    [JsonPropertyName("w1")]
    public float W1 { get; set; }  // +0x8
    [JsonPropertyName("w2")]
    public float W2 { get; set; }  // +0xC
    [JsonPropertyName("v1x")]
    public float V1x { get; set; }  // +0x10
    [JsonPropertyName("v2")]
    public Vector2D V2 { get; set; }  // +0x14
}

/// <summary>FeTwistConstraint_t, 12 bytes</summary>
public class FeTwistConstraint_t
{
    [JsonPropertyName("nNodeOrient")]
    public ushort NNodeOrient { get; set; }  // +0x0
    [JsonPropertyName("nNodeEnd")]
    public ushort NNodeEnd { get; set; }  // +0x2
    [JsonPropertyName("flTwistRelax")]
    public float FlTwistRelax { get; set; }  // +0x4
    [JsonPropertyName("flSwingRelax")]
    public float FlSwingRelax { get; set; }  // +0x8
}

/// <summary>FeVertexMapBuild_t, 48 bytes</summary>
public class FeVertexMapBuild_t
{
    [JsonPropertyName("m_VertexMapName")]
    public string M_VertexMapName { get; set; }  // +0x0
    [JsonPropertyName("m_nNameHash")]
    public uint M_nNameHash { get; set; }  // +0x8
    [JsonPropertyName("m_Color")]
    public Color M_Color { get; set; }  // +0xC
    [JsonPropertyName("m_flVolumetricSolveStrength")]
    public float M_flVolumetricSolveStrength { get; set; }  // +0x10
    [JsonPropertyName("m_nScaleSourceNode")]
    public int M_nScaleSourceNode { get; set; }  // +0x14
    [JsonPropertyName("m_Weights")]
    public float[] M_Weights { get; set; }  // +0x18
}

/// <summary>FeVertexMapDesc_t, 56 bytes</summary>
public class FeVertexMapDesc_t
{
    [JsonPropertyName("sName")]
    public string SName { get; set; }  // +0x0
    [JsonPropertyName("nNameHash")]
    public uint NNameHash { get; set; }  // +0x8
    [JsonPropertyName("nColor")]
    public uint NColor { get; set; }  // +0xC
    [JsonPropertyName("nFlags")]
    public uint NFlags { get; set; }  // +0x10
    [JsonPropertyName("nVertexBase")]
    public ushort NVertexBase { get; set; }  // +0x14
    [JsonPropertyName("nVertexCount")]
    public ushort NVertexCount { get; set; }  // +0x16
    [JsonPropertyName("nMapOffset")]
    public uint NMapOffset { get; set; }  // +0x18
    [JsonPropertyName("nNodeListOffset")]
    public uint NNodeListOffset { get; set; }  // +0x1C
    [JsonPropertyName("vCenterOfMass")]
    public Vector VCenterOfMass { get; set; }  // +0x20
    [JsonPropertyName("flVolumetricSolveStrength")]
    public float FlVolumetricSolveStrength { get; set; }  // +0x2C
    [JsonPropertyName("nScaleSourceNode")]
    public short NScaleSourceNode { get; set; }  // +0x30
    [JsonPropertyName("nNodeListCount")]
    public ushort NNodeListCount { get; set; }  // +0x32
}

/// <summary>FeWeightedNode_t, 4 bytes</summary>
public class FeWeightedNode_t
{
    [JsonPropertyName("nNode")]
    public ushort NNode { get; set; }  // +0x0
    [JsonPropertyName("nWeight")]
    public ushort NWeight { get; set; }  // +0x2
}

/// <summary>FeWorldCollisionParams_t, 12 bytes</summary>
public class FeWorldCollisionParams_t
{
    [JsonPropertyName("flWorldFriction")]
    public float FlWorldFriction { get; set; }  // +0x0
    [JsonPropertyName("flGroundFriction")]
    public float FlGroundFriction { get; set; }  // +0x4
    [JsonPropertyName("nListBegin")]
    public ushort NListBegin { get; set; }  // +0x8
    [JsonPropertyName("nListEnd")]
    public ushort NListEnd { get; set; }  // +0xA
}

/// <summary>FourCovMatrices3, 96 bytes</summary>
public class FourCovMatrices3
{
    [JsonPropertyName("m_vDiag")]
    public object /* opaque */ M_vDiag { get; set; }  // +0x0
    [JsonPropertyName("m_flXY")]
    public fltx4 M_flXY { get; set; }  // +0x30
    [JsonPropertyName("m_flXZ")]
    public fltx4 M_flXZ { get; set; }  // +0x40
    [JsonPropertyName("m_flYZ")]
    public fltx4 M_flYZ { get; set; }  // +0x50
}

/// <summary>FourVectors2D, 32 bytes</summary>
public class FourVectors2D
{
    [JsonPropertyName("x")]
    public fltx4 X { get; set; }  // +0x0
    [JsonPropertyName("y")]
    public fltx4 Y { get; set; }  // +0x10
}

public enum JointAxis_t : uint
{
    JOINT_AXIS_X = 0,
    JOINT_AXIS_Y = 1,
    JOINT_AXIS_Z = 2,
    JOINT_AXIS_COUNT = 3,
}

public enum JointMotion_t : uint
{
    JOINT_MOTION_FREE = 0,
    JOINT_MOTION_LOCKED = 1,
    JOINT_MOTION_COUNT = 2,
}

/// <summary>OldFeEdge_t, 72 bytes</summary>
public class OldFeEdge_t
{
    [JsonPropertyName("m_flK")]
    public float[] M_flK { get; set; }  // +0x0
    [JsonPropertyName("invA")]
    public float InvA { get; set; }  // +0xC
    [JsonPropertyName("t")]
    public float T { get; set; }  // +0x10
    [JsonPropertyName("flThetaRelaxed")]
    public float FlThetaRelaxed { get; set; }  // +0x14
    [JsonPropertyName("flThetaFactor")]
    public float FlThetaFactor { get; set; }  // +0x18
    [JsonPropertyName("c01")]
    public float C01 { get; set; }  // +0x1C
    [JsonPropertyName("c02")]
    public float C02 { get; set; }  // +0x20
    [JsonPropertyName("c03")]
    public float C03 { get; set; }  // +0x24
    [JsonPropertyName("c04")]
    public float C04 { get; set; }  // +0x28
    [JsonPropertyName("flAxialModelDist")]
    public float FlAxialModelDist { get; set; }  // +0x2C
    [JsonPropertyName("flAxialModelWeights")]
    public float[] FlAxialModelWeights { get; set; }  // +0x30
    [JsonPropertyName("m_nNode")]
    public ushort[] M_nNode { get; set; }  // +0x40
}

/// <summary>PhysFeModelDesc_t, 1760 bytes</summary>
public class PhysFeModelDesc_t
{
    [JsonPropertyName("m_CtrlHash")]
    public uint[] M_CtrlHash { get; set; }  // +0x0
    [JsonPropertyName("m_CtrlName")]
    public string[] M_CtrlName { get; set; }  // +0x18
    [JsonPropertyName("m_nStaticNodeFlags")]
    public uint M_nStaticNodeFlags { get; set; }  // +0x30
    [JsonPropertyName("m_nDynamicNodeFlags")]
    public uint M_nDynamicNodeFlags { get; set; }  // +0x34
    [JsonPropertyName("m_flLocalForce")]
    public float M_flLocalForce { get; set; }  // +0x38
    [JsonPropertyName("m_flLocalRotation")]
    public float M_flLocalRotation { get; set; }  // +0x3C
    [JsonPropertyName("m_nNodeCount")]
    public ushort M_nNodeCount { get; set; }  // +0x40
    [JsonPropertyName("m_nStaticNodes")]
    public ushort M_nStaticNodes { get; set; }  // +0x42
    [JsonPropertyName("m_nRotLockStaticNodes")]
    public ushort M_nRotLockStaticNodes { get; set; }  // +0x44
    [JsonPropertyName("m_nFirstPositionDrivenNode")]
    public ushort M_nFirstPositionDrivenNode { get; set; }  // +0x46
    [JsonPropertyName("m_nSimdTriCount1")]
    public ushort M_nSimdTriCount1 { get; set; }  // +0x48
    [JsonPropertyName("m_nSimdTriCount2")]
    public ushort M_nSimdTriCount2 { get; set; }  // +0x4A
    [JsonPropertyName("m_nSimdQuadCount1")]
    public ushort M_nSimdQuadCount1 { get; set; }  // +0x4C
    [JsonPropertyName("m_nSimdQuadCount2")]
    public ushort M_nSimdQuadCount2 { get; set; }  // +0x4E
    [JsonPropertyName("m_nQuadCount1")]
    public ushort M_nQuadCount1 { get; set; }  // +0x50
    [JsonPropertyName("m_nQuadCount2")]
    public ushort M_nQuadCount2 { get; set; }  // +0x52
    [JsonPropertyName("m_nTreeDepth")]
    public ushort M_nTreeDepth { get; set; }  // +0x54
    [JsonPropertyName("m_nNodeBaseJiggleboneDependsCount")]
    public ushort M_nNodeBaseJiggleboneDependsCount { get; set; }  // +0x56
    [JsonPropertyName("m_nRopeCount")]
    public ushort M_nRopeCount { get; set; }  // +0x58
    [JsonPropertyName("m_Ropes")]
    public ushort[] M_Ropes { get; set; }  // +0x60
    [JsonPropertyName("m_NodeBases")]
    public FeNodeBase_t[] M_NodeBases { get; set; }  // +0x78
    [JsonPropertyName("m_SimdNodeBases")]
    public FeSimdNodeBase_t[] M_SimdNodeBases { get; set; }  // +0x90
    [JsonPropertyName("m_Quads")]
    public FeQuad_t[] M_Quads { get; set; }  // +0xA8
    [JsonPropertyName("m_SimdQuads")]
    public FeSimdQuad_t[] M_SimdQuads { get; set; }  // +0xC0
    [JsonPropertyName("m_SimdTris")]
    public FeSimdTri_t[] M_SimdTris { get; set; }  // +0xD8
    [JsonPropertyName("m_SimdRods")]
    public FeSimdRodConstraint_t[] M_SimdRods { get; set; }  // +0xF0
    [JsonPropertyName("m_SimdRodsAnim")]
    public FeSimdRodConstraintAnim_t[] M_SimdRodsAnim { get; set; }  // +0x108
    [JsonPropertyName("m_InitPose")]
    public CTransform[] M_InitPose { get; set; }  // +0x120
    [JsonPropertyName("m_Rods")]
    public FeRodConstraint_t[] M_Rods { get; set; }  // +0x138
    [JsonPropertyName("m_Twists")]
    public FeTwistConstraint_t[] M_Twists { get; set; }  // +0x150
    [JsonPropertyName("m_HingeLimits")]
    public FeHingeLimit_t[] M_HingeLimits { get; set; }  // +0x168
    [JsonPropertyName("m_AntiTunnelBytecode")]
    public uint[] M_AntiTunnelBytecode { get; set; }  // +0x180
    [JsonPropertyName("m_DynKinLinks")]
    public FeDynKinLink_t[] M_DynKinLinks { get; set; }  // +0x198
    [JsonPropertyName("m_AntiTunnelProbes")]
    public FeAntiTunnelProbe_t[] M_AntiTunnelProbes { get; set; }  // +0x1B0
    [JsonPropertyName("m_AntiTunnelTargetNodes")]
    public ushort[] M_AntiTunnelTargetNodes { get; set; }  // +0x1C8
    [JsonPropertyName("m_NodeStrayBoxes")]
    public FeNodeStrayBox_t[] M_NodeStrayBoxes { get; set; }  // +0x1E0
    [JsonPropertyName("m_AxialEdges")]
    public FeAxialEdgeBend_t[] M_AxialEdges { get; set; }  // +0x1F8
    [JsonPropertyName("m_NodeInvMasses")]
    public float[] M_NodeInvMasses { get; set; }  // +0x210
    [JsonPropertyName("m_CtrlOffsets")]
    public FeCtrlOffset_t[] M_CtrlOffsets { get; set; }  // +0x228
    [JsonPropertyName("m_CtrlOsOffsets")]
    public FeCtrlOsOffset_t[] M_CtrlOsOffsets { get; set; }  // +0x240
    [JsonPropertyName("m_FollowNodes")]
    public FeFollowNode_t[] M_FollowNodes { get; set; }  // +0x258
    [JsonPropertyName("m_CollisionPlanes")]
    public FeCollisionPlane_t[] M_CollisionPlanes { get; set; }  // +0x270
    [JsonPropertyName("m_NodeIntegrator")]
    public FeNodeIntegrator_t[] M_NodeIntegrator { get; set; }  // +0x288
    [JsonPropertyName("m_SpringIntegrator")]
    public FeSpringIntegrator_t[] M_SpringIntegrator { get; set; }  // +0x2A0
    [JsonPropertyName("m_SimdSpringIntegrator")]
    public FeSimdSpringIntegrator_t[] M_SimdSpringIntegrator { get; set; }  // +0x2B8
    [JsonPropertyName("m_WorldCollisionParams")]
    public FeWorldCollisionParams_t[] M_WorldCollisionParams { get; set; }  // +0x2D0
    [JsonPropertyName("m_LegacyStretchForce")]
    public float[] M_LegacyStretchForce { get; set; }  // +0x2E8
    [JsonPropertyName("m_NodeCollisionRadii")]
    public float[] M_NodeCollisionRadii { get; set; }  // +0x300
    [JsonPropertyName("m_DynNodeFriction")]
    public float[] M_DynNodeFriction { get; set; }  // +0x318
    [JsonPropertyName("m_LocalRotation")]
    public float[] M_LocalRotation { get; set; }  // +0x330
    [JsonPropertyName("m_LocalForce")]
    public float[] M_LocalForce { get; set; }  // +0x348
    [JsonPropertyName("m_TaperedCapsuleStretches")]
    public FeTaperedCapsuleStretch_t[] M_TaperedCapsuleStretches { get; set; }  // +0x360
    [JsonPropertyName("m_TaperedCapsuleRigids")]
    public FeTaperedCapsuleRigid_t[] M_TaperedCapsuleRigids { get; set; }  // +0x378
    [JsonPropertyName("m_SphereRigids")]
    public FeSphereRigid_t[] M_SphereRigids { get; set; }  // +0x390
    [JsonPropertyName("m_WorldCollisionNodes")]
    public ushort[] M_WorldCollisionNodes { get; set; }  // +0x3A8
    [JsonPropertyName("m_TreeParents")]
    public ushort[] M_TreeParents { get; set; }  // +0x3C0
    [JsonPropertyName("m_TreeCollisionMasks")]
    public ushort[] M_TreeCollisionMasks { get; set; }  // +0x3D8
    [JsonPropertyName("m_TreeChildren")]
    public FeTreeChildren_t[] M_TreeChildren { get; set; }  // +0x3F0
    [JsonPropertyName("m_FreeNodes")]
    public ushort[] M_FreeNodes { get; set; }  // +0x408
    [JsonPropertyName("m_FitMatrices")]
    public FeFitMatrix_t[] M_FitMatrices { get; set; }  // +0x420
    [JsonPropertyName("m_FitWeights")]
    public FeFitWeight_t[] M_FitWeights { get; set; }  // +0x438
    [JsonPropertyName("m_ReverseOffsets")]
    public FeNodeReverseOffset_t[] M_ReverseOffsets { get; set; }  // +0x450
    [JsonPropertyName("m_AnimStrayRadii")]
    public FeAnimStrayRadius_t[] M_AnimStrayRadii { get; set; }  // +0x468
    [JsonPropertyName("m_SimdAnimStrayRadii")]
    public FeSimdAnimStrayRadius_t[] M_SimdAnimStrayRadii { get; set; }  // +0x480
    [JsonPropertyName("m_KelagerBends")]
    public FeKelagerBend2_t[] M_KelagerBends { get; set; }  // +0x498
    [JsonPropertyName("m_CtrlSoftOffsets")]
    public FeCtrlSoftOffset_t[] M_CtrlSoftOffsets { get; set; }  // +0x4B0
    [JsonPropertyName("m_JiggleBones")]
    public CFeIndexedJiggleBone[] M_JiggleBones { get; set; }  // +0x4C8
    [JsonPropertyName("m_SourceElems")]
    public ushort[] M_SourceElems { get; set; }  // +0x4E0
    [JsonPropertyName("m_GoalDampedSpringIntegrators")]
    public uint[] M_GoalDampedSpringIntegrators { get; set; }  // +0x4F8
    [JsonPropertyName("m_Tris")]
    public FeTri_t[] M_Tris { get; set; }  // +0x510
    [JsonPropertyName("m_nTriCount1")]
    public ushort M_nTriCount1 { get; set; }  // +0x528
    [JsonPropertyName("m_nTriCount2")]
    public ushort M_nTriCount2 { get; set; }  // +0x52A
    [JsonPropertyName("m_nReservedUint8")]
    public byte M_nReservedUint8 { get; set; }  // +0x52C
    [JsonPropertyName("m_nExtraPressureIterations")]
    public byte M_nExtraPressureIterations { get; set; }  // +0x52D
    [JsonPropertyName("m_nExtraGoalIterations")]
    public byte M_nExtraGoalIterations { get; set; }  // +0x52E
    [JsonPropertyName("m_nExtraIterations")]
    public byte M_nExtraIterations { get; set; }  // +0x52F
    [JsonPropertyName("m_SDFRigids")]
    public FeSDFRigid_t[] M_SDFRigids { get; set; }  // +0x530
    [JsonPropertyName("m_BoxRigids")]
    public FeBoxRigid_t[] M_BoxRigids { get; set; }  // +0x548
    [JsonPropertyName("m_DynNodeVertexSet")]
    public byte[] M_DynNodeVertexSet { get; set; }  // +0x560
    [JsonPropertyName("m_VertexSetNames")]
    public uint[] M_VertexSetNames { get; set; }  // +0x578
    [JsonPropertyName("m_RigidColliderPriorities")]
    public FeRigidColliderIndices_t[] M_RigidColliderPriorities { get; set; }  // +0x590
    [JsonPropertyName("m_MorphLayers")]
    public FeMorphLayerDepr_t[] M_MorphLayers { get; set; }  // +0x5A8
    [JsonPropertyName("m_MorphSetData")]
    public byte[] M_MorphSetData { get; set; }  // +0x5C0
    [JsonPropertyName("m_VertexMaps")]
    public FeVertexMapDesc_t[] M_VertexMaps { get; set; }  // +0x5D8
    [JsonPropertyName("m_VertexMapValues")]
    public byte[] M_VertexMapValues { get; set; }  // +0x5F0
    [JsonPropertyName("m_Effects")]
    public FeEffectDesc_t[] M_Effects { get; set; }  // +0x608
    [JsonPropertyName("m_LockToParent")]
    public FeCtrlOffset_t[] M_LockToParent { get; set; }  // +0x620
    [JsonPropertyName("m_LockToGoal")]
    public ushort[] M_LockToGoal { get; set; }  // +0x638
    [JsonPropertyName("m_SkelParents")]
    public short[] M_SkelParents { get; set; }  // +0x650
    [JsonPropertyName("m_DynNodeWindBases")]
    public FeNodeWindBase_t[] M_DynNodeWindBases { get; set; }  // +0x668
    [JsonPropertyName("m_SelfCollisionLayers")]
    public FeModelSelfCollisionLayer_t[] M_SelfCollisionLayers { get; set; }  // +0x680
    [JsonPropertyName("m_flInternalPressure")]
    public float M_flInternalPressure { get; set; }  // +0x698
    [JsonPropertyName("m_flDefaultTimeDilation")]
    public float M_flDefaultTimeDilation { get; set; }  // +0x69C
    [JsonPropertyName("m_flWindage")]
    public float M_flWindage { get; set; }  // +0x6A0
    [JsonPropertyName("m_flWindDrag")]
    public float M_flWindDrag { get; set; }  // +0x6A4
    [JsonPropertyName("m_flDefaultSurfaceStretch")]
    public float M_flDefaultSurfaceStretch { get; set; }  // +0x6A8
    [JsonPropertyName("m_flDefaultThreadStretch")]
    public float M_flDefaultThreadStretch { get; set; }  // +0x6AC
    [JsonPropertyName("m_flDefaultGravityScale")]
    public float M_flDefaultGravityScale { get; set; }  // +0x6B0
    [JsonPropertyName("m_flDefaultVelAirDrag")]
    public float M_flDefaultVelAirDrag { get; set; }  // +0x6B4
    [JsonPropertyName("m_flDefaultExpAirDrag")]
    public float M_flDefaultExpAirDrag { get; set; }  // +0x6B8
    [JsonPropertyName("m_flDefaultVelQuadAirDrag")]
    public float M_flDefaultVelQuadAirDrag { get; set; }  // +0x6BC
    [JsonPropertyName("m_flDefaultExpQuadAirDrag")]
    public float M_flDefaultExpQuadAirDrag { get; set; }  // +0x6C0
    [JsonPropertyName("m_flRodVelocitySmoothRate")]
    public float M_flRodVelocitySmoothRate { get; set; }  // +0x6C4
    [JsonPropertyName("m_flQuadVelocitySmoothRate")]
    public float M_flQuadVelocitySmoothRate { get; set; }  // +0x6C8
    [JsonPropertyName("m_flAddWorldCollisionRadius")]
    public float M_flAddWorldCollisionRadius { get; set; }  // +0x6CC
    [JsonPropertyName("m_flDefaultVolumetricSolveAmount")]
    public float M_flDefaultVolumetricSolveAmount { get; set; }  // +0x6D0
    [JsonPropertyName("m_flMotionSmoothCDT")]
    public float M_flMotionSmoothCDT { get; set; }  // +0x6D4
    [JsonPropertyName("m_flLocalDrag1")]
    public float M_flLocalDrag1 { get; set; }  // +0x6D8
    [JsonPropertyName("m_nRodVelocitySmoothIterations")]
    public ushort M_nRodVelocitySmoothIterations { get; set; }  // +0x6DC
    [JsonPropertyName("m_nQuadVelocitySmoothIterations")]
    public ushort M_nQuadVelocitySmoothIterations { get; set; }  // +0x6DE
}

/// <summary>RnBlendVertex_t, 16 bytes</summary>
public class RnBlendVertex_t
{
    [JsonPropertyName("m_nWeight0")]
    public ushort M_nWeight0 { get; set; }  // +0x0
    [JsonPropertyName("m_nIndex0")]
    public ushort M_nIndex0 { get; set; }  // +0x2
    [JsonPropertyName("m_nWeight1")]
    public ushort M_nWeight1 { get; set; }  // +0x4
    [JsonPropertyName("m_nIndex1")]
    public ushort M_nIndex1 { get; set; }  // +0x6
    [JsonPropertyName("m_nWeight2")]
    public ushort M_nWeight2 { get; set; }  // +0x8
    [JsonPropertyName("m_nIndex2")]
    public ushort M_nIndex2 { get; set; }  // +0xA
    [JsonPropertyName("m_nFlags")]
    public ushort M_nFlags { get; set; }  // +0xC
    [JsonPropertyName("m_nTargetIndex")]
    public ushort M_nTargetIndex { get; set; }  // +0xE
}

/// <summary>RnBodyDesc_t, 224 bytes</summary>
public class RnBodyDesc_t
{
    [JsonPropertyName("m_sDebugName")]
    public string M_sDebugName { get; set; }  // +0x0
    [JsonPropertyName("m_vPosition")]
    public Vector M_vPosition { get; set; }  // +0x8
    [JsonPropertyName("m_qOrientation")]
    public QuaternionStorage M_qOrientation { get; set; }  // +0x14
    [JsonPropertyName("m_vLinearVelocity")]
    public Vector M_vLinearVelocity { get; set; }  // +0x24
    [JsonPropertyName("m_vAngularVelocity")]
    public Vector M_vAngularVelocity { get; set; }  // +0x30
    [JsonPropertyName("m_vLocalMassCenter")]
    public Vector M_vLocalMassCenter { get; set; }  // +0x3C
    [JsonPropertyName("m_LocalInertiaInv")]
    public Vector[] M_LocalInertiaInv { get; set; }  // +0x48
    [JsonPropertyName("m_flMassInv")]
    public float M_flMassInv { get; set; }  // +0x6C
    [JsonPropertyName("m_flGameMass")]
    public float M_flGameMass { get; set; }  // +0x70
    [JsonPropertyName("m_flMassScaleInv")]
    public float M_flMassScaleInv { get; set; }  // +0x74
    [JsonPropertyName("m_flInertiaScaleInv")]
    public float M_flInertiaScaleInv { get; set; }  // +0x78
    [JsonPropertyName("m_flLinearDamping")]
    public float M_flLinearDamping { get; set; }  // +0x7C
    [JsonPropertyName("m_flAngularDamping")]
    public float M_flAngularDamping { get; set; }  // +0x80
    [JsonPropertyName("m_flLinearDragScale")]
    public float M_flLinearDragScale { get; set; }  // +0x84
    [JsonPropertyName("m_flAngularDragScale")]
    public float M_flAngularDragScale { get; set; }  // +0x88
    [JsonPropertyName("m_flLinearFluidDragScale")]
    public float M_flLinearFluidDragScale { get; set; }  // +0x8C
    [JsonPropertyName("m_flAngularFluidDragScale")]
    public float M_flAngularFluidDragScale { get; set; }  // +0x90
    [JsonPropertyName("m_vLastAwakeForceAccum")]
    public Vector M_vLastAwakeForceAccum { get; set; }  // +0x94
    [JsonPropertyName("m_vLastAwakeTorqueAccum")]
    public Vector M_vLastAwakeTorqueAccum { get; set; }  // +0xA0
    [JsonPropertyName("m_flBuoyancyScale")]
    public float M_flBuoyancyScale { get; set; }  // +0xAC
    [JsonPropertyName("m_flGravityScale")]
    public float M_flGravityScale { get; set; }  // +0xB0
    [JsonPropertyName("m_flTimeScale")]
    public float M_flTimeScale { get; set; }  // +0xB4
    [JsonPropertyName("m_nBodyType")]
    public int M_nBodyType { get; set; }  // +0xB8
    [JsonPropertyName("m_nGameIndex")]
    public uint M_nGameIndex { get; set; }  // +0xBC
    [JsonPropertyName("m_nGameFlags")]
    public uint M_nGameFlags { get; set; }  // +0xC0
    [JsonPropertyName("m_nMinVelocityIterations")]
    public sbyte M_nMinVelocityIterations { get; set; }  // +0xC4
    [JsonPropertyName("m_nMinPositionIterations")]
    public sbyte M_nMinPositionIterations { get; set; }  // +0xC5
    [JsonPropertyName("m_nMassPriority")]
    public sbyte M_nMassPriority { get; set; }  // +0xC6
    [JsonPropertyName("m_bEnabled")]
    public bool M_bEnabled { get; set; }  // +0xC7
    [JsonPropertyName("m_bSleeping")]
    public bool M_bSleeping { get; set; }  // +0xC8
    [JsonPropertyName("m_bIsContinuousEnabled")]
    public bool M_bIsContinuousEnabled { get; set; }  // +0xC9
    [JsonPropertyName("m_bDragEnabled")]
    public bool M_bDragEnabled { get; set; }  // +0xCA
    [JsonPropertyName("m_vGravity")]
    public Vector M_vGravity { get; set; }  // +0xCC
    [JsonPropertyName("m_bSpeculativeEnabled")]
    public bool M_bSpeculativeEnabled { get; set; }  // +0xD8
    [JsonPropertyName("m_bHasShadowController")]
    public bool M_bHasShadowController { get; set; }  // +0xD9
    [JsonPropertyName("m_nDynamicContinuousContactBehavior")]
    public DynamicContinuousContactBehavior_t M_nDynamicContinuousContactBehavior { get; set; }  // +0xDA
}

/// <summary>RnCapsule_t, 28 bytes</summary>
public class RnCapsule_t
{
    [JsonPropertyName("m_vCenter")]
    public Vector[] M_vCenter { get; set; }  // +0x0
    [JsonPropertyName("m_flRadius")]
    public float M_flRadius { get; set; }  // +0x18
}

/// <summary>RnCapsuleDesc_t, 56 bytes</summary>
public class RnCapsuleDesc_t : RnShapeDesc_t
{
    [JsonPropertyName("m_Capsule")]
    public RnCapsule_t M_Capsule { get; set; }  // +0x18
}

/// <summary>RnFace_t, 1 bytes</summary>
public class RnFace_t
{
    [JsonPropertyName("m_nEdge")]
    public byte M_nEdge { get; set; }  // +0x0
}

/// <summary>RnHalfEdge_t, 4 bytes</summary>
public class RnHalfEdge_t
{
    [JsonPropertyName("m_nNext")]
    public byte M_nNext { get; set; }  // +0x0
    [JsonPropertyName("m_nTwin")]
    public byte M_nTwin { get; set; }  // +0x1
    [JsonPropertyName("m_nOrigin")]
    public byte M_nOrigin { get; set; }  // +0x2
    [JsonPropertyName("m_nFace")]
    public byte M_nFace { get; set; }  // +0x3
}

/// <summary>RnHull_t, 248 bytes</summary>
public class RnHull_t
{
    [JsonPropertyName("m_vCentroid")]
    public Vector M_vCentroid { get; set; }  // +0x0
    [JsonPropertyName("m_flMaxAngularRadius")]
    public float M_flMaxAngularRadius { get; set; }  // +0xC
    [JsonPropertyName("m_Bounds")]
    public AABB_t M_Bounds { get; set; }  // +0x10
    [JsonPropertyName("m_vOrthographicAreas")]
    public Vector M_vOrthographicAreas { get; set; }  // +0x28
    [JsonPropertyName("m_MassProperties")]
    public matrix3x4_t M_MassProperties { get; set; }  // +0x34
    [JsonPropertyName("m_flVolume")]
    public float M_flVolume { get; set; }  // +0x64
    [JsonPropertyName("m_flSurfaceArea")]
    public float M_flSurfaceArea { get; set; }  // +0x68
    [JsonPropertyName("m_Vertices")]
    public RnVertex_t[] M_Vertices { get; set; }  // +0x70
    [JsonPropertyName("m_VertexPositions")]
    public Vector[] M_VertexPositions { get; set; }  // +0x88
    [JsonPropertyName("m_Edges")]
    public RnHalfEdge_t[] M_Edges { get; set; }  // +0xA0
    [JsonPropertyName("m_Faces")]
    public RnFace_t[] M_Faces { get; set; }  // +0xB8
    [JsonPropertyName("m_FacePlanes")]
    public RnPlane_t[] M_FacePlanes { get; set; }  // +0xD0
    [JsonPropertyName("m_nFlags")]
    public uint M_nFlags { get; set; }  // +0xE8
    [JsonPropertyName("m_pRegionSVM")]
    public CRegionSVM? M_pRegionSVM { get; set; }  // +0xF0
}

/// <summary>RnHullDesc_t, 272 bytes</summary>
public class RnHullDesc_t : RnShapeDesc_t
{
    [JsonPropertyName("m_Hull")]
    public RnHull_t M_Hull { get; set; }  // +0x18
}

/// <summary>RnMesh_t, 192 bytes</summary>
public class RnMesh_t
{
    [JsonPropertyName("m_vMin")]
    public Vector M_vMin { get; set; }  // +0x0
    [JsonPropertyName("m_vMax")]
    public Vector M_vMax { get; set; }  // +0xC
    [JsonPropertyName("m_Nodes")]
    public RnNode_t[] M_Nodes { get; set; }  // +0x18
    [JsonPropertyName("m_Vertices")]
    public object /* opaque */ M_Vertices { get; set; }  // +0x30
    [JsonPropertyName("m_Triangles")]
    public RnTriangle_t[] M_Triangles { get; set; }  // +0x48
    [JsonPropertyName("m_Wings")]
    public RnWing_t[] M_Wings { get; set; }  // +0x60
    [JsonPropertyName("m_TriangleEdgeFlags")]
    public byte[] M_TriangleEdgeFlags { get; set; }  // +0x78
    [JsonPropertyName("m_Materials")]
    public byte[] M_Materials { get; set; }  // +0x90
    [JsonPropertyName("m_vOrthographicAreas")]
    public Vector M_vOrthographicAreas { get; set; }  // +0xA8
    [JsonPropertyName("m_nFlags")]
    public uint M_nFlags { get; set; }  // +0xB4
    [JsonPropertyName("m_nDebugFlags")]
    public uint M_nDebugFlags { get; set; }  // +0xB8
}

/// <summary>RnMeshDesc_t, 216 bytes</summary>
public class RnMeshDesc_t : RnShapeDesc_t
{
    [JsonPropertyName("m_Mesh")]
    public RnMesh_t M_Mesh { get; set; }  // +0x18
}

/// <summary>RnNode_t, 32 bytes</summary>
public class RnNode_t
{
    [JsonPropertyName("m_vMin")]
    public Vector M_vMin { get; set; }  // +0x0
    [JsonPropertyName("m_nChildren")]
    public uint M_nChildren { get; set; }  // +0xC
    [JsonPropertyName("m_vMax")]
    public Vector M_vMax { get; set; }  // +0x10
    [JsonPropertyName("m_nTriangleOffset")]
    public uint M_nTriangleOffset { get; set; }  // +0x1C
}

/// <summary>RnPlane_t, 16 bytes</summary>
public class RnPlane_t
{
    [JsonPropertyName("m_vNormal")]
    public Vector M_vNormal { get; set; }  // +0x0
    [JsonPropertyName("m_flOffset")]
    public float M_flOffset { get; set; }  // +0xC
}

/// <summary>RnShapeDesc_t, 24 bytes</summary>
public class RnShapeDesc_t
{
    [JsonPropertyName("m_nCollisionAttributeIndex")]
    public uint M_nCollisionAttributeIndex { get; set; }  // +0x0
    [JsonPropertyName("m_nSurfacePropertyIndex")]
    public uint M_nSurfacePropertyIndex { get; set; }  // +0x4
    [JsonPropertyName("m_UserFriendlyName")]
    public string M_UserFriendlyName { get; set; }  // +0x8
    [JsonPropertyName("m_bUserFriendlyNameSealed")]
    public bool M_bUserFriendlyNameSealed { get; set; }  // +0x10
    [JsonPropertyName("m_bUserFriendlyNameLong")]
    public bool M_bUserFriendlyNameLong { get; set; }  // +0x11
    [JsonPropertyName("m_nToolMaterialHash")]
    public uint M_nToolMaterialHash { get; set; }  // +0x14
}

/// <summary>RnSoftbodyCapsule_t, 32 bytes</summary>
public class RnSoftbodyCapsule_t
{
    [JsonPropertyName("m_vCenter")]
    public Vector[] M_vCenter { get; set; }  // +0x0
    [JsonPropertyName("m_flRadius")]
    public float M_flRadius { get; set; }  // +0x18
    [JsonPropertyName("m_nParticle")]
    public ushort[] M_nParticle { get; set; }  // +0x1C
}

/// <summary>RnSoftbodyParticle_t, 4 bytes</summary>
public class RnSoftbodyParticle_t
{
    [JsonPropertyName("m_flMassInv")]
    public float M_flMassInv { get; set; }  // +0x0
}

/// <summary>RnSoftbodySpring_t, 8 bytes</summary>
public class RnSoftbodySpring_t
{
    [JsonPropertyName("m_nParticle")]
    public ushort[] M_nParticle { get; set; }  // +0x0
    [JsonPropertyName("m_flLength")]
    public float M_flLength { get; set; }  // +0x4
}

/// <summary>RnSphereDesc_t, 40 bytes</summary>
public class RnSphereDesc_t : RnShapeDesc_t
{
    [JsonPropertyName("m_Sphere")]
    public object /* opaque */ M_Sphere { get; set; }  // +0x18
}

/// <summary>RnTriangle_t, 12 bytes</summary>
public class RnTriangle_t
{
    [JsonPropertyName("m_nIndex")]
    public int[] M_nIndex { get; set; }  // +0x0
}

/// <summary>RnVertex_t, 1 bytes</summary>
public class RnVertex_t
{
    [JsonPropertyName("m_nEdge")]
    public byte M_nEdge { get; set; }  // +0x0
}

/// <summary>RnWing_t, 12 bytes</summary>
public class RnWing_t
{
    [JsonPropertyName("m_nIndex")]
    public int[] M_nIndex { get; set; }  // +0x0
}

/// <summary>VertexPositionColor_t, 16 bytes</summary>
public class VertexPositionColor_t
{
    [JsonPropertyName("m_vPosition")]
    public Vector M_vPosition { get; set; }  // +0x0
}

/// <summary>VertexPositionNormal_t, 24 bytes</summary>
public class VertexPositionNormal_t
{
    [JsonPropertyName("m_vPosition")]
    public Vector M_vPosition { get; set; }  // +0x0
    [JsonPropertyName("m_vNormal")]
    public Vector M_vNormal { get; set; }  // +0xC
}

