// Auto-generated by cs2-codegen from schemas_jsonschema.json
// Revision 10638965 (May 06 2026) — https://github.com/ValveResourceFormat/DumpSource2
// Do not edit by hand.
// Module: pulsedoc_lib

#nullable enable
#pragma warning disable CS8618  // non-nullable property not initialized (expected in generated serialization types)

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CS2Schema;

/// <summary>CPulseEditorSettings, 496 bytes</summary>
public class CPulseEditorSettings
{
    [JsonPropertyName("m_colCanvasBackground")]
    public Color M_colCanvasBackground { get; set; }  // +0x0
    [JsonPropertyName("m_colCanvasBackgroundWhenDebugging")]
    public Color M_colCanvasBackgroundWhenDebugging { get; set; }  // +0x4
    [JsonPropertyName("m_flGridSnapV2")]
    public float M_flGridSnapV2 { get; set; }  // +0x8
    [JsonPropertyName("m_bSnapAbsToGrid")]
    public bool M_bSnapAbsToGrid { get; set; }  // +0xC
    [JsonPropertyName("m_bSnapSizeToGrid")]
    public bool M_bSnapSizeToGrid { get; set; }  // +0xD
    [JsonPropertyName("m_bGridMinorPoints")]
    public bool M_bGridMinorPoints { get; set; }  // +0xE
    [JsonPropertyName("m_flGridMinorSpacingV2")]
    public float M_flGridMinorSpacingV2 { get; set; }  // +0x10
    [JsonPropertyName("m_flSuppressMinorGridFurtherThan")]
    public float M_flSuppressMinorGridFurtherThan { get; set; }  // +0x14
    [JsonPropertyName("m_colGridMinorColor")]
    public Color M_colGridMinorColor { get; set; }  // +0x18
    [JsonPropertyName("m_flGridMinorWidth")]
    public float M_flGridMinorWidth { get; set; }  // +0x1C
    [JsonPropertyName("m_nGridMajorMultiple")]
    public int M_nGridMajorMultiple { get; set; }  // +0x20
    [JsonPropertyName("m_colGridMajorColor")]
    public Color M_colGridMajorColor { get; set; }  // +0x24
    [JsonPropertyName("m_flGridMajorWidth")]
    public float M_flGridMajorWidth { get; set; }  // +0x28
    [JsonPropertyName("m_colGridOriginColor")]
    public Color M_colGridOriginColor { get; set; }  // +0x2C
    [JsonPropertyName("m_flGridOriginWidth")]
    public float M_flGridOriginWidth { get; set; }  // +0x30
    [JsonPropertyName("m_nFlowTooltipBoxMargin")]
    public float M_nFlowTooltipBoxMargin { get; set; }  // +0x34
    [JsonPropertyName("m_FontSequencePoint")]
    public string M_FontSequencePoint { get; set; }  // +0x38
    [JsonPropertyName("m_flSequencePointRadius")]
    public float M_flSequencePointRadius { get; set; }  // +0x40
    [JsonPropertyName("m_flSequencePointLinkWidth")]
    public float M_flSequencePointLinkWidth { get; set; }  // +0x44
    [JsonPropertyName("m_colSequencePointFadeOverlay")]
    public Color M_colSequencePointFadeOverlay { get; set; }  // +0x48
    [JsonPropertyName("m_colSequencePointSpontaneous")]
    public Color M_colSequencePointSpontaneous { get; set; }  // +0x4C
    [JsonPropertyName("m_colSequencePointYield")]
    public Color M_colSequencePointYield { get; set; }  // +0x50
    [JsonPropertyName("m_colSequencePoint")]
    public Color M_colSequencePoint { get; set; }  // +0x54
    [JsonPropertyName("m_colSequencePointLink")]
    public Color M_colSequencePointLink { get; set; }  // +0x58
    [JsonPropertyName("m_colSequencePointLinkYield")]
    public Color M_colSequencePointLinkYield { get; set; }  // +0x5C
    [JsonPropertyName("m_colSequencePointName")]
    public Color M_colSequencePointName { get; set; }  // +0x60
    [JsonPropertyName("m_colFlowTooltipBorder")]
    public Color M_colFlowTooltipBorder { get; set; }  // +0x64
    [JsonPropertyName("m_colFlowTooltipBackground")]
    public Color M_colFlowTooltipBackground { get; set; }  // +0x68
    [JsonPropertyName("m_colFlowTooltipForeground")]
    public Color M_colFlowTooltipForeground { get; set; }  // +0x6C
    [JsonPropertyName("m_flPortDragOffCreateThreshold")]
    public float M_flPortDragOffCreateThreshold { get; set; }  // +0x70
    [JsonPropertyName("m_colBool")]
    public Color M_colBool { get; set; }  // +0x74
    [JsonPropertyName("m_colNumber")]
    public Color M_colNumber { get; set; }  // +0x78
    [JsonPropertyName("m_colString")]
    public Color M_colString { get; set; }  // +0x7C
    [JsonPropertyName("m_colOther")]
    public Color M_colOther { get; set; }  // +0x80
    [JsonPropertyName("m_colCursorFlow")]
    public Color M_colCursorFlow { get; set; }  // +0x84
    [JsonPropertyName("m_FontFlowTooltip")]
    public string M_FontFlowTooltip { get; set; }  // +0x88
    [JsonPropertyName("m_FontLiteral")]
    public string M_FontLiteral { get; set; }  // +0x90
    [JsonPropertyName("m_FontDomainName")]
    public string M_FontDomainName { get; set; }  // +0x98
    [JsonPropertyName("m_vDomainNameOffsetPX")]
    public Vector2D M_vDomainNameOffsetPX { get; set; }  // +0xA0
    [JsonPropertyName("m_colDomainName")]
    public Color M_colDomainName { get; set; }  // +0xA8
    [JsonPropertyName("m_colDomainNameWhenDebugging")]
    public Color M_colDomainNameWhenDebugging { get; set; }  // +0xAC
    [JsonPropertyName("m_FontParentAssets")]
    public string M_FontParentAssets { get; set; }  // +0xB0
    [JsonPropertyName("m_colParentAssets")]
    public Color M_colParentAssets { get; set; }  // +0xB8
    [JsonPropertyName("m_colParentAssetsBroken")]
    public Color M_colParentAssetsBroken { get; set; }  // +0xBC
    [JsonPropertyName("m_flLiteralLabelSpacing")]
    public float M_flLiteralLabelSpacing { get; set; }  // +0xC0
    [JsonPropertyName("m_colDebuggerBrokenBorder")]
    public Color M_colDebuggerBrokenBorder { get; set; }  // +0xC4
    [JsonPropertyName("m_DebuggerBrokenImg")]
    public string M_DebuggerBrokenImg { get; set; }  // +0xC8
    [JsonPropertyName("m_DebuggerBrokenOtherImg")]
    public string M_DebuggerBrokenOtherImg { get; set; }  // +0xD0
    [JsonPropertyName("m_flDebuggerBrokenMarkerOffset")]
    public float M_flDebuggerBrokenMarkerOffset { get; set; }  // +0xD8
    [JsonPropertyName("m_flDebuggerBrokenMarkerSize")]
    public float M_flDebuggerBrokenMarkerSize { get; set; }  // +0xDC
    [JsonPropertyName("m_DebuggerBreakpointImg")]
    public string M_DebuggerBreakpointImg { get; set; }  // +0xE0
    [JsonPropertyName("m_DebuggerBreakpointDisabledImg")]
    public string M_DebuggerBreakpointDisabledImg { get; set; }  // +0xE8
    [JsonPropertyName("m_flDebuggerBreakpointOffset")]
    public float M_flDebuggerBreakpointOffset { get; set; }  // +0xF0
    [JsonPropertyName("m_flDebuggerBreakpointSize")]
    public float M_flDebuggerBreakpointSize { get; set; }  // +0xF4
    [JsonPropertyName("m_flYieldedCursorStackOffset")]
    public float M_flYieldedCursorStackOffset { get; set; }  // +0xF8
    [JsonPropertyName("m_GraphInstanceImg")]
    public string M_GraphInstanceImg { get; set; }  // +0x100
    [JsonPropertyName("m_flRecentExecTimeoutSec")]
    public float M_flRecentExecTimeoutSec { get; set; }  // +0x108
    [JsonPropertyName("m_flRecentExecStartOffset")]
    public float M_flRecentExecStartOffset { get; set; }  // +0x10C
    [JsonPropertyName("m_flRecentExecEndOffset")]
    public float M_flRecentExecEndOffset { get; set; }  // +0x110
    [JsonPropertyName("m_flRecentExecLineWidth")]
    public float M_flRecentExecLineWidth { get; set; }  // +0x114
    [JsonPropertyName("m_colRecentExecStartColor")]
    public Color M_colRecentExecStartColor { get; set; }  // +0x118
    [JsonPropertyName("m_colRecentExecEndColor")]
    public Color M_colRecentExecEndColor { get; set; }  // +0x11C
    [JsonPropertyName("m_colRecentExecRequirementFailStartColor")]
    public Color M_colRecentExecRequirementFailStartColor { get; set; }  // +0x120
    [JsonPropertyName("m_colRecentExecRequirementFailEndColor")]
    public Color M_colRecentExecRequirementFailEndColor { get; set; }  // +0x124
    [JsonPropertyName("m_flRecentExecConnectionIndicatorSize")]
    public float M_flRecentExecConnectionIndicatorSize { get; set; }  // +0x128
    [JsonPropertyName("m_RecentExecConnectionIndicatorImg")]
    public string M_RecentExecConnectionIndicatorImg { get; set; }  // +0x130
    [JsonPropertyName("m_bBreakOnExceptions")]
    public bool M_bBreakOnExceptions { get; set; }  // +0x138
    [JsonPropertyName("m_bShowExecutionHistory")]
    public bool M_bShowExecutionHistory { get; set; }  // +0x139
    [JsonPropertyName("m_bBoxSelectRequiresFullyContained")]
    public bool M_bBoxSelectRequiresFullyContained { get; set; }  // +0x13A
    [JsonPropertyName("m_flFlowMinWidth")]
    public float M_flFlowMinWidth { get; set; }  // +0x13C
    [JsonPropertyName("m_colSelectedBorder")]
    public Color M_colSelectedBorder { get; set; }  // +0x140
    [JsonPropertyName("m_flAppendButtonSize")]
    public float M_flAppendButtonSize { get; set; }  // +0x144
    [JsonPropertyName("m_colAppendHover")]
    public Color M_colAppendHover { get; set; }  // +0x148
    [JsonPropertyName("m_AppendImg")]
    public string M_AppendImg { get; set; }  // +0x150
    [JsonPropertyName("m_flMoveChildArrowOffset")]
    public float M_flMoveChildArrowOffset { get; set; }  // +0x158
    [JsonPropertyName("m_flMoveChildArrowSize")]
    public float M_flMoveChildArrowSize { get; set; }  // +0x15C
    [JsonPropertyName("m_MoveChildArrowImg")]
    public string M_MoveChildArrowImg { get; set; }  // +0x160
    [JsonPropertyName("m_colMoveChildArrow")]
    public Color M_colMoveChildArrow { get; set; }  // +0x168
    [JsonPropertyName("m_flConnectionTangentStrength")]
    public float M_flConnectionTangentStrength { get; set; }  // +0x16C
    [JsonPropertyName("m_flConnectionCurveSpacing")]
    public float M_flConnectionCurveSpacing { get; set; }  // +0x170
    [JsonPropertyName("m_flConnectionDeltaLimitScale")]
    public float M_flConnectionDeltaLimitScale { get; set; }  // +0x174
    [JsonPropertyName("m_flBrokenConnectionOffset")]
    public float M_flBrokenConnectionOffset { get; set; }  // +0x178
    [JsonPropertyName("m_flConnectionInflowOffset")]
    public float M_flConnectionInflowOffset { get; set; }  // +0x17C
    [JsonPropertyName("m_flConnectionInparamOffset")]
    public float M_flConnectionInparamOffset { get; set; }  // +0x180
    [JsonPropertyName("m_flConnectionInparamOffsetArray")]
    public float M_flConnectionInparamOffsetArray { get; set; }  // +0x184
    [JsonPropertyName("m_flConnectionCapBrokenSize")]
    public float M_flConnectionCapBrokenSize { get; set; }  // +0x188
    [JsonPropertyName("m_ConnectionCapBrokenImg")]
    public string M_ConnectionCapBrokenImg { get; set; }  // +0x190
    [JsonPropertyName("m_flConnectionColorLerpPercentageStart")]
    public float M_flConnectionColorLerpPercentageStart { get; set; }  // +0x198
    [JsonPropertyName("m_vecBlockCommentDefaultSize")]
    public Vector2D M_vecBlockCommentDefaultSize { get; set; }  // +0x19C
    [JsonPropertyName("m_vecBlockCommentMinSize")]
    public Vector2D M_vecBlockCommentMinSize { get; set; }  // +0x1A4
    [JsonPropertyName("m_colBlockCommentDefault")]
    public Color M_colBlockCommentDefault { get; set; }  // +0x1AC
    [JsonPropertyName("m_colBlockCommentTextLight")]
    public Color M_colBlockCommentTextLight { get; set; }  // +0x1B0
    [JsonPropertyName("m_colBlockCommentTextDark")]
    public Color M_colBlockCommentTextDark { get; set; }  // +0x1B4
    [JsonPropertyName("m_flBlockCommentRegionAlpha")]
    public float M_flBlockCommentRegionAlpha { get; set; }  // +0x1B8
    [JsonPropertyName("m_flTimelineSeekBarHeight")]
    public float M_flTimelineSeekBarHeight { get; set; }  // +0x1BC
    [JsonPropertyName("m_flTimelinePauseIconSize")]
    public float M_flTimelinePauseIconSize { get; set; }  // +0x1C0
    [JsonPropertyName("m_flTimelineCallModeIconSize")]
    public float M_flTimelineCallModeIconSize { get; set; }  // +0x1C4
    [JsonPropertyName("m_FontTimelineTime")]
    public string M_FontTimelineTime { get; set; }  // +0x1C8
    [JsonPropertyName("m_colTimelineLabel")]
    public Color M_colTimelineLabel { get; set; }  // +0x1D0
    [JsonPropertyName("m_vecTimelineIconFromPort")]
    public Vector2D M_vecTimelineIconFromPort { get; set; }  // +0x1D4
    [JsonPropertyName("m_vecTimelinePauseIconOffset")]
    public Vector2D M_vecTimelinePauseIconOffset { get; set; }  // +0x1DC
    [JsonPropertyName("m_flTimelineCursorHeight")]
    public float M_flTimelineCursorHeight { get; set; }  // +0x1E4
    [JsonPropertyName("m_flTimelineCursorTextHeight")]
    public float M_flTimelineCursorTextHeight { get; set; }  // +0x1E8
}

/// <summary>GetVarTarget_t, 16 bytes</summary>
public class GetVarTarget_t
{
    [JsonPropertyName("nVarDefID")]
    public PulseDocNodeID_t NVarDefID { get; set; }  // +0x0
    [JsonPropertyName("strValueEncoded")]
    public string StrValueEncoded { get; set; }  // +0x8
}

public enum PulsePortUserVisibility_t : uint
{
    UNSPECIFIED = 0,
    SHOW = 1,
    HIDE = 2,
}

/// <summary>SetVarTarget_t, 16 bytes</summary>
public class SetVarTarget_t
{
    [JsonPropertyName("nVarDefID")]
    public PulseDocNodeID_t NVarDefID { get; set; }  // +0x0
    [JsonPropertyName("strValueEncoded")]
    public string StrValueEncoded { get; set; }  // +0x8
}

