// Auto-generated by cs2-codegen from schemas_jsonschema.json
// Revision 10638965 (May 06 2026) — https://github.com/ValveResourceFormat/DumpSource2
// Do not edit by hand.
// Module: qcontrols

#nullable enable
#pragma warning disable CS8618  // non-nullable property not initialized (expected in generated serialization types)

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CS2Schema;

public enum GraphCanvasBackgroundImageSize_t : uint
{
    Natural = 0,
    Contain = 1,
    Cover = 2,
    Stretch = 3,
}

public enum GraphCanvasBackgroundPosition_t : uint
{
    Top = 0,
    Left = 0,
    Center = 1,
    Bottom = 2,
    Right = 2,
}

public enum GraphCanvasBackgroundRepeat_t : uint
{
    Repeat = 0,
    NoRepeat = 1,
    RepeatX = 2,
    RepeatY = 3,
}

public enum GraphCanvasBorderDrawBehavior_t : uint
{
    Centered = 0,
    Inside = 1,
    Outside = 2,
}

public enum GraphCanvasChildLayoutAlgorithm_t : uint
{
    DEFAULT = 0,
    VBOX = 1,
    VBOX_REVERSE = 2,
    HBOX = 3,
    HBOX_REVERSE = 4,
}

public enum GraphCanvasHAlign_t : uint
{
    LEFT = 0,
    CENTER = 1,
    RIGHT = 2,
    STRETCH = 3,
}

public enum GraphCanvasInteractionPriority_t : uint
{
    NONINTERACTIVE = 4294957297,
    GROUP = 0,
    BASE = 1,
    DRAG_HANDLE = 2,
    RESIZE_EDGE = 3,
    RESIZE_CORNER = 4,
    ADD_FLOW = 5,
    PORT = 6,
    ANCHOR = 7,
}

public enum GraphCanvasItemHoverBehavior_t : uint
{
    HOVER_PROPAGATE = 0,
    HOVER_STOP_PROPAGATION = 1,
}

public enum GraphCanvasPositioning_t : uint
{
    AUTO = 0,
    INSIDE_PARENT = 1,
    OUTSIDE_PARENT = 2,
    ON_PARENT_BORDER = 3,
}

public enum GraphCanvasPseudoClass_t : uint
{
    INVALID = 0,
    FIRST_CHILD = 1,
    LAST_CHILD = 2,
    NTH_CHILD = 3,
    NTH_LAST_CHILD = 4,
    ONLY_CHILD = 5,
    HOVER_ANCESTOR = 6,
    HOVER_DESCENDANT = 7,
    HOVER_CUSTOM_A = 8,
    HOVER_CUSTOM_B = 9,
    HOVER_CUSTOM_C = 10,
    SELECTED = 11,
    HOVER_SELF = 12,
}

public enum GraphCanvasRenderLayer_t : uint
{
    INVALID = 4294967295,
    COMMENTS = 0,
    CONNECTIONS_BACKGROUND = 1,
    GROUP_BACKGROUND = 2,
    DEFAULT = 3,
    NODES = 4,
    CONNECTIONS_FOREGROUND = 5,
    COMMENT_OVERLAY = 6,
    SELECTION_OVERLAY = 7,
    HOVER_OVERLAY = 8,
    STANDARD_LAYER_COUNT = 9,
    SPECIAL_DEBUGGER_OVERLAY = 10,
    SPECIAL_LAYER_HOVER_TOOLTIP = 11,
}

public enum GraphCanvasTextClipMode_t : uint
{
    EXPAND_ITEM = 0,
    CLIP_TEXT = 1,
    ELIDE_TEXT_END = 2,
    WORD_WRAP = 3,
}

public enum GraphCanvasVAlign_t : uint
{
    TOP = 0,
    CENTER = 1,
    BOTTOM = 2,
    STRETCH = 3,
}

public enum GraphCanvasVisibilityState_t : uint
{
    VISIBLE = 0,
    HIDDEN = 1,
    COLLAPSE = 2,
}

public enum LayoutAxis_t : uint
{
    X = 0,
    Y = 1,
}

