// Auto-generated by cs2-codegen from schemas_jsonschema.json
// Revision 10638965 (May 06 2026) — https://github.com/ValveResourceFormat/DumpSource2
// Do not edit by hand.
// Module: rendersystemdx11

#nullable enable
#pragma warning disable CS8618  // non-nullable property not initialized (expected in generated serialization types)

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CS2Schema;

/// <summary>RsBlendStateDesc_t, 32 bytes</summary>
public class RsBlendStateDesc_t
{
    [JsonPropertyName("m_srcBlendBits")]
    public uint M_srcBlendBits { get; set; }  // +0x0
    [JsonPropertyName("m_destBlendBits")]
    public uint M_destBlendBits { get; set; }  // +0x4
    [JsonPropertyName("m_srcBlendAlphaBits")]
    public uint M_srcBlendAlphaBits { get; set; }  // +0x8
    [JsonPropertyName("m_destBlendAlphaBits")]
    public uint M_destBlendAlphaBits { get; set; }  // +0xC
    [JsonPropertyName("m_renderTargetWriteMaskBits")]
    public uint M_renderTargetWriteMaskBits { get; set; }  // +0x10
    [JsonPropertyName("m_blendOpBits")]
    public int M_blendOpBits { get; set; }  // +0x0
    [JsonPropertyName("m_bAlphaToCoverageEnable")]
    public int M_bAlphaToCoverageEnable { get; set; }  // +0x0
    [JsonPropertyName("m_bIndependentBlendEnable")]
    public int M_bIndependentBlendEnable { get; set; }  // +0x0
    [JsonPropertyName("m_blendOpAlphaBits")]
    public uint M_blendOpAlphaBits { get; set; }  // +0x18
    [JsonPropertyName("m_blendEnableBits")]
    public byte M_blendEnableBits { get; set; }  // +0x1C
    [JsonPropertyName("m_srgbWriteEnableBits")]
    public byte M_srgbWriteEnableBits { get; set; }  // +0x1D
}

public enum RsComparison_t : byte
{
    RS_CMP_NEVER = 0,
    RS_CMP_LESS = 1,
    RS_CMP_EQUAL = 2,
    RS_CMP_LESS_EQUAL = 3,
    RS_CMP_GREATER = 4,
    RS_CMP_NOT_EQUAL = 5,
    RS_CMP_GREATER_EQUAL = 6,
    RS_CMP_ALWAYS = 7,
}

public enum RsCullMode_t : byte
{
    RS_CULL_NONE = 0,
    RS_CULL_BACK = 1,
    RS_CULL_FRONT = 2,
}

/// <summary>RsDepthStencilStateDesc_t, 8 bytes</summary>
public class RsDepthStencilStateDesc_t
{
    [JsonPropertyName("m_bDepthTestEnable")]
    public int M_bDepthTestEnable { get; set; }  // +0x0
    [JsonPropertyName("m_bDepthWriteEnable")]
    public int M_bDepthWriteEnable { get; set; }  // +0x0
    [JsonPropertyName("m_depthFunc")]
    public RsComparison_t M_depthFunc { get; set; }  // +0x1
    [JsonPropertyName("m_stencilState")]
    public RsStencilStateDesc_t M_stencilState { get; set; }  // +0x2
}

public enum RsFillMode_t : byte
{
    RS_FILL_SOLID = 0,
    RS_FILL_WIREFRAME = 1,
}

/// <summary>RsRasterizerStateDesc_t, 16 bytes</summary>
public class RsRasterizerStateDesc_t
{
    [JsonPropertyName("m_nFillMode")]
    public RsFillMode_t M_nFillMode { get; set; }  // +0x0
    [JsonPropertyName("m_nCullMode")]
    public RsCullMode_t M_nCullMode { get; set; }  // +0x1
    [JsonPropertyName("m_bDepthClipEnable")]
    public bool M_bDepthClipEnable { get; set; }  // +0x2
    [JsonPropertyName("m_bMultisampleEnable")]
    public bool M_bMultisampleEnable { get; set; }  // +0x3
    [JsonPropertyName("m_nDepthBias")]
    public int M_nDepthBias { get; set; }  // +0x4
    [JsonPropertyName("m_flDepthBiasClamp")]
    public float M_flDepthBiasClamp { get; set; }  // +0x8
    [JsonPropertyName("m_flSlopeScaledDepthBias")]
    public float M_flSlopeScaledDepthBias { get; set; }  // +0xC
}

/// <summary>RsStencilStateDesc_t, 6 bytes</summary>
public class RsStencilStateDesc_t
{
    [JsonPropertyName("m_bStencilEnable")]
    public int M_bStencilEnable { get; set; }  // +0x0
    [JsonPropertyName("m_frontStencilFailOp")]
    public int M_frontStencilFailOp { get; set; }  // +0x0
    [JsonPropertyName("m_frontStencilDepthFailOp")]
    public int M_frontStencilDepthFailOp { get; set; }  // +0x0
    [JsonPropertyName("m_frontStencilPassOp")]
    public int M_frontStencilPassOp { get; set; }  // +0x0
    [JsonPropertyName("m_frontStencilFunc")]
    public int M_frontStencilFunc { get; set; }  // +0x0
    [JsonPropertyName("m_backStencilFailOp")]
    public int M_backStencilFailOp { get; set; }  // +0x0
    [JsonPropertyName("m_backStencilDepthFailOp")]
    public int M_backStencilDepthFailOp { get; set; }  // +0x0
    [JsonPropertyName("m_backStencilPassOp")]
    public int M_backStencilPassOp { get; set; }  // +0x0
    [JsonPropertyName("m_backStencilFunc")]
    public int M_backStencilFunc { get; set; }  // +0x0
    [JsonPropertyName("m_nStencilReadMask")]
    public byte M_nStencilReadMask { get; set; }  // +0x4
    [JsonPropertyName("m_nStencilWriteMask")]
    public byte M_nStencilWriteMask { get; set; }  // +0x5
}

