// Auto-generated by cs2-codegen from schemas_jsonschema.json
// Revision 10638965 (May 06 2026) — https://github.com/ValveResourceFormat/DumpSource2
// Do not edit by hand.
// Module: resourcefile

#nullable enable
#pragma warning disable CS8618  // non-nullable property not initialized (expected in generated serialization types)

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CS2Schema;

/// <summary>CExampleSchemaVData_Monomorphic, 8 bytes</summary>
public class CExampleSchemaVData_Monomorphic
{
    [JsonPropertyName("m_nExample1")]
    public int M_nExample1 { get; set; }  // +0x0
    [JsonPropertyName("m_nExample2")]
    public int M_nExample2 { get; set; }  // +0x4
}

/// <summary>CExampleSchemaVData_PolymorphicBase, 16 bytes</summary>
public class CExampleSchemaVData_PolymorphicBase
{
    [JsonPropertyName("m_nBase")]
    public int M_nBase { get; set; }  // +0x8
}

/// <summary>CExampleSchemaVData_PolymorphicDerivedA, 24 bytes</summary>
public class CExampleSchemaVData_PolymorphicDerivedA : CExampleSchemaVData_PolymorphicBase
{
    [JsonPropertyName("m_nDerivedA")]
    public int M_nDerivedA { get; set; }  // +0x10
}

/// <summary>CExampleSchemaVData_PolymorphicDerivedB, 24 bytes</summary>
public class CExampleSchemaVData_PolymorphicDerivedB : CExampleSchemaVData_PolymorphicBase
{
    [JsonPropertyName("m_nDerivedB")]
    public int M_nDerivedB { get; set; }  // +0x10
}

/// <summary>InfoForResourceTypeCResourceManifestInternal, 1 bytes</summary>
public class InfoForResourceTypeCResourceManifestInternal
{
}

/// <summary>ResourceId_t, 8 bytes</summary>
public class ResourceId_t
{
    [JsonPropertyName("m_Value")]
    public ulong M_Value { get; set; }  // +0x0
}

