// Auto-generated by cs2-codegen from schemas_jsonschema.json
// Revision 10638965 (May 06 2026) — https://github.com/ValveResourceFormat/DumpSource2
// Do not edit by hand.
// Module: resourcecompiler

#nullable enable
#pragma warning disable CS8618  // non-nullable property not initialized (expected in generated serialization types)

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CS2Schema;

/// <summary>CBloomLayer, 176 bytes</summary>
public class CBloomLayer : CColorCorrectionLayer
{
    [JsonPropertyName("m_params")]
    public PostProcessingBloomParameters_t M_params { get; set; }  // +0x28
}

/// <summary>CBrightnessContrastColorCorrectionLayer, 48 bytes</summary>
public class CBrightnessContrastColorCorrectionLayer : CColorCorrectionLayer
{
    [JsonPropertyName("m_nBrightness")]
    public int M_nBrightness { get; set; }  // +0x28
    [JsonPropertyName("m_nContrast")]
    public int M_nContrast { get; set; }  // +0x2C
}

/// <summary>CColorBalanceColorCorrectionLayer, 80 bytes</summary>
public class CColorBalanceColorCorrectionLayer : CColorCorrectionLayer
{
    [JsonPropertyName("m_nRedCyanBalS")]
    public int M_nRedCyanBalS { get; set; }  // +0x28
    [JsonPropertyName("m_nRedCyanBalM")]
    public int M_nRedCyanBalM { get; set; }  // +0x2C
    [JsonPropertyName("m_nRedCyanBalH")]
    public int M_nRedCyanBalH { get; set; }  // +0x30
    [JsonPropertyName("m_nGreenMagentaBalS")]
    public int M_nGreenMagentaBalS { get; set; }  // +0x34
    [JsonPropertyName("m_nGreenMagentaBalM")]
    public int M_nGreenMagentaBalM { get; set; }  // +0x38
    [JsonPropertyName("m_nGreenMagentaBalH")]
    public int M_nGreenMagentaBalH { get; set; }  // +0x3C
    [JsonPropertyName("m_nBlueYellowBalS")]
    public int M_nBlueYellowBalS { get; set; }  // +0x40
    [JsonPropertyName("m_nBlueYellowBalM")]
    public int M_nBlueYellowBalM { get; set; }  // +0x44
    [JsonPropertyName("m_nBlueYellowBalH")]
    public int M_nBlueYellowBalH { get; set; }  // +0x48
    [JsonPropertyName("m_bPreserveLuminosity")]
    public bool M_bPreserveLuminosity { get; set; }  // +0x4C
}

/// <summary>CColorCorrectionLayer, 40 bytes</summary>
public class CColorCorrectionLayer
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x8
    [JsonPropertyName("m_nOpacityPercent")]
    public int M_nOpacityPercent { get; set; }  // +0x10
    [JsonPropertyName("m_bVisible")]
    public bool M_bVisible { get; set; }  // +0x14
    [JsonPropertyName("m_pLayerMask")]
    public CLayerMask? M_pLayerMask { get; set; }  // +0x18
}

/// <summary>CColorLookupColorCorrectionLayer, 80 bytes</summary>
public class CColorLookupColorCorrectionLayer : CColorCorrectionLayer
{
    [JsonPropertyName("m_fileName")]
    public string M_fileName { get; set; }  // +0x28
    [JsonPropertyName("m_lut")]
    public float[] M_lut { get; set; }  // +0x30
    [JsonPropertyName("m_nDim")]
    public int M_nDim { get; set; }  // +0x48
}

/// <summary>CColorTintColorCorrectionLayer, 64 bytes</summary>
public class CColorTintColorCorrectionLayer : CColorCorrectionLayer
{
    [JsonPropertyName("m_nTintColorR")]
    public int M_nTintColorR { get; set; }  // +0x28
    [JsonPropertyName("m_nTintColorG")]
    public int M_nTintColorG { get; set; }  // +0x2C
    [JsonPropertyName("m_nTintColorB")]
    public int M_nTintColorB { get; set; }  // +0x30
    [JsonPropertyName("m_nStrength")]
    public int M_nStrength { get; set; }  // +0x34
    [JsonPropertyName("m_bPreserveLuminosity")]
    public bool M_bPreserveLuminosity { get; set; }  // +0x38
}

/// <summary>CCurvesColorCorrectionLayer, 232 bytes</summary>
public class CCurvesColorCorrectionLayer : CColorCorrectionLayer
{
    [JsonPropertyName("m_curvePointsRGB")]
    public Vector2D[] M_curvePointsRGB { get; set; }  // +0x28
    [JsonPropertyName("m_curvePointsR")]
    public Vector2D[] M_curvePointsR { get; set; }  // +0x40
    [JsonPropertyName("m_curvePointsG")]
    public Vector2D[] M_curvePointsG { get; set; }  // +0x58
    [JsonPropertyName("m_curvePointsB")]
    public Vector2D[] M_curvePointsB { get; set; }  // +0x70
}

/// <summary>CFogScatteringLayer, 64 bytes</summary>
public class CFogScatteringLayer : CColorCorrectionLayer
{
    [JsonPropertyName("m_params")]
    public PostProcessingFogScatteringParameters_t M_params { get; set; }  // +0x28
}

/// <summary>CHueSaturationColorCorrectionLayer, 128 bytes</summary>
public class CHueSaturationColorCorrectionLayer : CColorCorrectionLayer
{
    [JsonPropertyName("m_nHueMaster")]
    public int M_nHueMaster { get; set; }  // +0x28
    [JsonPropertyName("m_nHueRed")]
    public int M_nHueRed { get; set; }  // +0x2C
    [JsonPropertyName("m_nHueYellow")]
    public int M_nHueYellow { get; set; }  // +0x30
    [JsonPropertyName("m_nHueGreen")]
    public int M_nHueGreen { get; set; }  // +0x34
    [JsonPropertyName("m_nHueCyan")]
    public int M_nHueCyan { get; set; }  // +0x38
    [JsonPropertyName("m_nHueBlue")]
    public int M_nHueBlue { get; set; }  // +0x3C
    [JsonPropertyName("m_nHueMagenta")]
    public int M_nHueMagenta { get; set; }  // +0x40
    [JsonPropertyName("m_nSaturationMaster")]
    public int M_nSaturationMaster { get; set; }  // +0x44
    [JsonPropertyName("m_nSaturationRed")]
    public int M_nSaturationRed { get; set; }  // +0x48
    [JsonPropertyName("m_nSaturationYellow")]
    public int M_nSaturationYellow { get; set; }  // +0x4C
    [JsonPropertyName("m_nSaturationGreen")]
    public int M_nSaturationGreen { get; set; }  // +0x50
    [JsonPropertyName("m_nSaturationCyan")]
    public int M_nSaturationCyan { get; set; }  // +0x54
    [JsonPropertyName("m_nSaturationBlue")]
    public int M_nSaturationBlue { get; set; }  // +0x58
    [JsonPropertyName("m_nSaturationMagenta")]
    public int M_nSaturationMagenta { get; set; }  // +0x5C
    [JsonPropertyName("m_nBrightnessMaster")]
    public int M_nBrightnessMaster { get; set; }  // +0x60
    [JsonPropertyName("m_nBrightnessRed")]
    public int M_nBrightnessRed { get; set; }  // +0x64
    [JsonPropertyName("m_nBrightnessYellow")]
    public int M_nBrightnessYellow { get; set; }  // +0x68
    [JsonPropertyName("m_nBrightnessGreen")]
    public int M_nBrightnessGreen { get; set; }  // +0x6C
    [JsonPropertyName("m_nBrightnessCyan")]
    public int M_nBrightnessCyan { get; set; }  // +0x70
    [JsonPropertyName("m_nBrightnessBlue")]
    public int M_nBrightnessBlue { get; set; }  // +0x74
    [JsonPropertyName("m_nBrightnessMagenta")]
    public int M_nBrightnessMagenta { get; set; }  // +0x78
}

/// <summary>CLayerMask, 24 bytes</summary>
public class CLayerMask
{
    [JsonPropertyName("m_nLumMaskCenter")]
    public int M_nLumMaskCenter { get; set; }  // +0x8
    [JsonPropertyName("m_nLumMaskWidth")]
    public int M_nLumMaskWidth { get; set; }  // +0xC
    [JsonPropertyName("m_nLumMaskShape")]
    public int M_nLumMaskShape { get; set; }  // +0x10
    [JsonPropertyName("m_bInverted")]
    public bool M_bInverted { get; set; }  // +0x14
}

/// <summary>CLevelsColorCorrectionLayer, 120 bytes</summary>
public class CLevelsColorCorrectionLayer : CColorCorrectionLayer
{
    [JsonPropertyName("m_nInputBlackPointRGB")]
    public int M_nInputBlackPointRGB { get; set; }  // +0x28
    [JsonPropertyName("m_nInputBlackPointR")]
    public int M_nInputBlackPointR { get; set; }  // +0x2C
    [JsonPropertyName("m_nInputBlackPointG")]
    public int M_nInputBlackPointG { get; set; }  // +0x30
    [JsonPropertyName("m_nInputBlackPointB")]
    public int M_nInputBlackPointB { get; set; }  // +0x34
    [JsonPropertyName("m_nInputWhitePointRGB")]
    public int M_nInputWhitePointRGB { get; set; }  // +0x38
    [JsonPropertyName("m_nInputWhitePointR")]
    public int M_nInputWhitePointR { get; set; }  // +0x3C
    [JsonPropertyName("m_nInputWhitePointG")]
    public int M_nInputWhitePointG { get; set; }  // +0x40
    [JsonPropertyName("m_nInputWhitePointB")]
    public int M_nInputWhitePointB { get; set; }  // +0x44
    [JsonPropertyName("m_nOutputBlackPointRGB")]
    public int M_nOutputBlackPointRGB { get; set; }  // +0x48
    [JsonPropertyName("m_nOutputBlackPointR")]
    public int M_nOutputBlackPointR { get; set; }  // +0x4C
    [JsonPropertyName("m_nOutputBlackPointG")]
    public int M_nOutputBlackPointG { get; set; }  // +0x50
    [JsonPropertyName("m_nOutputBlackPointB")]
    public int M_nOutputBlackPointB { get; set; }  // +0x54
    [JsonPropertyName("m_nOutputWhitePointRGB")]
    public int M_nOutputWhitePointRGB { get; set; }  // +0x58
    [JsonPropertyName("m_nOutputWhitePointR")]
    public int M_nOutputWhitePointR { get; set; }  // +0x5C
    [JsonPropertyName("m_nOutputWhitePointG")]
    public int M_nOutputWhitePointG { get; set; }  // +0x60
    [JsonPropertyName("m_nOutputWhitePointB")]
    public int M_nOutputWhitePointB { get; set; }  // +0x64
    [JsonPropertyName("m_flGammaRGB")]
    public float M_flGammaRGB { get; set; }  // +0x68
    [JsonPropertyName("m_flGammaR")]
    public float M_flGammaR { get; set; }  // +0x6C
    [JsonPropertyName("m_flGammaG")]
    public float M_flGammaG { get; set; }  // +0x70
    [JsonPropertyName("m_flGammaB")]
    public float M_flGammaB { get; set; }  // +0x74
}

/// <summary>CLocalContrastLayer, 64 bytes</summary>
public class CLocalContrastLayer : CColorCorrectionLayer
{
    [JsonPropertyName("m_params")]
    public PostProcessingLocalContrastParameters_t M_params { get; set; }  // +0x28
}

/// <summary>CPostProcessData, 32 bytes</summary>
public class CPostProcessData
{
    [JsonPropertyName("m_layers")]
    public CColorCorrectionLayer?[] M_layers { get; set; }  // +0x8
}

/// <summary>CToneMappingLayer, 104 bytes</summary>
public class CToneMappingLayer : CColorCorrectionLayer
{
    [JsonPropertyName("m_params")]
    public PostProcessingTonemapParameters_t M_params { get; set; }  // +0x28
}

/// <summary>CVibranceColorCorrectionLayer, 48 bytes</summary>
public class CVibranceColorCorrectionLayer : CColorCorrectionLayer
{
    [JsonPropertyName("m_nVibrance")]
    public int M_nVibrance { get; set; }  // +0x28
    [JsonPropertyName("m_nSaturation")]
    public int M_nSaturation { get; set; }  // +0x2C
}

/// <summary>CVignetteLayer, 80 bytes</summary>
public class CVignetteLayer : CColorCorrectionLayer
{
    [JsonPropertyName("m_params")]
    public PostProcessingVignetteParameters_t M_params { get; set; }  // +0x28
}

public enum LayerMaskType_t : uint
{
    LAYER_MASK_LUMINOSITY = 0,
    LAYER_MASK_COLOR_RANGE = 1,
}

public enum LayerType_t : uint
{
    LAYER_TYPE_LEVELS = 0,
    LAYER_TYPE_VIBRANCE = 1,
    LAYER_TYPE_BRIGHTNESS_CONTRAST = 2,
    LAYER_TYPE_LUT = 3,
    LAYER_TYPE_COLOR_BALANCE = 4,
    LAYER_TYPE_COLOR_TINT = 5,
    LAYER_TYPE_HUE_SATURATION = 6,
    LAYER_TYPE_CURVES = 7,
    LAYER_TYPE_TONEMAPPING = 8,
    LAYER_TYPE_BLOOM = 9,
    LAYER_TYPE_VIGNETTE = 10,
    LAYER_TYPE_LOCAL_CONTRAST = 11,
    LAYER_TYPE_FOG_SCATTERING = 12,
    MAX_LAYER_TYPES = 13,
}

