// Auto-generated by cs2-codegen from schemas_jsonschema.json
// Revision 10638965 (May 06 2026) — https://github.com/ValveResourceFormat/DumpSource2
// Do not edit by hand.
// Module: schemasystem

#nullable enable
#pragma warning disable CS8618  // non-nullable property not initialized (expected in generated serialization types)

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CS2Schema;

/// <summary>CSchemaSystemInternalRegistration, 384 bytes</summary>
public class CSchemaSystemInternalRegistration
{
    [JsonPropertyName("m_Vector2D")]
    public Vector2D M_Vector2D { get; set; }  // +0x0
    [JsonPropertyName("m_Vector")]
    public Vector M_Vector { get; set; }  // +0x8
    [JsonPropertyName("m_VectorWS")]
    public VectorWS M_VectorWS { get; set; }  // +0x14
    [JsonPropertyName("m_VectorAligned")]
    public VectorAligned M_VectorAligned { get; set; }  // +0x20
    [JsonPropertyName("m_Quaternion")]
    public Quaternion M_Quaternion { get; set; }  // +0x30
    [JsonPropertyName("m_QAngle")]
    public QAngle M_QAngle { get; set; }  // +0x40
    [JsonPropertyName("m_RotationVector")]
    public RotationVector M_RotationVector { get; set; }  // +0x4C
    [JsonPropertyName("m_RadianEuler")]
    public RadianEuler M_RadianEuler { get; set; }  // +0x58
    [JsonPropertyName("m_DegreeEuler")]
    public DegreeEuler M_DegreeEuler { get; set; }  // +0x64
    [JsonPropertyName("m_QuaternionStorage")]
    public QuaternionStorage M_QuaternionStorage { get; set; }  // +0x70
    [JsonPropertyName("m_matrix3x4_t")]
    public matrix3x4_t M_matrix3x4_t { get; set; }  // +0x80
    [JsonPropertyName("m_matrix3x4a_t")]
    public matrix3x4a_t M_matrix3x4a_t { get; set; }  // +0xB0
    [JsonPropertyName("m_Color")]
    public Color M_Color { get; set; }  // +0xE0
    [JsonPropertyName("m_Vector4D")]
    public Vector4D M_Vector4D { get; set; }  // +0xE4
    [JsonPropertyName("m_CTransform")]
    public CTransform M_CTransform { get; set; }  // +0x100
    [JsonPropertyName("m_pKeyValues")]
    public object /* opaque */? M_pKeyValues { get; set; }  // +0x120
    [JsonPropertyName("m_CUtlBinaryBlock")]
    public object /* opaque */ M_CUtlBinaryBlock { get; set; }  // +0x128
    [JsonPropertyName("m_CUtlString")]
    public string M_CUtlString { get; set; }  // +0x138
    [JsonPropertyName("m_CUtlSymbol")]
    public string M_CUtlSymbol { get; set; }  // +0x140
    [JsonPropertyName("m_stringToken")]
    public string M_stringToken { get; set; }  // +0x144
    [JsonPropertyName("m_stringTokenWithStorage")]
    public string M_stringTokenWithStorage { get; set; }  // +0x148
    [JsonPropertyName("m_ResourceTypes")]
    public string M_ResourceTypes { get; set; }  // +0x160
    [JsonPropertyName("m_KV3")]
    public object /* opaque */ M_KV3 { get; set; }  // +0x168
}

public enum fieldtype_t : byte
{
    FIELD_VOID = 0,
    FIELD_FLOAT32 = 1,
    FIELD_STRING = 2,
    FIELD_VECTOR = 3,
    FIELD_QUATERNION = 4,
    FIELD_INT32 = 5,
    FIELD_BOOLEAN = 6,
    FIELD_INT16 = 7,
    FIELD_CHARACTER = 8,
    FIELD_COLOR32 = 9,
    FIELD_EMBEDDED = 10,
    FIELD_CUSTOM = 11,
    FIELD_CLASSPTR = 12,
    FIELD_EHANDLE = 13,
    FIELD_POSITION_VECTOR = 14,
    FIELD_TIME = 15,
    FIELD_TICK = 16,
    FIELD_SOUNDNAME = 17,
    FIELD_INPUT = 18,
    FIELD_FUNCTION = 19,
    FIELD_VMATRIX = 20,
    FIELD_VMATRIX_WORLDSPACE = 21,
    FIELD_MATRIX3X4_WORLDSPACE = 22,
    FIELD_INTERVAL = 23,
    FIELD_UNUSED = 24,
    FIELD_VECTOR2D = 25,
    FIELD_INT64 = 26,
    FIELD_VECTOR4D = 27,
    FIELD_RESOURCE = 28,
    FIELD_TYPEUNKNOWN = 29,
    FIELD_CSTRING = 30,
    FIELD_HSCRIPT = 31,
    FIELD_VARIANT = 32,
    FIELD_UINT64 = 33,
    FIELD_FLOAT64 = 34,
    FIELD_POSITIVEINTEGER_OR_NULL = 35,
    FIELD_HSCRIPT_NEW_INSTANCE = 36,
    FIELD_UINT32 = 37,
    FIELD_UTLSTRINGTOKEN = 38,
    FIELD_QANGLE = 39,
    FIELD_NETWORK_ORIGIN_CELL_QUANTIZED_VECTOR = 40,
    FIELD_HMATERIAL = 41,
    FIELD_HMODEL = 42,
    FIELD_NETWORK_QUANTIZED_VECTOR = 43,
    FIELD_NETWORK_QUANTIZED_FLOAT = 44,
    FIELD_DIRECTION_VECTOR_WORLDSPACE = 45,
    FIELD_QANGLE_WORLDSPACE = 46,
    FIELD_QUATERNION_WORLDSPACE = 47,
    FIELD_HSCRIPT_LIGHTBINDING = 48,
    FIELD_V8_VALUE = 49,
    FIELD_V8_OBJECT = 50,
    FIELD_V8_ARRAY = 51,
    FIELD_V8_CALLBACK_INFO = 52,
    FIELD_UTLSTRING = 53,
    FIELD_NETWORK_ORIGIN_CELL_QUANTIZED_POSITION_VECTOR = 54,
    FIELD_HRENDERTEXTURE = 55,
    FIELD_HPARTICLESYSTEMDEFINITION = 56,
    FIELD_UINT8 = 57,
    FIELD_UINT16 = 58,
    FIELD_CTRANSFORM = 59,
    FIELD_CTRANSFORM_WORLDSPACE = 60,
    FIELD_HPOSTPROCESSING = 61,
    FIELD_MATRIX3X4 = 62,
    FIELD_SHIM = 63,
    FIELD_CMOTIONTRANSFORM = 64,
    FIELD_CMOTIONTRANSFORM_WORLDSPACE = 65,
    FIELD_ATTACHMENT_HANDLE = 66,
    FIELD_AMMO_INDEX = 67,
    FIELD_CONDITION_ID = 68,
    FIELD_AI_SCHEDULE_BITS = 69,
    FIELD_MODIFIER_HANDLE = 70,
    FIELD_ROTATION_VECTOR = 71,
    FIELD_ROTATION_VECTOR_WORLDSPACE = 72,
    FIELD_HVDATA = 73,
    FIELD_SCALE32 = 74,
    FIELD_STRING_AND_TOKEN = 75,
    FIELD_ENGINE_TIME = 76,
    FIELD_ENGINE_TICK = 77,
    FIELD_WORLD_GROUP_ID = 78,
    FIELD_GLOBALSYMBOL = 79,
    FIELD_HNMGRAPHDEFINITION = 80,
    FIELD_TYPECOUNT = 81,
}

public enum ThreeState_t : uint
{
    TRS_FALSE = 0,
    TRS_TRUE = 1,
    TRS_NONE = 2,
}

