// Auto-generated by cs2-codegen from schemas_jsonschema.json
// Revision 10638965 (May 06 2026) — https://github.com/ValveResourceFormat/DumpSource2
// Do not edit by hand.
// Module: sounddoc_lib

#nullable enable
#pragma warning disable CS8618  // non-nullable property not initialized (expected in generated serialization types)

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CS2Schema;

/// <summary>CEffectsPreviewList, 48 bytes</summary>
public class CEffectsPreviewList
{
    [JsonPropertyName("m_previewGraphInput")]
    public string M_previewGraphInput { get; set; }  // +0x0
    [JsonPropertyName("m_flMix")]
    public float M_flMix { get; set; }  // +0x8
    [JsonPropertyName("m_previewList")]
    public CPreviewList M_previewList { get; set; }  // +0x10
}

/// <summary>CFilterStage, 24 bytes</summary>
public class CFilterStage
{
    [JsonPropertyName("m_filterType")]
    public string M_filterType { get; set; }  // +0x0
    [JsonPropertyName("m_flFrequency")]
    public float M_flFrequency { get; set; }  // +0x8
    [JsonPropertyName("m_flQ")]
    public float M_flQ { get; set; }  // +0xC
    [JsonPropertyName("m_fldbGain")]
    public float M_fldbGain { get; set; }  // +0x10
    [JsonPropertyName("m_nFilterSlope")]
    public VMixFilterSlope_t M_nFilterSlope { get; set; }  // +0x14
    [JsonPropertyName("m_bEnable")]
    public bool M_bEnable { get; set; }  // +0x15
}

/// <summary>CGraphEditorState, 40 bytes</summary>
public class CGraphEditorState
{
    [JsonPropertyName("m_viewConfig")]
    public CGraphEditorViewConfig M_viewConfig { get; set; }  // +0x0
}

/// <summary>CGraphPreviewList, 40 bytes</summary>
public class CGraphPreviewList
{
    [JsonPropertyName("m_flVolume")]
    public float M_flVolume { get; set; }  // +0x0
    [JsonPropertyName("m_previewList")]
    public CPreviewList M_previewList { get; set; }  // +0x8
}

/// <summary>CMixAmp, 40 bytes</summary>
public class CMixAmp : CMixPropertyBase
{
    [JsonPropertyName("m_flVolume")]
    public float M_flVolume { get; set; }  // +0x20
}

/// <summary>CMixAudioMeter, 48 bytes</summary>
public class CMixAudioMeter : CMixPropertyBase
{
    [JsonPropertyName("m_flLeftLevel")]
    public float M_flLeftLevel { get; set; }  // +0x20
    [JsonPropertyName("m_flLeftPeak")]
    public float M_flLeftPeak { get; set; }  // +0x24
    [JsonPropertyName("m_flRightLevel")]
    public float M_flRightLevel { get; set; }  // +0x28
    [JsonPropertyName("m_flRightPeak")]
    public float M_flRightPeak { get; set; }  // +0x2C
}

/// <summary>CMixAutoFilter, 80 bytes</summary>
public class CMixAutoFilter : CMixPropertyBase
{
    [JsonPropertyName("m_desc")]
    public VMixAutoFilterDesc_t M_desc { get; set; }  // +0x20
}

/// <summary>CMixBlendAudio, 40 bytes</summary>
public class CMixBlendAudio : CMixPropertyBase
{
    [JsonPropertyName("m_flLockAmount")]
    public float M_flLockAmount { get; set; }  // +0x20
}

/// <summary>CMixBlendVsndsToImpulseResponse, 96 bytes</summary>
public class CMixBlendVsndsToImpulseResponse : CMixPropertyBase
{
    [JsonPropertyName("m_flWeight0")]
    public float M_flWeight0 { get; set; }  // +0x20
    [JsonPropertyName("m_flWeight1")]
    public float M_flWeight1 { get; set; }  // +0x24
    [JsonPropertyName("m_flWeight2")]
    public float M_flWeight2 { get; set; }  // +0x28
    [JsonPropertyName("m_flWeight3")]
    public float M_flWeight3 { get; set; }  // +0x2C
    [JsonPropertyName("m_flWeight4")]
    public float M_flWeight4 { get; set; }  // +0x30
    [JsonPropertyName("m_flWeight5")]
    public float M_flWeight5 { get; set; }  // +0x34
    [JsonPropertyName("m_flWeight6")]
    public float M_flWeight6 { get; set; }  // +0x38
    [JsonPropertyName("m_flWeight7")]
    public float M_flWeight7 { get; set; }  // +0x3C
    [JsonPropertyName("m_flPreDelayMS0")]
    public float M_flPreDelayMS0 { get; set; }  // +0x40
    [JsonPropertyName("m_flPreDelayMS1")]
    public float M_flPreDelayMS1 { get; set; }  // +0x44
    [JsonPropertyName("m_flPreDelayMS2")]
    public float M_flPreDelayMS2 { get; set; }  // +0x48
    [JsonPropertyName("m_flPreDelayMS3")]
    public float M_flPreDelayMS3 { get; set; }  // +0x4C
    [JsonPropertyName("m_flPreDelayMS4")]
    public float M_flPreDelayMS4 { get; set; }  // +0x50
    [JsonPropertyName("m_flPreDelayMS5")]
    public float M_flPreDelayMS5 { get; set; }  // +0x54
    [JsonPropertyName("m_flPreDelayMS6")]
    public float M_flPreDelayMS6 { get; set; }  // +0x58
    [JsonPropertyName("m_flPreDelayMS7")]
    public float M_flPreDelayMS7 { get; set; }  // +0x5C
}

/// <summary>CMixBoxverb, 112 bytes</summary>
public class CMixBoxverb : CMixPropertyBase
{
    [JsonPropertyName("m_flSizeMax")]
    public float M_flSizeMax { get; set; }  // +0x20
    [JsonPropertyName("m_flSizeMin")]
    public float M_flSizeMin { get; set; }  // +0x24
    [JsonPropertyName("m_flComplexity")]
    public float M_flComplexity { get; set; }  // +0x28
    [JsonPropertyName("m_flModDepth")]
    public float M_flModDepth { get; set; }  // +0x2C
    [JsonPropertyName("m_flModRate")]
    public float M_flModRate { get; set; }  // +0x30
    [JsonPropertyName("m_bParallel")]
    public bool M_bParallel { get; set; }  // +0x34
    [JsonPropertyName("m_filterType")]
    public VMixFilterDesc_t M_filterType { get; set; }  // +0x38
    [JsonPropertyName("m_flWidth")]
    public float M_flWidth { get; set; }  // +0x48
    [JsonPropertyName("m_flHeight")]
    public float M_flHeight { get; set; }  // +0x4C
    [JsonPropertyName("m_flDepth")]
    public float M_flDepth { get; set; }  // +0x50
    [JsonPropertyName("m_flFeedbackScale")]
    public float M_flFeedbackScale { get; set; }  // +0x54
    [JsonPropertyName("m_flFeedbackWidth")]
    public float M_flFeedbackWidth { get; set; }  // +0x58
    [JsonPropertyName("m_flFeedbackHeight")]
    public float M_flFeedbackHeight { get; set; }  // +0x5C
    [JsonPropertyName("m_flFeedbackDepth")]
    public float M_flFeedbackDepth { get; set; }  // +0x60
    [JsonPropertyName("m_flOutputGain")]
    public float M_flOutputGain { get; set; }  // +0x64
    [JsonPropertyName("m_flTaps")]
    public float M_flTaps { get; set; }  // +0x68
}

/// <summary>CMixBoxverb2, 112 bytes</summary>
public class CMixBoxverb2 : CMixPropertyBase
{
    [JsonPropertyName("m_flSizeMax")]
    public float M_flSizeMax { get; set; }  // +0x20
    [JsonPropertyName("m_flSizeMin")]
    public float M_flSizeMin { get; set; }  // +0x24
    [JsonPropertyName("m_flComplexity")]
    public float M_flComplexity { get; set; }  // +0x28
    [JsonPropertyName("m_flModDepth")]
    public float M_flModDepth { get; set; }  // +0x2C
    [JsonPropertyName("m_flModRate")]
    public float M_flModRate { get; set; }  // +0x30
    [JsonPropertyName("m_bParallel")]
    public bool M_bParallel { get; set; }  // +0x34
    [JsonPropertyName("m_filterType")]
    public VMixFilterDesc_t M_filterType { get; set; }  // +0x38
    [JsonPropertyName("m_flWidth")]
    public float M_flWidth { get; set; }  // +0x48
    [JsonPropertyName("m_flHeight")]
    public float M_flHeight { get; set; }  // +0x4C
    [JsonPropertyName("m_flDepth")]
    public float M_flDepth { get; set; }  // +0x50
    [JsonPropertyName("m_flFeedbackScale")]
    public float M_flFeedbackScale { get; set; }  // +0x54
    [JsonPropertyName("m_flFeedbackWidth")]
    public float M_flFeedbackWidth { get; set; }  // +0x58
    [JsonPropertyName("m_flFeedbackHeight")]
    public float M_flFeedbackHeight { get; set; }  // +0x5C
    [JsonPropertyName("m_flFeedbackDepth")]
    public float M_flFeedbackDepth { get; set; }  // +0x60
    [JsonPropertyName("m_flWetMix")]
    public float M_flWetMix { get; set; }  // +0x64
    [JsonPropertyName("m_flOutputGain")]
    public float M_flOutputGain { get; set; }  // +0x68
    [JsonPropertyName("m_flTaps")]
    public float M_flTaps { get; set; }  // +0x6C
}

/// <summary>CMixControlAutomatic, 32 bytes</summary>
public class CMixControlAutomatic : CMixPropertyBase
{
}

/// <summary>CMixControlCrossfade, 40 bytes</summary>
public class CMixControlCrossfade : CMixPropertyBase
{
    [JsonPropertyName("m_flFadeStart")]
    public float M_flFadeStart { get; set; }  // +0x20
    [JsonPropertyName("m_flFadeEnd")]
    public float M_flFadeEnd { get; set; }  // +0x24
}

/// <summary>CMixControlCurve, 112 bytes</summary>
public class CMixControlCurve : CMixPropertyBase
{
    [JsonPropertyName("m_flInputMin")]
    public float M_flInputMin { get; set; }  // +0x20
    [JsonPropertyName("m_flInputMax")]
    public float M_flInputMax { get; set; }  // +0x24
    [JsonPropertyName("m_flOutputMin")]
    public float M_flOutputMin { get; set; }  // +0x28
    [JsonPropertyName("m_flOutputMax")]
    public float M_flOutputMax { get; set; }  // +0x2C
    [JsonPropertyName("m_curve")]
    public object /* opaque */ M_curve { get; set; }  // +0x30
}

/// <summary>CMixControlInput, 48 bytes</summary>
public class CMixControlInput : CMixPropertyBase
{
    [JsonPropertyName("m_flDefaultValue")]
    public float M_flDefaultValue { get; set; }  // +0x20
    [JsonPropertyName("m_flMinRange")]
    public float M_flMinRange { get; set; }  // +0x24
    [JsonPropertyName("m_flMaxRange")]
    public float M_flMaxRange { get; set; }  // +0x28
    [JsonPropertyName("m_bUseDecibels")]
    public bool M_bUseDecibels { get; set; }  // +0x2C
}

/// <summary>CMixControlInputArray, 56 bytes</summary>
public class CMixControlInputArray : CMixPropertyBase
{
    [JsonPropertyName("m_vflData")]
    public float[] M_vflData { get; set; }  // +0x20
}

/// <summary>CMixControlListener, 32 bytes</summary>
public class CMixControlListener : CMixPropertyBase
{
}

/// <summary>CMixControlMax, 32 bytes</summary>
public class CMixControlMax : CMixPropertyBase
{
}

/// <summary>CMixControlMeter, 40 bytes</summary>
public class CMixControlMeter : CMixPropertyBase
{
    [JsonPropertyName("m_flValue")]
    public float M_flValue { get; set; }  // +0x20
}

/// <summary>CMixControlOutput, 40 bytes</summary>
public class CMixControlOutput : CMixPropertyBase
{
    [JsonPropertyName("m_flDefaultValue")]
    public float M_flDefaultValue { get; set; }  // +0x20
}

/// <summary>CMixControlRemap, 56 bytes</summary>
public class CMixControlRemap : CMixPropertyBase
{
    [JsonPropertyName("m_flInputMin")]
    public float M_flInputMin { get; set; }  // +0x20
    [JsonPropertyName("m_flInputMax")]
    public float M_flInputMax { get; set; }  // +0x24
    [JsonPropertyName("m_flOutputStart")]
    public float M_flOutputStart { get; set; }  // +0x28
    [JsonPropertyName("m_flOutputEnd")]
    public float M_flOutputEnd { get; set; }  // +0x2C
    [JsonPropertyName("m_flPower")]
    public float M_flPower { get; set; }  // +0x30
}

/// <summary>CMixControlStackInput, 48 bytes</summary>
public class CMixControlStackInput : CMixPropertyBase
{
    [JsonPropertyName("m_flDefaultValue")]
    public float M_flDefaultValue { get; set; }  // +0x20
    [JsonPropertyName("m_flMinRange")]
    public float M_flMinRange { get; set; }  // +0x24
    [JsonPropertyName("m_flMaxRange")]
    public float M_flMaxRange { get; set; }  // +0x28
}

/// <summary>CMixControlTransientInput, 32 bytes</summary>
public class CMixControlTransientInput : CMixPropertyBase
{
}

/// <summary>CMixConvolution, 64 bytes</summary>
public class CMixConvolution : CMixPropertyBase
{
    [JsonPropertyName("m_desc")]
    public VMixConvolutionDesc_t M_desc { get; set; }  // +0x20
}

/// <summary>CMixDelay, 88 bytes</summary>
public class CMixDelay : CMixPropertyBase
{
    [JsonPropertyName("m_nChannels")]
    public int M_nChannels { get; set; }  // +0x20
    [JsonPropertyName("m_flDelay")]
    public float M_flDelay { get; set; }  // +0x24
    [JsonPropertyName("m_fldbDirectGain")]
    public float M_fldbDirectGain { get; set; }  // +0x28
    [JsonPropertyName("m_fldbDelayGain")]
    public float M_fldbDelayGain { get; set; }  // +0x2C
    [JsonPropertyName("m_fldbFeedbackGain")]
    public float M_fldbFeedbackGain { get; set; }  // +0x30
    [JsonPropertyName("m_flWidth")]
    public float M_flWidth { get; set; }  // +0x34
    [JsonPropertyName("m_bEnableFilter")]
    public bool M_bEnableFilter { get; set; }  // +0x38
    [JsonPropertyName("m_filterType")]
    public string M_filterType { get; set; }  // +0x40
    [JsonPropertyName("m_flFrequency")]
    public float M_flFrequency { get; set; }  // +0x48
    [JsonPropertyName("m_flQ")]
    public float M_flQ { get; set; }  // +0x4C
    [JsonPropertyName("m_fldbGain")]
    public float M_fldbGain { get; set; }  // +0x50
}

/// <summary>CMixDelayImpulseResponse, 40 bytes</summary>
public class CMixDelayImpulseResponse : CMixPropertyBase
{
    [JsonPropertyName("m_flPreDelayMS")]
    public float M_flPreDelayMS { get; set; }  // +0x20
}

/// <summary>CMixDiffusor, 48 bytes</summary>
public class CMixDiffusor : CMixPropertyBase
{
    [JsonPropertyName("m_flSize")]
    public float M_flSize { get; set; }  // +0x20
    [JsonPropertyName("m_flComplexity")]
    public float M_flComplexity { get; set; }  // +0x24
    [JsonPropertyName("m_flFeedback")]
    public float M_flFeedback { get; set; }  // +0x28
    [JsonPropertyName("m_flOutputGain")]
    public float M_flOutputGain { get; set; }  // +0x2C
}

/// <summary>CMixDualCompressor, 88 bytes</summary>
public class CMixDualCompressor : CMixPropertyBase
{
    [JsonPropertyName("m_nChannels")]
    public int M_nChannels { get; set; }  // +0x20
    [JsonPropertyName("m_desc")]
    public VMixDualCompressorDesc_t M_desc { get; set; }  // +0x24
}

/// <summary>CMixDynamics, 88 bytes</summary>
public class CMixDynamics : CMixPropertyBase
{
    [JsonPropertyName("m_nChannels")]
    public int M_nChannels { get; set; }  // +0x20
    [JsonPropertyName("m_fldbNoiseGateThreshold")]
    public float M_fldbNoiseGateThreshold { get; set; }  // +0x24
    [JsonPropertyName("m_fldbGain")]
    public float M_fldbGain { get; set; }  // +0x28
    [JsonPropertyName("m_fldbCompressionThreshold")]
    public float M_fldbCompressionThreshold { get; set; }  // +0x2C
    [JsonPropertyName("m_fldbLimiterThreshold")]
    public float M_fldbLimiterThreshold { get; set; }  // +0x30
    [JsonPropertyName("m_fldbKneeWidth")]
    public float M_fldbKneeWidth { get; set; }  // +0x34
    [JsonPropertyName("m_flRatio")]
    public float M_flRatio { get; set; }  // +0x38
    [JsonPropertyName("m_flLimiterRatio")]
    public float M_flLimiterRatio { get; set; }  // +0x3C
    [JsonPropertyName("m_flAttackTime")]
    public float M_flAttackTime { get; set; }  // +0x40
    [JsonPropertyName("m_flReleaseTime")]
    public float M_flReleaseTime { get; set; }  // +0x44
    [JsonPropertyName("m_flRMSTime")]
    public float M_flRMSTime { get; set; }  // +0x48
    [JsonPropertyName("m_flWetMix")]
    public float M_flWetMix { get; set; }  // +0x4C
    [JsonPropertyName("m_bPeakMode")]
    public bool M_bPeakMode { get; set; }  // +0x50
    [JsonPropertyName("m_nUIPage")]
    public int M_nUIPage { get; set; }  // +0x54
}

/// <summary>CMixDynamics3Band, 184 bytes</summary>
public class CMixDynamics3Band : CMixPropertyBase
{
    [JsonPropertyName("m_nChannels")]
    public int M_nChannels { get; set; }  // +0x20
    [JsonPropertyName("m_fldbOutputGain")]
    public float M_fldbOutputGain { get; set; }  // +0x24
    [JsonPropertyName("m_flRMSTime")]
    public float M_flRMSTime { get; set; }  // +0x28
    [JsonPropertyName("m_flDepth")]
    public float M_flDepth { get; set; }  // +0x2C
    [JsonPropertyName("m_flWetMix")]
    public float M_flWetMix { get; set; }  // +0x30
    [JsonPropertyName("m_flTimeScale")]
    public float M_flTimeScale { get; set; }  // +0x34
    [JsonPropertyName("m_fldbKneeWidth")]
    public float M_fldbKneeWidth { get; set; }  // +0x38
    [JsonPropertyName("m_flLowCutoffFreq")]
    public float M_flLowCutoffFreq { get; set; }  // +0x3C
    [JsonPropertyName("m_flHighCutoffFreq")]
    public float M_flHighCutoffFreq { get; set; }  // +0x40
    [JsonPropertyName("m_bPeakMode")]
    public bool M_bPeakMode { get; set; }  // +0x44
    [JsonPropertyName("m_nSelectedPage")]
    public int M_nSelectedPage { get; set; }  // +0x48
    [JsonPropertyName("m_bands")]
    public VMixDynamicsBand_t[] M_bands { get; set; }  // +0x4C
}

/// <summary>CMixDynamicsCompressor, 80 bytes</summary>
public class CMixDynamicsCompressor : CMixPropertyBase
{
    [JsonPropertyName("m_nChannels")]
    public int M_nChannels { get; set; }  // +0x20
    [JsonPropertyName("m_desc")]
    public VMixDynamicsCompressorDesc_t M_desc { get; set; }  // +0x24
    [JsonPropertyName("m_nUIPage")]
    public int M_nUIPage { get; set; }  // +0x48
    [JsonPropertyName("m_bIsLimiter")]
    public bool M_bIsLimiter { get; set; }  // +0x4C
}

/// <summary>CMixEffectChain, 56 bytes</summary>
public class CMixEffectChain : CMixPropertyBase
{
    [JsonPropertyName("m_nChannels")]
    public int M_nChannels { get; set; }  // +0x20
    [JsonPropertyName("m_effectName")]
    public string M_effectName { get; set; }  // +0x28
    [JsonPropertyName("m_flXFade")]
    public float M_flXFade { get; set; }  // +0x30
}

/// <summary>CMixEffectName, 40 bytes</summary>
public class CMixEffectName : CMixPropertyBase
{
    [JsonPropertyName("m_defaultValue")]
    public string M_defaultValue { get; set; }  // +0x20
}

/// <summary>CMixEnvelope, 48 bytes</summary>
public class CMixEnvelope : CMixPropertyBase
{
    [JsonPropertyName("m_flAttackTime")]
    public float M_flAttackTime { get; set; }  // +0x20
    [JsonPropertyName("m_flHoldTime")]
    public float M_flHoldTime { get; set; }  // +0x24
    [JsonPropertyName("m_flReleaseTime")]
    public float M_flReleaseTime { get; set; }  // +0x28
}

/// <summary>CMixEnvelopeTrigger, 56 bytes</summary>
public class CMixEnvelopeTrigger : CMixPropertyBase
{
    [JsonPropertyName("m_flBaseValue")]
    public float M_flBaseValue { get; set; }  // +0x20
    [JsonPropertyName("m_flDestinationValue")]
    public float M_flDestinationValue { get; set; }  // +0x24
    [JsonPropertyName("m_flAttackTime")]
    public float M_flAttackTime { get; set; }  // +0x28
    [JsonPropertyName("m_flHoldTime")]
    public float M_flHoldTime { get; set; }  // +0x2C
    [JsonPropertyName("m_flReleaseTime")]
    public float M_flReleaseTime { get; set; }  // +0x30
}

/// <summary>CMixEQ8, 232 bytes</summary>
public class CMixEQ8 : CMixPropertyBase
{
    [JsonPropertyName("m_nChannels")]
    public int M_nChannels { get; set; }  // +0x20
    [JsonPropertyName("m_stages")]
    public CFilterStage[] M_stages { get; set; }  // +0x28
}

/// <summary>CMixFilter, 64 bytes</summary>
public class CMixFilter : CMixPropertyBase
{
    [JsonPropertyName("m_filterType")]
    public string M_filterType { get; set; }  // +0x20
    [JsonPropertyName("m_nChannels")]
    public int M_nChannels { get; set; }  // +0x28
    [JsonPropertyName("m_flFrequency")]
    public float M_flFrequency { get; set; }  // +0x2C
    [JsonPropertyName("m_flQ")]
    public float M_flQ { get; set; }  // +0x30
    [JsonPropertyName("m_fldbGain")]
    public float M_fldbGain { get; set; }  // +0x34
    [JsonPropertyName("m_nFilterSlope")]
    public VMixFilterSlope_t M_nFilterSlope { get; set; }  // +0x38
}

/// <summary>CMixFlanger, 72 bytes</summary>
public class CMixFlanger : CMixPropertyBase
{
    [JsonPropertyName("m_flDelay")]
    public float M_flDelay { get; set; }  // +0x20
    [JsonPropertyName("m_flFeedback")]
    public float M_flFeedback { get; set; }  // +0x24
    [JsonPropertyName("m_flFeedfoward")]
    public float M_flFeedfoward { get; set; }  // +0x28
    [JsonPropertyName("m_flModRate")]
    public float M_flModRate { get; set; }  // +0x2C
    [JsonPropertyName("m_flModDepth")]
    public float M_flModDepth { get; set; }  // +0x30
    [JsonPropertyName("m_bPhaseInvert")]
    public bool M_bPhaseInvert { get; set; }  // +0x34
    [JsonPropertyName("m_flGlideTime")]
    public float M_flGlideTime { get; set; }  // +0x38
    [JsonPropertyName("m_bAntialiasing")]
    public bool M_bAntialiasing { get; set; }  // +0x3C
    [JsonPropertyName("m_flGain")]
    public float M_flGain { get; set; }  // +0x40
}

/// <summary>CMixFreeverb, 48 bytes</summary>
public class CMixFreeverb : CMixPropertyBase
{
    [JsonPropertyName("m_flRoomSize")]
    public float M_flRoomSize { get; set; }  // +0x20
    [JsonPropertyName("m_flDamp")]
    public float M_flDamp { get; set; }  // +0x24
    [JsonPropertyName("m_flWidth")]
    public float M_flWidth { get; set; }  // +0x28
    [JsonPropertyName("m_flLateReflections")]
    public float M_flLateReflections { get; set; }  // +0x2C
}

/// <summary>CMixGroupBox, 40 bytes</summary>
public class CMixGroupBox : CMixPropertyBase
{
    [JsonPropertyName("m_color")]
    public Color M_color { get; set; }  // +0x20
    [JsonPropertyName("m_bMovesNodes")]
    public bool M_bMovesNodes { get; set; }  // +0x24
}

/// <summary>CMixImpulseResponseInput, 40 bytes</summary>
public class CMixImpulseResponseInput : CMixPropertyBase
{
    [JsonPropertyName("m_defaultValue")]
    public string M_defaultValue { get; set; }  // +0x20
}

/// <summary>CMixModDelay, 80 bytes</summary>
public class CMixModDelay : CMixPropertyBase
{
    [JsonPropertyName("m_bPhaseInvert")]
    public bool M_bPhaseInvert { get; set; }  // +0x20
    [JsonPropertyName("m_flGlideTime")]
    public float M_flGlideTime { get; set; }  // +0x24
    [JsonPropertyName("m_flDelay")]
    public float M_flDelay { get; set; }  // +0x28
    [JsonPropertyName("m_flFeedback")]
    public float M_flFeedback { get; set; }  // +0x2C
    [JsonPropertyName("m_flGain")]
    public float M_flGain { get; set; }  // +0x30
    [JsonPropertyName("m_flModRate")]
    public float M_flModRate { get; set; }  // +0x34
    [JsonPropertyName("m_flModDepth")]
    public float M_flModDepth { get; set; }  // +0x38
    [JsonPropertyName("m_filterType")]
    public VMixFilterType_t M_filterType { get; set; }  // +0x3C
    [JsonPropertyName("m_flFrequency")]
    public float M_flFrequency { get; set; }  // +0x40
    [JsonPropertyName("m_flQ")]
    public float M_flQ { get; set; }  // +0x44
    [JsonPropertyName("m_flFilterGain")]
    public float M_flFilterGain { get; set; }  // +0x48
    [JsonPropertyName("m_bAntialiasing")]
    public bool M_bAntialiasing { get; set; }  // +0x4C
}

/// <summary>CMixOsc, 48 bytes</summary>
public class CMixOsc : CMixPropertyBase
{
    [JsonPropertyName("m_desc")]
    public VMixOscDesc_t M_desc { get; set; }  // +0x20
}

/// <summary>CMixOutput, 48 bytes</summary>
public class CMixOutput : CMixPropertyBase
{
    [JsonPropertyName("m_flVolume1")]
    public float M_flVolume1 { get; set; }  // +0x20
    [JsonPropertyName("m_flVolume2")]
    public float M_flVolume2 { get; set; }  // +0x24
    [JsonPropertyName("m_sendTo")]
    public string M_sendTo { get; set; }  // +0x28
}

/// <summary>CMixPanner, 40 bytes</summary>
public class CMixPanner : CMixPropertyBase
{
    [JsonPropertyName("m_type")]
    public VMixPannerType_t M_type { get; set; }  // +0x20
    [JsonPropertyName("m_flStrength")]
    public float M_flStrength { get; set; }  // +0x24
}

/// <summary>CMixPitchShift, 56 bytes</summary>
public class CMixPitchShift : CMixPropertyBase
{
    [JsonPropertyName("m_nChannels")]
    public int M_nChannels { get; set; }  // +0x20
    [JsonPropertyName("m_flPitchScale")]
    public float M_flPitchScale { get; set; }  // +0x24
    [JsonPropertyName("m_flGrainMs")]
    public float M_flGrainMs { get; set; }  // +0x28
    [JsonPropertyName("m_nProcType")]
    public int M_nProcType { get; set; }  // +0x2C
    [JsonPropertyName("m_nQuality")]
    public int M_nQuality { get; set; }  // +0x30
}

/// <summary>CMixPlateverb, 64 bytes</summary>
public class CMixPlateverb : CMixPropertyBase
{
    [JsonPropertyName("m_flPrefilter")]
    public float M_flPrefilter { get; set; }  // +0x20
    [JsonPropertyName("m_flInputDiffusion1")]
    public float M_flInputDiffusion1 { get; set; }  // +0x24
    [JsonPropertyName("m_flInputDiffusion2")]
    public float M_flInputDiffusion2 { get; set; }  // +0x28
    [JsonPropertyName("m_flDecay")]
    public float M_flDecay { get; set; }  // +0x2C
    [JsonPropertyName("m_flDamp")]
    public float M_flDamp { get; set; }  // +0x30
    [JsonPropertyName("m_flFeedbackDiffusion1")]
    public float M_flFeedbackDiffusion1 { get; set; }  // +0x34
    [JsonPropertyName("m_flFeedbackDiffusion2")]
    public float M_flFeedbackDiffusion2 { get; set; }  // +0x38
}

/// <summary>CMixPresetDSP, 56 bytes</summary>
public class CMixPresetDSP : CMixPropertyBase
{
    [JsonPropertyName("m_nChannels")]
    public int M_nChannels { get; set; }  // +0x20
    [JsonPropertyName("m_effectName")]
    public string M_effectName { get; set; }  // +0x28
    [JsonPropertyName("m_flXFade")]
    public float M_flXFade { get; set; }  // +0x30
}

/// <summary>CMixPropertyBase, 32 bytes</summary>
public class CMixPropertyBase
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x8
    [JsonPropertyName("m_Comment")]
    public string M_Comment { get; set; }  // +0x10
    [JsonPropertyName("m_bActive")]
    public bool M_bActive { get; set; }  // +0x18
    [JsonPropertyName("m_bSolo")]
    public bool M_bSolo { get; set; }  // +0x19
    [JsonPropertyName("m_bEditProperties")]
    public bool M_bEditProperties { get; set; }  // +0x1A
}

/// <summary>CMixRemapVsndToImpulseResponse, 40 bytes</summary>
public class CMixRemapVsndToImpulseResponse : CMixPropertyBase
{
    [JsonPropertyName("m_flPreDelayMS")]
    public float M_flPreDelayMS { get; set; }  // +0x20
}

/// <summary>CMixShaper, 56 bytes</summary>
public class CMixShaper : CMixPropertyBase
{
    [JsonPropertyName("m_desc")]
    public VMixShaperDesc_t M_desc { get; set; }  // +0x20
}

/// <summary>CMixSplitter, 64 bytes</summary>
public class CMixSplitter : CMixPropertyBase
{
    [JsonPropertyName("m_flVolume1")]
    public float M_flVolume1 { get; set; }  // +0x20
    [JsonPropertyName("m_flVolume2")]
    public float M_flVolume2 { get; set; }  // +0x24
    [JsonPropertyName("m_flVolume3")]
    public float M_flVolume3 { get; set; }  // +0x28
    [JsonPropertyName("m_flVolume4")]
    public float M_flVolume4 { get; set; }  // +0x2C
    [JsonPropertyName("m_flVolume5")]
    public float M_flVolume5 { get; set; }  // +0x30
    [JsonPropertyName("m_flVolume6")]
    public float M_flVolume6 { get; set; }  // +0x34
    [JsonPropertyName("m_flVolume7")]
    public float M_flVolume7 { get; set; }  // +0x38
    [JsonPropertyName("m_flVolume8")]
    public float M_flVolume8 { get; set; }  // +0x3C
}

/// <summary>CMixSplitterBlend, 40 bytes</summary>
public class CMixSplitterBlend : CMixPropertyBase
{
    [JsonPropertyName("m_flLockAmount")]
    public float M_flLockAmount { get; set; }  // +0x20
}

/// <summary>CMixSteamAudioDirect, 88 bytes</summary>
public class CMixSteamAudioDirect : CMixPropertyBase
{
    [JsonPropertyName("m_bApplyDistanceAttenuation")]
    public bool M_bApplyDistanceAttenuation { get; set; }  // +0x20
    [JsonPropertyName("m_bApplyAirAbsorption")]
    public bool M_bApplyAirAbsorption { get; set; }  // +0x21
    [JsonPropertyName("m_bApplyDirectivity")]
    public bool M_bApplyDirectivity { get; set; }  // +0x22
    [JsonPropertyName("m_bApplyOcclusion")]
    public bool M_bApplyOcclusion { get; set; }  // +0x23
    [JsonPropertyName("m_bApplyTransmission")]
    public bool M_bApplyTransmission { get; set; }  // +0x24
    [JsonPropertyName("m_flDipoleWeight")]
    public float M_flDipoleWeight { get; set; }  // +0x28
    [JsonPropertyName("m_flDipolePower")]
    public float M_flDipolePower { get; set; }  // +0x2C
    [JsonPropertyName("m_flOcclusion")]
    public float M_flOcclusion { get; set; }  // +0x30
    [JsonPropertyName("m_flTransmissionLow")]
    public float M_flTransmissionLow { get; set; }  // +0x34
    [JsonPropertyName("m_flTransmissionMid")]
    public float M_flTransmissionMid { get; set; }  // +0x38
    [JsonPropertyName("m_flTransmissionHigh")]
    public float M_flTransmissionHigh { get; set; }  // +0x3C
    [JsonPropertyName("m_vecTransmission")]
    public float[] M_vecTransmission { get; set; }  // +0x40
}

/// <summary>CMixSteamAudioHybridReverb, 72 bytes</summary>
public class CMixSteamAudioHybridReverb : CMixPropertyBase
{
    [JsonPropertyName("m_flReverbTimeLow")]
    public float M_flReverbTimeLow { get; set; }  // +0x20
    [JsonPropertyName("m_flReverbTimeMid")]
    public float M_flReverbTimeMid { get; set; }  // +0x24
    [JsonPropertyName("m_flReverbTimeHigh")]
    public float M_flReverbTimeHigh { get; set; }  // +0x28
    [JsonPropertyName("m_vecReverbTime")]
    public float[] M_vecReverbTime { get; set; }  // +0x30
}

/// <summary>CMixSteamAudioPathing, 96 bytes</summary>
public class CMixSteamAudioPathing : CMixPropertyBase
{
    [JsonPropertyName("m_flPathingMixLevel")]
    public float M_flPathingMixLevel { get; set; }  // +0x20
    [JsonPropertyName("m_vPathingEQ")]
    public float[] M_vPathingEQ { get; set; }  // +0x24
    [JsonPropertyName("m_vPathingCoeffs")]
    public float[] M_vPathingCoeffs { get; set; }  // +0x30
    [JsonPropertyName("m_vecPathingEQ")]
    public float[] M_vecPathingEQ { get; set; }  // +0x48
}

/// <summary>CMixSteamAudioSource, 48 bytes</summary>
public class CMixSteamAudioSource : CMixPropertyBase
{
    [JsonPropertyName("m_nInterpolation")]
    public SteamAudioHRTFInterpolationType_t M_nInterpolation { get; set; }  // +0x20
    [JsonPropertyName("m_flDirectMixLevel")]
    public float M_flDirectMixLevel { get; set; }  // +0x24
    [JsonPropertyName("m_bEnablePerspectiveCorrection")]
    public bool M_bEnablePerspectiveCorrection { get; set; }  // +0x28
    [JsonPropertyName("m_bRelativePosition")]
    public bool M_bRelativePosition { get; set; }  // +0x29
}

/// <summary>CMixStereoDelay, 40 bytes</summary>
public class CMixStereoDelay : CMixPropertyBase
{
    [JsonPropertyName("m_flDelayLeft")]
    public float M_flDelayLeft { get; set; }  // +0x20
    [JsonPropertyName("m_flDelayRight")]
    public float M_flDelayRight { get; set; }  // +0x24
}

/// <summary>CMixSubgraph, 48 bytes</summary>
public class CMixSubgraph : CMixPropertyBase
{
    [JsonPropertyName("subgraphFile")]
    public string SubgraphFile { get; set; }  // +0x20
    [JsonPropertyName("subgraphName")]
    public string SubgraphName { get; set; }  // +0x28
}

/// <summary>CMixSubgraphSwitch, 104 bytes</summary>
public class CMixSubgraphSwitch : CMixPropertyBase
{
    [JsonPropertyName("bUseDetailedPlugNames")]
    public bool BUseDetailedPlugNames { get; set; }  // +0x20
    [JsonPropertyName("defaultSubgraph")]
    public CSelectableSubgraph DefaultSubgraph { get; set; }  // +0x28
    [JsonPropertyName("interpolationMode")]
    public VMixSubgraphSwitchInterpolationType_t InterpolationMode { get; set; }  // +0x40
    [JsonPropertyName("bOnlyTailsOnFadeOut")]
    public bool BOnlyTailsOnFadeOut { get; set; }  // +0x44
    [JsonPropertyName("flTransitionTime")]
    public float FlTransitionTime { get; set; }  // +0x48
    [JsonPropertyName("nChannels")]
    public int NChannels { get; set; }  // +0x4C
    [JsonPropertyName("subgraphs")]
    public CSelectableSubgraph[] Subgraphs { get; set; }  // +0x50
}

/// <summary>CMixSum, 128 bytes</summary>
public class CMixSum : CMixPropertyBase
{
    [JsonPropertyName("m_flVolume1")]
    public float M_flVolume1 { get; set; }  // +0x20
    [JsonPropertyName("m_flVolume2")]
    public float M_flVolume2 { get; set; }  // +0x24
    [JsonPropertyName("m_flVolume3")]
    public float M_flVolume3 { get; set; }  // +0x28
    [JsonPropertyName("m_flVolume4")]
    public float M_flVolume4 { get; set; }  // +0x2C
    [JsonPropertyName("m_flVolume5")]
    public float M_flVolume5 { get; set; }  // +0x30
    [JsonPropertyName("m_flVolume6")]
    public float M_flVolume6 { get; set; }  // +0x34
    [JsonPropertyName("m_flVolume7")]
    public float M_flVolume7 { get; set; }  // +0x38
    [JsonPropertyName("m_flVolume8")]
    public float M_flVolume8 { get; set; }  // +0x3C
    [JsonPropertyName("m_channelName")]
    public string[] M_channelName { get; set; }  // +0x40
}

/// <summary>CMixTrack, 80 bytes</summary>
public class CMixTrack : CMixPropertyBase
{
    [JsonPropertyName("m_nChannels")]
    public int M_nChannels { get; set; }  // +0x20
    [JsonPropertyName("m_nMixDownRule")]
    public int M_nMixDownRule { get; set; }  // +0x24
    [JsonPropertyName("m_sendOperator")]
    public string M_sendOperator { get; set; }  // +0x28
    [JsonPropertyName("m_Send1")]
    public string M_Send1 { get; set; }  // +0x30
    [JsonPropertyName("m_Send2")]
    public string M_Send2 { get; set; }  // +0x38
    [JsonPropertyName("m_Send3")]
    public string M_Send3 { get; set; }  // +0x40
    [JsonPropertyName("m_Send4")]
    public string M_Send4 { get; set; }  // +0x48
}

/// <summary>CMixUtility, 56 bytes</summary>
public class CMixUtility : CMixPropertyBase
{
    [JsonPropertyName("m_desc")]
    public VMixUtilityDesc_t M_desc { get; set; }  // +0x20
}

/// <summary>CMixVocoder, 72 bytes</summary>
public class CMixVocoder : CMixPropertyBase
{
    [JsonPropertyName("m_nBandCount")]
    public int M_nBandCount { get; set; }  // +0x20
    [JsonPropertyName("m_flBandwidth")]
    public float M_flBandwidth { get; set; }  // +0x24
    [JsonPropertyName("m_fldBModGain")]
    public float M_fldBModGain { get; set; }  // +0x28
    [JsonPropertyName("m_flAttackTime")]
    public float M_flAttackTime { get; set; }  // +0x2C
    [JsonPropertyName("m_flReleaseTime")]
    public float M_flReleaseTime { get; set; }  // +0x30
    [JsonPropertyName("m_flFreqRangeStart")]
    public float M_flFreqRangeStart { get; set; }  // +0x34
    [JsonPropertyName("m_flFreqRangeEnd")]
    public float M_flFreqRangeEnd { get; set; }  // +0x38
    [JsonPropertyName("m_fldBUnvoicedGain")]
    public float M_fldBUnvoicedGain { get; set; }  // +0x3C
    [JsonPropertyName("m_nDebugBand")]
    public int M_nDebugBand { get; set; }  // +0x40
    [JsonPropertyName("m_bPeakMode")]
    public bool M_bPeakMode { get; set; }  // +0x44
}

/// <summary>CMixVsndName, 40 bytes</summary>
public class CMixVsndName : CMixPropertyBase
{
    [JsonPropertyName("m_defaultValue")]
    public string M_defaultValue { get; set; }  // +0x20
}

/// <summary>CPreviewEntry, 24 bytes</summary>
public class CPreviewEntry
{
    [JsonPropertyName("m_soundName")]
    public string M_soundName { get; set; }  // +0x0
    [JsonPropertyName("m_trackName")]
    public string M_trackName { get; set; }  // +0x8
    [JsonPropertyName("m_bIsSoundEvent")]
    public bool M_bIsSoundEvent { get; set; }  // +0x10
}

/// <summary>CPreviewList, 32 bytes</summary>
public class CPreviewList
{
    [JsonPropertyName("m_sounds")]
    public CPreviewEntry[] M_sounds { get; set; }  // +0x0
    [JsonPropertyName("m_bPreviewInGame")]
    public bool M_bPreviewInGame { get; set; }  // +0x18
}

/// <summary>CSelectableSubgraph, 24 bytes</summary>
public class CSelectableSubgraph
{
    [JsonPropertyName("file")]
    public string File { get; set; }  // +0x8
    [JsonPropertyName("subgraphName")]
    public string SubgraphName { get; set; }  // +0x10
}

/// <summary>CVMixEditorEdge, 16 bytes</summary>
public class CVMixEditorEdge
{
    [JsonPropertyName("m_plug0")]
    public string M_plug0 { get; set; }  // +0x0
    [JsonPropertyName("m_plug1")]
    public string M_plug1 { get; set; }  // +0x8
}

/// <summary>CVMixEditorNode, 56 bytes</summary>
public class CVMixEditorNode
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x0
    [JsonPropertyName("m_friendlyName")]
    public string M_friendlyName { get; set; }  // +0x8
    [JsonPropertyName("m_type")]
    public string M_type { get; set; }  // +0x10
    [JsonPropertyName("m_vPos")]
    public Vector2D M_vPos { get; set; }  // +0x18
    [JsonPropertyName("m_vSize")]
    public Vector2D M_vSize { get; set; }  // +0x20
    [JsonPropertyName("m_properties")]
    public object /* opaque */ M_properties { get; set; }  // +0x28
}

/// <summary>CVMixToolEditorData, 8 bytes</summary>
public class CVMixToolEditorData
{
    [JsonPropertyName("m_nSelectedGraph")]
    public int M_nSelectedGraph { get; set; }  // +0x0
    [JsonPropertyName("m_nSelectedEffectPreset")]
    public int M_nSelectedEffectPreset { get; set; }  // +0x4
}

/// <summary>CVMixToolGraph, 72 bytes</summary>
public class CVMixToolGraph
{
    [JsonPropertyName("m_graphDescData")]
    public CVMixGraphDescData M_graphDescData { get; set; }  // +0x0
    [JsonPropertyName("m_editorNodes")]
    public CVMixEditorNode[] M_editorNodes { get; set; }  // +0x10
    [JsonPropertyName("m_editorEdges")]
    public CVMixEditorEdge[] M_editorEdges { get; set; }  // +0x28
    [JsonPropertyName("m_nPreviewNode")]
    public int M_nPreviewNode { get; set; }  // +0x40
}

/// <summary>CVMixToolGraphEntry, 152 bytes</summary>
public class CVMixToolGraphEntry
{
    [JsonPropertyName("m_graph")]
    public CVMixToolGraph M_graph { get; set; }  // +0x0
    [JsonPropertyName("m_editorState")]
    public CGraphEditorState M_editorState { get; set; }  // +0x48
    [JsonPropertyName("m_graphPreview")]
    public CGraphPreviewList M_graphPreview { get; set; }  // +0x70
}

public enum SteamAudioHRTFInterpolationType_t : uint
{
    SA_HRTFINTEROP_NEAREST = 0,
    SA_HRTFINTEROP_BILINEAR = 1,
}

public enum SteamAudioOcclusionModeType_t : uint
{
    SA_OCCLUSIONMODE_NONE = 0,
    SA_OCCLUSIONMODE_NOTRANSMISSION = 1,
    SA_OCCLUSIONMODE_FREQINDEPENDENT = 2,
    SA_OCCLUSIONMODE_FREQDEPENDENT = 3,
}

