// Auto-generated by cs2-codegen from schemas_jsonschema.json
// Revision 10638965 (May 06 2026) — https://github.com/ValveResourceFormat/DumpSource2
// Do not edit by hand.
// Module: steamaudio

#nullable enable
#pragma warning disable CS8618  // non-nullable property not initialized (expected in generated serialization types)

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CS2Schema;

/// <summary>CSteamAudioAmbisonicsField, 24 bytes</summary>
public class CSteamAudioAmbisonicsField
{
    [JsonPropertyName("m_field")]
    public float[] M_field { get; set; }  // +0x0
}

/// <summary>CSteamAudioBakedDimensionsData, 296 bytes</summary>
public class CSteamAudioBakedDimensionsData
{
    [JsonPropertyName("m_settings")]
    public SteamAudioCustomDataDimensionsSettings_t M_settings { get; set; }  // +0x0
    [JsonPropertyName("m_probes")]
    public CSteamAudioProbeData M_probes { get; set; }  // +0x18
    [JsonPropertyName("m_vecInOut")]
    public float[] M_vecInOut { get; set; }  // +0x20
    [JsonPropertyName("m_vecSize")]
    public float[] M_vecSize { get; set; }  // +0x38
    [JsonPropertyName("m_vecOutsideField")]
    public CSteamAudioAmbisonicsField[] M_vecOutsideField { get; set; }  // +0x50
    [JsonPropertyName("m_vecInsideSmallSizeField")]
    public CSteamAudioAmbisonicsField[] M_vecInsideSmallSizeField { get; set; }  // +0x68
    [JsonPropertyName("m_movables")]
    public object /* opaque */ M_movables { get; set; }  // +0x80
}

/// <summary>CSteamAudioBakedMaterialsData, 56 bytes</summary>
public class CSteamAudioBakedMaterialsData
{
    [JsonPropertyName("m_probes")]
    public CSteamAudioProbeData M_probes { get; set; }  // +0x0
    [JsonPropertyName("m_vecMaterialTokens")]
    public uint[] M_vecMaterialTokens { get; set; }  // +0x8
    [JsonPropertyName("m_vecMaterialWeights")]
    public float[] M_vecMaterialWeights { get; set; }  // +0x20
}

/// <summary>CSteamAudioBakedOcclusionData, 96 bytes</summary>
public class CSteamAudioBakedOcclusionData
{
    [JsonPropertyName("m_settings")]
    public SteamAudioCustomDataOcclusionSettings_t M_settings { get; set; }  // +0x0
    [JsonPropertyName("m_probes")]
    public CSteamAudioProbeData M_probes { get; set; }  // +0x10
    [JsonPropertyName("m_vecPathingRatio")]
    public float[] M_vecPathingRatio { get; set; }  // +0x18
    [JsonPropertyName("m_vecPathingDeviation")]
    public float[] M_vecPathingDeviation { get; set; }  // +0x30
    [JsonPropertyName("m_vecReflectionRatio")]
    public float[] M_vecReflectionRatio { get; set; }  // +0x48
}

/// <summary>CSteamAudioBakedPathingData, 184 bytes</summary>
public class CSteamAudioBakedPathingData
{
    [JsonPropertyName("m_nBands")]
    public int M_nBands { get; set; }  // +0x0
    [JsonPropertyName("m_probes")]
    public CSteamAudioProbeData M_probes { get; set; }  // +0x8
    [JsonPropertyName("m_movables")]
    public object /* opaque */ M_movables { get; set; }  // +0x10
}

/// <summary>CSteamAudioBakedReverbData, 552 bytes</summary>
public class CSteamAudioBakedReverbData
{
    [JsonPropertyName("m_nBands")]
    public int M_nBands { get; set; }  // +0x0
    [JsonPropertyName("m_scene")]
    public CSteamAudioSceneData M_scene { get; set; }  // +0x8
    [JsonPropertyName("m_probes")]
    public CSteamAudioProbeData M_probes { get; set; }  // +0x18
    [JsonPropertyName("m_grid")]
    public CSteamAudioProbeGrid M_grid { get; set; }  // +0x20
    [JsonPropertyName("m_reverbSettings")]
    public SteamAudioReverbSettings_t M_reverbSettings { get; set; }  // +0x78
    [JsonPropertyName("m_reverbClusteringSettings")]
    public SteamAudioReverbClusteringSettings_t M_reverbClusteringSettings { get; set; }  // +0x8C
    [JsonPropertyName("m_reverbCompressionSettings")]
    public SteamAudioReverbCompressionSettings_t M_reverbCompressionSettings { get; set; }  // +0x98
    [JsonPropertyName("m_clusteredProbes")]
    public CSteamAudioProbeData M_clusteredProbes { get; set; }  // +0xA0
    [JsonPropertyName("m_vecClusterForProbe")]
    public short[] M_vecClusterForProbe { get; set; }  // +0xA8
    [JsonPropertyName("m_compressedData")]
    public CSteamAudioCompressedReverb M_compressedData { get; set; }  // +0xC0
    [JsonPropertyName("m_compressedClusteredData")]
    public CSteamAudioCompressedReverb M_compressedClusteredData { get; set; }  // +0x120
    [JsonPropertyName("m_movables")]
    public object /* opaque */ M_movables { get; set; }  // +0x180
}

/// <summary>CSteamAudioCompressedReverb, 96 bytes</summary>
public class CSteamAudioCompressedReverb
{
    [JsonPropertyName("m_nChannels")]
    public int M_nChannels { get; set; }  // +0x0
    [JsonPropertyName("m_nBands")]
    public int M_nBands { get; set; }  // +0x4
    [JsonPropertyName("m_nBins")]
    public int M_nBins { get; set; }  // +0x8
    [JsonPropertyName("m_nProbes")]
    public int M_nProbes { get; set; }  // +0xC
    [JsonPropertyName("m_vecNumSingularValues")]
    public int[] M_vecNumSingularValues { get; set; }  // +0x10
    [JsonPropertyName("m_vecDictionary")]
    public float[] M_vecDictionary { get; set; }  // +0x28
    [JsonPropertyName("m_vecCompressedData")]
    public float[] M_vecCompressedData { get; set; }  // +0x40
    [JsonPropertyName("m_pCompressedData")]
    public object /* opaque */ M_pCompressedData { get; set; }  // +0x58
}

/// <summary>CSteamAudioProbeData, 8 bytes</summary>
public class CSteamAudioProbeData
{
    [JsonPropertyName("m_pProbeBatch")]
    public object /* opaque */ M_pProbeBatch { get; set; }  // +0x0
}

/// <summary>CSteamAudioProbeGrid, 88 bytes</summary>
public class CSteamAudioProbeGrid
{
    [JsonPropertyName("m_aabb")]
    public AABB_t M_aabb { get; set; }  // +0x0
    [JsonPropertyName("m_flSpacing")]
    public float M_flSpacing { get; set; }  // +0x18
    [JsonPropertyName("m_nx")]
    public int M_nx { get; set; }  // +0x1C
    [JsonPropertyName("m_ny")]
    public int M_ny { get; set; }  // +0x20
    [JsonPropertyName("m_nz")]
    public int M_nz { get; set; }  // +0x24
    [JsonPropertyName("m_vecLineSegments")]
    public CSteamAudioProbeLineSegment[] M_vecLineSegments { get; set; }  // +0x28
    [JsonPropertyName("m_vecProbes")]
    public Vector[] M_vecProbes { get; set; }  // +0x40
}

/// <summary>CSteamAudioProbeLineSegment, 72 bytes</summary>
public class CSteamAudioProbeLineSegment
{
    [JsonPropertyName("m_vStart")]
    public Vector M_vStart { get; set; }  // +0x0
    [JsonPropertyName("m_vEnd")]
    public Vector M_vEnd { get; set; }  // +0xC
    [JsonPropertyName("m_vecIntervals")]
    public float[] M_vecIntervals { get; set; }  // +0x18
    [JsonPropertyName("m_vecProbeIndices")]
    public int[] M_vecProbeIndices { get; set; }  // +0x30
}

/// <summary>CSteamAudioSceneData, 16 bytes</summary>
public class CSteamAudioSceneData
{
    [JsonPropertyName("m_pScene")]
    public object /* opaque */ M_pScene { get; set; }  // +0x0
    [JsonPropertyName("m_pStaticMesh")]
    public object /* opaque */ M_pStaticMesh { get; set; }  // +0x8
}

/// <summary>SteamAudioCustomDataDimensionsSettings_t, 20 bytes</summary>
public class SteamAudioCustomDataDimensionsSettings_t
{
    [JsonPropertyName("m_nAmbisonicsOrderOutsideField")]
    public int M_nAmbisonicsOrderOutsideField { get; set; }  // +0x0
    [JsonPropertyName("m_nAmbisonicsOrderInsideSizeField")]
    public int M_nAmbisonicsOrderInsideSizeField { get; set; }  // +0x4
    [JsonPropertyName("m_flOutsideThreshold")]
    public float M_flOutsideThreshold { get; set; }  // +0x8
    [JsonPropertyName("m_flSizeThreshold")]
    public float M_flSizeThreshold { get; set; }  // +0xC
    [JsonPropertyName("m_flInsideThreshold")]
    public float M_flInsideThreshold { get; set; }  // +0x10
}

/// <summary>SteamAudioCustomDataOcclusionSettings_t, 12 bytes</summary>
public class SteamAudioCustomDataOcclusionSettings_t
{
    [JsonPropertyName("m_bEnablePathing")]
    public bool M_bEnablePathing { get; set; }  // +0x0
    [JsonPropertyName("m_bEnableReflections")]
    public bool M_bEnableReflections { get; set; }  // +0x1
    [JsonPropertyName("m_nReflectionRays")]
    public int M_nReflectionRays { get; set; }  // +0x4
    [JsonPropertyName("m_nReflectionBounces")]
    public int M_nReflectionBounces { get; set; }  // +0x8
}

/// <summary>SteamAudioPathSettings_t, 16 bytes</summary>
public class SteamAudioPathSettings_t
{
    [JsonPropertyName("m_nNumVisSamples")]
    public int M_nNumVisSamples { get; set; }  // +0x0
    [JsonPropertyName("m_flProbeVisRadius")]
    public float M_flProbeVisRadius { get; set; }  // +0x4
    [JsonPropertyName("m_flProbeVisThreshold")]
    public float M_flProbeVisThreshold { get; set; }  // +0x8
    [JsonPropertyName("m_flProbePathRange")]
    public float M_flProbePathRange { get; set; }  // +0xC
}

/// <summary>SteamAudioReverbClusteringSettings_t, 12 bytes</summary>
public class SteamAudioReverbClusteringSettings_t
{
    [JsonPropertyName("m_bEnableClustering")]
    public bool M_bEnableClustering { get; set; }  // +0x0
    [JsonPropertyName("m_nCubeMapResolution")]
    public int M_nCubeMapResolution { get; set; }  // +0x4
    [JsonPropertyName("m_flDepthThreshold")]
    public float M_flDepthThreshold { get; set; }  // +0x8
}

/// <summary>SteamAudioReverbCompressionSettings_t, 8 bytes</summary>
public class SteamAudioReverbCompressionSettings_t
{
    [JsonPropertyName("m_bEnableCompression")]
    public bool M_bEnableCompression { get; set; }  // +0x0
    [JsonPropertyName("m_flQuality")]
    public float M_flQuality { get; set; }  // +0x4
}

/// <summary>SteamAudioReverbSettings_t, 20 bytes</summary>
public class SteamAudioReverbSettings_t
{
    [JsonPropertyName("m_nNumRays")]
    public int M_nNumRays { get; set; }  // +0x0
    [JsonPropertyName("m_nNumBounces")]
    public int M_nNumBounces { get; set; }  // +0x4
    [JsonPropertyName("m_flIRDuration")]
    public float M_flIRDuration { get; set; }  // +0x8
    [JsonPropertyName("m_nAmbisonicsOrder")]
    public int M_nAmbisonicsOrder { get; set; }  // +0xC
    [JsonPropertyName("m_bExportScene")]
    public bool M_bExportScene { get; set; }  // +0x10
}

