// Auto-generated by cs2-codegen from schemas_jsonschema.json
// Revision 10638965 (May 06 2026) — https://github.com/ValveResourceFormat/DumpSource2
// Do not edit by hand.
// Module: toolscene

#nullable enable
#pragma warning disable CS8618  // non-nullable property not initialized (expected in generated serialization types)

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CS2Schema;

/// <summary>CLightRigBackground, 5 bytes</summary>
public class CLightRigBackground
{
    [JsonPropertyName("m_bEnabled")]
    public bool M_bEnabled { get; set; }  // +0x0
    [JsonPropertyName("m_Color")]
    public Color M_Color { get; set; }  // +0x1
}

/// <summary>CLightRigExposure, 12 bytes</summary>
public class CLightRigExposure
{
    [JsonPropertyName("m_bEnabled")]
    public bool M_bEnabled { get; set; }  // +0x0
    [JsonPropertyName("m_flMinEV")]
    public float M_flMinEV { get; set; }  // +0x4
    [JsonPropertyName("m_flMaxEV")]
    public float M_flMaxEV { get; set; }  // +0x8
}

/// <summary>CLightRigGrid, 5 bytes</summary>
public class CLightRigGrid
{
    [JsonPropertyName("m_bEnabled")]
    public bool M_bEnabled { get; set; }  // +0x0
    [JsonPropertyName("m_Color")]
    public Color M_Color { get; set; }  // +0x1
}

/// <summary>CLightRigLight, 64 bytes</summary>
public class CLightRigLight
{
    [JsonPropertyName("m_vPosition")]
    public Vector M_vPosition { get; set; }  // +0x0
    [JsonPropertyName("m_vDirection")]
    public Vector M_vDirection { get; set; }  // +0xC
    [JsonPropertyName("m_vLookAt")]
    public Vector M_vLookAt { get; set; }  // +0x18
    [JsonPropertyName("m_Color")]
    public Color M_Color { get; set; }  // +0x24
    [JsonPropertyName("m_flAxisScale")]
    public float M_flAxisScale { get; set; }  // +0x28
    [JsonPropertyName("m_flRadius")]
    public float M_flRadius { get; set; }  // +0x2C
    [JsonPropertyName("m_flBrightness")]
    public float M_flBrightness { get; set; }  // +0x30
    [JsonPropertyName("m_flLightSourceRadius")]
    public float M_flLightSourceRadius { get; set; }  // +0x34
    [JsonPropertyName("m_flDistance")]
    public float M_flDistance { get; set; }  // +0x38
    [JsonPropertyName("m_bRelativePositioning")]
    public bool M_bRelativePositioning { get; set; }  // +0x3C
    [JsonPropertyName("m_bParentToCamera")]
    public bool M_bParentToCamera { get; set; }  // +0x3D
}

/// <summary>CLightRigPointLight, 64 bytes</summary>
public class CLightRigPointLight : CLightRigLight
{
}

/// <summary>CLightRigPostProcessing, 8 bytes</summary>
public class CLightRigPostProcessing
{
    [JsonPropertyName("m_hPostProcessing")]
    public InfoForResourceTypeCPostProcessingResource? M_hPostProcessing { get; set; }  // +0x0
}

/// <summary>CLightRigSky, 8 bytes</summary>
public class CLightRigSky
{
    [JsonPropertyName("m_hSkyMaterial")]
    public InfoForResourceTypeIMaterial2? M_hSkyMaterial { get; set; }  // +0x0
}

/// <summary>CLightRigSpotLight, 76 bytes</summary>
public class CLightRigSpotLight : CLightRigLight
{
    [JsonPropertyName("m_flOuterConeAngle")]
    public float M_flOuterConeAngle { get; set; }  // +0x40
    [JsonPropertyName("m_flInnerConeAngle")]
    public float M_flInnerConeAngle { get; set; }  // +0x44
    [JsonPropertyName("m_bCastShadows")]
    public bool M_bCastShadows { get; set; }  // +0x48
}

/// <summary>CLightRigSunLight, 84 bytes</summary>
public class CLightRigSunLight : CLightRigLight
{
    [JsonPropertyName("m_flShadowCascadeDistance0")]
    public float M_flShadowCascadeDistance0 { get; set; }  // +0x40
    [JsonPropertyName("m_flShadowCascadeDistance1")]
    public float M_flShadowCascadeDistance1 { get; set; }  // +0x44
    [JsonPropertyName("m_flShadowCascadeDistance2")]
    public float M_flShadowCascadeDistance2 { get; set; }  // +0x48
    [JsonPropertyName("m_flShadowCascadeDistance3")]
    public float M_flShadowCascadeDistance3 { get; set; }  // +0x4C
    [JsonPropertyName("m_bCastShadows")]
    public bool M_bCastShadows { get; set; }  // +0x50
}

/// <summary>CLightRigVMap, 232 bytes</summary>
public class CLightRigVMap
{
    [JsonPropertyName("m_MapName")]
    public string M_MapName { get; set; }  // +0x0
    [JsonPropertyName("m_bRender3DSkybox")]
    public bool M_bRender3DSkybox { get; set; }  // +0xE0
    [JsonPropertyName("m_bParticlesTraceAgainstMap")]
    public bool M_bParticlesTraceAgainstMap { get; set; }  // +0xE1
}

/// <summary>CToolSceneLightRig, 360 bytes</summary>
public class CToolSceneLightRig
{
    [JsonPropertyName("m_nRigType")]
    public LightRigType_t M_nRigType { get; set; }  // +0x8
    [JsonPropertyName("m_Suns")]
    public CLightRigSunLight[] M_Suns { get; set; }  // +0x10
    [JsonPropertyName("m_PointLights")]
    public CLightRigPointLight[] M_PointLights { get; set; }  // +0x28
    [JsonPropertyName("m_SpotLights")]
    public CLightRigSpotLight[] M_SpotLights { get; set; }  // +0x40
    [JsonPropertyName("m_Background")]
    public CLightRigBackground M_Background { get; set; }  // +0x58
    [JsonPropertyName("m_Grid")]
    public CLightRigGrid M_Grid { get; set; }  // +0x5D
    [JsonPropertyName("m_Exposure")]
    public CLightRigExposure M_Exposure { get; set; }  // +0x64
    [JsonPropertyName("m_PostProcessing")]
    public CLightRigPostProcessing M_PostProcessing { get; set; }  // +0x70
    [JsonPropertyName("m_Sky")]
    public CLightRigSky M_Sky { get; set; }  // +0x78
    [JsonPropertyName("m_BackgroundMap")]
    public CLightRigVMap M_BackgroundMap { get; set; }  // +0x80
}

public enum LightRigType_t : uint
{
    PREVIEW = 0,
    THUMBNAIL = 1,
    MATERIAL_THUMBNAIL = 2,
    NUM_TYPES = 3,
}

