// Auto-generated by cs2-codegen from schemas_jsonschema.json
// Revision 10638965 (May 06 2026) — https://github.com/ValveResourceFormat/DumpSource2
// Do not edit by hand.
// Module: vphysics2

#nullable enable
#pragma warning disable CS8618  // non-nullable property not initialized (expected in generated serialization types)

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CS2Schema;

/// <summary>IPhysAggregateInstance, 24 bytes</summary>
public class IPhysAggregateInstance : IPhysicsBodyList
{
    [JsonPropertyName("m_pSkeleton")]
    public object /* union */ M_pSkeleton { get; set; }  // +0x8
    [JsonPropertyName("m_bIsAxisAligned")]
    public bool M_bIsAxisAligned { get; set; }  // +0x10
}

/// <summary>IPhysicsBody, 8 bytes</summary>
public class IPhysicsBody
{
}

/// <summary>IPhysicsJoint, 8 bytes</summary>
public class IPhysicsJoint
{
}

/// <summary>IPhysicsParticleRope, 8 bytes</summary>
public class IPhysicsParticleRope
{
}

/// <summary>IPhysicsPlayerController, 8 bytes</summary>
public class IPhysicsPlayerController
{
}

/// <summary>IPhysicsRagdollControl, 8 bytes</summary>
public class IPhysicsRagdollControl
{
}

/// <summary>vphysics_save_cphysicsbody_t, 232 bytes</summary>
public class vphysics_save_cphysicsbody_t : RnBodyDesc_t
{
    [JsonPropertyName("m_nOldPointer")]
    public ulong M_nOldPointer { get; set; }  // +0xE0
}

/// <summary>vphysics_save_ragdoll_control_t, 56 bytes</summary>
public class vphysics_save_ragdoll_control_t
{
    [JsonPropertyName("m_flMinSpringFrequency")]
    public float M_flMinSpringFrequency { get; set; }  // +0x0
    [JsonPropertyName("m_flMaxSpringFrequency")]
    public float M_flMaxSpringFrequency { get; set; }  // +0x4
    [JsonPropertyName("m_flMaxStretch")]
    public float M_flMaxStretch { get; set; }  // +0x8
    [JsonPropertyName("m_bSolidCollisionAtZeroWeight")]
    public bool M_bSolidCollisionAtZeroWeight { get; set; }  // +0xC
    [JsonPropertyName("m_bRequiresDynamicBodies")]
    public bool M_bRequiresDynamicBodies { get; set; }  // +0xD
    [JsonPropertyName("m_bIgnoreTeleport")]
    public bool M_bIgnoreTeleport { get; set; }  // +0xE
    [JsonPropertyName("m_vLinearVelocityAccumulator")]
    public Vector M_vLinearVelocityAccumulator { get; set; }  // +0x10
    [JsonPropertyName("m_vAngularVelocityAccumulator")]
    public RotationVector M_vAngularVelocityAccumulator { get; set; }  // +0x1C
    [JsonPropertyName("m_vForceAccumulator")]
    public Vector M_vForceAccumulator { get; set; }  // +0x28
    [JsonPropertyName("m_nBodyCount")]
    public int M_nBodyCount { get; set; }  // +0x34
}

