// Auto-generated by cs2-codegen from schemas_jsonschema.json
// Revision 10638965 (May 06 2026) — https://github.com/ValveResourceFormat/DumpSource2
// Do not edit by hand.
// Module: worldrenderer

#nullable enable
#pragma warning disable CS8618  // non-nullable property not initialized (expected in generated serialization types)

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CS2Schema;

public enum AggregateInstanceStream_t : byte
{
    AGGREGATE_INSTANCE_STREAM_NONE = 0,
    AGGREGATE_INSTANCE_STREAM_LIGHTMAPUV_UNORM16 = 1,
    AGGREGATE_INSTANCE_STREAM_VERTEXTINT_UNORM8 = 2,
    AGGREGATE_INSTANCE_STREAM_VERTEXBLEND_UNORM8 = 4,
}

/// <summary>AggregateInstanceStreamOnDiskData_t, 24 bytes</summary>
public class AggregateInstanceStreamOnDiskData_t
{
    [JsonPropertyName("m_DecodedSize")]
    public uint M_DecodedSize { get; set; }  // +0x0
    [JsonPropertyName("m_BufferData")]
    public object /* opaque */ M_BufferData { get; set; }  // +0x8
}

/// <summary>AggregateLODSetup_t, 40 bytes</summary>
public class AggregateLODSetup_t
{
    [JsonPropertyName("m_vLODOrigin")]
    public Vector M_vLODOrigin { get; set; }  // +0x0
    [JsonPropertyName("m_fMaxObjectScale")]
    public float M_fMaxObjectScale { get; set; }  // +0xC
    [JsonPropertyName("m_fSwitchDistances")]
    public float[] M_fSwitchDistances { get; set; }  // +0x10
}

/// <summary>AggregateMeshInfo_t, 36 bytes</summary>
public class AggregateMeshInfo_t
{
    [JsonPropertyName("m_nVisClusterMemberOffset")]
    public uint M_nVisClusterMemberOffset { get; set; }  // +0x0
    [JsonPropertyName("m_nVisClusterMemberCount")]
    public byte M_nVisClusterMemberCount { get; set; }  // +0x4
    [JsonPropertyName("m_bHasTransform")]
    public bool M_bHasTransform { get; set; }  // +0x5
    [JsonPropertyName("m_nLODGroupMask")]
    public byte M_nLODGroupMask { get; set; }  // +0x6
    [JsonPropertyName("m_nDrawCallIndex")]
    public short M_nDrawCallIndex { get; set; }  // +0x8
    [JsonPropertyName("m_nLODSetupIndex")]
    public short M_nLODSetupIndex { get; set; }  // +0xA
    [JsonPropertyName("m_vTintColor")]
    public Color M_vTintColor { get; set; }  // +0xC
    [JsonPropertyName("m_objectFlags")]
    public ObjectTypeFlags_t M_objectFlags { get; set; }  // +0x10
    [JsonPropertyName("m_nLightProbeVolumePrecomputedHandshake")]
    public int M_nLightProbeVolumePrecomputedHandshake { get; set; }  // +0x14
    [JsonPropertyName("m_nInstanceStreamOffset")]
    public uint M_nInstanceStreamOffset { get; set; }  // +0x18
    [JsonPropertyName("m_nVertexAlbedoStreamOffset")]
    public uint M_nVertexAlbedoStreamOffset { get; set; }  // +0x1C
    [JsonPropertyName("m_instanceStreams")]
    public AggregateInstanceStream_t M_instanceStreams { get; set; }  // +0x20
}

/// <summary>AggregateRTProxySceneObject_t, 104 bytes</summary>
public class AggregateRTProxySceneObject_t
{
    [JsonPropertyName("m_nLayer")]
    public short M_nLayer { get; set; }  // +0x0
    [JsonPropertyName("m_BLASes")]
    public RTProxyBLAS_t[] M_BLASes { get; set; }  // +0x8
    [JsonPropertyName("m_Instances")]
    public RTProxyInstanceInfo_t[] M_Instances { get; set; }  // +0x20
    [JsonPropertyName("m_VBData")]
    public object /* opaque */ M_VBData { get; set; }  // +0x38
    [JsonPropertyName("m_IBData")]
    public object /* opaque */ M_IBData { get; set; }  // +0x48
    [JsonPropertyName("m_InstanceAlbedoData")]
    public object /* opaque */ M_InstanceAlbedoData { get; set; }  // +0x58
}

/// <summary>AggregateSceneObject_t, 120 bytes</summary>
public class AggregateSceneObject_t
{
    [JsonPropertyName("m_allFlags")]
    public ObjectTypeFlags_t M_allFlags { get; set; }  // +0x0
    [JsonPropertyName("m_anyFlags")]
    public ObjectTypeFlags_t M_anyFlags { get; set; }  // +0x4
    [JsonPropertyName("m_nLayer")]
    public short M_nLayer { get; set; }  // +0x8
    [JsonPropertyName("m_instanceStream")]
    public short M_instanceStream { get; set; }  // +0xA
    [JsonPropertyName("m_vertexAlbedoStream")]
    public short M_vertexAlbedoStream { get; set; }  // +0xC
    [JsonPropertyName("m_aggregateMeshes")]
    public AggregateMeshInfo_t[] M_aggregateMeshes { get; set; }  // +0x10
    [JsonPropertyName("m_lodSetups")]
    public AggregateLODSetup_t[] M_lodSetups { get; set; }  // +0x28
    [JsonPropertyName("m_visClusterMembership")]
    public ushort[] M_visClusterMembership { get; set; }  // +0x40
    [JsonPropertyName("m_fragmentTransforms")]
    public matrix3x4_t[] M_fragmentTransforms { get; set; }  // +0x58
    [JsonPropertyName("m_renderableModel")]
    public InfoForResourceTypeCModel? M_renderableModel { get; set; }  // +0x70
}

/// <summary>AggregateVertexAlbedoStreamOnDiskData_t, 16 bytes</summary>
public class AggregateVertexAlbedoStreamOnDiskData_t
{
    [JsonPropertyName("m_BufferData")]
    public object /* opaque */ M_BufferData { get; set; }  // +0x0
}

/// <summary>BakedLightingInfo_t, 72 bytes</summary>
public class BakedLightingInfo_t
{
    [JsonPropertyName("m_nLightmapVersionNumber")]
    public uint M_nLightmapVersionNumber { get; set; }  // +0x0
    [JsonPropertyName("m_nLightmapGameVersionNumber")]
    public uint M_nLightmapGameVersionNumber { get; set; }  // +0x4
    [JsonPropertyName("m_vLightmapUvScale")]
    public Vector2D M_vLightmapUvScale { get; set; }  // +0x8
    [JsonPropertyName("m_bHasLightmaps")]
    public bool M_bHasLightmaps { get; set; }  // +0x10
    [JsonPropertyName("m_bBakedShadowsGamma20")]
    public bool M_bBakedShadowsGamma20 { get; set; }  // +0x11
    [JsonPropertyName("m_bCompressionEnabled")]
    public bool M_bCompressionEnabled { get; set; }  // +0x12
    [JsonPropertyName("m_bSHLightmaps")]
    public bool M_bSHLightmaps { get; set; }  // +0x13
    [JsonPropertyName("m_nChartPackIterations")]
    public byte M_nChartPackIterations { get; set; }  // +0x14
    [JsonPropertyName("m_nVradQuality")]
    public byte M_nVradQuality { get; set; }  // +0x15
    [JsonPropertyName("m_lightMaps")]
    public InfoForResourceTypeCTextureBase?[] M_lightMaps { get; set; }  // +0x18
    [JsonPropertyName("m_bakedShadows")]
    public BakedLightingInfo_t_BakedShadowAssignment_t[] M_bakedShadows { get; set; }  // +0x30
}

/// <summary>BakedLightingInfo_t::BakedShadowAssignment_t, 12 bytes</summary>
public class BakedLightingInfo_t_BakedShadowAssignment_t
{
    [JsonPropertyName("m_nLightHash")]
    public uint M_nLightHash { get; set; }  // +0x0
    [JsonPropertyName("m_nMapHash")]
    public uint M_nMapHash { get; set; }  // +0x4
    [JsonPropertyName("m_nShadowChannel")]
    public sbyte M_nShadowChannel { get; set; }  // +0x8
}

/// <summary>BaseSceneObjectOverride_t, 4 bytes</summary>
public class BaseSceneObjectOverride_t
{
    [JsonPropertyName("m_nSceneObjectIndex")]
    public uint M_nSceneObjectIndex { get; set; }  // +0x0
}

/// <summary>ClutterSceneObject_t, 176 bytes</summary>
public class ClutterSceneObject_t
{
    [JsonPropertyName("m_Bounds")]
    public AABB_t M_Bounds { get; set; }  // +0x0
    [JsonPropertyName("m_flags")]
    public ObjectTypeFlags_t M_flags { get; set; }  // +0x18
    [JsonPropertyName("m_nLayer")]
    public short M_nLayer { get; set; }  // +0x1C
    [JsonPropertyName("m_instancePositions")]
    public Vector[] M_instancePositions { get; set; }  // +0x20
    [JsonPropertyName("m_instanceScales")]
    public float[] M_instanceScales { get; set; }  // +0x50
    [JsonPropertyName("m_instanceTintSrgb")]
    public Color[] M_instanceTintSrgb { get; set; }  // +0x68
    [JsonPropertyName("m_tiles")]
    public ClutterTile_t[] M_tiles { get; set; }  // +0x80
    [JsonPropertyName("m_renderableModel")]
    public InfoForResourceTypeCModel? M_renderableModel { get; set; }  // +0x98
    [JsonPropertyName("m_materialGroup")]
    public string M_materialGroup { get; set; }  // +0xA0
    [JsonPropertyName("m_flBeginCullSize")]
    public float M_flBeginCullSize { get; set; }  // +0xA4
    [JsonPropertyName("m_flEndCullSize")]
    public float M_flEndCullSize { get; set; }  // +0xA8
}

/// <summary>ClutterTile_t, 32 bytes</summary>
public class ClutterTile_t
{
    [JsonPropertyName("m_nFirstInstance")]
    public uint M_nFirstInstance { get; set; }  // +0x0
    [JsonPropertyName("m_nLastInstance")]
    public uint M_nLastInstance { get; set; }  // +0x4
    [JsonPropertyName("m_BoundsWs")]
    public AABB_t M_BoundsWs { get; set; }  // +0x8
}

/// <summary>CVoxelVisibility, 160 bytes</summary>
public class CVoxelVisibility
{
    [JsonPropertyName("m_nBaseClusterCount")]
    public uint M_nBaseClusterCount { get; set; }  // +0x40
    [JsonPropertyName("m_nPVSBytesPerCluster")]
    public uint M_nPVSBytesPerCluster { get; set; }  // +0x44
    [JsonPropertyName("m_vMinBounds")]
    public Vector M_vMinBounds { get; set; }  // +0x48
    [JsonPropertyName("m_vMaxBounds")]
    public Vector M_vMaxBounds { get; set; }  // +0x54
    [JsonPropertyName("m_flGridSize")]
    public float M_flGridSize { get; set; }  // +0x60
    [JsonPropertyName("m_nSkyVisibilityCluster")]
    public uint M_nSkyVisibilityCluster { get; set; }  // +0x64
    [JsonPropertyName("m_nSunVisibilityCluster")]
    public uint M_nSunVisibilityCluster { get; set; }  // +0x68
    [JsonPropertyName("m_NodeBlock")]
    public VoxelVisBlockOffset_t M_NodeBlock { get; set; }  // +0x6C
    [JsonPropertyName("m_RegionBlock")]
    public VoxelVisBlockOffset_t M_RegionBlock { get; set; }  // +0x74
    [JsonPropertyName("m_EnclosedClusterListBlock")]
    public VoxelVisBlockOffset_t M_EnclosedClusterListBlock { get; set; }  // +0x7C
    [JsonPropertyName("m_EnclosedClustersBlock")]
    public VoxelVisBlockOffset_t M_EnclosedClustersBlock { get; set; }  // +0x84
    [JsonPropertyName("m_MasksBlock")]
    public VoxelVisBlockOffset_t M_MasksBlock { get; set; }  // +0x8C
    [JsonPropertyName("m_nVisBlocks")]
    public VoxelVisBlockOffset_t M_nVisBlocks { get; set; }  // +0x94
}

/// <summary>EntityIOConnectionData_t, 64 bytes</summary>
public class EntityIOConnectionData_t
{
    [JsonPropertyName("m_outputName")]
    public string M_outputName { get; set; }  // +0x0
    [JsonPropertyName("m_targetType")]
    public uint M_targetType { get; set; }  // +0x8
    [JsonPropertyName("m_targetName")]
    public string M_targetName { get; set; }  // +0x10
    [JsonPropertyName("m_inputName")]
    public string M_inputName { get; set; }  // +0x18
    [JsonPropertyName("m_overrideParam")]
    public string M_overrideParam { get; set; }  // +0x20
    [JsonPropertyName("m_flDelay")]
    public float M_flDelay { get; set; }  // +0x28
    [JsonPropertyName("m_nTimesToFire")]
    public int M_nTimesToFire { get; set; }  // +0x2C
    [JsonPropertyName("m_paramMap")]
    public object /* opaque */ M_paramMap { get; set; }  // +0x30
}

/// <summary>EntityKeyValueData_t, 56 bytes</summary>
public class EntityKeyValueData_t
{
    [JsonPropertyName("m_connections")]
    public EntityIOConnectionData_t[] M_connections { get; set; }  // +0x8
    [JsonPropertyName("m_keyValuesData")]
    public object /* opaque */ M_keyValuesData { get; set; }  // +0x20
}

/// <summary>ExtraVertexStreamOverride_t, 48 bytes</summary>
public class ExtraVertexStreamOverride_t : BaseSceneObjectOverride_t
{
    [JsonPropertyName("m_nSubSceneObject")]
    public uint M_nSubSceneObject { get; set; }  // +0x4
    [JsonPropertyName("m_nDrawCallIndex")]
    public uint M_nDrawCallIndex { get; set; }  // +0x8
    [JsonPropertyName("m_nAdditionalMeshDrawPrimitiveFlags")]
    public MeshDrawPrimitiveFlags_t M_nAdditionalMeshDrawPrimitiveFlags { get; set; }  // +0xC
    [JsonPropertyName("m_extraBufferBinding")]
    public CRenderBufferBinding M_extraBufferBinding { get; set; }  // +0x10
}

/// <summary>InfoForResourceTypeVMapResourceData_t, 1 bytes</summary>
public class InfoForResourceTypeVMapResourceData_t
{
}

/// <summary>MaterialOverride_t, 40 bytes</summary>
public class MaterialOverride_t : BaseSceneObjectOverride_t
{
    [JsonPropertyName("m_nSubSceneObject")]
    public uint M_nSubSceneObject { get; set; }  // +0x4
    [JsonPropertyName("m_nDrawCallIndex")]
    public uint M_nDrawCallIndex { get; set; }  // +0x8
    [JsonPropertyName("m_pMaterial")]
    public InfoForResourceTypeIMaterial2? M_pMaterial { get; set; }  // +0x10
    [JsonPropertyName("m_vLinearTintColor")]
    public Vector M_vLinearTintColor { get; set; }  // +0x18
}

/// <summary>NodeData_t, 80 bytes</summary>
public class NodeData_t
{
    [JsonPropertyName("m_nParent")]
    public int M_nParent { get; set; }  // +0x0
    [JsonPropertyName("m_vOrigin")]
    public Vector M_vOrigin { get; set; }  // +0x4
    [JsonPropertyName("m_vMinBounds")]
    public Vector M_vMinBounds { get; set; }  // +0x10
    [JsonPropertyName("m_vMaxBounds")]
    public Vector M_vMaxBounds { get; set; }  // +0x1C
    [JsonPropertyName("m_flMinimumDistance")]
    public float M_flMinimumDistance { get; set; }  // +0x28
    [JsonPropertyName("m_ChildNodeIndices")]
    public int[] M_ChildNodeIndices { get; set; }  // +0x30
    [JsonPropertyName("m_worldNodePrefix")]
    public string M_worldNodePrefix { get; set; }  // +0x48
}

public enum ObjectTypeFlags_t : uint
{
    OBJECT_TYPE_NONE = 0,
    OBJECT_TYPE_MODEL = 8,
    OBJECT_TYPE_BLOCK_LIGHT = 16,
    OBJECT_TYPE_NO_SHADOWS = 32,
    OBJECT_TYPE_WORLDSPACE_TEXURE_BLEND = 64,
    OBJECT_TYPE_DISABLED_IN_LOW_QUALITY = 128,
    OBJECT_TYPE_RENDER_WITH_DYNAMIC = 512,
    OBJECT_TYPE_RENDER_TO_CUBEMAPS = 1024,
    OBJECT_TYPE_MODEL_HAS_LODS = 2048,
    OBJECT_TYPE_OVERLAY = 8192,
    OBJECT_TYPE_PRECOMPUTED_VISMEMBERS = 16384,
    OBJECT_TYPE_STATIC_CUBE_MAP = 32768,
    OBJECT_TYPE_DISABLE_VIS_CULLING = 65536,
    OBJECT_TYPE_BAKED_GEOMETRY = 131072,
    OBJECT_TYPE_NEEDS_DYNAMIC_SHADOWS = 262144,
    OBJECT_TYPE_HAS_AGGREGATE_RTPROXY = 524288,
}

/// <summary>PermEntityLumpData_t, 56 bytes</summary>
public class PermEntityLumpData_t
{
    [JsonPropertyName("m_name")]
    public string M_name { get; set; }  // +0x8
    [JsonPropertyName("m_childLumps")]
    public object /* opaque */[] M_childLumps { get; set; }  // +0x10
    [JsonPropertyName("m_entityKeyValues")]
    public EntityKeyValueData_t[] M_entityKeyValues { get; set; }  // +0x28
}

/// <summary>RTProxyBLAS_t, 68 bytes</summary>
public class RTProxyBLAS_t
{
    [JsonPropertyName("m_nFirstIndex")]
    public uint M_nFirstIndex { get; set; }  // +0x0
    [JsonPropertyName("m_nIndexCount")]
    public uint M_nIndexCount { get; set; }  // +0x4
    [JsonPropertyName("m_nVBByteOffset")]
    public uint M_nVBByteOffset { get; set; }  // +0x8
    [JsonPropertyName("m_nBaseVertex")]
    public uint M_nBaseVertex { get; set; }  // +0xC
    [JsonPropertyName("m_nVertexCount")]
    public ushort M_nVertexCount { get; set; }  // +0x10
    [JsonPropertyName("m_albedoFormat")]
    public VertexAlbedoFormat_t M_albedoFormat { get; set; }  // +0x12
    [JsonPropertyName("m_boundLs")]
    public AABB_t M_boundLs { get; set; }  // +0x14
    [JsonPropertyName("m_vVertexOriginLs")]
    public Vector M_vVertexOriginLs { get; set; }  // +0x2C
    [JsonPropertyName("m_vVertexExtentLs")]
    public Vector M_vVertexExtentLs { get; set; }  // +0x38
}

public enum RTProxyInstanceFlags_t : byte
{
    RTPROXY_INSTANCE_FLAG_NONE = 0,
    RTPROXY_INSTANCE_UNIQUE_MESH = 1,
}

/// <summary>RTProxyInstanceInfo_t, 60 bytes</summary>
public class RTProxyInstanceInfo_t
{
    [JsonPropertyName("m_nFlags")]
    public RTProxyInstanceFlags_t M_nFlags { get; set; }  // +0x0
    [JsonPropertyName("m_albedoFormat")]
    public VertexAlbedoFormat_t M_albedoFormat { get; set; }  // +0x1
    [JsonPropertyName("m_nBLASCount")]
    public ushort M_nBLASCount { get; set; }  // +0x2
    [JsonPropertyName("m_nBLASIndex")]
    public uint M_nBLASIndex { get; set; }  // +0x4
    [JsonPropertyName("m_nVertexAlbedoByteOffset")]
    public uint M_nVertexAlbedoByteOffset { get; set; }  // +0x8
    [JsonPropertyName("m_mWorldFromLocal")]
    public matrix3x4_t M_mWorldFromLocal { get; set; }  // +0xC
}

/// <summary>SceneObject_t, 136 bytes</summary>
public class SceneObject_t
{
    [JsonPropertyName("m_nObjectID")]
    public uint M_nObjectID { get; set; }  // +0x0
    [JsonPropertyName("m_vTransform")]
    public Vector4D[] M_vTransform { get; set; }  // +0x4
    [JsonPropertyName("m_flFadeStartDistance")]
    public float M_flFadeStartDistance { get; set; }  // +0x34
    [JsonPropertyName("m_flFadeEndDistance")]
    public float M_flFadeEndDistance { get; set; }  // +0x38
    [JsonPropertyName("m_vTintColor")]
    public Vector4D M_vTintColor { get; set; }  // +0x3C
    [JsonPropertyName("m_skin")]
    public string M_skin { get; set; }  // +0x50
    [JsonPropertyName("m_nObjectTypeFlags")]
    public ObjectTypeFlags_t M_nObjectTypeFlags { get; set; }  // +0x58
    [JsonPropertyName("m_vLightingOrigin")]
    public Vector M_vLightingOrigin { get; set; }  // +0x5C
    [JsonPropertyName("m_nOverlayRenderOrder")]
    public short M_nOverlayRenderOrder { get; set; }  // +0x68
    [JsonPropertyName("m_nLODOverride")]
    public short M_nLODOverride { get; set; }  // +0x6A
    [JsonPropertyName("m_nCubeMapPrecomputedHandshake")]
    public int M_nCubeMapPrecomputedHandshake { get; set; }  // +0x6C
    [JsonPropertyName("m_nLightProbeVolumePrecomputedHandshake")]
    public int M_nLightProbeVolumePrecomputedHandshake { get; set; }  // +0x70
    [JsonPropertyName("m_renderableModel")]
    public InfoForResourceTypeCModel? M_renderableModel { get; set; }  // +0x78
    [JsonPropertyName("m_renderable")]
    public InfoForResourceTypeCRenderMesh? M_renderable { get; set; }  // +0x80
}

/// <summary>VMapResourceData_t, 1 bytes</summary>
public class VMapResourceData_t
{
}

/// <summary>VoxelVisBlockOffset_t, 8 bytes</summary>
public class VoxelVisBlockOffset_t
{
    [JsonPropertyName("m_nOffset")]
    public uint M_nOffset { get; set; }  // +0x0
    [JsonPropertyName("m_nElementCount")]
    public uint M_nElementCount { get; set; }  // +0x4
}

/// <summary>World_t, 216 bytes</summary>
public class World_t
{
    [JsonPropertyName("m_builderParams")]
    public WorldBuilderParams_t M_builderParams { get; set; }  // +0x0
    [JsonPropertyName("m_worldNodes")]
    public NodeData_t[] M_worldNodes { get; set; }  // +0x60
    [JsonPropertyName("m_worldLightingInfo")]
    public BakedLightingInfo_t M_worldLightingInfo { get; set; }  // +0x78
    [JsonPropertyName("m_entityLumps")]
    public object /* opaque */[] M_entityLumps { get; set; }  // +0xC0
}

/// <summary>WorldBuilderParams_t, 96 bytes</summary>
public class WorldBuilderParams_t
{
    [JsonPropertyName("m_flMinDrawVolumeSize")]
    public float M_flMinDrawVolumeSize { get; set; }  // +0x0
    [JsonPropertyName("m_bBuildBakedLighting")]
    public bool M_bBuildBakedLighting { get; set; }  // +0x4
    [JsonPropertyName("m_bAggregateInstanceStreams")]
    public bool M_bAggregateInstanceStreams { get; set; }  // +0x5
    [JsonPropertyName("m_bakedLightingInfo")]
    public BakedLightingInfo_t M_bakedLightingInfo { get; set; }  // +0x8
    [JsonPropertyName("m_nCompileTimestamp")]
    public ulong M_nCompileTimestamp { get; set; }  // +0x50
    [JsonPropertyName("m_nCompileFingerprint")]
    public ulong M_nCompileFingerprint { get; set; }  // +0x58
}

/// <summary>WorldNode_t, 376 bytes</summary>
public class WorldNode_t
{
    [JsonPropertyName("m_sceneObjects")]
    public SceneObject_t[] M_sceneObjects { get; set; }  // +0x0
    [JsonPropertyName("m_visClusterMembership")]
    public ushort[] M_visClusterMembership { get; set; }  // +0x18
    [JsonPropertyName("m_aggregateSceneObjects")]
    public AggregateSceneObject_t[] M_aggregateSceneObjects { get; set; }  // +0x30
    [JsonPropertyName("m_clutterSceneObjects")]
    public ClutterSceneObject_t[] M_clutterSceneObjects { get; set; }  // +0x48
    [JsonPropertyName("m_rtProxies")]
    public AggregateRTProxySceneObject_t[] M_rtProxies { get; set; }  // +0x60
    [JsonPropertyName("m_extraVertexStreamOverrides")]
    public ExtraVertexStreamOverride_t[] M_extraVertexStreamOverrides { get; set; }  // +0x78
    [JsonPropertyName("m_materialOverrides")]
    public MaterialOverride_t[] M_materialOverrides { get; set; }  // +0x90
    [JsonPropertyName("m_extraVertexStreams")]
    public WorldNodeOnDiskBufferData_t[] M_extraVertexStreams { get; set; }  // +0xA8
    [JsonPropertyName("m_aggregateInstanceStreams")]
    public AggregateInstanceStreamOnDiskData_t[] M_aggregateInstanceStreams { get; set; }  // +0xC0
    [JsonPropertyName("m_vertexAlbedoStreams")]
    public AggregateVertexAlbedoStreamOnDiskData_t[] M_vertexAlbedoStreams { get; set; }  // +0xD8
    [JsonPropertyName("m_layerNames")]
    public string[] M_layerNames { get; set; }  // +0xF0
    [JsonPropertyName("m_sceneObjectLayerIndices")]
    public byte[] M_sceneObjectLayerIndices { get; set; }  // +0x108
    [JsonPropertyName("m_grassFileName")]
    public string M_grassFileName { get; set; }  // +0x120
    [JsonPropertyName("m_nodeLightingInfo")]
    public BakedLightingInfo_t M_nodeLightingInfo { get; set; }  // +0x128
    [JsonPropertyName("m_bHasBakedGeometryFlag")]
    public bool M_bHasBakedGeometryFlag { get; set; }  // +0x170
}

/// <summary>WorldNodeOnDiskBufferData_t, 56 bytes</summary>
public class WorldNodeOnDiskBufferData_t
{
    [JsonPropertyName("m_nElementCount")]
    public int M_nElementCount { get; set; }  // +0x0
    [JsonPropertyName("m_nElementSizeInBytes")]
    public int M_nElementSizeInBytes { get; set; }  // +0x4
    [JsonPropertyName("m_inputLayoutFields")]
    public RenderInputLayoutField_t[] M_inputLayoutFields { get; set; }  // +0x8
    [JsonPropertyName("m_pData")]
    public byte[] M_pData { get; set; }  // +0x20
}

